### ISSUE TITLE
Deployment of Julia-ipython for web usage

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/IJulia.jl#1]
This is perhaps a bit of an umbrella issue. I would like to have julia-ipython be ready for the classes this Fall. With stuff such [notebookcloud](https://github.com/carlsmith/notebookcloud), hosting such a solution for general use on tryjulia.org through EC2 seems like a possibility. As discussed on the mailing list, the earlier web-repl used to get about 50 trials a day and a few hundred a day whenever there was a mention on hackernews etc.

It would be nice to have a list of all the things that have to be done, so that they can be tracked for such a solution to be taken live in the next few months.

So far, I thought JuliaLang/julia#2775 was a bottleneck, but that has been resolved.

**Comment by stevengj** [comment]
Seems to be closed by JuliaBox.
