### ISSUE TITLE
Jupyter notebook fails to open with Julia 1.6.0 kernel 

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/IJulia.jl#1009]
Hey all, I am trying to update some older notebooks and when I run `jupyter lab` from my dir and then try to open a notebook with the 1.6 kernel I get:

```Julia
[I 15:36:22.736 LabApp] KernelRestarter: restarting kernel (3/5), new random ports
┌ Warning: this kernel.jl is different from the one provided by IJulia
│   this_kernel_file = "/Users/logankilpatrick/.julia/packages/IJulia/e8kqU/src/kernel.jl"
│   ijulia_kernel_file = "/Users/logankilpatrick/.julia/packages/IJulia/DrVMH/src/kernel.jl"
└ @ Main ~/.julia/packages/IJulia/e8kqU/src/kernel.jl:7
ERROR: LoadError: UndefVarError: InteractiveUtils not defined
in expression starting at /Users/logankilpatrick/.julia/packages/IJulia/e8kqU/src/kernel.jl:12
```

per here: https://github.com/JuliaLang/IJulia.jl/issues/955 I tried to build IJulia and then also removed and re-added it but the issue persisted.

**Comment by logankilpatrick** [comment]
This may be because I recently got a new laptop and transferred over all the content. I had to delete my IJulia folder in `.Julia/packages` to fix this issue. Not sure if there's anything that can be done on the dev side here, perhaps suggest this in the warning if it's appropriate?

**Comment by stevengj** [comment]
If deleting your IJulia folder fixed it, then building it should have worked too.  Perhaps you built it in the wrong version of Julia or in the wrong project?

**Comment by stevengj** [comment]
Closing this issue since you've resolved it, and it will be impossible to track down your original problem.
