### ISSUE TITLE
IJulia no longer loads shared library dependencies

### ISSUE THREAD

**Issue by mwallerb** [JuliaLang/IJulia.jl#1010]
Lately, I have been running into a very strange issue when using packages with dependencies on external libraries.  Consider the following code:
```
import Arpack
Arpack.eigs(zeros(100, 100))
```

If I execute this in a Julia 1.6 REPL, it works without problems.  However, if I fire up Jupyter with a IJulia kernel and paste the same code into a cell, I get the following error:
```
could not load library "[...]/packages/Arpack/cu5By/deps/usr/lib/libarpack.so"
libopenblas64_.so.0: cannot open shared object file: No such file or directory
```

When looking at the shared library dependencies, it becomes clear that Arpack depends on the internal libraries `julia/lib/...` that are packaged with julia:
```
$ ldd ~/.var/julia/packages/Arpack/cu5By/deps/usr/lib/libarpack.so
        linux-vdso.so.1 (0x00007ffd769b9000)
        libopenblas64_.so.0 => not found
        ...
```
I am spitballing here: can it be somehow these are automatically loaded when using Julia, but not when using IJulia?

**Reproducible:**  always
**System**: arch linux, Julia 1.6.0 from official channels (not distro version!), IJulia 1.23.2

**Comment by stevengj** [comment]
IJulia is literally running within `julia`, so I don't see how the library loading could be different…

Are you sure you are running the same version of Julia in the REPL and in IJulia?   (Try running `build IJulia` in your REPL.)

**Comment by mwallerb** [comment]
Thank you for the quick reply.

I ran `] build IJulia`, unfortunately the problem still persists.

When updating Julia 1.5 -> 1.6, I simply copied the manifests from v1.5/ to v1.6/. Can that cause some issues?

**Comment by stevengj** [comment]
Are you running IJulia in a different project environment than your REPL?

**Comment by mwallerb** [comment]
I suppose, but I am not sure.  The generated kernel for jupyter reads:
```
$ cat ~/.local/share/jupyter/kernels/julia-1.6/kernel.json
  ...
  "argv": [
    "/opt/julia-1.6.0/bin/julia",
    "-i",
    "--color=yes",
    "--project=@.",
    "/home/markus/.var/julia/packages/IJulia/e8kqU/src/kernel.jl",
    "{connection_file}"
  ],
  ...
```
so I suppose it uses the current directory as a project, which should translate to `~` since I start Jupyter in my autostart?

**Comment by fredrikekre** [comment]
> When updating Julia 1.5 -> 1.6, I simply copied the manifests from environments v1.5/ to v1.6/. Can that cause some issues?

Yes, manifests are not generally compatible with multiple Julia versions. I would run `pkg> resolve` to make sure you are using packages compatible with the current Julia.

**Comment by mwallerb** [comment]
> Yes, manifests are not generally compatible with multiple Julia versions. I would run `pkg> resolve` to make sure you are using packages compatible with the current Julia.

I just did, and it was a no-op I think (said `No changes` to both Project and Manifest). I might've run this before.

**Comment by mwallerb** [comment]
@stevengj @fredrikekre Ah! I think you pointed me to something! 

> Are you running IJulia in a different project environment than your REPL?

I inadvertadely did, and this is what messed it up I think. The generated kernels use `--project=@.`.  Now that refers to the directory of the notebook.  If I run the commands just with the REPL `julia` when started in that directory everything is fine.

However: if I run the commands in the REPL when as `julia --project=@.`, it gives me the same error!

I think this is because the notebook is in a subdirectory of my project, and that project declares a manifest file.  AFAIU it now picks up this manifest file, and then something goes wrong... what I don't understand is that I have installed that project using `pkg> dev .` and everything works ...
