### ISSUE TITLE
IJulia/kernel.jl should not change the global_logger

### ISSUE THREAD

**Issue by bluesmoon** [JuliaLang/IJulia.jl#1018]
Hi,

I'm using `IJulia v1.23.2` on `julia 1.5.3`

When we start IJulia kernels, we want logs sent to a log file. To do this, we add the following to our `kernel.json`:

`-L /path/to/our/init.jl`

And this `init.jl` file pulls in `LoggingExtras`, and sends logs to a file.

Unfortunately, it seems that after this has happened, kernel.jl's `init()` function runs, and changes the `global_logger` with these lines:

```julia
    logger = Base.CoreLogging.SimpleLogger(Base.stderr)
    Base.CoreLogging.global_logger(logger)
```

This causes logs to go to the notebook instead.

Would it be possible to make this a configurable option so that the global logger is changed only if that's what we want?

Thanks.

**Comment by fredrikekre** [comment]
One option would be to use an ijulia startup file instead which is included after `IJulia.init`: https://github.com/JuliaLang/IJulia.jl/blob/6f92c422e380a610ade654d1c56f87cede6dcafa/src/kernel.jl#L26

**Comment by bluesmoon** [comment]
That sounds like something I can play with. Will let you know how it goes.

**Comment by bluesmoon** [comment]
Using `startup_ijulia.jl` worked well for us.
