### ISSUE TITLE
works in Jupyter Notebook but not in Jupyter Lab

### ISSUE THREAD

**Issue by nrbeaton** [JuliaLang/IJulia.jl#1029]
OS: Arch Linux
Julia version 1.7.0
Jupyter Lab version 3.2.4

I've added the `IJulia` package in Julia as usual.

Running `jupyter notebook` from the terminal, choosing the Julia kernel, and doing stuff works totally fine.

Running `jupyter lab` from the terminal, choosing the Julia kernel, it says "connecting" for a while and then "unknown". Trying to run something in a cell does nothing. If I try restarting the kernel it just hangs on "restarting".

Python and SageMath work fine in Jupyter Lab, it's just Julia that's failing.

If there's a log or error message somewhere that I should post then tell me how and I'll do it.

**Comment by danielwe** [comment]
What's your jupyter_server version? For me, yesterday's 1.13 release of jupyter_server broke the IJulia kernels. Rolling back to jupyter_server 1.12.1 fixed the problem. Perhaps caused by https://github.com/jupyter-server/jupyter_server/pull/628?

**Comment by nrbeaton** [comment]
Yeah it's 1.13. Looks like the issue has been raised here https://github.com/jupyter-server/jupyter_server/issues/633.

**Comment by nrbeaton** [comment]
This has now been fixed with jupyter-server 1.13.1.
