### ISSUE TITLE
Feature: show methods applicable to object  (`methodswith`)

### ISSUE THREAD

**Issue by tfiers** [JuliaLang/IJulia.jl#1033]
Idle feature idea (sparked by [these tweets](https://twitter.com/alexisgallagher/status/1483487864843214853) on "the power of the dot: what I envy about OOP").

I want to mimic the `obj.<tab>` behaviour in IPython which is extremely useful for exploring APIs and writing code:

<img src="https://user-images.githubusercontent.com/3773558/150035985-c794b784-407d-4765-987a-649bbfe41285.png" width=350>

For Julia, by example:
```julia
using FilePaths
dir = p"~/subdir"
dir|
```
, and then pressing some **shortcut key** would show:
```
absolute
chown
cp
exists
⋮
```
i.e. we call
```julia
methodswith(typeof(dir), supertypes=true)
```
, and suitably present the results, and make them iteratively filterable.
The `methodswith` call should probably be cached, as it's often rather slow.

[Same idea could be done in julia-vscode](https://github.com/julia-vscode/julia-vscode/issues/2679).

**Comment by simeonschaub** [comment]
Have you seen #38791? That seems pretty much like what you are asking for.

**Comment by tfiers** [comment]
I haven't. That is fantastic (and long live Tim Holy). Closing this!
