### ISSUE TITLE
Can we collect all outputs into one?

### ISSUE THREAD

**Issue by colinfang** [JuliaLang/IJulia.jl#1047]
I am running Notebook with Julia kernel in VS Code with Julia extension

If I print multiple things with time intervals in a cell

```julia
println(1)
sleep(1)
println(2)
sleep(1)
println(3)
sleep(1)
println(4)
```

The output looks like

``` 
  "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "3\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "4\n"
     ]
    }
   ],
```

In my VS Code, it renders weirdly

![image](https://user-images.githubusercontent.com/1499555/181904804-35d7c69d-4188-4016-960d-160f31726752.png)

Python kernel is still able to generate 1 output instead of multiple in this case and hence gets rendered correctly

```
  "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1\n",
      "2\n",
      "3\n",
      "4\n"
     ]
   }
]
```

**Comment by digital-carver** [comment]
Looks like this one has been taken care of, and can be closed now? The output is the same as the Python one now.
