### ISSUE TITLE
Errors Linking Julia 1.8 and Jupyter Lab 3.3.4-2

### ISSUE THREAD

**Issue by Imoh-mfon** [JuliaLang/IJulia.jl#1050]
How do i link Julia 1.8 to the Jupyter Lab? I use Windows 10 computer , Julia 1.8 is not listed in Jupyter lab.

See error below:
(@v1.8) pkg> add iJulia.jl
    Updating registry at `C:\Users\XXX\.julia\registries\General.toml`
ERROR: The following package names could not be resolved:
 * iJulia (not found in project, manifest or registry)
   Suggestions: IJulia IJuliaBell IJuliaTimeMachine SimJulia libjulia_jll LCIO_Julia_Wrapper_jll IBMQJulia

(@v1.8) pkg>

I have Jupyter Lab version 3.3.4-2 installed

**Comment by stevengj** [comment]
You misspelled it: `add IJulia`
