### ISSUE TITLE
Displaying videos in IJulia?

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/IJulia.jl#107]
I am interested in using `matplotlib.animation` to generate animations embedded in IJulia notebooks. However, my first attempt to translate a simple `matplotlb` into Julia code did not work:

``` julia
using PyCall
using PyPlot
@pyimport matplotlib.animation as anim
fig=figure()
ims = [[imshow(randn(300,300,3))] for i=1:100]
ani = anim.ArtistAnimation(fig, ims, interval=25, blit=true)
show()
```

Next, I tried rendering the animation to a video file and loading it in IJulia. Using `display("video/mp4",...)` or `display("video/mpeg",...)` did not work. But embedding the HTML video tag _almost_ worked...

``` julia
using PyCall
using PyPlot
@pyimport matplotlib.animation as anim
fig=figure()
ims = [[imshow(randn(300,300,3))] for i=1:100]
ani = anim.ArtistAnimation(fig, ims, interval=25, blit=true)
ani[:save]("noise.mpg")
display("text/html", """<video autoplay controls><source src="noise.mpg" type="video/mpeg"></video>""")
```

This code renders an empty box and video playback controls, but the controls don't do anything, nor is a video displayed.

![untitled](https://f.cloud.github.com/assets/1732/1480359/1ad6504e-46a9-11e3-8c04-3ccb32d86970.png)

Am I on the right track to get embedded animations?

**Comment by Omer80** [comment]
Hi, I am also trying to animate a simulation using Julia. I would like to try to use the example given in matplotlib for dynamic image animation like here:

    ims = []
    for i in range(60):
    x += np.pi / 15.
    y += np.pi / 20.
    im = plt.imshow(f(x, y), cmap='viridis', animated=True)
    ims.append([im])

    ani = animation.ArtistAnimation(fig, ims, interval=50, blit=True, repeat_delay=1000)

(taken from http://matplotlib.org/examples/animation/dynamic_image2.html)

Is there an equivalent way to make it in Julia?

**Comment by JobJob** [comment]
Adapting the above, this works though the loop is a little slow:

    using PyCall
    using PyPlot
    @pyimport matplotlib.animation as anim# First set up the figure, the axis, and the plot element we want to animate
    f(x,y) = sin(x) .+ cos(y)
    fig = figure()
    ims = []
    nx = 120
    ny = 100
    x = repmat(linspace(0, 2pi, nx), 1, ny)
    y = repmat(linspace(0, 2pi, ny)', nx, 1)
    @show size(x) size(y)
    for i in 1:20
        x += pi ./ 15
        y += pi ./ 20
        im = imshow(f(x, y); cmap="viridis")
        push!(ims, PyCall.PyObject[im])
    end

    ani = anim.ArtistAnimation(fig, ims, interval=50, blit=true, repeat_delay=1000)
    ani[:save]("ani.mp4", extra_args=["-vcodec", "libx264", "-pix_fmt", "yuv420p"]);

    # # call our new function to display the animation
    display("text/html", string("""<video autoplay controls><source src="data:video/x-m4v;base64,""",
            base64(open(readbytes,"ani.mp4")),"""" type="video/mp4"></video>"""))

**Comment by Omer80** [comment]
@JobJob - Thanks for the guidance. I have some problem in using the code, it tries to install matplotlib, and then exit with importerror  - http://dpaste.com/0PB2GKV. Someone knows what could be the problem?
