### ISSUE TITLE
Output for semicolon-terminated lines with comments

### ISSUE THREAD

**Issue by ihnorton** [JuliaLang/IJulia.jl#109]
The output of a semicolon-terminated line with comment is not suppressed in IJulia (repl works as expected):

```
b = [ 5:9 ];    # foo
```

and

```
b; # foo
```

both dump the contents, but

```
b;
```

does not.

**Comment by tlnagy** [comment]
This can be closed as of v0.4.3

```{.julia}
julia> 1
1

julia> 1;

julia> 1; #

julia>
```

**Comment by stevengj** [comment]
@tlnagy, that is the REPL, and the REPL still doesn't get it right: as of Julia 0.5, `3 # ;` suppresses output even though the semicolon is inside a comma.

**Comment by tlnagy** [comment]
Ah, I must've gotten confused which repository I was in

**Comment by mgiugliano** [comment]
Unfortunately, on Julia 0.4.5 + Jupyter, I can routinely reproduce the same bug:

1 + 2
and
1 + 2; #this is a comment

both produce the same output. It can be prevented by adding a final ; to each comment

**Comment by stevengj** [comment]
(I've yet to hear a convincing reason why we should care enough to implement the parsing sophistication required to handle this reliably.    This is not a question of Julia behavior, just a question of whether you want interactive output.  If you want to suppress interactive output, it's not that hard to end your code cell with a semicolon.)

**Comment by JobJob** [comment]
Hi, 
I actually wrote a newer version of the regex on this line a while ago: https://github.com/JuliaLang/IJulia.jl/blob/master/src/execute_request.jl#L161

I guess I forgot to make a PR or maybe I wasn't 100% sure about how reliably it would work. Anyway, here is the regex and some test cases if someone else wants to run with it, don't have too much time to make a PR right now:

    code_samples = ["super(Tuple); #fred",
        "super(Tuple); #fred#fred",
        "super(Tuple); #fred #fred",
        "super(Tuple); ",
        "a=\"fred;123\"",
    ""]
    map(code->ismatch(r";\s*(#.*){0,1}$", code), code_samples)

**Comment by stevengj** [comment]
@JobJob, your regex gives the wrong answer for a `; #` inside a string, e.g. `"\"; #fred\""`

**Comment by StefanKarpinski** [comment]
There's no fully correct general way to do this other than having the Julia parser indicate somehow if the last expression had a trailing newline, which doesn't seem worth it to fix this, but maybe a convincing argument could be made...

**Comment by stevengj** [comment]
@StefanKarpinski, in principle you don't need a full-blown parser.  But you do need to recognize the various types of strings, comments, and escaping, walking backwards with a little finite-state-machine at least.  I agree that it doesn't seem worth it.

**Comment by stevengj** [comment]
Also, my feeling is that false positives (failing to output when the user wants output) are worse than false negatives (outputting when the user wants to suppress output).  The latter can always be fixed by adding another `;` at the end, but trying to wrangle output from `"\"; #fred\""` would be annoying.

**Comment by stevengj** [comment]
I'm closing this issue as we now use Base.REPL.ends_with_semicolon.  It is still not perfect (though improved somewhat thanks to JuliaLang/julia#20918), but it is consistent with the REPL.  Any further problems should be fixed in Julia itself.
