### ISSUE TITLE
Broken display of `AbstractString`s when preferred MIME type `istextmime`

### ISSUE THREAD

**Issue by jakobjpeters** [JuliaLang/IJulia.jl#1113]
### Description

Users implementing `show` methods for an `AbstractString` will have a broken display if the preferred MIME type `istextmime`. A motivating example is in Typstry.jl, which implements `show` for `"image/png"` and `"image/svg+xml"`. Both of these methods work in Pluto.jl, but only `"image/png"` works in IJulia.jl. This is because `"image/svg+xml"` is preferred over `"image/png"`, but this format assumes that an `AbstractString` is ["raw data"](https://github.com/JuliaLang/IJulia.jl/blob/185533665803d5c0f9de6103d0c386422d9e1c6a/src/inline.jl#L24). [Instead of dispatching to `show`, it is returned as a `String`](https://github.com/JuliaLang/IJulia.jl/blob/185533665803d5c0f9de6103d0c386422d9e1c6a/src/inline.jl#L41-L43).

I don't really understand this assumption, why is it being used? The only thing I have found so far is the same assumption in [`repr`](https://docs.julialang.org/en/v1/base/io-network/#Base.repr-Tuple{MIME,%20Any}) and presume that's where it came from. A notable difference is that users are able to implement `repr` to patch in a fix.

### Possible Solutions

- Remove the assumption the an `AbstractString` is "raw data"
    - I don't know if or what relies on this assumption
- Export `israwtext`
    - Users can implement this to override the assumption
    - Requires packages to depend on IJulia.jl
- Change [this line](https://github.com/JuliaLang/IJulia.jl/blob/185533665803d5c0f9de6103d0c386422d9e1c6a/src/inline.jl#L41) to `String(repr(mime, x; context = InlineIOContext(buf)))`
    - Users can implement a fix for `repr`, while preserving the preexisting behavior otherwise because `repr` uses the same assumption
    - Extra work to convert some values to a `String`

### 1. The output of `versioninfo()`

IJulia v0.24.2

```
julia> versioninfo()
Julia Version 1.10.3
Commit 0b4590a5507 (2024-04-30 10:59 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, tigerlake)
Threads: 8 default, 0 interactive, 4 GC (on 8 virtual cores)
Environment:
  JULIA_EDITOR = hx
```

### 2. How you installed Julia

juliaup

### 3. A minimal working example (MWE), also known as a minimum reproducible example

```julia
julia> using IJulia

julia> struct S <: AbstractString end

julia> Base.ncodeunits(::S) = 0;

julia> Base.iterate(::S) = nothing;

julia> Base.show(io::IO, ::MIME"image/svg+xml", ::S) = print(io, "s");

julia> S()
""

julia> show(stdout, "image/svg+xml", S())
s
julia> IJulia.display_dict(S())
Dict{String, Union{String, JSON.Writer.JSONText}} with 2 entries:
  "text/plain"    => "\"\""
  "image/svg+xml" => ""
```

**Comment by stevengj** [comment]
Why would an `AbstractString` type have a method to display as `image/svg+xml`?  That doesn't sound like a string?

**Comment by jakobjpeters** [comment]
My particular use case is for a `TypstString` in [Typstry.jl](https://github.com/jakobjpeters/Typstry.jl), which represents source text for the [Typst typsetting system](https://typst.app/). This text can be compiled to PDF, PNG, and SVG via Typst_jll.jl, so there's a direct correspondence between a `TypstString` and an SVG. Although the underlying implementation differs, I'd like `typst"$ 1 / x $` to be rendered in notebooks in a similar manner to `L"$ \frac{1}{x} $"`.

Thank you for the clarification! Does `display_dict` determine resulting output options? [This comment](https://github.com/JuliaLang/IJulia.jl/blob/185533665803d5c0f9de6103d0c386422d9e1c6a/src/inline.jl#L93-L94) seems to indicate so. If so, then is the solution to keep the current behavior for calls to `limitstringmime` except from within `display_dict`?

**Comment by stevengj** [comment]
Yes, it would probably suffice to change the definition of `limitstringmime` to:
```jl
function limitstringmime(mime::MIME, x, forcetext=false, mayberawtext=true)
```
change [this line](https://github.com/JuliaLang/IJulia.jl/blob/185533665803d5c0f9de6103d0c386422d9e1c6a/src/inline.jl#L40) to
```jl
if israwtext(mime, x) && mayberawtext
```
and change [this line](https://github.com/JuliaLang/IJulia.jl/blob/185533665803d5c0f9de6103d0c386422d9e1c6a/src/display.jl#L67) to:
```jl
display_mimestring(m::MIME, x) = (m, limitstringmime(m, x, false, false))
```

**Comment by stevengj** [comment]
Alternatively, an even simpler solution would be to change [this line](https://github.com/JuliaLang/IJulia.jl/blob/185533665803d5c0f9de6103d0c386422d9e1c6a/src/inline.jl#L25) to
```jl
israwtext(m::MIME, x::AbstractString) = !showable(m, x)
```
so that we only treat `x` as "raw" MIME data if it doesn't have it's own `show` method for that MIME type.
