### ISSUE TITLE
Pkg REPL mode broken in 1.11-rc4

### ISSUE THREAD

**Issue by nilshg** [JuliaLang/IJulia.jl#1119]
Already noticed this in rc3 but it's still a problem and I've just set up a completely new machine so could confirm that this happens on a fresh install (Windows 11, Julia 1.11-rc4 installed through Juliaup, then just `add IJulia; using IJulia; notebook()` and allowing the standard install of miniconda).

Then in a notebook I do:

```
] st
```

and get:

```
MethodError: no method matching do_cmd(::IJulia.MiniREPL, ::String; do_rethrow::Bool)
The function `do_cmd` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  do_cmd(::Pkg.REPLMode.Command, ::Any) got unsupported keyword argument "do_rethrow"
   @ Pkg ...\.julia\juliaup\julia-1.11.0-rc4+0.x64.w64.mingw32\share\julia\stdlib\v1.11\Pkg\src\REPLMode\REPLMode.jl:398
```

I assume this is related to the excision of Pkg?

**Comment by nilshg** [comment]
Just to prevent things from getting slackholed, @mkitti identified that in this commit:

https://github.com/JuliaLang/Pkg.jl/commit/12d2de14ec8660b867d75275b260f3664f44c40a

the `do_rethrow` keyword of `do_cmd` got removed. He suggested potentially dropping the keyword at the call site:

https://github.com/JuliaLang/IJulia.jl/blob/60568fabbe8abd54ae26b2acf2c426c830ed801b/src/execute_request.jl#L51

I'm not familiar enough with the IJulia codebase to understand whether that's a good idea though!

**Comment by nilshg** [comment]
This is great, thanks - might this warrant a patch release?

**Comment by stevengj** [comment]
https://github.com/JuliaRegistries/General/pull/118774
