### ISSUE TITLE
means of suppressing warnings (but not errors?)

### ISSUE THREAD

**Issue by catawbasam** [JuliaLang/IJulia.jl#116]
Thank you for your work on IJulia.  This is perhaps more a question than issue: is there a means of suppressing warnings but not errors?

I'd like to suppress nuisance warnings like the one below.  ipython_notebook_config.py contains a directive to suppress STDERR completely :
`# c.IPKernelApp.no_stderr = False`

StackOverflow also contains a promising hint at http://stackoverflow.com/questions/9031783/hide-all-warnings-in-ipython  -- but it doesn't appear to work with IJulia. 

(I'm using Julia 0.2 on 64-bit Windows)

```
[24]: using Gadfly

before the new definition.
Warning: New definition 
    |(NAtype,Any) at C:\Users\keithc\.julia\DataFrames\src\operators.jl:385
is ambiguous with: 
    |(Any,SynchronousStepCollection) at C:\Users\keithc\.julia\BinDeps\src\BinDeps.jl:286.
To fix, define 
    |(NAtype,SynchronousStepCollection)
before the new definition.
Warning: New definition 
    |(Any,NAtype) at C:\Users\keithc\.julia\DataFrames\src\operators.jl:385
is ambiguous with: 
    |(SynchronousStepCollection,Any) at C:\Users\keithc\.julia\BinDeps\src\BinDeps.jl:283.
To fix, define 
    |(SynchronousStepCollection,NAtype)
before the new definition.
```

**Comment by dmoliveira** [comment]
What is the end for this proposition?
I have the same problem until today. I can hidden warning messages at my notebook adding:
`display: none` in CSS. But when pushed to git the warnings returns because of my local workaround.
Any idea how to solve this? 

At the end becomes very incipient to share notebooks. Looks my [sample here](https://github.com/dmoliveira/my-juliabox/blob/master/Data%20Analysis%20-%20Julia%20%2B%20Gadfly%20-%20Scatter-Matrix%20Example.ipynb).

**Comment by zhangliye** [comment]
is it solved?  I have the same problem.  With these warnings, the notebook page looks really ugly.

**Comment by stevengj** [comment]
Nowadays, you can easily install a kernel that does suppresses deprecation warnings with
```
using IJulia
IJulia.installkernel("Julia nodeps", "--depwarn=no")
```
as explained in the README.  Deprecations are the main source of annoying warnings in typical code.

**Comment by zhangliye** [comment]
In fact, I want to suppress all kinds of warnings, including deprecation warnings.

**Comment by stevengj** [comment]
That's an issue for Julia itself.  If the `julia` executable has a flag to suppress all warnings (currently, it doesn't), then you can use `installkernel` to set up a kernel with that flag.

**Comment by zhangliye** [comment]
Got it. I think this function would be meaningful for some users. Thank you so much!

**Comment by maximerischard** [comment]
```
logging(DevNull; kind=:warn)
```
might also help, though I don't know how long that API will be around for.
