### ISSUE TITLE
Json config file. 

### ISSUE THREAD

**Issue by Carreau** [JuliaLang/IJulia.jl#129]
Just to keep you guys posted, you can now express most of config in json file. 
Same name that usual config file but `.py`-> `.json`. 
Json take precedence on `.py` and are just required to have a top lever `"version":1` key. 

Maybe it will help you to maintain custom Julia profile by processing json, than relying on regex.

cf https://github.com/ipython/ipython/pull/4265

**Comment by stevengj** [comment]
Resolved now that we are using only Jupyter.
