### ISSUE TITLE
Unable to type multiline Julia code in IJulia's plain console.

### ISSUE THREAD

**Issue by Ismael-VC** [JuliaLang/IJulia.jl#135]
ismaelvc@vm-0:~$ sudo ipython console --profile=julia
    Python 2.7.4 (default, Apr 19 2013, 18:28:01)
    Type "copyright", "credits" or "license" for more information.
    IPython 1.1.0 -- An enhanced Interactive Python.
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.
    IPython profile: julia
    Starting kernel event loops.

    In [1]: for i in 1:10
    syntax: incomplete: premature end of input
    at In[1]:2
 
    In [2]: for i = 1:10
    syntax: incomplete: premature end of input
    at In[2]:2
 
    In [3]: for i = 1:10 print(i) end                                                                                                                                                    
    12345678910

    In [4]: function test()
    syntax: incomplete: premature end of input
    at In[4]:2
 
    In [5]: function test() println("TEST") end
    Out[5]: test (generic function with 1 method)
 
    In [6]: test()
    TEST

**Comment by stevengj** [comment]
Further discussion of this problem should happen at jupyter/jupyter_console#11
