### ISSUE TITLE
Output not shown on Windows7

### ISSUE THREAD

**Issue by few** [JuliaLang/IJulia.jl#164]
I have a 32 bit julia 0.3-pre on Windows 7 64bit + 32 bit python-2.7. IJulia installs and starts without problems, but there are no output cells in the notebook (using Firefox 24.4.0). It appears to execute what I put into the input cells, but the output is just not shown.

There are no error messages in the console.

Julia Version:
Version 0.3.0-prerelease+2444 (2014-04-03 00:04 UTC)
Commit 9a00d2e* (0 days old master)
i686-w64-mingw32

**Comment by stevengj** [comment]
Closing this unless it can be reproduced with the latest version.
