### ISSUE TITLE
Notebook: Syntax highlighting not working in Safari

### ISSUE THREAD

**Issue by apleonhardt** [JuliaLang/IJulia.jl#168]
This may be a minor issue but is probably worth reporting: For some reason, Julia syntax highlighting doesn't work for IJulia notebooks in Safari on Mac OS X 10.9. I've tried to pin down the issue:

* Highlighting works in Python mode.
* Highlighting works in Chrome (calling up the very same IPython instance).
* No JS errors are thrown when IJulia boots up.

I'm not very knowledgeable when it comes to JS. A couple of amateurish observations: The language setting for all cells is correctly set to ```Julia```. Loading up the notebook in Julia mode does throw up loads of CSS warnings whereas loading a Python notebook doesn't. Maybe it's something trivial. Can any Mac user confirm this observation?

**Comment by zmughal** [comment]
This may have been fixed in IPython 3.2. See the issue at <https://github.com/EntropyOrg/p5-Devel-IPerl/issues/40> for more details.

**Comment by stevengj** [comment]
@zmughal, that's good to hear.  (The latest IJulia `master` dropped support for IPython 2.x.)
