### ISSUE TITLE
[PackageEvaluator.jl] Your package IJulia may have a testing issue.

### ISSUE THREAD

**Issue by IainNZ** [JuliaLang/IJulia.jl#175]
*This issue is being filed by a script, but if you reply, I will see it.*

[PackageEvaluator.jl](https://github.com/IainNZ/PackageEvaluator.jl) is a script that runs nightly. It attempts to load all Julia packages and run their test (if available) on both the stable version of Julia (0.2) and the nightly build of the unstable version (0.3).

The results of this script are used to generate a [package listing](http://iainnz.github.io/packages.julialang.org/) enhanced with testing results.

The status of this package, IJulia, on...

* Julia 0.2 is **'No tests, but package loads.'** [![PackageEvaluator.jl](http://iainnz.github.io/packages.julialang.org/badges/using_pass.svg)](http://iainnz.github.io/packages.julialang.org/?pkg=IJulia&ver=0.2)
* Julia 0.3 is **'No tests, but package loads.'** [![PackageEvaluator.jl](http://iainnz.github.io/packages.julialang.org/badges/using_pass.svg)](http://iainnz.github.io/packages.julialang.org/?pkg=IJulia&ver=0.3)

*'No tests, but package loads.'* can be due to their being no tests (you should write some if you can!) but can also be due to PackageEvaluator not being able to find your tests. Consider adding a [`test/runtests.jl`](https://github.com/JuliaLang/julia/pull/6191) file.

*'Package doesn't load.'* is the worst-case scenario. Sometimes this arises because your package doesn't have BinDeps support, or needs something that can't be installed with BinDeps. If this is the case for your package, please [file an issue](https://github.com/IainNZ/PackageEvaluator.jl) and an exception can be made so your package will not be tested.

**This automatically filed issue is a one-off message. Starting soon, issues will only be filed when the testing status of your package changes in a negative direction (gets worse). If you'd like to opt-out of these status-change messages, reply to this message.**

**Comment by stevengj** [comment]
Seems no longer relevant.
