### ISSUE TITLE
Syntax highlighting dies on Julia upgrade

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/IJulia.jl#176]
I have found that when I install a new version of Julia, (I live on Homebrew-built julia) I must `Pkg.build("IJulia")` in order to get syntax highlighting to come back.  I'm not entirely sure how consistent this is, since I only made the connection between syntax highlighting and `Pkg.build("IJulia")` today, but my symptoms are that syntax highlighting doesn't work, (in Chrome or Safari) force-refreshing the page doesn't fix anything, (CMD-SHIFT-R in Chrome) and running `Pkg.build("IJulia")` inside of Julia looks like it doesn't do anything:

```julia
julia> Pkg.build("IJulia")
INFO: Building Homebrew
HEAD is now at c588ffb Remove git rebasing code that slipped through
HEAD is now at 1b85de5 Update netcdf bottle
INFO: Building Nettle
INFO: Building ZMQ
INFO: Building IJulia
Found IPython version 2.0.0 ... ok.
Creating julia profile in IPython...
(Existing KernelManager.kernel_cmd setting in ipython_config.py is untouched.)
(Existing IPythonWidget.execute_on_complete_input setting in ipython_qtconsole_config.py is untouched.)
(Existing FrontendWidget.lexer_class setting in ipython_qtconsole_config.py is untouched.)
(Existing NotebookApp.port setting in ipython_notebook_config.py is untouched.)
(Existing ipynblogo.png file untouched.)
(Existing ipynblogo.svg file untouched.)
(Existing favicon.ico file untouched.)
(Existing custom.js file untouched.)
(Existing julia.js file untouched.)
```

But when I force refresh the page, (Without even restarting the ipython notebook server) syntax highlighting suddenly works again.

**Comment by stevengj** [comment]
Seems resolved?
