### ISSUE TITLE
Plotting with Winston causes kernel to die

### ISSUE THREAD

**Issue by lendle** [JuliaLang/IJulia.jl#180]
If this should be repored to Winston.jl instead of here let me know.  It's probably some issue with my setup and not IJulia or Winston, but I've run out of ideas to debug it. 

I can load Winston with `using Winston`, but when I try to `plot`, the kernel dies in both the notebook and qtconsole. Plotting in the notebook works with Gadfly, and Winston works fine in a normal, non-IJulia julia session. I'm running arch linux, but did not have this problem on Ubuntu or OS X. I've tried with ipython versions 1.2 and 2.1. 

```
Julia Version 0.3.0-prerelease+3121
Commit e1468d5 (2014-05-19 22:16 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY)
  LAPACK: libopenblas
  LIBM: libopenlibm
```
Nothing useful shows up in the ipython console: 
```
2014-05-21 15:08:28.492 [NotebookApp] Saving notebook at /Untitled0.ipynb
2014-05-21 15:08:28.692 [NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel bc34b423-1176-4730-8eae-f9a23296792e restarted
Starting kernel event loops.
```
I also tried [this trick](https://github.com/JuliaLang/IJulia.jl/issues/178#issuecomment-43668196) for debugging but couldn't get it to work.

**Comment by stevengj** [comment]
Closing unless this is reproducible with a modern version.
