### ISSUE TITLE
DisplayAs type for using ad-hoc mimetypes?

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/IJulia.jl#187]
Sometimes I want to write one-off functions in the notebook for displaying things in a particular way. We could add a simple definition like this:

```
immutable DisplayAs{M<:MIME}
    data
end

writemime{M<:MIME}(io::IO, ::M, x::DisplayAs{M}) = write(io, x.data)
```

Then you could write functions like

```
asimage(x) = DisplayAs{MIME"image/png"}(to_png_data(x))
```

that specify how to display things without defining a new type with its own `writemime` methods.

**Comment by stevengj** [comment]
Dup of JuliaLang/julia#13256
