### ISSUE TITLE
Syntax highlighting not working in Firefox

### ISSUE THREAD

**Issue by berceanu** [JuliaLang/IJulia.jl#193]
Firefox v 30.0
IPython 2.1.0
IJulia 0.1.12
OS: Linux

I tried refresing without any luck. In Chromium/Google Chrome it seems to work fine (although sometimes a refresh is needed).

**Comment by mfsch** [comment]
I have the same issues with Firefox on Ubuntu 14.10. When a notebook is loaded, all code cells are not highlighted until their type is changed to something else and back to code. In Chrome, highlighting works fine.

**Comment by Carreau** [comment]
> I have the same issues with Firefox on Ubuntu 14.10. When a notebook is loaded, all code cells are not highlighted until their type is changed to something else and back to code. In Chrome, highlighting works fine.

What version of IPython ?

**Comment by mfsch** [comment]
ipython3 version: 2.3.0
IJulia version: 0.2.1
Julia version 0.3.2
Firefox version: 36.0.1

**Comment by Carreau** [comment]
This is fixed on IPython 3.  2.x is legacy. 3.x is stable.

**Comment by mfsch** [comment]
Thanks, upgrading IPython did indeed fix the problem.

**Comment by fakerms** [comment]
I have the same problem. Firefox (version 84.0) is on Windows 10. Jupyter is on Ubuntu 20.04.1 LTS (WSL2).
IPython version is 7.18.1.
IJulia v1.23.1
```julia
> versioninfo()
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 24
```
Not always failed on Firefox, but randomly.
Works fine on Edge.

**Comment by travigd** [comment]
This issue is seven years old. Please create a new one (though your problem is not actually with IJulia).
