### ISSUE TITLE
Typing combining character puts cursor in strange location when using Consolas font

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/IJulia.jl#195]
Here are two IJulia cells.

![screen shot 2014-06-17 at 5 32 41 pm](https://cloud.githubusercontent.com/assets/1732/3306962/16e0564c-f667-11e3-950e-0c4df05efce6.png)

In the upper cell, I typed `\sigma<TAB>\hat<TAB>=1`

In the lower cell, I typed `\hat<TAB>\sigma<TAB>=1`

For comparison, here is what the command line looks like for me (OSX 10.9.3):

![screen shot 2014-06-17 at 5 33 01 pm](https://cloud.githubusercontent.com/assets/1732/3306966/1c5da1a6-f667-11e3-911e-5c33941ca1d5.png)

On most recent Julia master and IJulia v0.1.12.

**Comment by stevengj** [comment]
Seems to be Somebody Else's Problem (either Microsoft's or Jupyter's) if it is still happening.
