### ISSUE TITLE
Installing IPython notebook and dependencies as part of IJulia setup.

### ISSUE THREAD

**Issue by johansigfrids** [JuliaLang/IJulia.jl#199]
Getting IPython setup can be a bit hairy, and is probably the trickiest bit I have to walk someone through when I want them to give Julia/IJulia a try. It would be great if this could happen automagically as part of installing IJulia. 

Getting it to work as part of the install could be hairy as well but maybe it could be made easier by packaging up IPython and dependecies into a binary with something like PyInstaller and then installing the resulting executable as a binary dependency.

**Comment by htgoebel** [comment]
Please not: I just updates PyInstaller to support pyzmq 14.0+

**Comment by tkelman** [comment]
@htgoebel thanks for the update. Does PyInstaller allow building 32 bit executables on 64 bit Windows at this time?

**Comment by davidanthoff** [comment]
I've continued on my branch a little bit. Right now I'm using miniconda to install python, that seems to solve most of the problems I pointed out earlier. There are still a few problems on this, but I'm working on it and I should have some time for this now.

**Comment by stevengj** [comment]
miniconda is something that should work on MacOS too, ideally, although I'm sure you have some Windows-specific stuff.

**Comment by davidanthoff** [comment]
My code is Windows only for now, but I'm sure something very similar could be done on other platforms as well. My branch should be ready for other people to try out/test etc in a few days at most, I'm more or less done just want to do some more tests.

**Comment by tkelman** [comment]
Done by #357!
