### ISSUE TITLE
Breaks on OSX

### ISSUE THREAD

**Issue by nfoti** [JuliaLang/IJulia.jl#2]
I've played with this code a bit on OSX by changing the path to julia-release.so to julia-release.dylib.  When I try to load the magic I get an error that the "Resource is temporarily unavailable".  I've also tried running the lines from `julia.py` that initialize julia, load PyCall, etc. inside an IPython session and have found that the code breaks because the line `self.jcall('PyObject')` returns `None` and the resulting calls that use the returned function seg fault because of this.  However, on Linux the call to `sefl.jcall('PyObject')` returns a function pointer that can be used.  Is there something obvious that needs to be done when initializing julia-release.dylib on OSX?  I'm going to look through the code for the repl, but I was just wondering if anyone knew off the top of their head.

It would be great to get the julia magic working as the ipython notebook is an awesome way to do research.  I'd be glad to help in any way I can.

Thanks.

**Comment by stevengj** [comment]
Problems in this should now be directed to https://github.com/JuliaLang/pyjulia
