### ISSUE TITLE
Insertion of greek letters

### ISSUE THREAD

**Issue by dhoegh** [JuliaLang/IJulia.jl#202]
Hi, since Julia is fully capable of assigning values to unicode letters and no one has greek letters on their keyboard, it could be a great feature if the insertion of greek letters could be made as autocompletion just like code completion. I’m visualizing something like:
\theta press ctrl+space to get: θ.
So when you want to insert a greek letter you write \ in front just like latex, you could maybe also just skip the backslash. I tried to take a look in custom.js where it probably should be implemented, but my javascript skills is not sufficient:(

**Comment by Suckhwan** [comment]
thanks a lot!

**Comment by albz** [comment]
Can anyone explain me the following: on a mac you can write the most common Greek letter, eg pi, by pressing alt+p. I am wondering whether this sort of shortcuts cannot be used on a Windows console. What's the issue?

**Comment by stevengj** [comment]
@albz, that's a feature of the Mac keyboard (true across all programs, not just Jupyter): there are special key combinations for typing accented Latin characters and a few other symbols like π.   Windows doesn't have this.

**Comment by dnabanita7** [comment]
It is not working on colab.

**Comment by sx-meng** [comment]
> Just hit the tab key after typing `\alpha`

It does not seem to work in nterat with Julia kernel. How to type a Greek letter in nterat with IJulia? Thanks.
