### ISSUE TITLE
Errors while installing IJulia on Windows.

### ISSUE THREAD

**Issue by vasili111** [JuliaLang/IJulia.jl#204]
I Use Windows x64, Anaconda-2.0.1-Windows-x86_64,  julia-0.3.0-rc1-0480f1b-win64. When installing IJulia, I run Julia as administrator.  I am getting errors when trying to install IJulia:

julia> Pkg.add("IJulia")
INFO: Installing BinDeps v0.2.14
INFO: Installing HTTPClient v0.1.4
INFO: Installing IJulia v0.1.12
INFO: Installing JSON v0.3.7
INFO: Installing LibCURL v0.1.3
INFO: Installing LibExpat v0.0.4
INFO: Installing Nettle v0.1.4
INFO: Installing REPLCompletions v0.0.1
INFO: Installing URIParser v0.0.2
INFO: Installing URLParse v0.0.0
INFO: Installing WinRPM v0.1.1
INFO: Installing ZMQ v0.1.12
INFO: Installing Zlib v0.1.7
INFO: Building WinRPM
Warning: error initializing module WinRPM:
ErrorException()
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win3
2/openSUSE_Factory//repodata/repomd.xml
===============================[ ERROR: WinRPM ]================================

error compiling xp_parse: error compiling xp_make_parser: could not load module
libexpat-1: %1 is not a valid Win32 application.

while loading C:\Users\admin\.julia\v0.3\WinRPM\deps\build.jl, in expression sta
rting on line 2

================================================================================

INFO: Building LibCURL
INFO: Updating WinRPM package list
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win3
2/openSUSE_Factory//repodata/repomd.xml
===============================[ ERROR: LibCURL ]===============================

error compiling xp_parse: error compiling xp_make_parser: could not load module
libexpat-1: %1 is not a valid Win32 application.

while loading C:\Users\admin\.julia\v0.3\LibCURL\deps\build.jl, in expression st
arting on line 13

================================================================================

INFO: Building Nettle
INFO: Updating WinRPM package list
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win3
2/openSUSE_Factory//repodata/repomd.xml
===============================[ ERROR: Nettle ]================================

error compiling xp_parse: error compiling xp_make_parser: could not load module
libexpat-1: %1 is not a valid Win32 application.

while loading C:\Users\admin\.julia\v0.3\Nettle\deps\build.jl, in expression sta
rting on line 35

================================================================================

INFO: Building ZMQ
INFO: Building IJulia
Found IPython version 2.1.0 ... ok.
Creating julia profile in IPython...
Changing KernelManager.kernel_cmd to ["C:\\Users\\admin\\AppData\\Local\\Julia-0
.3.0-rc1\\bin\\julia.exe", "-F", "C:\\Users\\admin\\.julia\\v0.3\\IJulia\\src\\k
ernel.jl", "{connection_file}"] in ipython_config.py...
(Existing IPythonWidget.execute_on_complete_input setting in ipython_qtconsole_c
onfig.py is untouched.)
(Existing FrontendWidget.lexer_class setting in ipython_qtconsole_config.py is u
ntouched.)
(Existing NotebookApp.port setting in ipython_notebook_config.py is untouched.)
(Existing ipynblogo.png file untouched.)
(Existing ipynblogo.svg file untouched.)
(Existing favicon.ico file untouched.)
(Existing custom.js file untouched.)
(Existing julia.js file untouched.)

================================[ BUILD ERRORS ]================================

WARNING: WinRPM, LibCURL and Nettle had build errors.

 - packages with build errors remain installed in C:\Users\admin\.julia\v0.3
 - build a package and all its dependencies with `Pkg.build(pkg)`
 - build a single package by running its `deps/build.jl` script

================================================================================

INFO: Package database updated

julia> ipython notebook --profile julia
ERROR: syntax: extra token "notebook" after end of expression

julia>

**Comment by reevu** [comment]
@ihnorton 
shell> ipython notebook --profile=julia 
worked for me

**Comment by stevengj** [comment]
Nowadays (with IPython 3) it should just be `ipython notebook`; no need for the profile.

Sounds like this issue can be closed.

**Comment by NikolaMandic** [comment]
I have this issue 
WARNING: Nettle and ZMQ had build errors.

 - packages with build errors remain installed in C:\Users\user\.julia\v0.3
 - build the package(s) and all dependencies with `Pkg.build("Nettle", "ZMQ")`
 - build a single package by running its `deps/build.jl` script

**Comment by NikolaMandic** [comment]
windows x64
latest julia and jupyter downloaded maybe yesterday

**Comment by stevengj** [comment]
@NikolaMandic, please (a) file separate issues when your problem is different than that of the original issue and (b) file issues with the appropriate package (c) file issues with the appropriate packages (if your problem is building Nettle, file an issue with nettle) and (d) check to be sure it is not a firewall issue (try downloading from those URLs manually — they might be blocked by some firewall you are behind).
