### ISSUE TITLE
Add help information to tooltip until docstrings finalized?

### ISSUE THREAD

**Issue by tlnagy** [JuliaLang/IJulia.jl#219]
It's much more difficult to do exploratory work in IJulia vs IPython because the helpful tooltips aren't that useful. It would be nice to include the information from the `help()` for a given function until the docstring syntax/implementation is finalized.

**Comment by cdagnino** [comment]
Is this in the works? I think this would make a ton of difference for many people!

**Comment by stevengj** [comment]
@Carreau and @minrk, I tried implementing this in our `object_info_request` handler, but it looks like this handler is never being called in IPython 3.   Does the compatibility shim not send these messages?

**Comment by minrk** [comment]
I am seeing oinfo requests when I trigger inspection from IPython 3 to an IPython 2 kernel. I see it when I hit shift-tab.

**Comment by stevengj** [comment]
Ah, shift-tab was it; I forgot the shortcut.  (This doesn't seem to be very discoverable, e.g. it is not listed in the help.)

Anyway, commit a6e57462726006b049228f35f0e415d9f5b95725 seems to be working, so this issue is now fixed.

**Comment by minrk** [comment]
It is in the keyboard shortcut quick-help dialog:

![screen shot 2015-05-21 at 18 35 39](https://cloud.githubusercontent.com/assets/151929/7762359/505ebd10-ffe8-11e4-9576-346e0ff7ccda.PNG)

**Comment by stevengj** [comment]
You're right, I missed it!

**Comment by ppau1** [comment]
I can't see the docstring when clicking shift-tab? Is this implemented?
