### ISSUE TITLE
print not working for %%julia magic under ipython notebook

### ISSUE THREAD

**Issue by chtlp** [JuliaLang/IJulia.jl#222]
Hi, I am trying to mix some Julia code with python, and I installed IJulia, and

```
cd ~/.julia/v0.3/IJulia/python/
python setup.py install
```

to install the julia magic. I can run the julia code with `%%julia`, but the output of the cell only shows the last return value, and is not showing the print results. To demonstrate, I will put a screenclip here:

￼
![screenshot](https://cloud.githubusercontent.com/assets/568535/3948097/b221c760-269d-11e4-82ba-71844a22fbed.png)

What might be wrong? I am running the server under CentOS 6 with Anaconda.

**Comment by stevengj** [comment]
This is now a pyjulia issue.
