### ISSUE TITLE
Ijulia notebook in the console

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/IJulia.jl#223]
This was a little too funny for me not to open an issue about.  I just got access to a new cluster at the University of Washington, and so of course the first thing I do is load IJulia onto it!  I then run `ipython notebook --profile-julia` over SSH.... and this is what greets my eyes:

![screen shot 2014-08-21 at 12 09 00 am](https://cloud.githubusercontent.com/assets/130920/3991738/f28c2db6-28e8-11e4-89cb-61a1324c1750.png)

At first, I think to myself "Wow, an in-terminal IJulia Notebook?!  We're insane!".  Then I realize it's just because `links` is the only program available to handle URLs from the command line.  XD

Do we want to special-case out `links` so that users aren't...... underwhelmed.... by their shiny IJulia interface?  :P  Unfortunately since `links` doesn't support Javascript I can't do too much.

**Comment by axsk** [comment]
You could try connecting via 'ssh -L 8998:localhost:8998 user@remote'.
This should forward the remote IJulia port to your local computer. Then just open localhost:8998 in your local browser.

This works for me so far. Unfortunately opening a notebook results in the top right status indicator showing "Kernel busy" and entering any commands results in no answer, just showing the "in computation"-* in the cell.

Can you get any results back? If not I would open an issue for this, as I currently need this feature :(

**Comment by stevengj** [comment]
Yes, ssh tunnels are the way to go for this.

**Comment by stevengj** [comment]
I don't think there's much further to do on this.  If we want a warning for opening `jupyter notebook` with `links` suggesting SSH tunneling instead, that would be  Jupyter issue.
