### ISSUE TITLE
Support Jupyter (IPython 3) kernel spec

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/IJulia.jl#224]
This should be a very simple matter of writing out a couple of extra files to the `.ipython` directory.

cc: @ellisonbg, @Carreau

**Comment by stevengj** [comment]
@Carreau, since ipython#6537 was merged, is there anything else holding this up?

**Comment by Carreau** [comment]
> @Carreau, since ipython#6537 was merged, is there anything else holding this up?

Me getting time to finis #210 among other. I should be definitively in berkeley in something like 48h.
probably will take a day or two to get office space and badges, and I resume my work.
(prey for delta airline to get power outlets, and I'll geek in the plane)

**Comment by stevengj** [comment]
Cool, thanks!  So we are not waiting on any changes on the IPython side anymore.

**Comment by Carreau** [comment]
Except for last minute [raptor](http://xkcd.com/292/), no.

**Comment by jiahao** [comment]
It looks like both 0.3.6+ and 0.4-dev work quite nicely with 3.0.0rc1:

![screen shot 2015-02-22 at 9 14 12 pm](https://cloud.githubusercontent.com/assets/1732/6321962/c9721568-bad7-11e4-8993-320acdc5f4a5.png)

Really liking the improved scrolling behavior!

**Comment by jiahao** [comment]
It looks like the only thing left to do is to fix this deprecation warning:

```
/Library/Python/2.7/site-packages/IPython/kernel/manager.py:95: UserWarning: Setting kernel_cmd is deprecated, use kernel_spec to start different kernels.
```

Otherwise it looks like all systems go.

**Comment by Carreau** [comment]
Just don't use `--profile=julia` and you are good to go. 
(unless you get some other custom things in your profile)

**Comment by jiahao** [comment]
I don't need `--profile=julia` anymore??!! (mind blown)

**Comment by Carreau** [comment]
We do out best so that you do not have to:

![capture d ecran 2015-02-22 a 18 37 12](https://cloud.githubusercontent.com/assets/335567/6322075/f1ce54a6-bac1-11e4-9e76-0a3b2a0a22cc.png)

Still a bit of work, but all languages should be equal citizen soon.

**Comment by jiahao** [comment]
I would really like to have both Julia 0.3 and 0.4 accessible from Jupyter. Is that possible now or is that still WIP?

**Comment by Carreau** [comment]
> I would really like to have both Julia 0.3 and 0.4 accessible from Jupyter. Is that possible now or is that still WIP?

I guess changing [this line](https://github.com/JuliaLang/IJulia.jl/blob/master/deps/build.jl#L160) to install in `julia${major_version}` instead of only Julia should work so that you get 2 kernelspecs. Thant how we do it for python.

**Comment by jiahao** [comment]
I'll give it a try.

Sadly, 3.0 breaks one of my favorite packages, @shashi's `Interact.jl` for accessing IPython widgets:

![screen shot 2015-02-22 at 9 57 28 pm](https://cloud.githubusercontent.com/assets/1732/6322236/ea4450ca-badd-11e4-86f9-2f6ab0b5a9ac.png)

but I suppose this was inevitable.

**Comment by Carreau** [comment]
:-( Sorry about that, That's also why we split in Jupyter, we hope to have non-python contributor, at least in the governance of the project, to minimally know what the breakage in differents kernels might be and get early feedback. 

Side question as you are around: are you aware that we have https://try.jupyter.org ?

**Comment by jiahao** [comment]
Indeed, making essentially that change and rebuilding `Pkg.build("IJulia")` on both julia versions produces the desired result:

![screen shot 2015-02-22 at 10 16 18 pm](https://cloud.githubusercontent.com/assets/1732/6322359/86ec461a-bae0-11e4-8420-7c4ca202752b.png)

> Side question as you are around: are you aware that we have https://try.jupyter.org ?

Not until you mentioned it!

**Comment by Carreau** [comment]
> Not until you mentioned it!

Well, it's still in progress it spawns Docker container without network access
that are torn don after 2 hours for people to try  (Hosted graciously by rackspace).
If you like to add Julia demo, that would be great. And if Julia community would like 
to help with it that would be great.

**Comment by jiahao** [comment]
You're welcome to use all the notebooks I have posted publicly at

https://github.com/jiahao/ijulia-notebooks

and

https://github.com/jiahao/ijulia-notebooks-assorted
