### ISSUE TITLE
Support `workspace()` call

### ISSUE THREAD

**Issue by netvl** [JuliaLang/IJulia.jl#226]
Is it possible for IJulia to support `workspace()` call? Currently if you invoke `workspace()` the notebook becomes unusable until kernel restart. It seems this happens because `workspace()` clears some important globals:
![scr](https://cloud.githubusercontent.com/assets/280456/4024623/70484be0-2bd2-11e4-9899-2e5da0f355b9.png)

**Comment by stevengj** [comment]
Closing as `workspace` no longer exists.
