### ISSUE TITLE
print, println, and @printf do not print results in the notebook

### ISSUE THREAD

**Issue by nfoti** [JuliaLang/IJulia.jl#23]
When I run `print("Test")` in an IJulia notebook the string is printed to the terminal but not as the result of the cell in the notebook as is the case when I run `print "Test"` in an IPython notebook.

**Comment by wizofe** [comment]
I still have this issue. Is it somehow resolved?

**Comment by stevengj** [comment]
Works for me:
![image](https://user-images.githubusercontent.com/2913679/109975175-5d90b480-7cc8-11eb-8511-3e3b050f8553.png)
This issue was fixed 7 years ago.  Any problem you are seeing now is unrelated and should be opened in a new issue or discussed on https://discourse.julialang.org/
