### ISSUE TITLE
indent doesn't respect ipython profile

### ISSUE THREAD

**Issue by swadey** [JuliaLang/IJulia.jl#237]
Normally, ipython notebooks use this map/setting to configure tab indent size:
```javascript
IPython.Cell.options_default.cm_config.indentUnit = 2;
```

It looks like line 276 of julia.js overrides this with a hard-coded 4.  
```javascript
 return (state.scopes.length + delta) * 4; 
```
I'm guessing the 4 should be something like `_conf.indentUnit` as in:
```javascript
 return (state.scopes.length + delta) * _conf.indentUnit; 
```

**Comment by malmaud** [comment]
Can this be closed now with the deprecation of ipython 2?

**Comment by stevengj** [comment]
Yes.
