### ISSUE TITLE
Object info request refuse to inspect `push!(`

### ISSUE THREAD

**Issue by Carreau** [JuliaLang/IJulia.jl#241]
```julia
push!(<shift-tab> #does not works
```

Assuming I do `push=push!` suddenly both work.
```julia
push(<shift-tab> #works.
push!(<shift-tab> #works
```

Instead if I restart the kernel and do `foo = push!` then `foo(<shift tab>` works, `push!(<shift tab>` does not.

IPython notebook (javascript part) seem to send the full text `push!(` to the kernel, the UI seem to get a weird response where the kernel does actually look for `push`without bang. Here is the reply:

```javascript
{"header":
  {"msg_id":"....",
  "username":"username",
  "version":"5.0",
  "session":"...",
  "msg_type":"inspect_reply"
},
"metadata":{},
"msg_id":"8bd08501-f25e-4484-94fe-9fe7358e74a6",
"parent_header":
{"msg_id":"...",
 "username":"username",
 "session":"...",
 "msg_type":"object_info_request"},"msg_type":"inspect_reply",
 "content": {
    "name":"push",   //here seem to look for push
    "found":false,
    "data":{},
    "metadata":{},
    "status":"ok"
}
}
```

Any clues ?

IPython master, julia-master,  IJulia super recent.

**Comment by stevengj** [comment]
`push!(` is now parsed correctly in an object info request.  (We have other problems with object_info_request in 0.4, but that's a separate issue.)
