### ISSUE TITLE
Interrupting kernel when sampling in Mamba.jl causes the kernel to shutdown

### ISSUE THREAD

**Issue by rsmith31415** [JuliaLang/IJulia.jl#242]
There is a very specific issue related to the Mamba package. I detailed the problem [here](https://github.com/brian-j-smith/Mamba.jl/issues/8). However, it seems to be an issue with the IJulia kernel. 

Basically, when we run [this code](http://mambajl.readthedocs.org/en/latest/examples/rats.html#analysis-program) (or any code involving sampling) and interrupt the kernel while executing the last line (`sim = mcmc(model, rats, inits, 10000, burnin=2500, thin=2, chains=2)`), the interruption causes the kernel to shutdown.

The Julia interpreter behaves as expected: `^Cexception on 1: ERROR: interrupt`

This is happening in Julia 0.3.1 with IJulia 0.1.15.

**Comment by stevengj** [comment]
Closing as it is not clear this is still reproducible?
