### ISSUE TITLE
Uncaught TypeError: undefined is not a function in custom.js

### ISSUE THREAD

**Issue by dbartow** [JuliaLang/IJulia.jl#246]
Friends,

I've just gone through a fresh install of IPython, Julia and IJulia on Ubuntu 14.04.1.  There seems to be a problem in custom.js in the IJulia profile that causes notebooks to not load and function.  I was able to duplicate this in multiple environments and reproduce it in each major browser on Windows, Linux and Mac OS X so it seems to be a legit problem. 
 
I also vetted it out with the IPython guys in their Gitter channel.  Switching from the IJulia profile to any IPython profile gets rid of the error.  Switching back to IJulia causes the problem to return.  I included my setup instructions for IPython, Julia and IJulia below.  Any guidance would be appreciated.

These are my installation instructions that I followed exactly for IPython and IJulia:  https://gist.github.com/dbartow/166114161e0c438600db

Here is a screenshot of the error happening in Chrome latest on Mac OS X.

![screen shot 2014-11-03 at 9 58 31 am](https://cloud.githubusercontent.com/assets/3112388/4887350/c5617514-6383-11e4-9d47-4306d6383908.png)

**Comment by stevengj** [comment]
Doesn't seem relevant to the current version, which doesn't install custom js anymore.
