### ISSUE TITLE
IJulia does not save files on IPython 3.0.0 dev

### ISSUE THREAD

**Issue by ivanslapnicar** [JuliaLang/IJulia.jl#252]
All commands work, but when I do "Save and ceckpoint'
the file is created, but is empty, except for the content below.
The (unsaved changes) message is properly displayed.

{
 "cells": [],
 "metadata": {
  "signature": "sha256:59f47cff041fffac7bd96bcd535bce0d924dc66425290a9e0e100c903c12bbd6"
 },
 "nbformat": 4,
 "nbformat_minor": 0
}

**Comment by douglas-larocca** [comment]
I was able to resolve this by removing the references to `CodeMirror` in custom.js. The current version of IJulia checks the IPython version before attempting to configure CodeMirror in custom.js with

```
if (parseInt(IPython.version[0]) < 3) {


    $([IPython.events]).on('notebook_loaded.Notebook', function(){
        "use strict";
        // add here logic that should be run once per **notebook load**
        // (!= page load), like restarting a checkpoint

        var md = IPython.notebook.metadata;
        if(md.language){
            console.log('language already defined and is :', md.language);
        } else {
            md.language = 'Julia' ;
            console.log('add metadata hint that language is julia...');
        }
    });


    $([IPython.events]).on('app_initialized.NotebookApp', function(){
        "use strict";
        // add here logic that should be run once per **page load**
        // like adding specific UI for Julia, or changing the default value
        // of codecell highlight to a julia one if availlable.

        // this will not work for 1.0, unless julia profile
        // manually ships julia.js in
        // <profile dir>/static/components/codemirror/mode/julia/julia.js
        // hopefully it will be directly included in codemirror itself
        // for future releases.
        IPython.CodeCell.options_default['cm_config']['mode'] = 'julia';

        CodeMirror.requireMode('julia', function(){
            var cells = IPython.notebook.get_cells();
            for(var i in cells){
                var c = cells[i];
                if (c.cell_type === 'code'){
                    c.auto_highlight();
                }
            }
        });

        // handle identifiers ending with ! (this works in ipython 2.x)
        IPython.Tooltip.last_token_re = /[a-z_][0-9a-z._!]*$/gi;
    });

}
```

If `CodeMirror` isn't in the namespace, you'll get

> :8999/static/custom/custom.js:78 Uncaught TypeError: undefined is not a function

Because there was a JS error, the `IPython.notebook._fully_loaded` switch isn't flipped and consequently the notebook can't be saved.

My guess is that this has been fixed by wrapping the section in `if (parseInt(IPython.version[0]) < 3)` but maybe `Pkg.add("IJulia")` is picking up an older version or refusing to overwrite an existing `config.js`?

For now I've removed the whole block and it works. But can't we use 

```
require([' <codemirror import path?> '], function(CodeMirror) { 
    $([IPython.events]).on('notebook_loaded.Notebook', function(){
        CodeMirror ...
    });
});
```

or something like this?

**Comment by Carreau** [comment]
> But can't we use [`requirejs`]

No because the path have changed between 2 (no path, codemirror incompatible with require IIRC)  and 3, and `require` did not exist in 1.0.

Can you force update `custom.js` with  `Pkg.build("IJulia")` ?

But if codemirror loading fail, the notebook should not even load...

**Comment by douglas-larocca** [comment]
Codemirror doesn't fail, fully loading fails due to the reference to codemirror.

**Comment by stevengj** [comment]
This issue doesn't seem relevant anymore as we are no longer using custom.js.
