### ISSUE TITLE
having problems installing ijulia on ubuntu

### ISSUE THREAD

**Issue by francispoulin** [JuliaLang/IJulia.jl#254]
Hello,

I am brand new to julia (its been a few hours) and I am keen to try ijulia (I really like ipython).  Unfortunately, I have failed to install it on both my ubuntu and mac machines.  Here is the problem on my ubuntu.  

Sorry to be helpless but any advice would be greatly appreciated.

Thanks.

julia> Pkg.build("IJulia")
INFO: Building Nettle
==========================================================================================================[ ERROR: Nettle ]==========================================================================================================

no method Dict{Any,Any}(Dict{Any,Any},)
at /home/fpoulin/.julia/v0.2/Nettle/deps/build.jl:33

=====================================================================================================================================================================================================================================
INFO: Building ZMQ
===========================================================================================================[ ERROR: ZMQ ]============================================================================================================

no method Dict{Any,Any}(Dict{Any,Any},)
at /home/fpoulin/.julia/v0.2/ZMQ/deps/build.jl:8

=====================================================================================================================================================================================================================================
INFO: Building IJulia
Found IPython version 1.2.1 ... ok.
Creating julia profile in IPython...
(Existing KernelManager.kernel_cmd setting in ipython_config.py is untouched.)
(Existing IPythonWidget.execute_on_complete_input setting in ipython_qtconsole_config.py is untouched.)
(Existing FrontendWidget.lexer_class setting in ipython_qtconsole_config.py is untouched.)
(Existing NotebookApp.port setting in ipython_notebook_config.py is untouched.)
(Existing ipynblogo.png file untouched.)
(Existing ipynblogo.svg file untouched.)
(Existing favicon.ico file untouched.)
(Existing custom.js file untouched.)
(Existing julia.js file untouched.)

==========================================================================================================[ BUILD ERRORS ]===========================================================================================================

WARNING: ZMQ and Nettle had build errors.

 - packages with build errors remain installed in /home/fpoulin/.julia/v0.2
 - build a package and all its dependencies with `Pkg.build(pkg)`
 - build a single package by running its `deps/build.jl` script

=====================================================================================================================================================================================================================================

**Comment by stevengj** [comment]
These are not really IJulia issues; you should report them at ApproxFun etc.

**Comment by vanstark88** [comment]
another thing to notice is to update to Xcode dev version if you run under OS X El Capitan‎
