### ISSUE TITLE
Different PATH at command-line REPL and IJulia

### ISSUE THREAD

**Issue by pablocouto** [JuliaLang/IJulia.jl#256]
On my system (OS X 10.10.1), julia and IJulia get different values for the `PATH` variable. This is what I get in julia:

``` julia
julia> ENV["PATH"]
"/Users/personal/anaconda/bin:/Users/personal/Library/Haskell/bin:/Users/personal/android-sdk/platform-tools:/Users/personal/android-sdk/tools:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/usr/texbin"
```

Starting IJulia from the same shell with `ipython notebook --profile julia`, I get this:

``` julia
In [1]:
ENV["PATH"]
Out[1]:
"/opt/local/bin:/Users/personal/anaconda/bin:/Users/personal/Library/Haskell/bin:/Users/personal/android-sdk/platform-tools:/Users/personal/android-sdk/tools:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/usr/texbin"
```

I came across this while trying to use PyPlot, which I can load from julia but not from IJulia. If I correct `PATH` in IJulia by removing `/opt/local/bin:`, PyPlot loads fine.

I tried to remove `~/.ipython/profile_julia/` and then run `Pkg.build("IJulia")` from julia, but this didn’t help with the issue. I noticed that in julia, after the build, `PATH` changed to the following:

``` julia
julia> ENV["PATH"]
"/Users/personal/.julia/v0.3/Homebrew/deps/usr/bin:/Users/personal/.julia/v0.3/Homebrew/deps/usr/sbin:/Users/personal/anaconda/bin:/Users/personal/Library/Haskell/bin:/Users/personal/android-sdk/platform-tools:/Users/personal/android-sdk/tools:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/usr/texbin"
```

I found an apparently similar issue (#184), but wasn’t able to find a solution there.

**Comment by stevengj** [comment]
I think IPython prepends the path of the kernel (`/Users/personal/.julia/v0.3/Homebrew/deps/usr/bin` in this case) to `PATH` before launching the kernel, though I'm not sure why.  (@Carreau, can you confirm?)

In any case, once you rebuilt, it seems that you have `/Users/personal/anaconda/bin` in your `PATH`, so are still having problems?

**Comment by pablocouto** [comment]
Yes, the issue remains after rebuilding. The change in `PATH` I mentioned last doesn’t persist after restarting julia. In IJulia, `PATH` continues being prepended with `/opt/local/bin:`.

**Comment by stevengj** [comment]
Is your `julia` installed in `/opt/local/bin`?

**Comment by pablocouto** [comment]
Yes, it’s there.

**Comment by stevengj** [comment]
This sounds like it may be an IPython issue then; @minrk, do you know why IPython is prepending the kernel path to `PATH`?

**Comment by stevengj** [comment]
Closing as a Jupyter issue — Jupyter still seems to be prepending the kernel executable's directory to PATH
