### ISSUE TITLE
bug in clear_history()

### ISSUE THREAD

**Issue by afniedermayer** [JuliaLang/IJulia.jl#258]
When calling clear_history(), I get this error message:

`delete!` has no method matching delete!(::Dict{Integer,UTF8String}, ::Int64, ::Nothing)
while loading In[3], in expression starting on line 1

 in clear_history at /home/andras/.julia/v0.3/IJulia/src/history.jl:21
 in clear_history at /home/andras/.julia/v0.3/IJulia/src/history.jl:31
 in clear_history at /home/andras/.julia/v0.3/IJulia/src/history.jl:35

**Comment by stevengj** [comment]
Fixed by #259
