### ISSUE TITLE
Add --color=yes as argument to get color output

### ISSUE THREAD

**Issue by dhoegh** [JuliaLang/IJulia.jl#260]
It would be nice if the output in IJulia allowed for colors, for an example for the output of  `@code_warntype`. `@code_warntype` gets colors if `--color=yes` is added as a startup argument in the `ipython_config.py` file, but it do not color the error messages which also would be nice.

**Comment by stevengj** [comment]
Doesn't `julia --color=yes` use [ANSI escape codes](https://en.wikipedia.org/wiki/ANSI_escape_code) for colored text in a terminal.   How are these supposed to work in the browser?

**Comment by dhoegh** [comment]
http://stackoverflow.com/questions/16816013/is-it-possible-to-print-using-different-color-in-ipythons-notebook

**Comment by Carreau** [comment]
I wouldn't rely too much on ANSI for in-browser color support, it works but is known to have edge cases, 
especially when converting with nbconvert to format that need to strip coloring.

ANSI coloring is also relatively painful when dealing with dark and light background. 
It can be worked-around-ish by mapping dark-[a-color]-to light-[same-color], and lots f things like that, 
but is always wonky.
It would be much nicer is something like the display system was use to send real html
to the page with actual classes (much like [bootstrap](http://getbootstrap.com/css/#helper-classes-backgrounds)) than convey semantic information. 

IHaskell do a great job at that, having even a representation for unshowable types.

**Comment by IainNZ** [comment]
@stevengj does Julia "know" that IJulia is consuming its stdout? Is there some way `print_with_color` can do something different to the ANSI codes on that basis?

**Comment by stevengj** [comment]
@IainNZ, one option is to do something like [how readline is implemented](https://github.com/JuliaLang/IJulia.jl/blob/9b677b1e12e2d9ad17ab9e02589eccc2c3cd5c9d/src/stdio.jl#L59-L79).

This is a bit hacky, though.  Ideally, I'd like the warning to call `display` on an object with `writemime` methods for `text/html` etc so that colors would appear automatically for appropriate backends.

**Comment by KristofferC** [comment]
Closed by https://github.com/JuliaLang/IJulia.jl/pull/470?
