### ISSUE TITLE
Changes to custom.js are wiped on upgrade

### ISSUE THREAD

**Issue by garrison** [JuliaLang/IJulia.jl#262]
When I upgrade IJulia, any changes I have made to `custom.js` are wiped out.  I would like, for instance, to have a [pop-up notification](https://github.com/sjpfenninger/ipython-extensions) when the kernel finishes after running a long process.  This requires adding a few lines to `custom.js`.

I see a few possible solutions:

- make a section for user-specified things in `custom.js`, which is untouched during an IJulia upgrade.
- change `custom.js` to include another file (e.g. `custom_julia.js`), which in turn is upgraded in full every time.  If this include line is missing from `custom.js`, it is added, but everything else is left untouched.

**Comment by Carreau** [comment]
This should be fixed in IPython 3.0 we have a specific kernel.js for kernels authors, and custom.js should be left free for user to configure. 

List of extensions can be configured in plain config files, without writing JS (and [even with a beautiful gui](https://github.com/ipython-contrib/IPython-notebook-extensions/pull/164) like tool that we are considering including later) .

**Comment by garrison** [comment]
Thanks for the note @Carreau .  That leaves me wondering: will there be a way to fix this while remaining compatible with previous IPython versions?

**Comment by Carreau** [comment]
If IJulia want to make its custom things like you propose, where basicaly custom.js is replaced but loads a custom_julia.js if present then yes. 

A "fix" on IPython side is less likely as the IPython team is too small to maintain 2 version of IPython at the same time.

**Comment by garrison** [comment]
Thanks, this is good to know.  Currently the IJulia README says IPython 1.0 is the minimum required version.

**Comment by Carreau** [comment]
Ouch, IPython 1.0 was a thing ? Can't even remember what it looked like.

**Comment by stevengj** [comment]
If you want your own `custom.js`, you should probably just make your own profile in `.ipython` for now.

**Comment by stevengj** [comment]
The IPython kernel has the luxury of being shipped with the IPython front-end, so they can assume the front-end is up-to-date.  Since IJulia is shipped separately, we prefer to maintain compatibility with at least the previous major release.

**Comment by jiahao** [comment]
I believe this should be closed by #276

**Comment by jiahao** [comment]
Actually not, `custom.js` is still being copied when the `IJulia` package is built.

**Comment by stevengj** [comment]
@jiahao, it's still being copied in order to maintain compatibility with IPython 2.0... I've seen too many users with multiple IPython versions on their machines after different install attempts.

**Comment by garrison** [comment]
Bumping now that IPython 3.0 is the minimum version as of a5ebc708.  Actually, from looking at a5ebc708 I suspect this issue is fixed already, as `custom.js` is no longer even mentioned in the repository...

**Comment by stevengj** [comment]
Yes, custom.js is gone now.
