### ISSUE TITLE
error message on startup - WARNING: zero{T}(::Type{Ptr{T}}) is deprecated, use Ptr{T}(0) instead.

### ISSUE THREAD

**Issue by sononix** [JuliaLang/IJulia.jl#263]
dump from the terminal goes like 

```
WARNING: zero{T}(::Type{Ptr{T}}) is deprecated, use Ptr{T}(0) instead.
 in depwarn at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in zero at deprecated.jl:29
 in anonymous at no file
 in include at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in reload_path at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in _require at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in require at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in include at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in include at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in include_from_node1 at loading.jl:128
 in process_options at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in _start at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
```

**Comment by kmsquire** [comment]
@sononix, it's obvious you're installing from brew, but could you also provide which version of OSX you're on, and the output of `versioninfo()`. 

Cc: @staticfloat

**Comment by sononix** [comment]
well I had been rolling my own and someone suggested brew :) here is a link to the previous post
https://github.com/JuliaLang/julia/issues/9842

Im on OS 10.9 and 

julia> versioninfo()
Julia Version 0.4.0-dev+2818
Commit 196544c* (2015-01-19 18:50 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.0.0)
  CPU: Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_AFFINITY HASWELL)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by stevengj** [comment]
IJulia itself doesn't use the `zero` function at all.  The only dependency of IJulia that uses `zero` is ZMQ, but that doesn't use it for any pointer types.   So, I can only conclude that the use of `zero(::Ptr)` is in Julia itself.

**Comment by stevengj** [comment]
Closing as no longer relevant.
