### ISSUE TITLE
Execution of parallel code

### ISSUE THREAD

**Issue by gdmsl** [JuliaLang/IJulia.jl#265]
Is there a way to execute parallel code in IJulia like the macros @ parallel or @ spawn ? And how can the number of threads be changed?

**Comment by stevengj** [comment]
It works exactly like in the REPL or in other Julia code.  You can add threads with the `addprocs` command ([see the manual](http://docs.julialang.org/en/latest/stdlib/parallel/#general-parallel-computing-support)).

**Comment by axsk** [comment]
Actually I miss the warning and error messages thrown on other threads. This makes debugging quite tricky.

OT: Last days I opened lots of issues, and many turned out to be my faults, so I feel extremely unsure, so I will just append this here :/

**Comment by stevengj** [comment]
@axsk, I can't reproduce that problem.  With Julia 0.4, I get error messages from other worker processes:
![image](https://cloud.githubusercontent.com/assets/2913679/9945461/67be5bc0-5d5b-11e5-9d33-0bb465bbbd4a.png)

**Comment by axsk** [comment]
Hmm, my problems seems to be pmap related.

Realizing that errors in pmap got supressed in IJulia I tested it in the REPL ```pmap(sqrt,[-1])``` and this lead to an error message, so I thought it was actually IJulias problem.

But ```pmap(sqrt,[-1]); "overwrite"``` results just in ```"overwrite"```: the error gets supressed in IJulia and the REPL as well...
Should I file a Julia issue for this?

**Comment by stevengj** [comment]
Yes, sounds like it.
