### ISSUE TITLE
ditch IPython _* history variables?

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/IJulia.jl#267]
Early on, I made IJulia emulate IPython's history variables: `_`/`__`/`___` refer to the last three execution results, and `_nn` refers to `Out[nn]`.

At this point, however, I'm not sure that was a great idea, and I'm inclined to ditch them, keeping only `ans` for the last execution result (like Matlab and the Julia REPL) and `Out[nn]` to fetch any output.   `_` in particular just seems to be too popular as a variable name to shadow it with a global (see e.g. kmsquire/Match.jl#14).

Thoughts?  @StefanKarpinski, @Carreau, are these underscore history variables important to anyone?

**Comment by minrk** [comment]
`_` is a convention IPython inherited from the vanilla Python REPL (IPython added `__` and `___`), I'm not sure if anyone uses anything beyond `_`, even in IPython. If there's a better precedent in the community, I think dropping `_*` is a good idea.

**Comment by quinnj** [comment]
+1. I was only aware of them from digging around in the iJulia source code, so I wouldn't imagine there are many reliances on them. I think using `ans` is much more common in the Julia community.

**Comment by Carreau** [comment]
+1 also.

Envoyé de mon iPhone

**Comment by StefanKarpinski** [comment]
+1 – I never cared for this in the first place. How about also exposing `In[n]`?

**Comment by stevengj** [comment]
@StefanKarpinski, `In` and `Out` are already exposed.

**Comment by malmaud** [comment]
So ends an era.
