### ISSUE TITLE
Reloading of types

### ISSUE THREAD

**Issue by poulson** [JuliaLang/IJulia.jl#269]
Any time that my notebook implements a type, I get an error stating that I cannot modify a constant if I rerun the cell (e.g., while debugging the type).

The only workaround that I'm aware of is to restart the kernel and rerun the entire notebook, but this is quite time-consuming when the notebook contains a plotting package (in my case, PyPlot).

Is there a better solution?

**Comment by stevengj** [comment]
This is not really IJulia, but a property of Julia (you'll notice the same thing in the REPL).  Types are constants and can't be redefined.

A possible workaround is discussed in #226.  Closing this issue in favor of 226.

**Comment by timholy** [comment]
And perhaps more important for @poulson's immediate needs: http://docs.julialang.org/en/release-0.3/manual/workflow-tips/

**Comment by poulson** [comment]
Thanks @timholy ! That should solve it.
