### ISSUE TITLE
`using RCall` kills an IJulia notebook session

### ISSUE THREAD

**Issue by dmbates** [JuliaLang/IJulia.jl#275]
I am using ipython 2.3.0 on an Ubuntu Utopic amd64 system and IJulia 0.1.16. I tried versions 0.3.5 and 0.4.0-dev+3395 as the Julia kernels in IJulia notebooks.

As soon as I try to execute
```julia
using RCall
```
in an IJulia notebook it kills the kernel.  I'm not terribly surprised that this could happen.  The __init__ function for the RCall package attempts to initialize an embedded R process.  I can imagine that the communication between ipython and julia complicates this.

However, I don't know how to start debugging.  Am I missing something in the documentation?

**Comment by stevengj** [comment]
I assume that it works in the REPL on your machine?  It's not obvious to me why the embedded R process should have any effect on the (zeromq-based) communication between Julia and IPython.

I would change `capture_stderr = true` to `false` in IJulia.jl and change `verbose = false` to `true`, and then look in the terminal where you launched IPython to see if there is a more informative error message.

**Comment by dmbates** [comment]
@stevengj  Yes, I should have mentioned that RCall does indeed work from the REPL.

Thanks for your suggestion - it helped.  It turns out that the embedded R decided that it needed another argument when started by the julia process started by IJulia than it did when it was started from a julia REPL.
