### ISSUE TITLE
Latex Equations in iJulia (not printing)

### ISSUE THREAD

**Issue by alexocampo907** [JuliaLang/IJulia.jl#278]
I'm having trouble getting my latex equations to display in print preview. Regular latex displays in print preview but when I try to use an equation such as  \begin{align} it doesn't display (see attached screen shots).

![displays in ijulia](https://cloud.githubusercontent.com/assets/3952528/6254186/c1bda7ee-b774-11e4-957a-e769b6e53878.png)
![doesn t display in print preview](https://cloud.githubusercontent.com/assets/3952528/6254189/c5add3c4-b774-11e4-9a26-ca9ca14f308c.png)

Thank you for any help,

Alex

**Comment by Carreau** [comment]
That's most likely a bug in IPython. Can you try the 3.0 Rc release ? Does it do the same when you manually `nbconvert --to html` ?

**Comment by stevengj** [comment]
They can't try the 3.0 release until #224 is completed, no?

This seems like the same thing as JuliaLang/JuliaBox#76

**Comment by Carreau** [comment]
The kernel might start as Python, but the conversion to html/print preview should work.

**Comment by alexocampo907** [comment]
It is different to JuliaLang/JuliaBox#76 because my latex actually shows up in the print preview. For instance if I type $\alpha$ in a markdown cell, it will display. 

However if I try to use \begin{equation} or any other type of equation latex, it will show fine in the console and then not show in the print preview.

Carreau, how do I execute the manual nbconvert --to html?

**Comment by Carreau** [comment]
> Carreau, how do I execute the manual nbconvert --to html?

Shoudl be :
```
$ ipython nbconvert --to html <your ipynb>
```
Should create an html file with the same name.

**Comment by alexocampo907** [comment]
Sorry for my technical illiteracy. But I triend the manual nbconvert and it gave me an error. 

I set the working directory:
`Alexs-MacBook-Air-2:Methods II alexocampo$ pwd`
`/Users/alexocampo/Documents/Harvard/Semester 2/Methods II`

Then ran the code you mentioned:
`Alexs-MacBook-Air-2:Methods II alexocampo$ ipython nbconvert --to html <HW 2 Methods.ipynb>`
`-bash: syntax error near unexpected token newline' >`

**Comment by jiahao** [comment]
Take out the angle brackets and try again.

**Comment by alexocampo907** [comment]
Thanks! The manual nbconvert worked but still no latex equations displaying :(

**Comment by stevengj** [comment]
@alexocampo907, I think `nbconvert` needs LaTeX (e.g. MacTeX) to be installed on your system for equation rendering (and for nice PDF output).

**Comment by Carreau** [comment]
> @alexocampo907, I think nbconvert needs LaTeX (e.g. MacTeX) to be installed on your system for equation rendering (and for nice PDF output)?

For Html it should still rely on mathjax. 
I'm at Strata the next two days, but assigned that to me to have a look.

**Comment by alexocampo907** [comment]
Any progress on this issue?

It does use mathjax. I know this because I had to use  [the following stack exchange](http://stackoverflow.com/questions/25652834/ipython-markdown-rendering-failing) in order to get my regular latex (i.e. non equation latex) to show in the print preview.

**Comment by Carreau** [comment]
I would try IPython 3.0 RC, it seem to work (for me at least) on 3.0-dev, and there will most likely not be a bugfix on 2.x. I'll try on 2.x later.

**Comment by alexocampo907** [comment]
Sorry again for my technical illiteracy, but do I upgrade to IPython 3.0 RC by putting the following in the terminal?

` pip install ipython --upgrade`

**Comment by Carreau** [comment]
that shouLd work, if it does not force the version with `pip install ipython==3.0.0rc1`

**Comment by jiahao** [comment]
Works for me in 3.0.0rc1 also.

**Comment by Carreau** [comment]
> Works for me in 3.0.0rc1 also.

Great ! Seem like 3.0 will be a good release !

**Comment by alexocampo907** [comment]
ok guys BIG PROBLEM now. I installed the latest version of Ipython using the instructions above, but now my IJulia won't open! See attachement for the error:

![screen shot 2015-02-22 at 9 47 31 pm](https://cloud.githubusercontent.com/assets/3952528/6322142/8fd92c10-badc-11e4-87ea-d2261c72df30.png)

Any idea why this is happening?

**Comment by Carreau** [comment]
can you get the full command line, and/or try the command line directly ( `ipython notebook`)?

**Comment by Carreau** [comment]
And also:

Oh, you are a R user, do you know there is an [R Kernel too](https://github.com/takluyver/IRkernel).

**Comment by Carreau** [comment]
Without the full traceback, I would try nuking `~/.ipython/profile_julia` away (or temporary move it somewhere else). The issue a `Pkg.build("IJulia")` to recreate it.

**Comment by alexocampo907** [comment]
Thanks for your quick help!

I was able to get the notebook to start by doing 
`pip install jinja2 tornado pyzmq --upgrade`
and 
`pip install jsonschema`

but now when I am inside looking at my file all I see is a blank file (attached)
![screen shot 2015-02-22 at 10 00 47 pm](https://cloud.githubusercontent.com/assets/3952528/6322254/4c734c42-bade-11e4-9c04-f9c1964801cb.png)

Thanks for the tip about the R kernel too!

**Comment by Carreau** [comment]
Force refresh page a few time  (Cmd-Shift-R)
If does not work
   Open JS console. (Cmd-Alt-J) see it error. 
Retry force refresh (Chrome is stubborn)

This is typical of cached Javascript from IPython 2.0, or custom.Js not upgraded.

**Comment by jiahao** [comment]
I had this problem too. Please update IJulia with `Pkg.update()` and try again. v0.2.0 was tagged very recently.

**Comment by Carreau** [comment]
> pip install jinja2 tornado pyzmq --upgrade

And you should not have to do that, it means that IPython was not installed previously with `pip install ipython[all]`. But I guess this is due to  you using conda, with which I'm not super familiar with.

**Comment by alexocampo907** [comment]
Ok progress! I reinstalled and updated the IJulia package like you all said and now I am seeing my work again! THANK YOU THANK YOU THANK YOU! 

However, now I am having an issue while trying to print (attached)
![screen shot 2015-02-22 at 10 12 59 pm](https://cloud.githubusercontent.com/assets/3952528/6322340/1a57ddd4-bae0-11e4-8daa-efae8409305c.png)

**Comment by Carreau** [comment]
`No module named mistune` is self explanatory, you are missing it, you need to pip-install it. 

try `pip install ipython[all]==3.0.0rc1` (with or without the ==3.0.0rc1 depending on what you did earlier), it will reinstall IPython making sure you have all dependencies.

**Comment by alexocampo907** [comment]
Ok, I tried `pip install ipython[all]==3.0.0rc1` and I am still having the same problem:

`Could not import nbconvert: No module named mistune`

**Comment by alexocampo907** [comment]
Working!! I did:

`pip install mistune`

now everything is working (including equation Latex) and I think we can say that this issue is closed! Thank you to everyone who helped out and my apologies again for my lack of knowledge with IPython.
