### ISSUE TITLE
Equivalent of IPython.display.Image

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/IJulia.jl#281]
What is the equivalent in IJulia?

```python
from IPython.display import Image

Image(url="http://path.com/image.png")
```

**Comment by jiahao** [comment]
Just about anything you want to do in Python, you can do with PyCall.

![screen shot 2015-02-24 at 12 18 30 pm](https://cloud.githubusercontent.com/assets/1732/6354724/5674efa6-bc1f-11e4-9944-30969192ebdf.png)

**Comment by juliohm** [comment]
Thank you @jiahao, will use PyCall as a workaround.

**Comment by stevengj** [comment]
@juliohm, there is also the [Images.jl](https://github.com/timholy/Images.jl) package in Julia, which can display images in various formats.  It doesn't download images for you, but you can always download using the `download` function in Julia.

If you just want to display the image in a notebook, you can do so just by an `<img src="...">` tag in html, e.g. `display("text/html", "<img src=\"http://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Polar_Bear_AdF.jpg/320px-Polar_Bear_AdF.jpg\">")`

**Comment by juliohm** [comment]
@stevengj, that is true, thanks for the tip. I was forgot about html/markdown support, we can do it directly into a markdown cell:

```
<img src="url">
```
or 
```
![image](url)
```

**Comment by stevengj** [comment]
@juliohm, that's right, but I was referring to doing `display("text/html", ".....")` if you want to output HTML to be displayed programatically from Julia.

**Comment by juliohm** [comment]
Got it, will keep this option in mind too. Thanks!
