### ISSUE TITLE
Tab completion not working on 0.4-dev/IPython 3.0?

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/IJulia.jl#284]
It's working fine for me in the text REPL. Wondering if it's working for anyone else on IPython 3.0.

**Comment by stevengj** [comment]
@Carreau, could this be a problem with the compatibility layer?

**Comment by Carreau** [comment]
I need an example, on Julia 0.4.0-dev+3395 it works here for `P<tab>` -> `Pkg<dot><ad><tab>` -> `Pkg.add`

**Comment by jiahao** [comment]
Sorry, I should have clarified that it was the Latex tab-completion that doesn't work for me. For example, `N\prime<tab>` doesn't do anything - it doesn't insert new tabs, nor does it replace `\prime` with the prime symbol.

**Comment by Carreau** [comment]
Does also works here... Do you have multiple line ? or something else ?
Is your kernel busy ? Can you execute ? Does it work in REPL ?

**Comment by jiahao** [comment]
Apparently this was a transient problem. After I restarted IPython notebook I can use Latex tab-completion again.

**Comment by Carreau** [comment]
OK, let us know if it starts again.
