### ISSUE TITLE
0.3.6 Kernel dies on startup in Ipython 3

### ISSUE THREAD

**Issue by dhoegh** [JuliaLang/IJulia.jl#286]
When I update to IPython 3 the 0.3.6 kernel just dies on startup and hence pops up with kernel restarting which it do successfully. See the log from `ipython notebook --debug`
```
[D 11:40:00.444 NotebookApp] 200 GET /api/contents/Untitled1.ipynb/checkpoints?_=1425811199833 (::1) 2.00ms
[D 11:40:00.460 NotebookApp] Initializing websocket connection /api/kernels/964ff4ad-6dd0-4ec9-afa8-93ce6e7dfd6f/channels
[D 11:40:00.462 NotebookApp] Requesting kernel info from 964ff4ad-6dd0-4ec9-afa8-93ce6e7dfd6f
[D 11:40:00.462 NotebookApp] Connecting to: tcp://127.0.0.1:61786
Starting kernel event loops.
[D 11:40:10.466 NotebookApp] Received kernel info: {'language_info': {'version': '0.3.6', 'name': 'julia'}, 'banner': '', 'protoco
l_version': '4.0'}
[I 11:40:10.467 NotebookApp] Kernel 964ff4ad-6dd0-4ec9-afa8-93ce6e7dfd6f speaks protocol 4.0
[D 11:40:10.468 NotebookApp] Opening websocket /api/kernels/964ff4ad-6dd0-4ec9-afa8-93ce6e7dfd6f/channels
[D 11:40:10.468 NotebookApp] Connecting to: tcp://127.0.0.1:61786
[D 11:40:10.469 NotebookApp] Connecting to: tcp://127.0.0.1:61787
[D 11:40:10.470 NotebookApp] Connecting to: tcp://127.0.0.1:61788
[I 11:40:12.441 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 964ff4ad-6dd0-4ec9-afa8-93ce6e7dfd6f restarted
[D 11:40:12.450 NotebookApp] Connecting to: tcp://127.0.0.1:61789
[D 11:40:15.450 NotebookApp] KernelRestarter: restart apparently succeeded
Starting kernel event loops.
[D 11:40:22.418 NotebookApp] 200 GET /static/components/codemirror/mode/julia/julia.js?v=20150308113954 (::1) 2.00ms
```
When I install IJulia on julia 0.4.0-dev+3622 the kernal start up normally. My version info is:`
```
julia> versioninfo()
Julia Version 0.3.6
Commit 0c24dca (2015-02-17 22:12 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by kmsquire** [comment]
See:

https://github.com/JuliaLang/ZMQ.jl/issues/71
https://github.com/JuliaLang/ZMQ.jl/issues/72

**Comment by dhoegh** [comment]
It it's not one of them, my 0.4.0 is working, because it is build 27 February, 0.3.6 do not work.

**Comment by fonnesbeck** [comment]
I am getting similar behavior, but with the following message:

    ERROR: key not found: "HOME"
     in load_juliarc at ./client.jl:327
     in process_options at ./client.jl:254
     in _start at ./client.jl:354
    [I 11:09:44.420 NotebookApp] KernelRestarter: restarting kernel (1/5)

Julia starts up fine on the command line, its just via IJulia that it dies. I got the same message on the command line prior to upgrading Julia.

**Comment by fonnesbeck** [comment]
I've built Julia from the current master (0.4.0-dev) but am still getting this behavior. The kernel fails upon startup from the notebook.

**Comment by jiahao** [comment]
@fonnesbeck please try the latest master of ZMQ.jl using `Pkg.checkout("ZMQ")` and see if the problem persists.

**Comment by fonnesbeck** [comment]
It appears that I am already up to date:

    julia> Pkg.checkout("ZMQ")INFO: Checking out ZMQ master...
    INFO: Pulling ZMQ latest master...
    INFO: No packages to install, update or remove

**Comment by jiahao** [comment]
@fonnesbeck are you on IPython 3.0.0 also? Do you see the problem with 2.4.x?

**Comment by fonnesbeck** [comment]
I am on the current IPython master, so yes. Have not attempted on 2.4.

**Comment by stevengj** [comment]
`ERROR: key not found: "HOME"` in `in load_juliarc at ./client.jl:327` sounds like you have a bug in your `.juliarc` file.  Can you delete/rename this file and try again?

**Comment by fonnesbeck** [comment]
This is a fresh install, so I don't yet have a .juliarc.jl file.

**Comment by fonnesbeck** [comment]
I also get this on my OS X desktop. The kernel keeps restarting. Here is some of the terminal output:

     16:31:10.870 NotebookApp] Kernel started: cf8bde34-7f82-4840-a219-07a9c39bca69
    [I 16:31:21.010 NotebookApp] Kernel shutdown: cf8bde34-7f82-4840-a219-07a9c39bca69
    [W 16:31:21.022 NotebookApp] 404 GET /kernelspecs/julia%200.4/logo-64x64.png (::1) 10.55ms referer=http://localhost:8890/notebooks/02-ProbabilisticRepresentations.ipynb
    [I 16:31:21.034 NotebookApp] Kernel started: 6209a03c-5e91-47a0-9434-b793fb2d1c1e
    [I 16:31:27.034 NotebookApp] KernelRestarter: restarting kernel (1/5)
    [W 16:31:31.053 NotebookApp] Timeout waiting for kernel_info reply from 6209a03c-5e91-47a0-9434-b793fb2d1c1e
    [I 16:31:33.042 NotebookApp] KernelRestarter: restarting kernel (1/5)
    WARNING:root:kernel 6209a03c-5e91-47a0-9434-b793fb2d1c1e restarted
    [I 16:31:39.054 NotebookApp] KernelRestarter: restarting kernel (1/5)
    WARNING:root:kernel 6209a03c-5e91-47a0-9434-b793fb2d1c1e restarted
    [I 16:31:45.065 NotebookApp] KernelRestarter: restarting kernel (1/5)
    WARNING:root:kernel 6209a03c-5e91-47a0-9434-b793fb2d1c1e restarted
    [I 16:31:51.071 NotebookApp] KernelRestarter: restarting kernel (1/5)
    WARNING:root:kernel 6209a03c-5e91-47a0-9434-b793fb2d1c1e restarted

**Comment by fonnesbeck** [comment]
I also get this on my OS X desktop. The kernel keeps restarting. Here is some of the terminal output:

     16:31:10.870 NotebookApp] Kernel started: cf8bde34-7f82-4840-a219-07a9c39bca69
    [I 16:31:21.010 NotebookApp] Kernel shutdown: cf8bde34-7f82-4840-a219-07a9c39bca69
    [W 16:31:21.022 NotebookApp] 404 GET /kernelspecs/julia%200.4/logo-64x64.png (::1) 10.55ms referer=http://localhost:8890/notebooks/02-ProbabilisticRepresentations.ipynb
    [I 16:31:21.034 NotebookApp] Kernel started: 6209a03c-5e91-47a0-9434-b793fb2d1c1e
    [I 16:31:27.034 NotebookApp] KernelRestarter: restarting kernel (1/5)
    [W 16:31:31.053 NotebookApp] Timeout waiting for kernel_info reply from 6209a03c-5e91-47a0-9434-b793fb2d1c1e
    [I 16:31:33.042 NotebookApp] KernelRestarter: restarting kernel (1/5)
    WARNING:root:kernel 6209a03c-5e91-47a0-9434-b793fb2d1c1e restarted
    [I 16:31:39.054 NotebookApp] KernelRestarter: restarting kernel (1/5)
    WARNING:root:kernel 6209a03c-5e91-47a0-9434-b793fb2d1c1e restarted
    [I 16:31:45.065 NotebookApp] KernelRestarter: restarting kernel (1/5)
    WARNING:root:kernel 6209a03c-5e91-47a0-9434-b793fb2d1c1e restarted
    [I 16:31:51.071 NotebookApp] KernelRestarter: restarting kernel (1/5)
    WARNING:root:kernel 6209a03c-5e91-47a0-9434-b793fb2d1c1e restarted

**Comment by fonnesbeck** [comment]
I also get this on my OS X desktop. The kernel keeps restarting. Here is some of the terminal output:

     16:31:10.870 NotebookApp] Kernel started: cf8bde34-7f82-4840-a219-07a9c39bca69
    [I 16:31:21.010 NotebookApp] Kernel shutdown: cf8bde34-7f82-4840-a219-07a9c39bca69
    [W 16:31:21.022 NotebookApp] 404 GET /kernelspecs/julia%200.4/logo-64x64.png (::1) 10.55ms referer=http://localhost:8890/notebooks/02-ProbabilisticRepresentations.ipynb
    [I 16:31:21.034 NotebookApp] Kernel started: 6209a03c-5e91-47a0-9434-b793fb2d1c1e
    [I 16:31:27.034 NotebookApp] KernelRestarter: restarting kernel (1/5)
    [W 16:31:31.053 NotebookApp] Timeout waiting for kernel_info reply from 6209a03c-5e91-47a0-9434-b793fb2d1c1e
    [I 16:31:33.042 NotebookApp] KernelRestarter: restarting kernel (1/5)
    WARNING:root:kernel 6209a03c-5e91-47a0-9434-b793fb2d1c1e restarted
    [I 16:31:39.054 NotebookApp] KernelRestarter: restarting kernel (1/5)
    WARNING:root:kernel 6209a03c-5e91-47a0-9434-b793fb2d1c1e restarted
    [I 16:31:45.065 NotebookApp] KernelRestarter: restarting kernel (1/5)
    WARNING:root:kernel 6209a03c-5e91-47a0-9434-b793fb2d1c1e restarted
    [I 16:31:51.071 NotebookApp] KernelRestarter: restarting kernel (1/5)
    WARNING:root:kernel 6209a03c-5e91-47a0-9434-b793fb2d1c1e restarted

**Comment by fonnesbeck** [comment]
I also get this on my OS X desktop. The kernel keeps restarting. Here is some of the terminal output:

     16:31:10.870 NotebookApp] Kernel started: cf8bde34-7f82-4840-a219-07a9c39bca69
    [I 16:31:21.010 NotebookApp] Kernel shutdown: cf8bde34-7f82-4840-a219-07a9c39bca69
    [W 16:31:21.022 NotebookApp] 404 GET /kernelspecs/julia%200.4/logo-64x64.png (::1) 10.55ms referer=http://localhost:8890/notebooks/02-ProbabilisticRepresentations.ipynb
    [I 16:31:21.034 NotebookApp] Kernel started: 6209a03c-5e91-47a0-9434-b793fb2d1c1e
    [I 16:31:27.034 NotebookApp] KernelRestarter: restarting kernel (1/5)
    [W 16:31:31.053 NotebookApp] Timeout waiting for kernel_info reply from 6209a03c-5e91-47a0-9434-b793fb2d1c1e
    [I 16:31:33.042 NotebookApp] KernelRestarter: restarting kernel (1/5)
    WARNING:root:kernel 6209a03c-5e91-47a0-9434-b793fb2d1c1e restarted
    [I 16:31:39.054 NotebookApp] KernelRestarter: restarting kernel (1/5)
    WARNING:root:kernel 6209a03c-5e91-47a0-9434-b793fb2d1c1e restarted
    [I 16:31:45.065 NotebookApp] KernelRestarter: restarting kernel (1/5)
    WARNING:root:kernel 6209a03c-5e91-47a0-9434-b793fb2d1c1e restarted
    [I 16:31:51.071 NotebookApp] KernelRestarter: restarting kernel (1/5)
    WARNING:root:kernel 6209a03c-5e91-47a0-9434-b793fb2d1c1e restarted

**Comment by fonnesbeck** [comment]
I also get this on my OS X desktop. The kernel keeps restarting. Here is some of the terminal output:

     16:31:10.870 NotebookApp] Kernel started: cf8bde34-7f82-4840-a219-07a9c39bca69
    [I 16:31:21.010 NotebookApp] Kernel shutdown: cf8bde34-7f82-4840-a219-07a9c39bca69
    [W 16:31:21.022 NotebookApp] 404 GET /kernelspecs/julia%200.4/logo-64x64.png (::1) 10.55ms referer=http://localhost:8890/notebooks/02-ProbabilisticRepresentations.ipynb
    [I 16:31:21.034 NotebookApp] Kernel started: 6209a03c-5e91-47a0-9434-b793fb2d1c1e
    [I 16:31:27.034 NotebookApp] KernelRestarter: restarting kernel (1/5)
    [W 16:31:31.053 NotebookApp] Timeout waiting for kernel_info reply from 6209a03c-5e91-47a0-9434-b793fb2d1c1e
    [I 16:31:33.042 NotebookApp] KernelRestarter: restarting kernel (1/5)
    WARNING:root:kernel 6209a03c-5e91-47a0-9434-b793fb2d1c1e restarted
    [I 16:31:39.054 NotebookApp] KernelRestarter: restarting kernel (1/5)
    WARNING:root:kernel 6209a03c-5e91-47a0-9434-b793fb2d1c1e restarted
    [I 16:31:45.065 NotebookApp] KernelRestarter: restarting kernel (1/5)
    WARNING:root:kernel 6209a03c-5e91-47a0-9434-b793fb2d1c1e restarted
    [I 16:31:51.071 NotebookApp] KernelRestarter: restarting kernel (1/5)
    WARNING:root:kernel 6209a03c-5e91-47a0-9434-b793fb2d1c1e restarted

**Comment by johansigfrids** [comment]
I am seeing this as well, this in Win 8.1 64 with Julia 0.3.6 and IPython 3.0.0 (from Anaconda). The kernel crashes whenever I open a notebook, but after a single restart everything works fine.

**Comment by dhoegh** [comment]
Do it also work for you if you use Julia 0.4.0?

**Comment by fonnesbeck** [comment]
Restarting definitely does not fix the issue for me on 0.4.0.

**Comment by dhoegh** [comment]
It where a question for @johansigfrids, since he se the behavior on 0.3.6 as I also do. Your problem seem to have another root.

**Comment by pylang** [comment]
I confirm similar issues with IPython crashing at startup using a fresh Julia install.  Everything installed ok except for ZMQ:  

```
=================================[ ERROR: ZMQ ]=================================


Provider PackageManager failed to satisfy dependency zmq
while loading ~\.julia\v0.3\ZMQ\deps\build.jl, in expression startin
g on line 22

===============================================================================

================================[ BUILD ERRORS ]================================


WARNING: ZMQ had build errors.

 - packages with build errors remain installed in ~\.julia\v0.3
 - build the package(s) and all dependencies with `Pkg.build("ZMQ")`
 - build a single package by running its `deps/build.jl` script

===============================================================================
```
Trying Pkg.build("ZMQ") did not find any problems.

[Win7, Python 2 (default), Python 3 (virtualenv), Julia 0.3.6]

**Comment by stevengj** [comment]
See the [debugging suggestions](https://github.com/JuliaLang/IJulia.jl#debugging-ijulia-problems) in the README to possibly get a more informative error message.

**Comment by dhoegh** [comment]
Thank you for the pointer @stevengj. I cant really see any obvious error messages in the output maybe you can see something, the output was: 
```
C:\Users\Hoegh>ipython notebook
[I 20:00:23.865 NotebookApp] Using existing profile dir: 'C:\\Users\\Hoegh\\.ipython\\profile_default'
[I 20:00:23.875 NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
[I 20:00:23.915 NotebookApp] Serving notebooks from local directory: C:\Users\Hoegh
[I 20:00:23.915 NotebookApp] 0 active kernels
[I 20:00:23.915 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
[I 20:00:23.915 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 20:00:27.256 NotebookApp] Creating new notebook in
[I 20:00:28.266 NotebookApp] Kernel started: 7c555a71-d46a-4938-8375-790b7b62becf
[W 20:00:28.283 NotebookApp] 404 GET /kernelspecs/julia%200.3/logo-64x64.png (::1) 15.00ms referer=http://localhost:8888/notebooks
/Untitled1.ipynb?kernel_name=julia%200.3
PROFILE = ["key"=>"60dbba92-72c6-482c-ae5f-6b642c40389a","transport"=>"tcp","signature_scheme"=>"hmac-sha256","shell_port"=>60808,
"hb_port"=>60812,"ip"=>"127.0.0.1","control_port"=>60811,"stdin_port"=>60810,"iopub_port"=>60809]
[W 20:00:38.293 NotebookApp] Timeout waiting for kernel_info reply from 7c555a71-d46a-4938-8375-790b7b62becf
SENDING IPython Msg [ idents status ] {
  header = ["msg_id"=>"4cd7457b-7aff-492d-889d-919ac19387c1","msg_type"=>"status","username"=>"jlkernel","session"=>"????"],
  metadata = Dict{String,Any}(),
  content = ["execution_state"=>"starting"]
}
Starting kernel event loops.
got msg part B05EDEE02428449E9FCB4711F26FC86E
got msg part <IDS|MSG>
RECEIVED IPython Msg [ idents B05EDEE02428449E9FCB4711F26FC86E ] {
  header = ["msg_id"=>"E956FDCB347A426389510C0B80304F7A","msg_type"=>"kernel_info_request","username"=>"username","version"=>"5.0"
,"session"=>"B05EDEE02428449E9FCB4711F26FC86E"],
  metadata = Dict{String,Any}(),
  content = Dict{String,Any}()
}
SENDING IPython Msg [ idents status ] {
  header = ["msg_id"=>"05567082-9c17-446b-b9f7-33f449008b0e","msg_type"=>"status","username"=>"jlkernel","session"=>"????"],
  metadata = Dict{String,Any}(),
  content = ["execution_state"=>"busy"]
}
SENDING IPython Msg [ idents B05EDEE02428449E9FCB4711F26FC86E ] {
  header = ["msg_id"=>"08858720-6acc-4f51-a9f4-b04e1ccd5d73","msg_type"=>"kernel_info_reply","username"=>"username","session"=>"B0
5EDEE02428449E9FCB4711F26FC86E"],
  metadata = Dict{String,Any}(),
  content = ["language_version"=>[0,3,6],"language"=>"julia","protocol_version"=>[4,0]]
}
SENDING IPython Msg [ idents status ] {
  header = ["msg_id"=>"a7db134c-e866-4353-86b5-51ae1203bbd8","msg_type"=>"status","username"=>"jlkernel","session"=>"????"],
  metadata = Dict{String,Any}(),
  content = ["execution_state"=>"idle"]
}
got msg part ???↑?
got msg part <IDS|MSG>
RECEIVED IPython Msg [ idents ???↑? ] {
  header = ["msg_id"=>"6a593857-dc63-43f1-9165-ec5f3dc8107a","msg_type"=>"kernel_info_request","username"=>"username","date"=>"201
5-03-25T20:00:28.291023","version"=>"5.0","session"=>"B05EDEE02428449E9FCB4711F26FC86E"],
  metadata = Dict{String,Any}(),
  content = Dict{String,Any}()
}
SENDING IPython Msg [ idents status ] {
  header = ["msg_id"=>"d071a0cb-8251-4bb0-aef2-839d2ecfca3e","msg_type"=>"status","username"=>"jlkernel","session"=>"????"],
  metadata = Dict{String,Any}(),
  content = ["execution_state"=>"busy"]
}
SENDING IPython Msg [ idents ???↑? ] {
  header = ["msg_id"=>"b7f70109-5adc-4424-88a1-c376709b1ce7","msg_type"=>"kernel_info_reply","username"=>"username","session"=>"B0
5EDEE02428449E9FCB4711F26FC86E"],
  metadata = Dict{String,Any}(),
  content = ["language_version"=>[0,3,6],"language"=>"julia","protocol_version"=>[4,0]]
}
SENDING IPython Msg [ idents status ] {
  header = ["msg_id"=>"ecdd4f9c-1cfe-4ca9-9ef1-c38e2c9002e3","msg_type"=>"status","username"=>"jlkernel","session"=>"????"],
  metadata = Dict{String,Any}(),
  content = ["execution_state"=>"idle"]
}
[I 20:00:39.258 NotebookApp] Kernel 7c555a71-d46a-4938-8375-790b7b62becf speaks protocol 4.0
got msg part B05EDEE02428449E9FCB4711F26FC86E
got msg part <IDS|MSG>
RECEIVED IPython Msg [ idents B05EDEE02428449E9FCB4711F26FC86E ] {
  header = ["msg_id"=>"DD524068F7874EB6BB36F123FC960951","msg_type"=>"kernel_info_request","username"=>"username","version"=>"5.0"
,"session"=>"B05EDEE02428449E9FCB4711F26FC86E"],
  metadata = Dict{String,Any}(),
  content = Dict{String,Any}()
}
SENDING IPython Msg [ idents status ] {
  header = ["msg_id"=>"c4078e05-293e-4b31-ab08-d1ee536584c1","msg_type"=>"status","username"=>"jlkernel","session"=>"????"],
  metadata = Dict{String,Any}(),
  content = ["execution_state"=>"busy"]
}
SENDING IPython Msg [ idents B05EDEE02428449E9FCB4711F26FC86E ] {
  header = ["msg_id"=>"41a0f5f4-6386-41b1-acd2-da9eb31d872c","msg_type"=>"kernel_info_reply","username"=>"username","session"=>"B0
5EDEE02428449E9FCB4711F26FC86E"],
  metadata = Dict{String,Any}(),
  content = ["language_version"=>[0,3,6],"language"=>"julia","protocol_version"=>[4,0]]
}
SENDING IPython Msg [ idents status ] {
  header = ["msg_id"=>"43effe0f-14d6-4f61-bf5c-4b01893313cd","msg_type"=>"status","username"=>"jlkernel","session"=>"????"],
  metadata = Dict{String,Any}(),
  content = ["execution_state"=>"idle"]
}
[I 20:00:40.283 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 7c555a71-d46a-4938-8375-790b7b62becf restarted
PROFILE = ["key"=>"60dbba92-72c6-482c-ae5f-6b642c40389a","transport"=>"tcp","signature_scheme"=>"hmac-sha256","shell_port"=>60808,
"hb_port"=>60812,"ip"=>"127.0.0.1","control_port"=>60811,"stdin_port"=>60810,"iopub_port"=>60809]
SENDING IPython Msg [ idents status ] {
  header = ["msg_id"=>"eb5d6e47-cc93-432c-a277-5c1ff05ee6df","msg_type"=>"status","username"=>"jlkernel","session"=>"????"],
  metadata = Dict{String,Any}(),
  content = ["execution_state"=>"starting"]
}
Starting kernel event loops.
```

**Comment by stevengj** [comment]
The `got msg part ???↑?` looks odd...

**Comment by dhoegh** [comment]
This issue can be resolved by installing from fresh, see: https://groups.google.com/forum/m/?fromgroups#!topic/julia-users/1t-qtenxQNA
