### ISSUE TITLE
No syntax highlight for the first cell in IJulia notebook

### ISSUE THREAD

**Issue by Sisyphuss** [JuliaLang/IJulia.jl#288]
The syntax highlight for the first cell in IJulia notebook doesn't work.

IJulia version: 0.2.1

**Comment by jiahao** [comment]
This particular problem is fixed in IPython 3.0, which is the new stable release.

**Comment by Sisyphuss** [comment]
Thanks jiahao. I updated my IPython. The problem disappeared. 
But for JuliaBox, I think they haven't updated it yet.

**Comment by Sisyphuss** [comment]
It was my fault. They have updated.
