### ISSUE TITLE
Pyplot figures are HUGE!!

### ISSUE THREAD

**Issue by spencerlyon2** [JuliaLang/IJulia.jl#290]
A screenshot captures it all...

![screen shot 2015-04-07 at 12 54 09 am](https://cloud.githubusercontent.com/assets/1001948/7017142/b0a662e0-dcc0-11e4-8609-77402e278346.png)

Any ideas?

I feel like this started happening just within the last couple months.

**Comment by stevengj** [comment]
I've never seen that... did you change a matplotlibrc configuration file or something?

**Comment by spencerlyon2** [comment]
I haven't changed my rc file for a few years, but when I deleted the one I have been using the problem was resolved. Not sure what was in it that caused the problems...

Thanks for the tip
