### ISSUE TITLE
Problem with some hyperbolic functions

### ISSUE THREAD

**Issue by sherrinm** [JuliaLang/IJulia.jl#291]
julia> 1/cosh(π)
0.08626673833405443

julia> sech(π)
ERROR: `convert` has no method matching convert(::Type{MathConst{:π}}, ::Int64)
 in sech at special/trig.jl:101

julia> sech(1.0π)
0.08626673833405443

julia> # Similar for csch(π) and coth(π)

**Comment by stevengj** [comment]
This is a Julia issue, not an IJulia issue.   See JuliaLang/julia#5561 and JuliaLang/julia#7994

**Comment by sherrinm** [comment]
Sorry posted it to the wrong group
