### ISSUE TITLE
Package Installation Errors

### ISSUE THREAD

**Issue by jeremy-y12** [JuliaLang/IJulia.jl#292]
The IJulia package fails to build on my system, probably due to the accents in the folder path:
```
INFO: Building IJulia
Found IPython version 2.2.0 ... ok.
Creating julia profile in IPython...
Creating ipython_qtconsole_config.py with IPythonWidget.execute_on_complete_inpu
t = False...
===============================[ ERROR: IJulia ]================================


opening file C:\Users\J?r?my\.ipython\profile_julia\ipython_qtconsole_config.py:
 No such file or directory
while loading C:\Users\Jérémy\.julia\v0.3\IJulia\deps\build.jl, in expression st
arting on line 92

================================================================================
```

I am using Windows 8.1 and Julia 0.3.7

**Comment by stevengj** [comment]
We're using `ipython locate profile julia` to get the profile location, but I'm guessing there is a Unicode encoding mismatch.  We're reading it as UTF-8, but maybe `ipython` is outputting UTF-16?  @Carreau, do you know what encoding `ipython` uses for unicode console output on Windows?

**Comment by stevengj** [comment]
Does running `chcp 65001` (to change the Windows console to UTF-8) help?

**Comment by Carreau** [comment]
On windows I'm not sure, I guess it might try to output what the prefered encodding on windows is. 

You can run `python -c 'import sys; print(sys.getdefaultencoding())'` to see.

**Comment by stevengj** [comment]
It's possible that Python is using `WriteConsoleW` to output Unicode, and it is the Windows console's fault for mucking with the code page?

Why they are still dealing with code pages in 2015 is beyond me.

**Comment by stevengj** [comment]
@Carreau, [according to docs.python.org](https://docs.python.org/2/howto/unicode.html), "Python’s default encoding is the ‘ascii’ encoding," which raises a `UnicodeEncodeError` on non-ASCII characters.  So, that doesn't seem to be what is used here?

**Comment by stevengj** [comment]
Aha, according to [this page](http://stackoverflow.com/questions/2596714/why-does-python-print-unicode-characters-when-the-default-encoding-is-ascii), for output of Unicode strings to stdout, Python uses `sys.stdout.encoding`.   @jeremy-y12, what does `python -c "import sys; print(sys.stdout.encoding)"` give?

**Comment by stevengj** [comment]
@jeremy-y12, I've pushed the workaround setting `PYTHONIOENCODING`.  Do a `Pkg.update()` and try again, and let us know if this fixes things for you.

**Comment by Carreau** [comment]
Yeah, Python default on windows is crazy, and we still get weirds errors when some things try to be smart and try to "detect" output stream encoding.

**Comment by jeremy-y12** [comment]
It works now, thanks.
