### ISSUE TITLE
16-bit image display?

### ISSUE THREAD

**Issue by Jakki42** [JuliaLang/IJulia.jl#294]
Using image.jl imread to load 16 bit images works as long as it's not displayed:

This works fine:
`imread(filename);`

But this causes an error:
`imread(filename)`

```julia
`map` has no method matching map(::BitShift{Gray{UfixedBase{Uint8,8}},8}, ::Gray{UfixedBase{Uint16,16}})
```

**Comment by timholy** [comment]
Fix coming; held up by new test failure on 0.4 due to https://github.com/JuliaLang/julia/pull/9666#issuecomment-93711651.

**Comment by stevengj** [comment]
In any case, this is an Images problem, not an IJulia issue.

**Comment by timholy** [comment]
Works if you do `Pkg.update()`.
