### ISSUE TITLE
Malformed data kills kernel

### ISSUE THREAD

**Issue by jaredly** [JuliaLang/IJulia.jl#295]
If a message sent to the kernel is missing some information on the `header` object, the entire kernel becomes unresponsive.

This seems like it would be pretty straightforward to solve.

```
KERNEL EXCEPTION
key not found: "session"

 in getindex at dict.jl:617
 in msg_pub at /home/jared/.julia/v0.3/IJulia/src/msg.jl:23
KERNEL EXCEPTION
key not found: "session"
```

```
KERNEL EXCEPTION
key not found: "username"

 in getindex at dict.jl:617
 in msg_pub at /home/jared/.julia/v0.3/IJulia/src/msg.jl:23
```

I found this problem while working on an alternate frontend notebook for ipython. Using the protocol version 5.0.

When I fixed the missing fields, everything worked fine, but it seemed like the server should be a bit more robust.

**Comment by Carreau** [comment]
IPython 3.x get an adapter that does the transition between v4 and v5 message spec. I suppose that trying to speak directly with IJulia might does some weird things and not well supported.

**Comment by stevengj** [comment]
Right now we are ignoring malformed messages, and we don't support the v5 message spec.   At some point we will switch over to v5 once it is clear that IPython 3 is pretty universal in our userbase.   We could try to support both versions of the message spec, but it doesn't seem worth it right now as it works well enough with v4.

In general, I'm skeptical that we should be robust to malformed messages unless there is some specific front-end we are targeting whose bugs we are compensating for; it seems like there are a lot of ways that messages could be messed up.

**Comment by jaredly** [comment]
I'm not speaking directly to iJulia -- I'm going through ipython 3.x.
But it doesn't seem like malformed messages are being ignored -- like I said, the kernel becomes unresponsive and has to be restarted.

**Comment by stevengj** [comment]
Hmm, that is a bug; not sure what the source is, though.

**Comment by stevengj** [comment]
Closing as not reproducible.
