### ISSUE TITLE
Error installing IJulia on Debian Sid

### ISSUE THREAD

**Issue by NhanHo** [JuliaLang/IJulia.jl#300]
I'm trying to install IJulia on my Debian box. Julia version is 0.3.7, python 2.7.9 and ipython 2.3.0 . I got an error on ZMQ dependency. I can find the ZMQ lib under ~/.julia/v0.3/ZMQ/deps/usr/lib after running `Pkg.build("ZMQ")`.  The build process of ZMQ seems to complete successfully, however Julia returns an error

```
Provider BuildProcess failed to satisfy dependency zmq
       while loading /home/nhanho/.julia/v0.3/ZMQ/deps/build.jl, in expression starting on line 22
```

The line in question would be 
```
@BinDeps.install [:zmq => :zmq]
```

Attempts to copy lib folder of ZMQ to lib32 and lib64 didn't result in anything (I thought it was a mix up because of 64 bit library)

If I tried to start a Julia notebook, it will repeatedly try to reset the kernel with error "ZMQ not properly installed"

**Comment by stevengj** [comment]
Can you just install the `libzmq-dev` Debian package and re-run `Pkg.build("ZMQ")` in Julia?

**Comment by stevengj** [comment]
In any case, this is not really an IJulia issue per se.   If you continue to have problems, you should file an issue at the ZMQ package.
