### ISSUE TITLE
Expressions not being evaluated under 0.4-dev

### ISSUE THREAD

**Issue by sebastiang** [JuliaLang/IJulia.jl#301]
notebook starts, files can be saved, etc. but on shift-enter, the line is marked as being evaluated yet no output is shown. During load of IJulia, and on execution of the first notebooks however, the following warning appears

    Warning: both Libdl and Base export "dlopen_e"; uses of it in module ZMQ must be qualified

**Comment by stevengj** [comment]
To use 0.4 you often need to be on the git master versions of packages as well.  I think this particular problem was fixed in JuliaLang/BinDeps.jl@77bf10df1c56bd6c83b15dced5bb1a2b0f840a9f

If you don't want to deal with continual breakage like this, you should use Julia 0.3.x.

**Comment by kmsquire** [comment]
(Or someone could just tag BinDeps and/or ZMQ)

**Comment by sebastiang** [comment]
I'm an idiot! I should have realized that as I've been dealing with the same and making a few fixes in many of those packages...
