### ISSUE TITLE
problem with IJulia and Kernel

### ISSUE THREAD

**Issue by LukasB82** [JuliaLang/IJulia.jl#302]
Hi
I am totally new with Julia and tried to set up IJulia as described in "Setting up Your Julia Environment".

The Kernel died instantly calling an error:
"The kernel appears to have died. It will restart automatically."

Restart Kernel gets:
Error: ZMQ not properly installed Please run Pkg.build("ZMQ")
...
...
while loading [path] in expression starting on line 19
while loading [path] in expression starting on line 13
while loading [path] in expression starting on line 4

and then it stays in a restarting loop.

Following setups I get:
Julia 0.3.7
anaconda 2.2.0

kind regards
Lukas

**Comment by jiahao** [comment]
Did you try doing as the error message said? What happens when you try to run ` Pkg.build("ZMQ")`?

**Comment by LukasB82** [comment]
I did and did it again after restarting today morning and finally it works now
