### ISSUE TITLE
Allow adjusting the output size of displayed matrices

### ISSUE THREAD

**Issue by garrison** [JuliaLang/IJulia.jl#307]
When matrices are displayed in IJulia, they are displayed under the assumption of an 80-character display.  For instance,

    zeros(1, 40)

leads to

    1x40 Array{Float64,2}:
     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0

It would be great if this display size were somehow adjustable.

If I am following things correctly, it seems that the size is calculated [here in julia's `base/show.jl`](https://github.com/JuliaLang/julia/blob/053780d0795b93149825cd2085425f34a3449fe5/base/show.jl#L992-L993).  However, `Base.tty_size()` seems to always return `(30,80)` for me when running in IJulia notebook, regardless of the size of the window used to start the session.

CC: @mishmash

**Comment by stevengj** [comment]
`ENV["COLUMNS"] = 200`

**Comment by stevengj** [comment]
Documentation improvements in d84e3896ae83f16f92d85db7dbf73c6018b77fb4

**Comment by garrison** [comment]
Thanks!
