### ISSUE TITLE
Red boxes around unicode characters

### ISSUE THREAD

**Issue by rodonn** [JuliaLang/IJulia.jl#308]
When I write code the includes unicode characters in IJulia, those characters are wrapped in red boxes when I export to PDF or "print preview".

I asked the IPython group, since I had seen a similar issue there (when using Python 3 which also allows unicode characters). https://github.com/ipython/ipython/issues/5536#issuecomment-98808432

They said the problem is in the parsing done by pygments.

**Comment by rodonn** [comment]
![screen shot 2015-05-04 at 11 45 53 pm](https://cloud.githubusercontent.com/assets/2594443/7467991/d2008d1e-f2b7-11e4-8a66-5709cd9847c6.png)

**Comment by stevengj** [comment]
@malmaud, didn't you look at this at one point?

**Comment by malmaud** [comment]
If memory serves, I did encounter this problem but didn't fix it. It is indeed a problem with the Julia pygments lexer and should just be a matter of changing a regex. I'll submit a PR to pygments.

**Comment by stevengj** [comment]
Thanks!

**Comment by rodonn** [comment]
It looks like Pygments might already have an open issue for this, but it doesn't look like anyone is working on it currently. 
https://bitbucket.org/birkenfeld/pygments-main/issue/1074/square-boxes-around-unicode-characters-in

I took a quick look at the Python3 lexer, which does support Unicode characters. It looks like the fix might be as simple as adding "flags = re.UNICODE" to tell the python regex parser to allow unicode characters. 

I haven't tested the change yet though.

**Comment by malmaud** [comment]
I created a PR on bitbucket that solves this:  https://bitbucket.org/birkenfeld/pygments-main/pull-request/471/support-unicode-identifiers-in-julia/diff

**Comment by jiahao** [comment]
Yay!

Unicode code points go up to 0x10ffff; is it possible to allow characters beyond 0xffff in the name regex?

**Comment by malmaud** [comment]
Yes it is.

**Comment by rodonn** [comment]
I tried out the new pygments lexer. It seems like it is no longer putting red boxes around unicode characters in an IJulia notebook, but now it is putting boxes around '#' characters


![screen shot 2015-05-25 at 12 49 38 pm](https://cloud.githubusercontent.com/assets/2594443/7801653/ee70135e-02dc-11e5-89c9-b6803fefab35.png)

**Comment by rodonn** [comment]
Forward progress :)

**Comment by malmaud** [comment]
Should work now.

**Comment by rodonn** [comment]
Thanks! Works great for me now.

**Comment by maximerischard** [comment]
Thank you! The fix works great.

**Comment by malmaud** [comment]
Unfortunately, [my PR on pygments](https://bitbucket.org/birkenfeld/pygments-main/pull-request/471/support-unicode-identifiers-in-julia/diff) doesn't seem to be getting attention despite my efforts. Maybe we should consider locally patching pygments?

**Comment by Carreau** [comment]
Just ask the Julia ML, tweeter spheer to DDoS of +1.

**Comment by kshyatt** [comment]
Should I start livetweeting this PR like I did JuliaCon? Please advise :smile:

**Comment by malmaud** [comment]
Thanks @Carreu!

**Comment by damiendr** [comment]
I get no red boxes but notice how `:\theta` is not highlighted the same ways as `:W`. Should I open a new issue here, or on pygments?

IJulia                        1.1.7

![capture d ecran 2015-10-15 a 12 12 37](https://cloud.githubusercontent.com/assets/1659790/10510912/1db056dc-7336-11e5-8673-04ec7f86ea81.png)

**Comment by malmaud** [comment]
Can you open an issue on pygments and link to it here?

**Comment by damiendr** [comment]
Done: https://bitbucket.org/birkenfeld/pygments-main/issues/1159/parsing-of-symbols-with-unicode-characters
