### ISSUE TITLE
"using ijulia" is fine but "notebook()" explodes, same error with "ipython notebook --profile julia" {on Centos6.6 with Anaconda2.7 fully updated} {with export LC_ALL=en_US.UTF-8 and export LANG=en_US.UTF-8} 

### ISSUE THREAD

**Issue by hushfrog** [JuliaLang/IJulia.jl#312]
Many, people reporting the same error on mac platforms.

ERROR: failed process: Process(`ipython notebook --profile julia`, ProcessExited(1)) [1]
 in pipeline_error at process.jl:502
 in notebook at /root/.julia/v0.3/IJulia/src/IJulia.jl:177
 in notebook at /root/.julia/v0.3/IJulia/src/IJulia.jl:176

**Comment by pao** [comment]
What happens if you just run `ipython notebook --profile julia` from a terminal? (Does `--profile` work with IPython 3.x?)

**Comment by hushfrog** [comment]
Same result with Anaconda 34
Same result with RH Python v2.7 and v3.3
Sane error when run by "python notebook --profile julia"

**Comment by hushfrog** [comment]
Same problem on Mac 10.10

**Comment by hushfrog** [comment]
IJulia simply does not work with CentOS/RHEL v6.x with any version of anaconda or RHEL provided ipython

**Comment by stevengj** [comment]
What happens if you simply run `ipython notebook` from the terminal (with IPython 3 ... run `ipython --version` to make sure you have a recent version.)

**Comment by stevengj** [comment]
Closing this issue as the `--profile julia` method is no longer relevant with IPython 3.

**Comment by zoof** [comment]
`--profile julia` may no longer be relevant but calling `notebook()` from julia still calls it that way:
 
    ERROR: failed process: Process(`ipython notebook --profile julia`, ProcessExited(1)) [1]
     in pipeline_error at process.jl:502
     in notebook at /home/tct/.julia/v0.3/IJulia/src/IJulia.jl:177
     in notebook at /home/tct/.julia/v0.3/IJulia/src/IJulia.jl:176

**Comment by stevengj** [comment]
@zoof, not in the latest `master` version (not yet tagged).
