### ISSUE TITLE
Syntax highlighting doesn't work very well in the first cell.

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/IJulia.jl#313]
I'm not sure if this is an `IJulia.jl` issue or a `Jupyther`/`IPython` issue but here's what it looks.

[![Screen shot](http://paste.opensuse.org/images/24807390.png)](http://paste.opensuse.org/24807390)

The syntax highlighing in the first cell is not really working. By not working here I actually mean that it is highlighting python syntax. It sometimes works and refreshing the page sometimes makes a difference.

**Comment by Carreau** [comment]
Is the syntax ok until you execute ? If so this is fixed in IPython, and should be released soon.

**Comment by yuyichao** [comment]
The highlight can be bad before I execute it but IIRC it usually (if not always) starts OK though (it goes bad after some typing).

**Comment by Carreau** [comment]
You can try to upgrade to IPython 3.x branch if you like see if it still happen.

**Comment by yuyichao** [comment]
OK. I'll try later.

**Comment by Sisyphuss** [comment]
According to my experience, you should just wait it for a while, and then the highlight of the first cell will work normally.

**Comment by stevengj** [comment]
Seems no longer reproducible?
