### ISSUE TITLE
IJulia crash on Windows 8.1 with IPython 3.1.0

### ISSUE THREAD

**Issue by nowozin** [JuliaLang/IJulia.jl#317]
I have used IJulia regularly over the last year, but after upgrading Julia to 0.3.9 experience the following problem.

When starting IJulia using either the command line or through `notebook()`, the browser interface comes up.  When creating or opening a Julia notebook file the kernel, `julia.exe`, immediately crashes and is restarted, then crashes again.

This does not seem to be a _Jupyter_ issue because I can create and work with Python notebooks.
I tried Julia versions 0.3.8, 0.3.9, and 0.4.0-dev+5277 and `Pkg.build("IJulia")`, as well as reinstalling packages from scratch by deleting the `v0.3` directory.

I use the Anaconda 64-bit distribution, and `conda --version` gives `conda 3.11.0-dirty`.

```
julia> versioninfo(true)
Julia Version 0.4.0-dev+5277
Commit 539c818 (2015-06-09 08:51 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
  WORD_SIZE: 64
           Microsoft Windows [Version 6.3.9600]
  uname: MINGW32_NT-6.2 1.0.12(0.46/3/2) 2012-07-05 14:56 i686 unknown
```

**Comment by stevengj** [comment]
Can you try https://github.com/JuliaLang/IJulia.jl#debugging-ijulia-problems to see if you can get more information?

**Comment by tkelman** [comment]
How long ago did you upgrade, or when specifically did it start crashing?

It looks like opensuse did a rebuild of their gcc cross-compilers recently which may have caused this. I just tagged a new version of WinRPM, so if you do `Pkg.update(); Pkg.build("WinRPM")` it might fix this.

**Comment by nowozin** [comment]
Hi Steven,

I did enable `verbose` as described in the above link, however the output and behaviour is the same.
This is the complete console window output when starting ipython, then opening or creating a notebook file:

```
[I 09:03:54.036 NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
[I 09:03:54.075 NotebookApp] Serving notebooks from local directory: d:\dev
[I 09:03:54.076 NotebookApp] 0 active kernels
[I 09:03:54.076 NotebookApp] The IPython Notebook is running at: http://localhost:8998/
[I 09:03:54.076 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
C:\Anaconda\lib\site-packages\IPython\kernel\manager.py:95: UserWarning: Setting kernel_cmd is deprecated, use kernel_spec to start different kernels.  warnings.warn("Setting kernel_cmd is deprecated, use kernel_spec to "
[I 09:03:59.861 NotebookApp] Kernel started: da49a5d3-e033-4feb-aeaa-8701bca9514e
[W 09:04:09.891 NotebookApp] Timeout waiting for kernel_info reply from da49a5d3-e033-4feb-aeaa-8701bca9514e
[I 09:04:20.855 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel da49a5d3-e033-4feb-aeaa-8701bca9514e restarted
```

A Windows popup appears `julia.exe has stopped working...`.

Tony, I upgraded late last week but have not upgraded for two weeks before since.
I just upgraded WinRPM to 0.1.9 and rebuild it and now the **notebook interface is working again** with Julia 0.3.9, so indeed this may have been related to WinRPM.
