### ISSUE TITLE
Julia Fails to Start

### ISSUE THREAD

**Issue by LEAP-nishit** [JuliaLang/IJulia.jl#318]
I have a clean install of Python (Anaconda) and Julia. Jupyter and Julia work fine before installing IJulia by typing Pkg.add("IJulia") in julia term. 

After adding the pkg, julia terminal fails, same in the case for starting a Julia notebook. 

Workaround was to remove libstdc++-6.dll (I think this was provided during the install) and rename libstdc++-6-copy.dll to libstdc++-6.dll.

**Comment by stevengj** [comment]
What OS are you using?

**Comment by stevengj** [comment]
Does IPython (i.e. the Python back-end) work?  What led you to believe that the problem was `libstdc++-6.dll`?

**Comment by ihnorton** [comment]
I think this should be fixed by https://github.com/JuliaLang/julia/pull/11793 when you update your install or build ... Please comment if not.

See also [0.3.10 release announcement](https://groups.google.com/d/msg/julia-users/MEtS3mWgRRg/2MJaHoaIK2gJ)

**Comment by tkelman** [comment]
Yes, thanks @ihnorton. This was at least partially my fault for switching zmq over to winrpm/opensuse, but it's resolved for the time being, with continuing work items to future-proof even further.
