### ISSUE TITLE
Use julia profile in ipython kernel mode

### ISSUE THREAD

**Issue by sebastiansturm** [JuliaLang/IJulia.jl#320]
Hi,

I'd like to use IJulia as an alternative backend for ob-ipython (https://github.com/gregsexton/ob-ipython), which requires running ipython in kernel mode. When I call ```ipython kernel --profile julia --debug```, ipython seems to load the right settings:
```
[IPKernelApp] Config changed:
[IPKernelApp] {'IPKernelApp': {'profile': 'julia', 'log_level': 10}}
[IPKernelApp] IPYTHONDIR set to: /Users/sebastian/.ipython
[IPKernelApp] Using existing profile dir: '/Users/sebastian/.ipython/profile_julia'
[IPKernelApp] Searching path ['/Users/sebastian', '/Users/sebastian/.ipython/profile_julia', '/usr/local/etc/ipython', '/etc/ipython'] for config files
[IPKernelApp] Attempting to load config file: ipython_config.py
[IPKernelApp] Loaded config file: /Users/sebastian/.ipython/profile_julia/ipython_config.py
[IPKernelApp] Config changed:
[IPKernelApp] {'IPKernelApp': {'profile': 'julia', 'log_level': 10}, 'KernelManager': {'kernel_cmd': ['/usr/local/Cellar/julia/HEAD/bin/julia', '-i', '-F', '/Users/sebastian/.julia/v0.4/IJulia/src/kernel.jl', '{connection_file}']}}
[IPKernelApp] Attempting to load config file: ipython_kernel_config.py
[IPKernelApp] Loaded config file: /Users/sebastian/.ipython/profile_julia/ipython_kernel_config.py
[IPKernelApp] Connection file not found: kernel-67546.json
[IPKernelApp] Starting the kernel at pid: 67546
[IPKernelApp] shell ROUTER Channel on port: 54079
[IPKernelApp] iopub PUB Channel on port: 54080
[IPKernelApp] stdin ROUTER Channel on port: 54081
[IPKernelApp] control ROUTER Channel on port: 54082
[IPKernelApp] Heartbeat REP Channel on port: 54083
[IPKernelApp] To connect another client to this kernel, use:
[IPKernelApp]     --existing kernel-67546.json --profile julia
NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-67546.json --profile julia
[IPKernelApp] Writing connection file: /Users/sebastian/.ipython/profile_julia/security/kernel-67546.json
[IPKernelApp] Loading IPython extensions...
[IPKernelApp] Loading IPython extension: storemagic
```
However, connecting to the kernel via ```ipython console --existing kernel-67546.json --profile julia``` does not actually establish an IJulia console, but instead sends everything to Python. For instance, ```sin(5)``` yields ```NameError: name 'sin' is not defined```. Is this expected behavior? If so, how can I get ipython to serve a Julia kernel?
I'm using ipython 3.1.0 and Julia 0.4.0-dev+5319 on Mac OS 10.10, and the IJulia package has been downloaded and built from source yesterday.

**Comment by Carreau** [comment]
OK I  guess that the bit confusing part, but IPython need a way to launch the Python process which is "The IPython Kernel written in Python". And that is was `ipython kernel` is. Basically by the point `ipython kernel` is called, the language is already decided by the parent process. 

The usage of profiles to launch kernels has also been deprecated for a certain time, but that's not completely relevant now.

The other confusing part is that the Python kernel is the only one IIRC that can start without specifying the connexion file. Usually the way it works is the following, the program that interact with the user:

   - ask the language.
   - look in `.ipython/kernels` /`.jupyter/kernels` for the matching language.get the kernel.json file
   - find 3 free ports, bind to it, 
   - write the json connexion file.
   - subprocess run the info found in kernel.json that describe how to launch a kernel.

in the case of julia:

```
$ cat /Users/bussonniermatthias/.ipython/kernels/julia-0.3/kernel.json
{
  "display_name": "Julia 0.3.9-pre",
  "argv": [
    "/Users/bussonniermatthias/dev/julia/usr/bin/julia",
    "-i",
    "-F",
    "/Users/bussonniermatthias/.julia/v0.3/IJulia/src/kernel.jl",
    "{connection_file}"
  ],
  "language": "julia"
}
```

In the case of notebook, we provide a RST api to do that, which make things look simpler.
I suppose you are mostly in the same case than  [Hydrogen](https://github.com/willwhitney/hydrogen/blob/master/lib/kernel.coffee#L47-L490) the code in here will be much smaller to understand than the one in [IPython](https://github.com/jupyter/jupyter_client/blob/master/jupyter_client/launcher.py#L14) 

Does that make sens ?

**Comment by sebastiansturm** [comment]
thanks alot! In reply to a similar issue on the ob-ipython github page, @ajsteven130 told me that ```jupyter_client``` can be used to write a kernel manager for Julia. It's not clear to me yet if hydrogen uses that approach (or, if not, which approach is preferable), but I'll be sure to check out both. Thanks again!
