### ISSUE TITLE
Kernel restarts endlessly on any julia command

### ISSUE THREAD

**Issue by mbaz** [JuliaLang/IJulia.jl#322]
IJulia was working flawlessly on my system a few days ago. I ran a system update recently and now it fails. I can start a notebook, but upon entering any command (e.g. 2+2), the kernel dies and enters a restart/die endless loop.

I just ran a Pkg.update() and the problem persists.  I'm running IJulia stable, not master.

$ ipython --version
2.4.1
$ python --version
Python 3.4.3
$ julia --version
julia version 0.3.9

I get the same results starting the notebook from inside Julia or using ipython on the command line. I enabled debug messages in IJulia; I pasted the result here: https://gist.github.com/mbaz/3a4193d97bdfb93765ba

Note the segmentation fault right after the first IPython message is sent.

**Comment by mbaz** [comment]
The problem seems to be caused by the recent upgrade of ZMQ from 4.0 to 4.1. I downgraded to ZMQ 4.0 and the problem went away.

**Comment by mbaz** [comment]
Confirmed error is in ZMQ... filed an issue there. Sorry for the noise.

**Comment by minrk** [comment]
In that case, it is the bug fixed by #314. zeromq-4.1.1 had a bug that messed with the heartbeat mechanism. This is fixed in zeromq-4.1.2.

**Comment by mbaz** [comment]
@minrk Even with ZMQ and IJulia master, the error keeps occuring with zeromq-4.2.1. If I downgrade to zeromq-4.0.5, the problem goes away.
