### ISSUE TITLE
Segmentation fault upon creating a notebook

### ISSUE THREAD

**Issue by gaborbernat** [JuliaLang/IJulia.jl#323]
Here's a snippet of the error (using Antergos - Arch Linux latest of most) with Julia 0.3.9 and Pkg.add("IJulia"):

	poll([{fd=23, events=POLLIN}], 1, 0)    = 1 ([{fd=23, revents=POLLIN}])
	read(23, "\1\0\0\0\0\0\0\0", 8)         = 8
	poll([{fd=23, events=POLLIN}], 1, 0)    = 0 (Timeout)
	poll([{fd=7, events=POLLIN}, {fd=5, events=POLLIN}, {fd=6, events=POLLIN}, {fd=9, events=POLLIN}, {fd=10, events=POLLIN}, {fd=11, events=POLLIN}, {fd=12, events=POLLIN}, {fd=13, events=POLLIN}, {fd=14, events=POLLIN}, {fd=23, events=POLLIN
	}, {fd=22, events=POLLIN}], 11, 2502SENDING IPython Msg [ idents status ] {
	  header = ["msg_id"=>"d6faa9dc-0b47-4a60-8a4a-428b7cfbbf5a","msg_type"=>"status","username"=>"jlkernel","session"=>"????"],
	  metadata = Dict{String,Any}(),
	  content = ["execution_state"=>"starting"]
	}

	signal (11): Segmentation fault
	unknown function (ip: 1422176418)
	jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
	setindex! at dict.jl:559
	Message at /home/bernat/.julia/v0.3/ZMQ/src/ZMQ.jl:415
	send_ipython at /home/bernat/.julia/v0.3/IJulia/src/msg.jl:50
	jlcall_send_ipython_20550 at  (unknown line)
	jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
	send_status at /home/bernat/.julia/v0.3/IJulia/src/msg.jl:108
	init at /home/bernat/.julia/v0.3/IJulia/src/IJulia.jl:107
	jlcall_init_20465 at  (unknown line)
	jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
	unknown function (ip: 1422473032)
	unknown function (ip: 1422469545)
	unknown function (ip: 1422538269)
	unknown function (ip: 1422540960)
	jl_load at /usr/bin/../lib/julia/libjulia.so (unknown line)
	include at /usr/bin/../lib/julia/sys.so (unknown line)
	jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
	include_from_node1 at loading.jl:128
	jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
	process_options at /usr/bin/../lib/julia/sys.so (unknown line)
	_start at /usr/bin/../lib/julia/sys.so (unknown line)
	jlcall__start_17455 at /usr/bin/../lib/julia/sys.so (unknown line)
	jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
	unknown function (ip: 4200709)
	julia_trampoline at /usr/bin/../lib/julia/libjulia.so (unknown line)
	unknown function (ip: 4199613)
	__libc_start_main at /usr/bin/../lib/libc.so.6 (unknown line)
	unknown function (ip: 4199673)
	unknown function (ip: 0)
	) = ? ERESTART_RESTARTBLOCK (Interrupted by signal)
	--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_DUMPED, si_pid=18885, si_uid=1000, si_status=SIGSEGV, si_utime=344, si_stime=36} ---
	restart_syscall(<... resuming interrupted call ...>

Any ideas how to fix it?

**Comment by vchuravy** [comment]
I am also seeing this.

````
[W 22:41:38.052 NotebookApp] 404 GET /kernelspecs/julia-0.3/logo-64x64.png (::1) 2.49ms referer=http://localhost:8888/notebooks/Untitled1.ipynb?kernel_name=julia-0.3
PROFILE = ["key"=>"43bd985d-7fb3-4cad-bc99-02218018ee86","transport"=>"tcp","signature_scheme"=>"hmac-sha256","shell_port"=>56561,"ip"=>"127.0.0.1","control_port"=>37017,"hb_port"=>46793,"stdin_port"=>60356,"iopub_port"=>49385]
SENDING IPython Msg [ idents status ] {
  header = ["msg_id"=>"007ba6a7-9664-49f9-b4a5-d8970e6a198a","msg_type"=>"status","username"=>"jlkernel","session"=>"????"],
  metadata = Dict{String,Any}(),
  content = ["execution_state"=>"starting"]
}

signal (11): Segmentation fault
unknown function (ip: -1084002142)
jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
setindex! at dict.jl:559
Message at /home/wallnuss/.julia/v0.3/ZMQ/src/ZMQ.jl:415
send_ipython at /home/wallnuss/.julia/v0.3/IJulia/src/msg.jl:50
jlcall_send_ipython_20637 at  (unknown line)
jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
send_status at /home/wallnuss/.julia/v0.3/IJulia/src/msg.jl:108
init at /home/wallnuss/.julia/v0.3/IJulia/src/IJulia.jl:107
jlcall_init_20549 at  (unknown line)
jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
unknown function (ip: -1083705528)
unknown function (ip: -1083709015)
unknown function (ip: -1083640291)
unknown function (ip: -1083637600)
jl_load at /usr/bin/../lib/julia/libjulia.so (unknown line)
include at /usr/bin/../lib/julia/sys.so (unknown line)
jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
include_from_node1 at loading.jl:128
jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
process_options at /usr/bin/../lib/julia/sys.so (unknown line)
_start at /usr/bin/../lib/julia/sys.so (unknown line)
jlcall__start_17455 at /usr/bin/../lib/julia/sys.so (unknown line)
jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
unknown function (ip: 4200709)
julia_trampoline at /usr/bin/../lib/julia/libjulia.so (unknown line)
unknown function (ip: 4199613)
__libc_start_main at /usr/bin/../lib/libc.so.6 (unknown line)
unknown function (ip: 4199673)
unknown function (ip: 0)
````

**Comment by vchuravy** [comment]
This might be related to ZMQ.jl/#83.

I downgraded from ZMQ 4.1 to 4.0 and also to from python=pyzmq-14.6 to python-pyzmq-14.5 and the problem goes away.

**Comment by mbaz** [comment]
@vchuravy Yes, downgrading those two packages fixes the problem for me too.

**Comment by jpopham91** [comment]
I'm having the same issue in arch.  I'll try downgrading zmq and see if that fixes it.
```
WARNING:root:kernel 55bde29d-91a8-4483-9191-6acebc1843de restarted
PROFILE = ["key"=>"cd19b9d7-be33-4ff3-9923-486490b389f8","transport"=>"tcp","signature_scheme"=>"hmac-sha256","shell_port"=>42338,"ip"=>"127.0.0.1","control_port"=>38831,"hb_port"=>46754,"stdin_port"=>36064,"iopub_port"=>43876]
SENDING IPython Msg [ idents status ] {
  header = ["msg_id"=>"1629f391-6f43-480a-9431-0ed4d1b00733","msg_type"=>"status","username"=>"jlkernel","session"=>"????"],
  metadata = Dict{String,Any}(),
  content = ["execution_state"=>"starting"]
}

signal (11): Segmentation fault
unknown function (ip: -985464590)
jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
setindex! at dict.jl:559
Message at /home/jake/.julia/v0.3/ZMQ/src/ZMQ.jl:415
send_ipython at /home/jake/.julia/v0.3/IJulia/src/msg.jl:50
jlcall_send_ipython_20556 at  (unknown line)
jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
send_status at /home/jake/.julia/v0.3/IJulia/src/msg.jl:108
init at /home/jake/.julia/v0.3/IJulia/src/IJulia.jl:107
jlcall_init_20471 at  (unknown line)
jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
unknown function (ip: -985167880)
unknown function (ip: -985171367)
unknown function (ip: -985102659)
unknown function (ip: -985099968)
jl_load at /usr/bin/../lib/julia/libjulia.so (unknown line)
include at /usr/bin/../lib/julia/sys.so (unknown line)
jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
include_from_node1 at loading.jl:128
jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
process_options at /usr/bin/../lib/julia/sys.so (unknown line)
_start at /usr/bin/../lib/julia/sys.so (unknown line)
jlcall__start_17462 at /usr/bin/../lib/julia/sys.so (unknown line)
jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
unknown function (ip: 4200709)
julia_trampoline at /usr/bin/../lib/julia/libjulia.so (unknown line)
unknown function (ip: 4199613)
__libc_start_main at /usr/bin/../lib/libc.so.6 (unknown line)
unknown function (ip: 4199673)
unknown function (ip: 0)
[I 20:39:48.508 NotebookApp] KernelRestarter: restarting kernel (1/5)
```

**Comment by ahwillia** [comment]
Sorry if this is a dumb question, but how did you downgrade these packages exactly? `Pkg.pin("ZMQ",v"4.0")` gives me an error (unregistered version).

**Comment by mbaz** [comment]
@ahwillia I didn't downgrade the julia packages, but the actual libraries. In arch:

    [/var/cache/pacman/pkg]$ sudo pacman -U python-pyzmq-14.5.0-2-x86_64.pkg.tar.xz zeromq-4.0.5-1-x86_64.pkg.tar.xz

**Comment by jpopham91** [comment]
Alternatively, if you installed pyzmq using pip:

```
sudo pip install pyzmq==14.5
```

**Comment by ahwillia** [comment]
Weird. So I'm still having these issues using:

```
pyzmq: 14.5.0-py27_0
zeromq: 4.0.4-0
```

Tried downgrading and reinstalling with conda, and also with pip (combining pip screwed everything up for a while, but I have IPython Notebooks running fine again). Is there a way for me to confirm the versions being used by the Julia kernel?

**Comment by stevengj** [comment]
@ahwillia, in Julia 0.4 you can do `Libdl.dllist()` to get a list of libraries that are loaded, while in Julia 0.3 the equivalent function is `Base.Sys.dllist()`.

**Comment by ahwillia** [comment]
Hmm, looks like it loads `/usr/local/Cellar/zeromq/4.1.2/lib/libzmq.5.dylib`. I'm guessing IJulia did this automatically through homebrew when I originally set things up?

I haven't had much luck downgrading zeromq... I tried following [this suggested workflow](http://stackoverflow.com/questions/3987683/homebrew-install-specific-version-of-formula), but I keep breaking IJulia when I do so.

**Comment by tkelman** [comment]
That is your system's global homebrew version of zmq, not the private one from Homebrew.jl. You might need to `brew unlink zeromq` then `Pkg.build("ZMQ")`

**Comment by ahwillia** [comment]
@tkelman -- Thanks! I think that did the trick for me.

**Comment by stevengj** [comment]
Great!

**Comment by tkelman** [comment]
Something appears quite broken with latest ZMQ, but it can probably continue being tracked at https://github.com/JuliaLang/ZMQ.jl/issues/83
