### ISSUE TITLE
add command to register kernel in jupyter?

### ISSUE THREAD

**Issue by minad** [JuliaLang/IJulia.jl#324]
Hi,

Iruby has a command `iruby register` which registers the kernel in jupyter by creating a kernel.json. Can we have the same for julia?

**Comment by Carreau** [comment]
It does it already when you `Pkg.Add("IJulia")` at least it should

**Comment by minad** [comment]
Ok thx. Didn't work for me. However there was also a problem that it couldn't start ipython at first, so I reinstalled IPython and then did again Pkg.Add("IJulia")

**Comment by minad** [comment]
maybe if you type "notebook()" in julia, it could check if the kernel.json is present?

**Comment by Carreau** [comment]
Maybe, I don't use `notebook()` as (IIRC) it uses `profiles` that tend to be kind-of deprecated now that jupyter-notebook with be a separate package than IPython. You shoudl be able to just also `Pkg.build(...)` to just do the build step.

**Comment by minad** [comment]
ok, Pkg.build does it!
