### ISSUE TITLE
Connecting to running computations does not work

### ISSUE THREAD

**Issue by axsk** [JuliaLang/IJulia.jl#326]
When running a time expensive computation via IJulia notebook I would like to be able to close my browser session and reopen it at another time, having the newest Output informations available.

Unfortunately when I close the page and reopen it again this does not work.
The page title says "(Starting) testnotebook" where testnotebook is my notebooks name.
The cell which is still computing (according to some printouts in the IJulia terminal) is just preceded by "In [ ]:", i.e. there is no information about the cell beeing in evaluation.

I don't even know whether this is supported by plain IPython, but if so it would be nice to have this feature also in IJulia.

**Comment by Carreau** [comment]
No it is not supportes in plain IPython, and we are working on that in github/Jupyter/notebook. It does require a significant refactor though.

**Comment by stevengj** [comment]
Closing this as a Jupyter issue.
