### ISSUE TITLE
Tab auto-completion failed in Jupyter sometimes

### ISSUE THREAD

**Issue by egoecho** [JuliaLang/IJulia.jl#332]
The IJulia works fine previously in ipython 2.x. Recently I updated ipython to 3.2.1 (Jupyter). In notebook mode, IJulia working page works fine at the time I create it. However, if I just close this page without choose "Close and Halt" and open this page next time, the tab-auto-completion doesn't work anymore in this page unless I restart Julia Kernel again. When I push tab-key, a below error information shows:

KERNEL EXCEPTION
key not found: "text"

 in getindex at dict.jl:617
 in complete_request at /home/jxiong/.julia/v0.3/IJulia/src/handlers.jl:7
 in eventloop at /home/jxiong/.julia/v0.3/IJulia/src/IJulia.jl:123
 in anonymous at task.jl:340

My Julia version is 0.3.9 and IJulia package version  is 0.2.5.

**Comment by stevengj** [comment]
Can you try updating to IJulia master?  `Pkg.checkout("IJulia"); Pkg.update()` and then `ipython notebook` (no more `--profile julia`).

**Comment by egoecho** [comment]
The problem has solved after I updated IJulia as you told. The tab-autocompletion works fine until so far. Thank you so much!

**Comment by stevengj** [comment]
Great!  Probably I will tag the new IJulia version (so that you don't need to do checkout) around the time Julia 0.4 comes out later this month.
