### ISSUE TITLE
"module JSON should explicitly import colon from base" and related weirdness

### ISSUE THREAD

**Issue by kersulis** [JuliaLang/IJulia.jl#333]
Today I reinstalled Julia 0.4 into `~/Documents/julia`. Now when I try to build IJulia, I get these messages:

```bash
INFO: Building ZMQ
INFO: Building IJulia
WARNING: module JSON should explicitly import colon from Base
WARNING: module JSON should explicitly import colon from Base
Found IPython version 4.0.0-b1 ... ok.
Writing IJulia kernelspec to /home/jkersulis/.ipython/kernels/julia-0.4/kernel.json ...
(Existing logo-32x32.png file untouched.)
(Existing logo-64x64.png file untouched.)
```
And now when I open a Jupyter notebook and switch to a julia-0.4 kernel, it perpetually shows "busy". Here are the messages that come from jupyter notebook (with the `debug` flag) when I attempt to switch kernels:

```bash
[W 17:05:35.928 NotebookApp] 404 GET /kernelspecs/julia-0.4/logo-64x64.png (127.0.0.1) 5.38ms referer=http://localhost:8888/notebooks/Untitled.ipynb
[D 17:05:35.929 NotebookApp] Found kernel julia-0.4 in /home/jkersulis/.ipython/kernels
[D 17:05:35.930 NotebookApp] Native kernel (python2) available from /home/jkersulis/.virtualenvs/notebook/local/lib/python2.7/site-packages/ipykernel/resources
[D 17:05:35.936 NotebookApp] Connecting to: tcp://127.0.0.1:36765
[I 17:05:35.937 NotebookApp] Kernel started: 40dc8995-723a-4ba1-b9c0-5e2959ea0aef
[D 17:05:35.937 NotebookApp] Kernel args: {'kernel_name': u'julia-0.4', 'cwd': u'/home/jkersulis'}
[D 17:05:35.939 NotebookApp] 201 POST /api/sessions (127.0.0.1) 10.29ms
[D 17:05:35.944 NotebookApp] Initializing websocket connection /api/kernels/40dc8995-723a-4ba1-b9c0-5e2959ea0aef/channels
[D 17:05:35.945 NotebookApp] Requesting kernel info from 40dc8995-723a-4ba1-b9c0-5e2959ea0aef
[D 17:05:35.946 NotebookApp] Connecting to: tcp://127.0.0.1:52756
Starting kernel event loops.
[D 17:05:41.484 NotebookApp] Received kernel info: {u'implementation': u'ijulia', u'banner': u'Julia: A fresh approach to technical computing.', u'language_info': {u'mimetype': u'application/julia', u'file_extension': u'.jl', u'version': u'0.4.0', u'name': u'julia'}, u'help_links': [{u'url': u'http://julialang.org/', u'text': u'Julia Home Page'}, {u'url': u'http://docs.julialang.org/', u'text': u'Julia Documentation'}, {u'url': u'http://pkg.julialang.org/', u'text': u'Julia Packages'}], u'protocol_version': u'5.0'}
[D 17:05:41.484 NotebookApp] Opening websocket /api/kernels/40dc8995-723a-4ba1-b9c0-5e2959ea0aef/channels
[D 17:05:41.485 NotebookApp] Connecting to: tcp://127.0.0.1:52756
[D 17:05:41.485 NotebookApp] Connecting to: tcp://127.0.0.1:49407
[D 17:05:41.485 NotebookApp] Connecting to: tcp://127.0.0.1:59454
```

It looks like only the logo is missing, but clearly it isn't connecting to a 0.4 kernel. I'm guessing there's something simple I have overlooked. Has anyone else seen this?

**Comment by swt30** [comment]
The JSON warnings are from a different package due to recent changes in Julia v0.4 master. You can ignore them for now until JSON.jl tags a new version, or do `Pkg.checkout("JSON")` to fix them straight away. The kernel thing might be fixed by https://github.com/JuliaLang/julia/commit/40c32db509dfce6dd4621ec07d9cb4af4cc884b0 - have you tried the latest Julia master?

**Comment by kersulis** [comment]
Thank you for the info. I checkout out JSON, ran `git pull && make` for Julia, and did `Pkg.build("IJulia")`. The JSON warnings are gone, but the kernel issue remains.

I tried pressing Ctrl-c while the kernel was showing busy, and it did return the cell's output as described in [issue 331](https://github.com/JuliaLang/IJulia.jl/issues/331). The behavior is unchanged after JuliaLang/julia@40c32db509dfce6dd4621ec07d9cb4af4cc884b0.

**Comment by kersulis** [comment]
Closing in favor of #331. JSON warnings were a separate issue.
