### ISSUE TITLE
installation proceeduce on ubuntu?

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/IJulia.jl#335]
i'm not sure of any specifics on why this was fighting me so much on Ubuntu 15.04, but wanted to document my steps as i went:
```
julia> Pkg.build("IJulia")
$ virtualenv create julia-env
$ . julia-env/bin/activate
$ sudo apt-get install libzmq-dev # needed otherwise pyzmq builds wrong
$ pip install --upgrade --force-reinstall pyzmq # to rebuild pyzmq right
$ pip install jsonschema
$ pip install jinja2 tornado pyzmq ipython
```

**Comment by stevengj** [comment]
This is because the IPython on Ubuntu is ancient?

**Comment by vtjnash** [comment]
ah, that might make sense, although on this particular machine, someone has also placed a binary in /usr/local that's somewhere in between and was the one getting used:
```
$ /usr/local/bin/ipython --version
3.1.0
$ /usr/bin/ipython --version
2.3.0
$ ipython --version
3.2.1
```
the main issues seemed to be that pyzmq needed libzmq-dev installed and that it needed jsonscheme (which wasn't in README list).

**Comment by stevengj** [comment]
So is it just that they installed a broken binary in `/usr/local/bin`?

**Comment by stevengj** [comment]
Why doesn't the Ubuntu `pyzmq` package work?

**Comment by stevengj** [comment]
Added notes to the `README`

**Comment by vtjnash** [comment]
> Why doesn't the Ubuntu pyzmq package work?

not sure. the virtualenv one didn't work either. the only error ipython gave was that the version of pyzmq was wrong (even though it wasn't).
