### ISSUE TITLE
strange phenomenon with randn

### ISSUE THREAD

**Issue by xiongyl** [JuliaLang/IJulia.jl#336]
See the following picture. 

![ijulia](https://cloud.githubusercontent.com/assets/4945392/9133535/0cef2694-3d2f-11e5-9948-b1fb695a2b9b.png)

The only difference between block [2] and block [3] is the first printing sentence of block[2]. The two scripts are supposed to get same results. However we get different results as the picture shows.

**Comment by lindahua** [comment]
@xiongyl is working with me on some research projects.

We found such inconsistent results only on IJulia. The codes work as expected when using REPL.

**Comment by stevengj** [comment]
Interesting... it works for me in Julia 0.4-dev.

**Comment by stevengj** [comment]
IJulia and ZMQ don't call `rand*`, so that is not it.

**Comment by stevengj** [comment]
It works for me on Julia 0.3.8 (I haven't tried 0.3.11).  What is the output of `versioninfo()`?

**Comment by yuyichao** [comment]
This can be reproduced on juliabox (0.3.9)

**Comment by yuyichao** [comment]
And `0.4.0-dev+5491` with a different number in the second case.

**Comment by xiongyl** [comment]
I tried `Pkg.checkout("IJulia")` but the result didn't change. 
The output of `versioninfo()` is as following. 
```
Julia Version 0.3.11
Commit 483dbf5 (2015-07-27 06:18 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by stevengj** [comment]
@yuyichao, I can't reproduce with Julia 0.3.9 on JuliaBox:
![image](https://cloud.githubusercontent.com/assets/2913679/9141050/a6dd177e-3d03-11e5-9e4e-82a609d15fb2.png)

**Comment by yuyichao** [comment]
You need the print in the front

**Comment by yuyichao** [comment]
Which doesn't make too much sense I know. Some async stuff?

**Comment by stevengj** [comment]
As I understand it, it is certainly possible that the `println` yields to another async task, and if another async task is using the random-number generator then it will alter the state.

However, I don't know what other background task could be running that would be using `rand`.   IJulia has other tasks running that are processing ZMQ and JSON communications with Jupyter, but I don't see any random numbers in there.

**Comment by yuyichao** [comment]
I can reproduce it with IJulia locally as well. Will see if I can get a backtrace.

**Comment by stevengj** [comment]
Oh, I think I know where it comes from: see the `uuid4()` function in IJulia, which calls `Base.Random.uuid4()`.

**Comment by yuyichao** [comment]
.... so should the solution be supplying the uuid function with a independent random number generator?

The base function doesn't really have a API for it at this point so maybe it's necessary to duplicate some logic for compatibility with 0.3?

**Comment by stevengj** [comment]
Yes.

I just double-checked the IPython source, and it looks like a [new UUID4](https://github.com/jupyter/jupyter_client/blob/1c77df8fe707171504c4a761093041c7ff130c86/jupyter_client/session.py#L453-L455) is generated for [every message](https://github.com/jupyter/jupyter_client/blob/1c77df8fe707171504c4a761093041c7ff130c86/jupyter_client/session.py#L504-L505), and the docs also imply that the msg_id is unique to the message, so we should do that too.

**Comment by stevengj** [comment]
I'll submit a PR to Julia shortly with
```
function uuid4(rng::AbstractRNG=GLOBAL_RNG)
    u = rand(rng, UInt128)
    u &= 0xffffffffffff0fff3fffffffffffffff
    u |= 0x00000000000040008000000000000000
    UUID(u)
end
```

**Comment by yuyichao** [comment]
Actually copying that to `Compat.jl` is probably a better idea than duplicating the logic in `IJulia`.

**Comment by stevengj** [comment]
Probably.  I also notice that the UUID stuff is currently undocumented.

There is also https://github.com/forio/UUID.jl

**Comment by stevengj** [comment]
The problem with putting it in `Compat.jl` is that it is currently unexported... we could define `Compat.uuid4()`, but not `Base.Random.uuid4()`...
