### ISSUE TITLE
Installation error: `could not spawn setenv(...)` on Mac Yosemite

### ISSUE THREAD

**Issue by DSLituiev** [JuliaLang/IJulia.jl#338]
I am trying to instal IJulia on a Mac Yosemite with Anaconda3-2.3.0.

After a long log (no errors within visible log part) I am getting:

    Copying logo-32x32.png to Julia IPython profile.
    Copying logo-64x64.png to Julia IPython profile.
    
    ==================================================================================[ BUILD ERRORS ]==================================================================================
    
    WARNING: Homebrew had build errors.
    
     - packages with build errors remain installed in /Users/dlituiev/.julia/v0.3
     - build the package(s) and all dependencies with `Pkg.build("Homebrew")`
     - build a single package by running its `deps/build.jl` script
    
    ====================================================================================================================================================================================
    INFO: Package database updated
    
    julia> Pkg.build("Homebrew")
    INFO: Building Homebrew
    ================================================================================[ ERROR: Homebrew ]=================================================================================
    
    could not spawn setenv(`git rev-parse --git-dir`; dir="/Users/dlituiev/.julia/v0.3/Homebrew/deps/usr"): no such file or directory (ENOENT)
    while loading /Users/dlituiev/.julia/v0.3/Homebrew/deps/build.jl, in expression starting on line 2
    
    ====================================================================================================================================================================================
    
    ==================================================================================[ BUILD ERRORS ]==================================================================================
    
    WARNING: Homebrew had build errors.
    
     - packages with build errors remain installed in /Users/dlituiev/.julia/v0.3
     - build the package(s) and all dependencies with `Pkg.build("Homebrew")`
     - build a single package by running its `deps/build.jl` script
    
    ====================================================================================================================================================================================

**Comment by stevengj** [comment]
Please report the error at https://github.com/JuliaLang/Homebrew.jl
