### ISSUE TITLE
Support for IPython 4.0

### ISSUE THREAD

**Issue by pazzo83** [JuliaLang/IJulia.jl#340]
I recently installed version 4.0 of IPython, where a full switch to Jupyter for the notebook app was made.  Consequently, any of the notebook profiles (like julia) that were installed are not recognized now.  Do you have any suggestions as to how I can get IJulia to work with IPython 4.0/Jupyter?

Thanks!

**Comment by yuyichao** [comment]
Have you tried to reinstall IJulia? I'm under the impression that we've already dropped the support for ipython profile and switched fully to use the kernel spec on the master.

**Comment by pazzo83** [comment]
Hmm, I just installed it earlier, I can try to remove and install again.  I noticed I got it to work when I change the command being run in the notebook function in IJulia.jl to: run(`jupyter notebook`)

Of course, I first had to move over the config settings from the profile_julia folder in .ipython to jupyter_notebook_config.py in .jupyter.

**Comment by stevengj** [comment]
Just do `Pkg.checkout("IJulia")` to get the version that uses the Jupyter protocol exclusively.

I should probably go ahead an pull the trigger on tagging this, so that you don't need `master`.  I've been using it for a while and it seems quite stable, and I think most people have IPython 3 these days.

(I'm mainly worried about Ubuntu users, since the latest Ubuntu is still on IPython 2.x.)

**Comment by stevengj** [comment]
See #325

**Comment by pazzo83** [comment]
Using the master branch (via Pkg.checkout) didn't seem to work.  When I initialize IJulia (running "using IJulia"), it outputs a warning saying:
Warning: error initializing module IJulia:
Base.MethodError(f=srand, args=(Base.Random.MersenneTwister(state=Base.dSFMT.DSFMT_state(val=Array{Int32, 1} [lots of random numbers]))))

That said, I am able to call "notebook()", and this starts IPython notebook.  However, using version 4.0, it does not seem to read any of the kernels (including the Julia one) from .ipython/kernels.  The only one that appears is for my version of Python.

Any ideas?

Thanks!

**Comment by stevengj** [comment]
What is the output of `Pkg.build("IJulia")`?

**Comment by pazzo83** [comment]
Here is the output:

julia> Pkg.build("IJulia")
INFO: Building WinRPM
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win3
2/openSUSE_13.1/repodata/repomd.xml
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win6
4/openSUSE_13.1/repodata/repomd.xml
INFO: Building Nettle
INFO: Updating WinRPM package list
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win3
2/openSUSE_13.1/repodata/repomd.xml
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win6
4/openSUSE_13.1/repodata/repomd.xml
INFO: Building ZMQ
INFO: Building IJulia
Found IPython version 4.0.0 ... ok.
Writing IJulia kernelspec to C:\Users\F585581\.ipython\kernels\julia-0.3\kernel.
json ...
(Existing logo-32x32.png file untouched.)
(Existing logo-64x64.png file untouched.)

Note, this is a Win 7 machine.

Thanks!

**Comment by stevengj** [comment]
And after running that, the Julia kernel still does not show up in `ipython notebook`?

**Comment by pazzo83** [comment]
Only if I add this line to the jupyter_notebook_config.py:
c.NotebookApp.port = 8998

However, I still get the Method errors from Julia, as it is complaining about the srand method in __init__ in IJulia.jl.  So when I call notebook, and then attempt to open a notebook using Julia, attempts to reach the kernel time out and I see additional Method errors like I see when I initialize IJulia (calling "using IJulia").

**Comment by stevengj** [comment]
@pazzo83, the old port for IJulia was 8998, so you're probably just going to the wrong URL out of habit in your browser.   The default port is 8888, so you should be going to `localhost:8888`.  (Running `ipython notebook` should automatically open this URL in your browser.)

Regarding the method errors, it could be that the latest IJulia `master` inadvertently depends on Julia 0.4; I'll check it out right now and fix it soon if so.

**Comment by pazzo83** [comment]
Understood, if I remove that override (for the port) and have it default to 8888, then only "Python" shows up as an available notebook, and not "Julia".  Quite strange, could be an issue on my end.

**Comment by stevengj** [comment]
@pazzo83, maybe you are running another IPython/Jupyter process already.

**Comment by pazzo83** [comment]
Thanks for all your help!  Got it working running 0.4-dev (a version from July 28th).  Probably an IPython thing, but the 0.3.11 Julia version was still showing up in the drop down from the main page, even though I've long since deleted that kernel (I basically removed the .ipython folder entirely before I checked out the IJulia master branch, then let it rebuild it running Pkg.build("IJulia")).  Anyways, that strange srand error is now gone as well.

Thanks!!

**Comment by stevengj** [comment]
I will be pushing an update to Compat soon that will fix the `srand` issue on 0.3.  (It turned out to be fairly involved; there was quite a lot of code that was added to 0.4 in order to expand random-number support for non-global state.)

**Comment by stevengj** [comment]
Okay, with Compat 0.6 it should work again with Julia 0.3.
