### ISSUE TITLE
Kernel keeps dying with Jupyterhub

### ISSUE THREAD

**Issue by Yurlungur** [JuliaLang/IJulia.jl#341]
Hi, I'm trying to get IJulia working with Jupyterhub for all users and I'm running into quite a lot of trouble. When I start the Julia kernel, my kernel keeps dying and I get a debug error of the form:
```
/usr/local/julia/usr/bin/julia: error while loading shared libraries: libimf.so: cannot open shared object file: No such file or directory
```

I really appreciate any help you can offer me. Thanks!

### Here are the details of my configuration

* I am using Ubuntu 14.04.
* I installed Julia in /usr/local/julia using the 0.3 release, compiled against intel mkl. It runs via CLI just fine and it passes all tests when I call "make testall"
* I changed the default Julia package directory to a global location, /usr/local/julia-packages, so that the IJulia package would be global.
* To install IJulia globally, I loaded julia as root, called Pkg.add("IJulia"), and finally, called
```
cp -r .local/share/jupyter/kernels/julia/ /usr/local/share/jupyter/kernels/
```
* I manage most python packages through the Ubuntu package manager. But to keep the important ones up to date, I use pip to install them into a directory in /usr/local. e.g., as root I call
```
PYTHONUSERBASE=/usr/local/python-pip pip3 install jupyterhub --user
```
and I have the following lines in my global profile
```
# here we add the /usr/local directory for pip
export PYTHONPATH="/usr/local/python-pip/lib/python2.7/site-packages":"${PYTHONPATH}"
export PYTHONPATH="/usr/local/python-pip/lib/python3.4/site-packages":"${PYTHONPATH}"
export PATH=/usr/local/python-pip/bin:$PATH
```

**Comment by stevengj** [comment]
Did you do "sudo make install prefix=/usr/local"?  Your install path looks funky, which makes me think you copied files manually.

**Comment by Yurlungur** [comment]
You mean for Julia? Or for Jupyterhub? 

In the case of python, I created the folder /usr/local/python-pip and then set the PYTHONUSERBASE variable so that it would install into that folder instead of other folders. I do have Jupyterhub working for python3 and bash, so I would be surprised if that were the problem... but I could be wrong. It is a very funky way of setting things up, I admit.

**Comment by Yurlungur** [comment]
Ah, one more thing, if that's relevant: I compiled Julia against intel MKL.

**Comment by Yurlungur** [comment]
I found the problem and a solution. However, if anyone can advise me on the best solution, I would appreciate it.

Since I compiled Julia against intel MKL, it's linked to several intel dynamic libraries. Normally, I use a custom LD_LIBRARY_PATH (defined in a file in /etc/profile.d) to tell programs where to look. However, Jupyterhub sanitizes the environment, so this variable is lost. For now, I've fixed this by modifying spawner.py and whitelisting the variable in jupyterhub.

Similarly, the JULIA_PKGDIR shell variable is lost, meaning that Julia no longer knows where to look for packages.

I will also query the Jupyterhub developers about the best way to handle this. But I suppose if anyone else has this problem, here's a quick hack.

**Comment by stevengj** [comment]
I mean that `/usr/local/julia/usr/bin/julia` looks wrong.  It should be in /usr/local/bin/julia, or /usr/local/julia/bin/julia if you want to keep the Julia stuff in its own prefix /usr/local/julia.

**Comment by minrk** [comment]
JupyterHub only passes a whitelist of environment variables to notebook-server subprocesses (to avoid passing things like authentication environment keys to users). By default, this list is just the bare minimum. You can specify these env variables for your kernel in two ways:

1. add environment variables to the kernelspec itself. Kernelspecs have a top-level `env` dict, which is environment variables to set for the kernel (not the notebook server), e.g.

  ```json
  {
    "display_name": "Julia 0.4.0-dev",
    "argv": [
      "/usr/local/bin/julia",
      "-i",
      "-F",
      "/usr/local/share/julia/v0.4/IJulia/src/kernel.jl",
      "{connection_file}"
    ],
    "language": "julia",
    "env": {
      "LD_LIBRARY_PATH": "/opt/local/lib"
    }
  }
  ```
2. add the keys to the Spawner's env_keep (in jupyterhub_config.py), so that notebooks inherit this env from the Hub process:

   ```python
   c.Spawner.env_keep.extend(['LD_LIBRARY_PATH', 'JULIA_PKGDIR'])
   ```

**Comment by Yurlungur** [comment]
@stevengj Oh I see. No, I didn't call 'make install' at all. I did a git clone directly into /usr/local and then just added that directory to my path. Should that matter? That was one of the options listed in the Julia documentation.

@minrk Perfect. Thank you very much! I wonder if LD_LIBRARY_PATH should be passed by the default Julia kernelspec? I suspect it only matters if I compile Julia against Intel MKL.

**Comment by stevengj** [comment]
@Yurlungur, in general, you should compile things in your own directory, not in /usr/anything, and install afterwards.    The `julia` readme does not recommend cloning directly into `/usr/local`.

Probably you should use `-rpath` when linking to build the path into to the `julia` executable, so that `LD_LIBRARY_PATH` is not required.

You could set the `JULIA_PKGDIR` in your `.juliarc` file so that it doesn't require a global environment variable; this won't be affected by the Jupyter settings.

**Comment by Yurlungur** [comment]
@stevengj I see. Okay. Thanks for your help!
