### ISSUE TITLE
 [C 05:11:05.325 NotebookApp] Bad config encountered during initialization: #12751 

### ISSUE THREAD

**Issue by vikohtb** [JuliaLang/IJulia.jl#343]
When I try to run IJulia since julia 
>using IJulia 
>notebook()

[C 05:11:05.325 NotebookApp] Bad config encountered during initialization:
[C 05:11:05.325 NotebookApp] Unrecognized flag: '--profile'
ERROR: failed process: Process(ipython notebook --profile julia, ProcessExited(1)) [1]
in pipeline_error at process.jl:502
in notebook at /home/vikohtb/.julia/v0.3/IJulia/src/IJulia.jl:177
in notebook at /home/vikohtb/.julia/v0.3/IJulia/src/IJulia.jl:176
And the directory src does not exist.

**Comment by stevengj** [comment]
I'm guessing you have a recent version of IPython?  Try `Pkg.update(); Pkg.checkout("IJulia"); Pkg.build("IJulia")` to get the latest git `master` of IJulia, which no longer uses `--profile` (and consequently requires IPython 3 or later).

**Comment by vikohtb** [comment]
Thanks! that works, the error is done. But in the page open says Jupyter no IJulia, that means something?

**Comment by pao** [comment]
The Jupyter project is the new name for IPython, to highlight its support for multiple programming languages.

**Comment by stevengj** [comment]
Technically, IPython still exists: it is the Python kernel (back-end) for the Jupyter front-end.  IJulia is the Julia back-end for the Jupyter front-end.
