### ISSUE TITLE
Macro output appears to late

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/IJulia.jl#344]
I am using Jupyterhub with IJulia. Within such a notebook, e.g. the output of macro `@timev` does not always appear before the value of the cell.

For example:

Input:
```
@timev 2+3
```

Output:
```
  0.000002 seconds (4 allocations: 160 bytes)
Out[38]:
5
elapsed time (ns): 1873
bytes allocated:   160
pool allocs:       4
```

All four lines produced by `@timev` should appear before the actual output `5`.

Within the code generated by the macro `timev`, `println` is indeed called before returning the value to the caller. However, Julia's I/O is often a bit delayed (it seems to be handled by a separate task), and so it seems to appear on stdout too late.

This could e.g. be fixed within `timev` by first outputting into a buffer, converting this to a string, and then outputting the string -- string output seems to have less delay than other output. However, I think this should be fixed somewhere else instead, probably here in IJulia. (The error does not happen in the REPL.) Maybe a `flush` or a `taskwait` are missing somewhere, but this is just a wild guess.

**Comment by stevengj** [comment]
Dup of #342
