### ISSUE TITLE
Slow startup time

### ISSUE THREAD

**Issue by rsmith31415** [JuliaLang/IJulia.jl#346]
I noticed the creation of a new IJulia kernel is very slow (15+ seconds) compared to other kernels. Is this a known issue? This occurs in the Jupyter notebook but also starting a new kernel in the terminal.

Hopefully, there is some way to alleviate this a little bit. I'm testing several kernels with nose and the tests in which IJulia kernels are involved usually fail due to the amount of time they require.

I'm using Ubuntu 15.4 and IPython 4.0.0.

**Comment by stevengj** [comment]
15+ seconds sounds unusually slow.  What version of Julia do you have?

(Launch times will improve in Julia 0.4, which is coming out soon, due to the addition of precompiled modules.)

**Comment by rsmith31415** [comment]
Julia 0.3. Yes, I expect to install 0.4 as soon as I can. If that's the problem, feel free to close this issue. Thanks.

**Comment by rsmith31415** [comment]
On the other hand, the Julia REPL launches instantaneously. Does that make sense?

**Comment by stevengj** [comment]
What is the time required for `using IJulia` in the REPL?

**Comment by rsmith31415** [comment]
About 11 seconds. It looks like this will get a nice improvement after 0.4, right?

**Comment by stevengj** [comment]
Yes this should be sped up enormously in 0.4, but JuliaLang/ZMQ.jl#85 needs to be fixed first.

(On my machine, `using IJulia` takes about 6 seconds, but maybe my computer is a bit newer.)

**Comment by rsmith31415** [comment]
I tested in 0.4-rc4 and now the start up time is ~7 seconds.  `using IJulia` takes ~2 seconds, which I think, is very good. Do you think that can be improved? Other dependencies such as Nettle, JSON, Compat load quickly and ZMQ, Conda are a bit slower but not excessively slow.

**Comment by stevengj** [comment]
Yes, I think it can still be improved; I'm still not precompiling Julia—I'm working on fixing a precompilation in JSON first (JuliaLang/JSON.jl#129).

Also, precompilation in Julia in general is a very new feature and has not really been optimized yet.  I'm expecting that loading of precompiled packages will continue to get faster in future Julia versions once people get sufficiently spoiled by the new load times.

(Conda isn't actually a runtime dependency, only a build-time dependency, so its load time is not relevant here.)

**Comment by rsmith31415** [comment]
Wow. I'm glad to hear that. I thought all the dependencies were taking advantage of precompilation. I will follow JuliaLang/JSON.jl#129 then. Thanks.

**Comment by stevengj** [comment]
I just enabled precompilation for IJulia, and `using IJulia` is down to 0.3sec on my machine.

**Comment by stevengj** [comment]
Starting the kernel now seems to be down to about 2.7sec on my machine.

I'm closing this as I think the low-hanging fruit have been picked.  Profiling and further improvements are welcome, of course, but I suspect it may be mainly a matter of optimizing precompilation of Julia in general.

**Comment by rsmith31415** [comment]
Thank you. Interestingly, I didn't see another improvement after updating to IJulia 1.1.5 (still ~7 seconds). I guess that is due to my somewhat old computer. IJulia is indeed fast (1.18s). 

I'm not sure how much optimizing precompilation will help now that loading times are very reasonable. On the bright side, my tests are not timing out anymore.

**Comment by stevengj** [comment]
I think there is a lot of room for improving precompilation in Julia itself; load times are still way larger than starting a C program of comparable complexity.
