### ISSUE TITLE
Delayed output

### ISSUE THREAD

**Issue by rened** [JuliaLang/IJulia.jl#347]
Following up from https://groups.google.com/forum/#!topic/julia-users/nyb9qRJgzpo.

The issue is that the display of output to STDOUT is interrupted / delayed by computations. This test code

```jl
print(1:4); flush(STDOUT); svd(rand(1000,1000)); println("done"); 
```

prints "1:" and after the svd is done "4done", so flushing does not seem to help here.

This started to occur some time in the last weeks on Julia master, in 0.3.11 it works.

**Comment by stevengj** [comment]
The issue is that the sending of `stdout` messages to Jupyter is handled by a separate green thread (it doesn't pre-empt `svd`), and exactly when that gets woken up is somewhat random.

Maybe IJulia could hook into `flush` to force it to wake up the stdout thread.

**Comment by amellnik** [comment]
This may be an unrelated issue, but in 0.4 if you "run all cells" or similar you can end up with the output of anything that prints in the wrong cell:

![image](https://cloud.githubusercontent.com/assets/7132414/10113010/1d45bc56-6395-11e5-97e1-92ca7f2d1417.png)

**Comment by stevengj** [comment]
@amellnik, that is #342.

**Comment by amellnik** [comment]
Ah, apologies, I didn't look far enough back.

**Comment by stevengj** [comment]
Actually, IJulia already hooks into `flush`.  It is just that it looks like the hooks broke in Julia 0.4.  Let me look into it further.

**Comment by stevengj** [comment]
Okay, I fixed it so that the IJulia `flush` is actually being called.   However, at the time `flush` is called, after `1:` has printed but before the `4` has printed, `nb_available(STDOUT)` is returning `0`, so it thinks there is nothing to send.

@vtjnash, is this some kind of buffering?  How can the `flush` command get everything that has been written to the pipe at this point?

**Comment by vtjnash** [comment]
The only way to get the kernel to give you everything on the pipe (with certainty), is to close the write end of the pipe and redirect_stdout to a new pipe for each new cell.

**Comment by stevengj** [comment]
@vtjnash, that's not really acceptable for us, because there might be an `@async` task from a previous input cell still running and printing I/O to `STDOUT`.

So, this is really a kernel thing and there's nothing we can do about it?

**Comment by stevengj** [comment]
Can we get the kernel to treat the `STDOUT` pipe as a pseudoterminal, so that it won't buffer I/O?

**Comment by vtjnash** [comment]
I don't see how to have printing from `@async` to work at an arbitrary time later, but also expect to know when all output has been received.

**Comment by stevengj** [comment]
@vtjnash, I just want to stop the kernel from buffering STDOUT.

**Comment by vtjnash** [comment]
The problem is that it's really expensive to ask the kernel for that data (and the kernel really dislikes actually buffering any data), so it is a slightly difficult problem to coordinate flushing everyone's buffers. On linux, we know that the libuv read size > default kernel buffer size, so calling `yield()` once after `flush()` has returned should suffice to return all of the buffered data. (make sure you have an `@async` task reading the data or `flush()` will deadlock however).

On windows, ReadFile doesn't have a non-blocking version (the non-blocking version, PeakNamedPipe, is documented to never block, except for when it does), so I think you would need to call `ccall(:SwitchToThread, Void, stdcall, ()); yield()` to have a pretty good chance to read all of the buffered data from the kernel (assuming you had a separate `@async` task that is doing the read created first)

**Comment by StefanKarpinski** [comment]
"Pretty good chance" seems like an improvement.

**Comment by stevengj** [comment]
In our case, there are multiple `@async` tasks going on, so just `yield` seems insufficient — couldn't it wake up one of the other tasks?  And there are separate tasks for `STDOUT` and `STDERR`.

**Comment by vtjnash** [comment]
it's a fair scheduler, so you can safely assume it will wake up all of them. come to think of it though, you may need to call `yield()` twice (in case the reader task was already queued with some of the data, because you would need `yield` to call `process_events()` with the reader task is actually waiting for the data)

**Comment by rsmith31415** [comment]
Does anyone know what is the status of this issue? Based on recent closed issues, I assumed this was mostly fixed. However, after updating Julia (0.4.1) and IJulia, I found that I get a similar issue:

After executing `@time sum(linspace(0,1,1e6))`, there is a stream message after the `execution_state: idle` message is received:
```
In [25]: kc.execute('@time sum(linspace(0,1,1e6))')
Out[25]: 'da1ad3fc-1937-4b91-a719-cd9de44adeee'

In [26]: kc.get_shell_msg(timeout=1)
Out[26]:
{'buffers': [],
 'content': {u'execution_count': 3,
  u'payload': u'',
  u'status': u'ok',
  u'user_expressions': {}},
 'header': {'date': '2015-12-03T17:10:58.550513',
  u'msg_id': u'1aa0aa87-0cf7-4b1e-a114-aeafb5b3b823',
  u'msg_type': u'execute_reply',
  u'session': u'4f3df0fa-34a0-480b-96fc-ffb4a3c7cc7e',
  u'username': u'user',
  u'version': u'5.0'},
 'metadata': {},
 'msg_id': u'1aa0aa87-0cf7-4b1e-a114-aeafb5b3b823',
 'msg_type': u'execute_reply',
 'parent_header': {u'date': datetime.datetime(2015, 12, 3, 17, 10, 56, 260207),
  u'msg_id': u'da1ad3fc-1937-4b91-a719-cd9de44adeee',
  u'msg_type': u'execute_request',
  u'session': u'4f3df0fa-34a0-480b-96fc-ffb4a3c7cc7e',
  u'username': u'user',
  u'version': u'5.0'}}

In [27]: kc.get_iopub_msg(timeout=1)
Out[27]:
{'buffers': [],
 'content': {u'execution_state': u'busy'},
 'header': {'date': '2015-12-03T17:11:03.161155',
  u'msg_id': u'a0d3a2c7-2c76-4a9c-88ed-b3c8786b80b6',
  u'msg_type': u'status',
  u'session': u'4f3df0fa-34a0-480b-96fc-ffb4a3c7cc7e',
  u'username': u'jlkernel',
  u'version': u'5.0'},
 'metadata': {},
 'msg_id': u'a0d3a2c7-2c76-4a9c-88ed-b3c8786b80b6',
 'msg_type': u'status',
 'parent_header': {u'date': datetime.datetime(2015, 12, 3, 17, 10, 56, 260207),
  u'msg_id': u'da1ad3fc-1937-4b91-a719-cd9de44adeee',
  u'msg_type': u'execute_request',
  u'session': u'4f3df0fa-34a0-480b-96fc-ffb4a3c7cc7e',
  u'username': u'user',
  u'version': u'5.0'}}

In [28]: kc.get_iopub_msg(timeout=1)
Out[28]:
{'buffers': [],
 'content': {u'code': u'@time sum(linspace(0,1,1e6))', u'execution_count': 3},
 'header': {'date': '2015-12-03T17:11:04.063564',
  u'msg_id': u'2cf0d337-edc9-465a-9547-c551ec7f72ca',
  u'msg_type': u'execute_input',
  u'session': u'4f3df0fa-34a0-480b-96fc-ffb4a3c7cc7e',
  u'username': u'user',
  u'version': u'5.0'},
 'metadata': {},
 'msg_id': u'2cf0d337-edc9-465a-9547-c551ec7f72ca',
 'msg_type': u'execute_input',
 'parent_header': {u'date': datetime.datetime(2015, 12, 3, 17, 10, 56, 260207),
  u'msg_id': u'da1ad3fc-1937-4b91-a719-cd9de44adeee',
  u'msg_type': u'execute_request',
  u'session': u'4f3df0fa-34a0-480b-96fc-ffb4a3c7cc7e',
  u'username': u'user',
  u'version': u'5.0'}}

In [29]: kc.get_iopub_msg(timeout=1)
Out[29]:
{'buffers': [],
 'content': {u'name': u'stdout', u'text': u'  '},
 'header': {'date': '2015-12-03T17:11:05.140277',
  u'msg_id': u'931bf8b7-6d7e-4aff-bf76-d814adb73fd8',
  u'msg_type': u'stream',
  u'session': u'4f3df0fa-34a0-480b-96fc-ffb4a3c7cc7e',
  u'username': u'user',
  u'version': u'5.0'},
 'metadata': {},
 'msg_id': u'931bf8b7-6d7e-4aff-bf76-d814adb73fd8',
 'msg_type': u'stream',
 'parent_header': {u'date': datetime.datetime(2015, 12, 3, 17, 10, 56, 260207),
  u'msg_id': u'da1ad3fc-1937-4b91-a719-cd9de44adeee',
  u'msg_type': u'execute_request',
  u'session': u'4f3df0fa-34a0-480b-96fc-ffb4a3c7cc7e',
  u'username': u'user',
  u'version': u'5.0'}}

In [30]: kc.get_iopub_msg(timeout=1)
Out[30]:
{'buffers': [],
 'content': {u'data': {u'text/plain': u'499999.99999999994'},
  u'execution_count': 3,
  u'metadata': {}},
 'header': {'date': '2015-12-03T17:11:06.130795',
  u'msg_id': u'cce658a5-fa95-452a-adde-943f9d1bed95',
  u'msg_type': u'execute_result',
  u'session': u'4f3df0fa-34a0-480b-96fc-ffb4a3c7cc7e',
  u'username': u'user',
  u'version': u'5.0'},
 'metadata': {},
 'msg_id': u'cce658a5-fa95-452a-adde-943f9d1bed95',
 'msg_type': u'execute_result',
 'parent_header': {u'date': datetime.datetime(2015, 12, 3, 17, 10, 56, 260207),
  u'msg_id': u'da1ad3fc-1937-4b91-a719-cd9de44adeee',
  u'msg_type': u'execute_request',
  u'session': u'4f3df0fa-34a0-480b-96fc-ffb4a3c7cc7e',
  u'username': u'user',
  u'version': u'5.0'}}

In [31]: kc.get_iopub_msg(timeout=1)
Out[31]:
{'buffers': [],
 'content': {u'execution_state': u'idle'},
 'header': {'date': '2015-12-03T17:11:08.095832',
  u'msg_id': u'f172ff7c-d87e-45a6-8752-5ca2ee4527f8',
  u'msg_type': u'status',
  u'session': u'4f3df0fa-34a0-480b-96fc-ffb4a3c7cc7e',
  u'username': u'jlkernel',
  u'version': u'5.0'},
 'metadata': {},
 'msg_id': u'f172ff7c-d87e-45a6-8752-5ca2ee4527f8',
 'msg_type': u'status',
 'parent_header': {u'date': datetime.datetime(2015, 12, 3, 17, 10, 56, 260207),
  u'msg_id': u'da1ad3fc-1937-4b91-a719-cd9de44adeee',
  u'msg_type': u'execute_request',
  u'session': u'4f3df0fa-34a0-480b-96fc-ffb4a3c7cc7e',
  u'username': u'user',
  u'version': u'5.0'}}

In [32]: kc.get_iopub_msg(timeout=1)
Out[32]:
{'buffers': [],
 'content': {u'name': u'stdout',
  u'text': u'0.023915 seconds (6.76 k allocations: 280.694 KB)\n'},
 'header': {'date': '2015-12-03T17:11:09.247268',
  u'msg_id': u'34eda40c-821b-4686-a51d-0add17dbb970',
  u'msg_type': u'stream',
  u'session': u'4f3df0fa-34a0-480b-96fc-ffb4a3c7cc7e',
  u'username': u'user',
  u'version': u'5.0'},
 'metadata': {},
 'msg_id': u'34eda40c-821b-4686-a51d-0add17dbb970',
 'msg_type': u'stream',
 'parent_header': {u'date': datetime.datetime(2015, 12, 3, 17, 10, 56, 260207),
  u'msg_id': u'da1ad3fc-1937-4b91-a719-cd9de44adeee',
  u'msg_type': u'execute_request',
  u'session': u'4f3df0fa-34a0-480b-96fc-ffb4a3c7cc7e',
  u'username': u'user',
  u'version': u'5.0'}}
```

So basically, the pattern is the following:

```
'content': {u'execution_state': u'busy'},
'content': {u'code': u'@time sum(linspace(0,1,1e6))', u'execution_count': 3},
'content': {u'name': u'stdout', u'text': u'  '},
'content': {u'data': {u'text/plain': u'499999.99999999994'},
'content': {u'execution_state': u'idle'},
'content': {u'name': u'stdout', u'text': u'0.023915 seconds (6.76 k allocations: 280.694 KB)\n'},
```

**Comment by stevengj** [comment]
cc @JobJob

**Comment by JobJob** [comment]
@rsmith31415 are you on master?

    Pkg.checkout("IJulia")

I have the same output on the current tagged version (the default one installed by `Pkg.add("IJulia")`) but it's fixed for me with the latest master. 

If you are on the latest master - what OS are you using here?

**Comment by rsmith31415** [comment]
Oh, sorry. I thought the changes had been made available in the tagged version. No, everything looks okay in master.

**Comment by JobJob** [comment]
Great!
