### ISSUE TITLE
Completion should return the whole string

### ISSUE THREAD

**Issue by rsmith31415** [JuliaLang/IJulia.jl#348]
Currently when using `complete` in the IJulia kernel, the result is incomplete. In the following example, I executed previously `using Gadfly`.

```
In [14]: kc.complete('Geom.l')
Out[14]: '970e098d-aec1-4b9e-a602-8071e2ae5cc2'

In [15]: kc.get_shell_msg(timeout=1)
Out[15]:
{'buffers': [],
 'content': {'cursor_end': None,
  'cursor_start': -1,
  'matches': [u'label', u'label_layouts', u'line'],
  'metadata': {},
  'status': 'ok'},
 'header': {u'msg_id': u'f0ee6401-80a6-4209-ac36-0c30d6a93939',
  u'msg_type': u'complete_reply',
  u'session': u'bc516e73-3295-43e5-b5ef-8d7476dd8962',
  u'username': u'user',
  'version': '5.0'},
 'metadata': {},
 'msg_id': u'f0ee6401-80a6-4209-ac36-0c30d6a93939',
 'msg_type': u'complete_reply',
 'parent_header': {u'date': datetime.datetime(2015, 8, 30, 14, 11, 22, 751024),
  u'msg_id': u'970e098d-aec1-4b9e-a602-8071e2ae5cc2',
  u'msg_type': u'complete_request',
  u'session': u'bc516e73-3295-43e5-b5ef-8d7476dd8962',
  u'username': u'user'}}
```

The matches property contains  `[u'label', u'label_layouts', u'line']`. It should be `[u'Geom.label', u'Geom.label_layouts', u'Geom.line']`

This is  the [spec](http://jupyter-client.readthedocs.org/en/latest/messaging.html#completion) for that section:

```
content = {
    # The code context in which completion is requested
    # this may be up to an entire multiline cell, such as
    # 'foo = a.isal'
    'code' : str,

    # The cursor position within 'code' (in unicode characters) where completion is requested
    'cursor_pos' : int,
}
```

and the response:

```
content = {
# The list of all matches to the completion request, such as
# ['a.isalnum', 'a.isalpha'] for the above example.
'matches' : list,

# The range of text that should be replaced by the above matches when a completion is accepted.
# typically cursor_end is the same as cursor_pos in the request.
'cursor_start' : int,
'cursor_end' : int,

# Information that frontend plugins might use for extra display information about completions.
'metadata' : dict,

# status should be 'ok' unless an exception was raised during the request,
# in which case it should be 'error', along with the usual error message content
# in other messages.
'status' : 'ok'
}
```

In the example above, the user types `a.isal` and the response is `['a.isalnum', 'a.isalpha']`. As a comparison, this is the completion in the IPython kernel:

```
In [13]: kc.complete('np.a')
Out[13]: 'd540ba62-8067-446e-bd68-3a2a62c29c10'

In [14]: kc.get_shell_msg(timeout=1)
Out[14]:
{'buffers': [],
 'content': {u'cursor_end': 4,
  u'cursor_start': 0,
  u'matches': [u'np.abs',
   u'np.absolute',
   u'np.absolute_import',
   u'np.add',
   u'np.add_docstring',
   u'np.add_newdoc',
   u'np.add_newdoc_ufunc',
   u'np.add_newdocs',
   u'np.alen',
   u'np.all',
   u'np.allclose',
   u'np.alltrue',
   u'np.alterdot',
   u'np.amax',
   u'np.amin',
   u'np.angle',
   u'np.any',
   u'np.append',
   u'np.apply_along_axis',
   u'np.apply_over_axes',
   u'np.arange',
   u'np.arccos',
   u'np.arccosh',
   u'np.arcsin',
   u'np.arcsinh',
   u'np.arctan',
   u'np.arctan2',
   u'np.arctanh',
   u'np.argmax',
   u'np.argmin',
   u'np.argpartition',
   u'np.argsort',
   u'np.argwhere',
   u'np.around',
   u'np.array',
   u'np.array2string',
   u'np.array_equal',
   u'np.array_equiv',
   u'np.array_repr',
   u'np.array_split',
   u'np.array_str',
   u'np.asanyarray',
   u'np.asarray',
   u'np.asarray_chkfinite',
   u'np.ascontiguousarray',
   u'np.asfarray',
   u'np.asfortranarray',
   u'np.asmatrix',
   u'np.asscalar',
   u'np.atleast_1d',
   u'np.atleast_2d',
   u'np.atleast_3d',
   u'np.average'],
  u'metadata': {},
  u'status': u'ok'},
 'header': {u'date': datetime.datetime(2015, 8, 30, 14, 12, 50, 595892),
  u'msg_id': u'c3430d88-003c-495e-9d0e-253992d93682',
  u'msg_type': u'complete_reply',
  u'session': u'951f264b-865c-4313-a80f-d45624b6ddb0',
  u'username': u'user',
  u'version': u'5.0'},
 'metadata': {},
 'msg_id': u'c3430d88-003c-495e-9d0e-253992d93682',
 'msg_type': u'complete_reply',
 'parent_header': {u'date': datetime.datetime(2015, 8, 30, 14, 12, 50, 577079),
  u'msg_id': u'd540ba62-8067-446e-bd68-3a2a62c29c10',
  u'msg_type': u'complete_request',
  u'session': u'4ae54883-be3a-486f-9e06-79f02eeda145',
  u'username': u'user',
  u'version': u'5.0'}}
```

**Comment by stevengj** [comment]
Does it work in the Julia REPL?

**Comment by stevengj** [comment]
Assuming you have IPython 3.x, are you on the latest `master` version of IJulia?  Try `Pkg.checkout("IJulia"); Pkg.build("IJulia")` and then re-run `ipython notebook` (no `--profile`) if not.

**Comment by rsmith31415** [comment]
I'm not sure if I understand correctly what you mean in your first message. I'm using the IJulia kernel without the front-end (IJulia master, IPython 4, python 2.7), but I tested in the notebook anyway and the notebook is receiving the completions without the prefix (`['label', 'label_layouts', 'line']` in this case)

**Comment by terraqout** [comment]
:+1:

**Comment by stevengj** [comment]
The completion behavior here is implemented in Julia Base, using the REPLCompletions package, so that we get the same completions that you would get in the Julia REPL.   To see explicitly what it gives, see:
```
julia> Base.REPLCompletions.completions("Base.Ra", 7)
(UTF8String["Random","RandomDevice","Range","RangeIndex","RangeVecIntList","Rational","RawFD"],6:7,true)
```
Note that the current behavior only returns the portion of the string that comes after the dot.

As far as I can tell, using this behavior is perfectly allowed by the Jupyter notebook spec.  In the `complete_reply` message, we specify the range of cursor positions to replace with the text.

**Comment by rsmith31415** [comment]
@stevengj I don't think it is following the spec. As I quoted in the first message, the spec describes an example: complete `a.isal` should produce `['a.isalnum', 'a.isalpha']`, not `['isalnum', 'isalpha']`. You can see that other kernels follow this behavior (ipykernel, ir). The problem usually is that some code editors expect the full token, not only the remaining part. At least, that's how I noticed something wasn't working in IJulia but works in other kernels.

**Comment by stevengj** [comment]
@rsmith31415, an example is not the spec.  The spec only says that we should return a "range of text that should be replaced by the above matches when a completion is accepted".  This is what we are doing.

Can you give me an example of where this would cause a problem in some other editor?

@Carreau, @minrk, do you have any comments on the completion protocol?

**Comment by Carreau** [comment]
@willwhitney is working on completion, I put that on my todo list, but I'll probably not have a look in the next few days.

**Comment by minrk** [comment]
The spec only requires that the reply contain the cursor span of the text to be replaced by the matches. 

Given the `complete_request`:

```python
{
  "code": "a.isa",
  "cursor_pos": 5,
}
```

The following are two `complete_reply` messages are equally correct:

```python
{
  "matches": ['a.isalnum', 'a.isalpha'],
  "cursor_start": 0,
  "cursor_end": 5,
}
```

```python
{
  "matches": ['lnum', 'lpha'],
  "cursor_start": 5,
  "cursor_end": 5,
}
```

**Comment by rsmith31415** [comment]
@stevengj I understand that an example is not the spec, but if every implementation is going to return something slightly different, the spec won't serve a practical purpose. Remember, kernels don't live in a vacuum; they are meant to be used by front-ends and in order to get that working without major issues, kernels need to adopt similar practices.

>Can you give me a specific example of where this would cause a problem in some other editor?

Sure. The ace editor won't complete correctly if you don't return the whole string. [This](http://plnkr.co/edit/6MVntVmXYUbjR0DI82Cr?p=preview) is the basic example for a custom completer.

@minrk I wish the spec could be more strict in the inputs and outputs it requires. I don't mind which way you choose, but in this case, asserting that both outputs are okay causes fragmentation in a (hopefully) growing ecosystem for kernels.

**Comment by Carreau** [comment]
The spec is relatively strict and is meant for fuzzy completion. 

what if you have  `Geom.lbl` and you want to complete to `"Geom.label"`, you have to tell that you replace `7:9` by `abel`, or even if you have `geom.lbl` by above, then `1:9`,`Geom.label` is totally fine. 

I would also like the Julia completion to reply `[1,2,3,4])` index `11`, to reply with "insert `sum(` at `1:1`. 
So making the completion spec stricter is not technically possible, unless all the completion have a common substring at the beginning, with a length smaller than the replace range, in which case we could have a unique completion reply, but that would be useless extra computation.

**Comment by rsmith31415** [comment]
@Carreau I understand, but keep in mind that won't work in ace-based editors (those editors are expecting to complete `Geom.lbl` with an additional string). Obviously, this is not a great reason not to want fuzzy completion but you can see that this kind of changes isolate the jupyter ecosystem quite a bit because then you can't use x or y library.

**Comment by Carreau** [comment]
That's [completly untrue](http://plnkr.co/edit/6MVntVmXYUbjR0DI82Cr?p=preview).
<img width="363" alt="screen shot 2015-09-29 at 16 31 41" src="https://cloud.githubusercontent.com/assets/335567/10180089/a23d0010-66c7-11e5-8e6d-4e5450d4fa86.png">

**Comment by rsmith31415** [comment]
That's great. Is there some easy way to know if that works with dots (e.g. `Geom.l`)? Maybe they fixed that already.

**Comment by Carreau** [comment]
You might need to patch [that](https://github.com/ajaxorg/ace/blob/2321094da546579ea2ba76f996521c4cf1509ba9/lib/ace/autocomplete.js#L177-L200)to actually being able to insert in arbitrary location.

**Comment by rsmith31415** [comment]
Maybe that is needed but I was referring to the situation in which `Geom.l` won't show the pop up window  in order to select a suggestion. The suggestions are being retrieved but the ace editor discards all of them.

By the way, the fuzzy matching you were describing before is already implemented?

**Comment by rsmith31415** [comment]
I checked the ace source ([this](https://github.com/ajaxorg/ace/blob/2321094da546579ea2ba76f996521c4cf1509ba9/lib/ace/autocomplete.js#L451) is the relevant part) . For a needle, in this example, `Geom.l` (the value which is supposed to be completed), there is an array of matches (e.g. `['label', 'label layouts', 'line']`). For every possible match, we take the needle and iterate letter by letter to see if we can find that letter in the tentative match. If that letter can be found, the match goes to an array of results that will be shown to the user in the pop up (there is a penalty involved but that doesn't matter here.) However, the first letter of `Geom.l` is not found in `label` and then that match is ignored. The same happens with `label layouts` and `line`. Therefore, the pop up is not shown because the array of results is empty.

Here you can see (line 468) why the results need at least some part of the prefix to avoid the `continue loop` statement:

```
for (var j = 0; j < needle.length; j++) {
    // TODO add penalty on case mismatch
    var i1 = caption.indexOf(lower[j], lastIndex + 1);
    var i2 = caption.indexOf(upper[j], lastIndex + 1);
    index = (i1 >= 0) ? ((i2 < 0 || i1 < i2) ? i1 : i2) : i2;
    if (index < 0)
        continue loop;
```

**Comment by minrk** [comment]
@rsmith31415 the spec returns the cursor range to replace, and the text to replace it with. I don't think there's an issue of fragmentation in whether common prefixes are included or not in the reply, since the information needed to transform one to the other is available. If the editor's API needs the information in a different shape, that can be done by an adapter between the editor and the message. In the notebook, for instance, we send the entire cell for completion, so that the kernel can use the whole cell as context to determine the completion. The reply doesn't need to contain the whole cell, just the range of text to be replaced and its replacement, and the different frontends transform this reply into the shape needed for the editor.

**Comment by stevengj** [comment]
@rsmith31415, one reason the notebook sends the whole cell is that front ends don't know what constitutes an identifier in a given language.  Does ace know that `♡̂⁽³⁾!″` is a valid identifier in Julia, for example?

Also, the spec is not limited to "completions".  It also allows replacement.  e.g. we use it to complete `\alpha<tab>` to `α`, and now IPython does the same.

The spec even allows us to completely rewrite the code cell if we want.  e.g. I was toying with the idea of making something like `;<tab>` auto-indent the entire cell.

**Comment by rsmith31415** [comment]
@minrk 

>If the editor's API needs the information in a different shape, that can be done by an adapter between the editor and the message.

Well, that's of course a solution. However, it doesn't sound great when you want to support several kernels. Fortunately, I have seen so far that kernels actually behave in a very similar way, but maybe because many of them were written by the same people (you and takluyver), so there is no need to deal with special cases.

@stevengj I believe ace inspects the current line and uses a tokenizer to determine which token is going to replace. I'm not sure if unicode characters are currently supported, but there is an issue when displaying unicode, so that's clearly a limitation of the editor. Therefore, I expect that something like \alpha<tab> won't work correctly. Assuming that display issue can be fixed, I think `\alpha<tab>` will work as expected. Maybe `;tab` is not really needed in ace because there you have modes (vim, emacs) with enough functionality to auto-indent whatever you want. 

By the way, another thing that does't work in ace with the current IJulia behavior is, as @Carreau suggested, the replacement after selecting a match. For example, if you remove the filter that is discarding matches because don't contain part of the prefix, then you actually get the correct results in the pop up, but when you select one of them, instead of replacing `Geom.l` with `Geom.line`, you only get `line`.

**Comment by stevengj** [comment]
It would be better for ace not to rely on a tokenizer, as tokenizers are inevitably language-specific.

Anyway, closing this as it seems to be an ace bug (ace is not following the Jupyter messaging spec) rather than an IJulia bug.
