### ISSUE TITLE
Error in trying to use IJulia notebook

### ISSUE THREAD

**Issue by Omer80** [JuliaLang/IJulia.jl#350]
I followed the instructions for installation of Julia notebook on Ubuntu 14.04, but when I try to run it I get:
```
    [C 14:19:20.374 NotebookApp] Bad config encountered during initialization:
    [C 14:19:20.374 NotebookApp] Unrecognized flag: '--profile'
    ERROR: failed process: Process(`ipython notebook --profile julia`, ProcessExited(1)) [1]
     in pipeline_error at process.jl:502
     in notebook at /home/ohm/.julia/v0.3/IJulia/src/IJulia.jl:177
     in notebook at /home/ohm/.julia/v0.3/IJulia/src/IJulia.jl:176
```

What might be the problem?

**Comment by sammorris81** [comment]
I think this may be related to some changes for `jupyter` (from `ipython`).  I was able to fix this by changing line 177 in `~/.julia/v0.3/IJulia/src/IJulia.jl`

##### Original:
`run('$ipython notebook --profile julia')` 

##### Edited:
`run('$ipython notebook --profile=julia')`

@stevengj I was going to submit a pull request, but it's not clear if this is an issue for versions of `ipython` or if this is really an issue only for people who have recently installed `jupyter`

**Comment by stevengj** [comment]
@sammorris81, you should use the latest `master` version of IJulia: `Pkg.checkout("IJulia"); Pkg.build("IJulia")` ... this gets rid of the `--profile` entirely.
