### ISSUE TITLE
Julia kernel update from 0.3.7 to 0.3.11

### ISSUE THREAD

**Issue by doyaklee** [JuliaLang/IJulia.jl#351]
I uninstalled previous version of Julia 0.3.7 and installed 0.3.11.
After that I rebuilt and updated all packages including IJulia.

However, in the IPython notebook, I still only can see Julia 0.3.7 kernel and versioninfo() in IPython notebook shell says I'm using Julia 0.3.7. 

Could you let me know what I'm missing? Thanks!

**Comment by stevengj** [comment]
Did you run `Pkg.build("IJulia")`?  Did you relaunch `ipython notebook`?

**Comment by doyaklee** [comment]
@stevengj  Yes. I rerun Pkg.build("IJulia") and also relaunched ipython notebook. In fact I tried to reboot the machine itself, but it still didn't change

**Comment by stevengj** [comment]
What is the output of `versioninfo(true)` when you are running `Pkg.build`?  What is `ipython --version`?

**Comment by doyaklee** [comment]
After ``Pkg.build("IJulia")``, ``IPython --version`` result is ``4.0.0``, and part of the ``versioninfo(true)`` result is as follows:
![versioninfo](https://cloud.githubusercontent.com/assets/14086459/9691150/af27833a-530e-11e5-8375-48becec2112f.png)

**Comment by stevengj** [comment]
Try `Pkg.checkout("IJulia"); Pkg.build("IJulia")` and then just run `ipython notebook` (with no `--profile`).

**Comment by doyaklee** [comment]
I cleared ``dirty`` flag above using ``git checkout .``
Then, I followed your suggestion:: ``Pkg.checkout("IJulia") ; Pkg.build("IJulia") `` then run ``ipython notebook``, but it still just shows 0.3.7.
After that, I tried to remove and re-add IJulia package, then run ``ipython notebook``. It still just shows 0.3.7.

I first thought that this could be just a notational problem, meaning that in fact the kernel is 0.3.11, and ipython notebook just says the kernel is 0.3.7.  But in that notebook ``versioninfo(true)`` said that Julia Version is 0.3.7. It's weird since I already removed 0.3.7. version of Julia and in addition added Julia 0.3.11 into my ``path``.

**Comment by stevengj** [comment]
@doyaklee, my guess at this point is that you have more than one version of IPython installed, and IJulia is finding a different version than the one you are running.  Do you have more than one Python distro on your computer, for example?

For example, try running
```
run(`ipython --version`)
```
in Julia and compare the output to what you get on the command-line where you are running `ipython`.

**Comment by stevengj** [comment]
Or kill IPython and run `using IJulia; IJulia.notebook()` in Julia to launch the notebook.

**Comment by doyaklee** [comment]
@stevengj  I checked that I only have one IPython version. 
Now I found that I messed up something with Anaconda and Juno.
Before installing Julia 0.3.11, I originally installed Julia 0.3.7 + Juno IDE bundle. 
I don't know what exactly happened since Julia + Juno bundle needs no build process, install, etc., but just file extraction. 

Anyway, in IPython notebook's `versioninfo(true)`, I found that 
``PATH = c:\Julia_juno\resources\app\julia\bin;c:\Julia_juno\resources\app\julia\bin\..\Git\bin;C:\ProgramData\Oracle\Java\javapath;C:\Perl64\site\bin...`` 
where `Julia_juno` is the folder I extracted Juno IDE. 

Also I checked that 
``C:\Users\Username\AppData\Roaming\jupyter\kernels\julia-0.3\kernel.json``
contains
``
{
  "display_name": "Julia 0.3.7",
  "argv": [
    "c:\\\\Julia_juno\\\\resources\\\\app\\\\julia\\\\bin\\\\julia.exe",
    "-i",
    "-F",
    "C:\\\\Users\\\\Username\\\\.julia\\\\v0.3\\\\IJulia\\\\src\\\\kernel.jl",
    "{connection_file}"
  ],
  "language": "julia"
}
``

So, I tried two things:
1. delete Juno IDE folder and modify `kernel.json` file's `argv` with the one that contains Julia 0.3.11 version -- it didn't work.
2. download newer Julia + Juno IDE bundle and replace the old `Julia_juno` folder with the new one -- it didn't work.

Another Anaconda thing I may mess up is that I have two Anaconda environments for Python 2.7 and Python 3.4 separately. 

Anyway now I found that this is not the problem coming from `IJulia` and I messed a lot of things, so I just gave up at this point since I can anyway run Julia with previous version. So, if you want, please close this Issue. Thanks!

**Comment by doyaklee** [comment]
Some updates:: 

I have another machine that has Julia 0.3.10 and 0.3.11. This machine also has two Anaconda environments for Python 2.7 and Python 3.4. The difference between this machine and previous machine is that this machine haven't installed Juno. 

Now I found that the problem lies in `C:\Users\Username\AppData\Roaming\jupyter\kernels\julia-0.3\kernel.json` file. As said before, after update and re-build `IJulia' with Julia 0.3.11, it still contains

``
"argv": [
    "C:\\\\Users\\\\Username\\\\AppData\\\\Local\\\\Julia-0.3.10\\\\bin\\\\julia.exe",
    "-i",
    "-F",
    "C:\\\\Users\\\\Username\\\\.julia\\\\v0.3\\\\IJulia\\\\src\\\\kernel.jl",
    "{connection_file}"
  ]
``

even after I deleted Julia 0.3.10 from my `path` and added Julia 0.3.11 into my `path`. So, I think the problem is `Pkg.build("IJulia")` doesn't automatically update this part since after I just changed `argv` part as `Julia-0.3.11`  now it worked perfectly.

I still don't know what Juno IDE did so that after deleting Juno IDE and modifying `kernel.json` IPython notebook still doesn't recognize 0.3.11 kernel. But anyway there's some progres I think.

**Comment by stevengj** [comment]
`Pkg.build("IJulia")` overwrites the entire `kernel.jl` file.   Where were you running `Pkg.build?`  In the REPL of the new Julia (correct) or in Jupyter (wrong, since you are still running it from the *old* version of Julia) or in Juno (wrong, for the same reason, I think, although I haven't used Juno).

**Comment by doyaklee** [comment]
It's still weird since after updating `path` to exclude the old version of Julia executable and include the new version of Julia executable, I did `Pkg.build("IJulia")` in the REPL of new version of Julia. 
Btw, what I meant was `kernel.json` file under `...\jupyter\kernels` folder, not the `kernel.jl` file  under `...\IJulia\src` folder. Is `kernel.json` file also overwritten?

**Comment by doyaklee** [comment]
After several attempts of manually changing `display_name` in `kernel.json` files and doing `Pkg.build("IJulia")`, I found that `Pkg.build("IJulia")` updated `C:\Users\Username\.ipython\kernels\julia-0.3\kernel.json`, but it didn't update `C:\Users\Username\AppData\Roaming\jupyter\kernels\julia-0.3\kernel.json`. Furthermore, I found that `ipython notebook` follows `...\jupyter\...\kernel.json`, not `...\.ipython\...\kernel.json`. I think this causes current problem.

**Comment by stevengj** [comment]
It uses the `ipython locate` command to find the correct location to install into.

@Carreau, @minrk, is `ipython locate` no longer the correct way to find the config director in IPython 4?

**Comment by minrk** [comment]
`ipython locate` shows you the IPython directory. With IPython/Jupyter 4.0, there is now a Jupyter directory. You can find the Jupyter locations with `jupyter --paths` or `jupyter --paths --json` for a parseable version. Installing kernelspecs should be done by calling `[jupyter|ipython] kernelspec install` rather than trying to guess where IPython/Jupyter would put kernelspecs. I'll see if I can make a PR on build.jl that uses the most official mechanism possible on both 3 and 4.

**Comment by minrk** [comment]
#353 should make the change to use `jupyter kernelspec` when available and `ipython kernelspec` on IPython 3. It removes the need to query anything about paths, on both IPython 3 and Jupyter going forward.
