### ISSUE TITLE
Autocompletion sometimes breake

### ISSUE THREAD

**Issue by dhoegh** [JuliaLang/IJulia.jl#352]
Sometimes the autocompletion breaks in a notebook and it can only be restored to a working condition by closing and reopening the notebook. I do not have a consistent way of reproducing it. The output in the terminal give the following each time I tab.
``` 
KERNEL EXCEPTION
KeyError: text not found

 in getindex at dict.jl:718
 in complete_request at C:\Users\dho\.julia\v0.4\IJulia\src\handlers.jl:7
 in eventloop at C:\Users\dho\.julia\v0.4\IJulia\src\IJulia.jl:123
 in anonymous at task.jl:447
```

**Comment by stevengj** [comment]
I think this should be fixed in the latest IJulia `master` version (`Pkg.checkout("IJulia"); Pkg.build("IJulia")`) with IPython 3 or later.

**Comment by dhoegh** [comment]
Thank you, I see the latest tag is from the spring, could you tag a new version?

**Comment by stevengj** [comment]
Yes, I've been holding back on dropping IPython 2 support, but I'm planning to tag something shortly, after running a few tests.

**Comment by stevengj** [comment]
Tagged as IJulia 1.0.
