### ISSUE TITLE
can't install on windows julia 0.4

### ISSUE THREAD

**Issue by Ken-B** [JuliaLang/IJulia.jl#354]
I'm trying to install IJulia on windows 7. I made a fresh install of the latest julia 0.4 rc binary. Also a fresh anaconda win64 python3.4 installation and I ran `conda install ipython-notebook` successfully.

However, adding (and building) IJulia creates following error:
```
INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/reposi
tories/windows:/mingw:/win32/openSUSE_13.1/repodata/repomd.xml
INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/reposi
tories/windows:/mingw:/win64/openSUSE_13.1/repodata/repomd.xml
INFO: Building Nettle
INFO: Updating WinRPM package list
INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/reposi
tories/windows:/mingw:/win32/openSUSE_13.1/repodata/repomd.xml
INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/reposi
tories/windows:/mingw:/win64/openSUSE_13.1/repodata/repomd.xml
INFO: Building ZMQ
INFO: Building IJulia
Found jupyter kernelspec version 4.0.0 ... ok.
Writing IJulia kernelspec to C:\Users\Ken\AppData\Local\Temp\jul97CD.tmp\julia-0
.4\kernel.json ...
Copying logo-32x32.png to Julia kernelspec.
Copying logo-64x64.png to Julia kernelspec.
Installing julia kernelspec julia-0.4

julia> Traceback (most recent call last):
  File "C:\CodingProgs\Anaconda\Scripts\jupyter-kernelspec-script.py", line 7, i
n <module>
    main()
  File "C:\CodingProgs\Anaconda\Scripts\jupyter-kernelspec-script.py", line 4, i
n main
    KernelSpecApp.launch_instance()
  File "C:\CodingProgs\Anaconda\lib\site-packages\traitlets\config\application.p
y", line 592, in launch_instance
    app.start()
  File "C:\CodingProgs\Anaconda\lib\site-packages\jupyter_client\kernelspecapp.p
y", line 177, in start
    return self.subapp.start()
  File "C:\CodingProgs\Anaconda\lib\site-packages\jupyter_client\kernelspecapp.p
y", line 113, in start
    replace=self.replace,
  File "C:\CodingProgs\Anaconda\lib\site-packages\jupyter_client\kernelspec.py",
 line 208, in install_kernel_spec
    shutil.copytree(source_dir, destination)
  File "C:\CodingProgs\Anaconda\lib\shutil.py", line 297, in copytree
    names = os.listdir(src)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\
Users\\Ken\\AppData\\Local\\Temp\\jul97CD.tmp\\julia-0.4'
```

FYI:
```
julia> versioninfo()
Julia Version 0.4.0-rc1
Commit e5c6964 (2015-09-09 16:07 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```
Let me know what I can do to help and debug.

**Comment by stevengj** [comment]
@minrk, this looks like a problem introduced by #353.  Any ideas?

**Comment by minrk** [comment]
Arg, I never get things right on Windows on my first go, sorry about that. Yes, it's definitely due to #353. The bug isn't immediately obvious to me, but it may involve escapes and backslashes.

**Comment by stevengj** [comment]
Normally you don't have to escape anything for `run`, because `run` bypasses the shell entirely and spawns the process directly with the specified arguments.

**Comment by mmoh** [comment]
```
julia> Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\jupyter-kernelspec-script.py", line 7, in <module>
    main()
  File "C:\Anaconda3\Scripts\jupyter-kernelspec-script.py", line 4, in main
    KernelSpecApp.launch_instance()
  File "C:\Anaconda3\lib\site-packages\traitlets\config\application.py", line 592, in launch_instance
    app.start()
  File "C:\Anaconda3\lib\site-packages\jupyter_client\kernelspecapp.py", line 177, in start
    return self.subapp.start()
  File "C:\Anaconda3\lib\site-packages\jupyter_client\kernelspecapp.py", line 113, in start
    replace=self.replace,
  File "C:\Anaconda3\lib\site-packages\jupyter_client\kernelspec.py", line 208, in install_kernel_spec
    shutil.copytree(source_dir, destination)
  File "C:\Anaconda3\lib\shutil.py", line 297, in copytree
    names = os.listdir(src)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\mmoh\\AppData\\Local\\Temp\\jul5955.tmp\\julia-0.5'
```

Also 
```
Julia Version 0.5.0-dev+9
Commit 248eb0b (2015-09-10 04:03 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

Same problem. This happened when updating to newest Julia version. I hope this can be updated soon.

**Comment by Ken-B** [comment]
Meanwhile I found out that adding a `sleep(1)` before removing the temporary directory in the last line of the build.jl will make the build pass. 

However, even when the build finishes successful, it will not run jupyter with this kernel on windows. I think it has to do with `escape_string` for windows backslashes in the path. If a define an extra function 
`esc_str(s::AbstractString) = @windows ? s : escape_string(s)` and substitute the `escape_string`, it works. I haven't tried on non-windows.

These are hacks, but it now works on my system.

Unrelated to this issue: #353 removed the `find_ipython` function, but that function is still called in the `notebook()` default argument [on this line](https://github.com/JuliaLang/IJulia.jl/blob/7052b07422ff7e9a7101f06018e9568dba781116/src/IJulia.jl#L183).

**Comment by stevengj** [comment]
Thanks, `notebook` is fixed by b4fd27f49ce2ec5e790fa75b1d34e5ca60a044a5.

**Comment by stevengj** [comment]
I think I'm just going to get rid of the temporary directory thing, and put it in a permanent directory under `deps`.  I don't think leaving an extra copy of the directory lying around is a problem.

**Comment by stevengj** [comment]
The call to `escape_string` should be removed entirely because `JSON.json` already escapes strings as needed.

**Comment by stevengj** [comment]
Should be fixed now; let me know if not.

**Comment by stevengj** [comment]
(Still, it is somewhat bizarre that `jupyter kernelspec install` is affected by an `rm` that occurs *after* the process has returned, since the `run` function is synchronous.  @minrk, does `kernelspec install` spawn a detached process or something?)

**Comment by mmoh** [comment]
@stevengj  Thanks! Did a Pkg.checkout("IJulia") and everything is back to working now.

**Comment by minrk** [comment]
Ah, I think I know what's going on with the return. It's a bizarre Windows behavior, but I think I know how to fix it.

**Comment by stevengj** [comment]
@minrk, I'm glad someone understands these things.  When you fix it, please link the fix from here so that I can be enlightened.

**Comment by minrk** [comment]
@stevengj it's jupyter/jupyter_core#54. Python provides an `exec` command on Windows, even though Windows doesn't actually have exec. The behavior is more akin to fork & exec, so the `jupyter` command was returning immediately, while the exec'd process (`jupyter-kernelspec`) continued in the background.
