### ISSUE TITLE
Latest Update of IJulia has build failures

### ISSUE THREAD

**Issue by mattcbro** [JuliaLang/IJulia.jl#356]
I am running 64 bit linux mint 17.1 and just ran Pkg.update(), got an error and then for chuckles tried to run Pkg.build("IJulia").  The end result is this error:
===========================================================================[ ERROR: IJulia ]============================================================================

Jupyter or IPython 3.0 or later is required for IJulia, got IPython 1.2.1 instead
while loading /home/matthew/.julia/v0.3/IJulia/deps/build.jl, in expression starting on line 18

========================================================================================================================================================================
However the standard repository build for IPython is 1.2.1.  This will be the case for any Ubuntu 14.04 based distro.

So I uninstalled that package then used pip to reinstall IPython, ie
>  sudo pip install ipython --upgrade

This installation notably refused to install pexpect 3.1 and decorator 3.4.0 since they were "owned" by the OS.

But I'm still SOL. From the Julia prompt:
julia> Pkg.build("IJulia")
INFO: Building Nettle
INFO: Building ZMQ
INFO: Building IJulia
Found IPython version 4.0.0 ... ok.
Writing IJulia kernelspec to julia-0.3/kernel.json ...
===========================================================================[ ERROR: IJulia ]============================================================================

function cp does not accept keyword arguments
while loading /home/matthew/.julia/v0.3/IJulia/deps/build.jl, in expression starting on line 66

========================================================================================================================================================================

The end result is that IJulia is no longer working, and I do not see a clear path to success.

**Comment by mattcbro** [comment]
Oh I forgot to mention.  This is all happening on Julia 0.3.11

**Comment by parente** [comment]
Started happening against jupyter/docker-stacks builds today too.

**Comment by parente** [comment]
https://github.com/JuliaLang/IJulia.jl/commit/e01b2e44f18b2f1dbcc167273949dd2ac8258dea#commitcomment-13197892 shows the regression

**Comment by mattcbro** [comment]
Oh yeah thats it.  This line:
copy_config(src, dest) = cp(src, joinpath(dest, src), remove_destination=true)
apparently only works in version 0.4 .  I would think there is an easy work around,  to support the remove_destination keyword argument in 0.3.11

**Comment by stevengj** [comment]
Should be fixed now.

Note that IPython 1.x and 2.x are no longer supported.

**Comment by parente** [comment]
@stevengj Thanks for the perfectly timed fix: was just about to rebuild the docker image for jupyter containing IJulia. :)

**Comment by mattcbro** [comment]
Thanks for fixing this so quickly.  For those who might have a similar problem please note that I also had to upgrade/install jupyter to get this to start working again.

Prior to that I got this error:
failed process: Process(`ipython kernelspec install --replace --user julia-0.3`, ProcessExited(1)) [1]
while loading /home/matthew/.julia/v0.3/IJulia/deps/build.jl, in expression starting on line 81

Fortunately pip worked for that as well via:
sudo pip install -U jupyter

So these software updates are ahead of the distributions versions.
