### ISSUE TITLE
replace the [kernel spec] when install a new version Julia

### ISSUE THREAD

**Issue by AnakinShieh** [JuliaLang/IJulia.jl#359]
When I tried to install a new version Julia (from 0.3.10 to 0.3.11), I found that Jupyter notebook can't use Julia.
I didn't know the reason then, and thought it was Jupyter's problem until I find the kernel spec file in %Appdata/Roaming/Jupyter/kernels/Julia-0.3, It was the older 0.3.10 kernel spec file so Jupyter Notebook can't invoke the Julia 0.3.11 kernel.
Maybe it should force to add a new kernel spec file when adding  "IJulia" package.
Sorry for my English, I hope I have expressed this issue clearly.

**Comment by stevengj** [comment]
As explained in the README (https://github.com/JuliaLang/IJulia.jl#updating-julia-and-ijulia), you will need to open up the command-line (REPL) of the new Julia version and run `Pkg.build("IJulia")` to tell Jupyter where to find it.  This will overwrite the kernel spec file.
