### ISSUE TITLE
JUPYTER env variable does not seem to be respected

### ISSUE THREAD

**Issue by cournape** [JuliaLang/IJulia.jl#367]
If I understand the instructions correctly, defining `JUPYTER` environment variable to an existing jupyter installation should not install conda when doing `Pkg.add("IJulia")`. Yet, that's what seems to happen (using latest `0.3.11` julia binary for Linux).

**Comment by cournape** [comment]
I am a completely new to julia, so maybe I am missing something, but it looks as if the code in `build.jl` is wrong in https://github.com/JuliaLang/IJulia.jl/blob/master/deps/build.jl#L25

IIUC, when `JUPYTER` is defined, one get a string, but when not defined, we get a sequence of strings, so when `JUPYTER` is defined, one iterate over every character of the corresponding value, hence that case always failing.

**Comment by stevengj** [comment]
Thanks for the bug report.

**Comment by cournape** [comment]
Thanks for the quick fix !
