### ISSUE TITLE
Feature request: a magic to toggle on/off whether to show the return value and/or warning

### ISSUE THREAD

**Issue by Sisyphuss** [JuliaLang/IJulia.jl#371]
Update: the returned value "showed in **Out[ ]:**"

**Comment by stevengj** [comment]
What return value and warning are you talking about?  You mean the return value from executing a code cell?

**Comment by Sisyphuss** [comment]
Yes, the one showed in **Out[  ]:**.

**Comment by stevengj** [comment]
You can just end the cell with a semicolon to suppress the `Out[*]` return value.

**Comment by Sisyphuss** [comment]
I changed the title of this issue. This feature can help quick **development/presentation** switch.

**Comment by Sisyphuss** [comment]
Maybe this is more an *IPython* issue...

**Comment by stevengj** [comment]
If you want a global setting to suppress all output, I suppose that would should be filed with Jupyter.  I still can't figure out what you're trying to accomplish, though.

**Comment by Sisyphuss** [comment]
@stevengj I know what you mean. Thanks.
