### ISSUE TITLE
nbconvert failed: PDF creating failed

### ISSUE THREAD

**Issue by gr225607** [JuliaLang/IJulia.jl#373]
Can't seem to download as a pdf, any help would be appreciated. 

I installed pandoc and MikTex, and now getting this error:

![image](https://cloud.githubusercontent.com/assets/5554569/10445154/f4d10982-713c-11e5-93f3-a7e1d0b2c70c.png)

**Comment by stevengj** [comment]
Please report the problem at https://github.com/jupyter/nbconvert

**Comment by gr225607** [comment]
ok thanks
