### ISSUE TITLE
isdefined(Main, :IJulia) returns false

### ISSUE THREAD

**Issue by rohitvarkey** [JuliaLang/IJulia.jl#377]
[Patchwork](https://github.com/shashi/Patchwork.jl) uses `isdefined(Main, :IJulia)` to load IJulia specific code. I've also been working on something like that for [Vega](https://johnmyleswhite/Vega.jl) but using this doesn't work.

I'm using Julia 0.4.0-rc1 and on `IJulia` master.

I added an `@show isdefined(Main, :IJulia)` in Patchwork.jl and got `false`. Then ran the same in the notebook which gave me `true`!
```
In [1]: using Patchwork
INFO: Recompiling stale cache file /Users/rohitvarkey/.julia/lib/v0.4/Patchwork.ji for module Patchwork.
isdefined(Main,:IJulia) = false
In [2]: isdefined(Main, :IJulia)
Out[2]: true
```

I thought it was a problem with my Jupyter config but seems to be affecting others too. See https://github.com/shashi/Patchwork.jl/issues/12.

**Comment by yuyichao** [comment]
This is not going to work with precompiled module. You need to do the detection in your `__init__` function.

Also, this is not a IJulia issue and I think there's aloready an base julia issue for conditional module.

**Comment by rohitvarkey** [comment]
Thanks @yuyichao. Sorry for the noise.
