### ISSUE TITLE
Error span displayed around unicode characters in code

### ISSUE THREAD

**Issue by bspeice** [JuliaLang/IJulia.jl#378]
I having a strange issue that I can't seem to work around. When I use unicode characters in code blocks, there's a red box drawn around them with a `span.err` class. I can't seem to remove them using a custom css, and converting the notebook to html, stripping the class, and then to PDF produces something that doesn't look so good (issue with converters).

Is there anything that can be done to fix how this is rendered?
![ijulia error box](https://github-cloud.s3.amazonaws.com/assets/1199853/10565517/feba47ee-759f-11e5-95e9-a75c8a55bbce.png)

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/IJulia.jl/issues/308
