### ISSUE TITLE
Completion of method and path completion in strings and cmd are broken on Jupyter

### ISSUE THREAD

**Issue by dhoegh** [JuliaLang/IJulia.jl#380]
The completion is broken on Jupyter when two lines or more is present. 
```
a=1
max(1,<tab> # this do not give method completion when anything is present on line 1
```

```
a=1
"p<tab> # It tries to complete methods instead of paths
```

```
a=1
`p<tab> # It tries to complete methods instead of paths
```
This behavior are due to the new v5 message spec according to https://github.com/JuliaLang/julia/pull/9467. Unfortunately PR the was closed due to missing response.

**Comment by stevengj** [comment]
One easy option would be only to send the current line to the `completions` function.

Ideally, the completions function would parse backwards until it found the beginning of an expression, but I'm not sure how easy that is in the current parser.  (@Keno, any comments?)

**Comment by dhoegh** [comment]
JuliaLang/julia#9467 would close this issue and it was fully functioning, as far as I have tested. But @Carreau closed it due to missing response.

**Comment by stevengj** [comment]
@dhoegh, I agree that it would be good to get something like that merged.  However, we still need to implement a workaround in IJulia for earlier Julia versions.

Sending only the current line is a bit annoying because it could easily get confused by multi-line expressions, but it may be the best workaround for now.

**Comment by stevengj** [comment]
Okay, I pushed a workaround.

**Comment by dhoegh** [comment]
Thank you that was fast:+1:. I can confirm it fixes the issue. Could you tag a new version?
