### ISSUE TITLE
Add dataframe variables names at autocomplete

### ISSUE THREAD

**Issue by dmoliveira** [JuliaLang/IJulia.jl#381]
Some cool feature could be loading the variables names in a way that we can use as autocomplete.
For example, lets suppose that the following dataframe is loaded as:
```
train = readtable("data/train.csv")
```
and
```
showcols(train)
```
results in 

891x12 DataFrames.DataFrame

| Col # | Name        | Eltype     | Missing |
|-------|-------------|------------|---------|
| 1     | PassengerId | Int64      | 0       |
| 2     | Survived    | Int64      | 0       |
| 3     | Pclass      | Int64      | 0       |
| 4     | Name        | UTF8String | 0       |
| 5     | Sex         | UTF8String | 0       |
| 6     | Age         | Float64    | 177     |
| 7     | SibSp       | Int64      | 0       |
| 8     | Parch       | Int64      | 0       |
| 9     | Ticket      | UTF8String | 0       |
| 10    | Fare        | Float64    | 0       |
| 11    | Cabin       | UTF8String | 687     |
| 12    | Embarked    | UTF8String | 2       |

then a cool feature could be when I do
```
a = [:<TAB>]
```
the variables from the dataframe will appears as option in auto-complete list.

**Comment by stevengj** [comment]
IJulia just call's Julia's built-in completion routines, so this kind of extensible completion would be added there, not here.
