### ISSUE TITLE
ERROR: Failed to precompile IJulia to /apps/infrafs1/dbrowne/.julia/lib/v0.4/IJulia.ji

### ISSUE THREAD

**Issue by dbrowne** [JuliaLang/IJulia.jl#382]
Getting the following errror in Version 0.4.0-rc4 (2015-10-04 03:14 UTC)
 in my .julia dir I have ZMQ version v"0.4.0-dev+6521" 

julia> using IJulia
INFO: Precompiling module IJulia...
ERROR: LoadError: InitError: ZMQ version 2.2.0 < 3 is not supported
 in error at ./error.jl:21
 in __init__ at /apps/infrafs1/dbrowne/.julia/v0.4/ZMQ/src/ZMQ.jl:562
 in _require_from_serialized at loading.jl:84
 in require at ./loading.jl:225
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at ./client.jl:284
 in _start at ./client.jl:411
during initialization of module ZMQ
while loading /apps/infrafs1/dbrowne/.julia/v0.4/IJulia/src/IJulia.jl, in expression starting on line 15
ERROR: Failed to precompile IJulia to /apps/infrafs1/dbrowne/.julia/lib/v0.4/IJulia.ji
 in error at ./error.jl:21
 in compilecache at loading.jl:383
 in require at ./loading.jl:250

Any suggestions?

**Comment by stevengj** [comment]
You need a newer version of the `libzmq` library.   If you have a problem with this, file an issue with ZMQ.jl.
