### ISSUE TITLE
IJulia symlink EISDIR error on Windows 7 with Julia 0.4.0

### ISSUE THREAD

**Issue by CarlBrunius** [JuliaLang/IJulia.jl#385]
Hi,

I've tried to install IJulia on my computer as suggested on IJulia front page (Pkg.add("IJulia"), but am getting error (see below). I've installed Jupyter (2015-11-10) through Anaconda3-2.4.0 and also installed R kernel which seems is working. Julia was started "As administrator" and my local user has administrator rights.

Julia window:
```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0 (2015-10-08 06:20 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> Pkg.add("IJulia")
WARNING: Note: on Windows, creating file symlinks requires Administrator privile
ges.
ERROR: symlink: illegal operation on a directory (EISDIR)
 in symlink at fs.jl:167
 in mkcachedir at pkg/cache.jl:17
 in prefetch at pkg/cache.jl:33
 in resolve at pkg/entry.jl:434
 in edit at pkg/entry.jl:26
 in anonymous at task.jl:447
 in sync_end at task.jl:413
 [inlined code] from task.jl:422
 in add at pkg/entry.jl:64
 in add at pkg/entry.jl:73
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:32
 in cd at pkg/dir.jl:31
 in add at pkg.jl:23

julia>
```

I'm new to Julia AND Jupyter, so I apologise if this is a simple mistake. I Googled the error message but didn't find a solution.

Computer: HP Folio 9470m
CPU: i7-3687U
OS: Windows 7 Enterprise
Julia: 0.4.0

Best wishes,
Carl

**Comment by JobJob** [comment]
Have you been able to successfully install any other packages?

**Comment by CarlBrunius** [comment]
Hi,
Tried at home to Pkg.update(). It appears that Julia installation is trying to access my network drive:

```
julia> Pkg.update()
INFO: Initializing package repository Z:\.julia\v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
fatal: unable to access 'Z:\/.gitconfig': Invalid argument
ERROR: failed process: Process(`git clone -q -b metadata-v2 git://github.com/Jul
iaLang/METADATA.jl METADATA`, ProcessExited(128)) [128]
 in run at process.jl:531
```

Why has it installed stuff on my network drive? I thought I had installed only locally?! Google tells me that network mapping is a known issue. I guess I'll have to scout for how to map it to local directory instead... And I had hoped that -: for once :- everything would work straight out-of-the-box... -: sigh :-

At home (without having work LAN) I installed Julia 0.4.1 - same problem. I need to figure out how to point Julia to different location. If you have advice, I'd be very happy :)

Thanks,
Carl

**Comment by yuyichao** [comment]
Did you set up the network drive to be your HOME ?

**Comment by CarlBrunius** [comment]
I just had a Windows 7 install by our IT dept. They must've done it, since I honestly don't even know how to set up HOME -: Shamefully ignorant :- I just want to start writing code :)

**Comment by CarlBrunius** [comment]
Tried to:
```
ENV["HOME"] ="C:\\julia-0.4.1"
ENV["JULIA_PKGDIR"]="C:\\Julia-0.4.1\\juliaPackages"
Pkg.init()
Pkg.update()
Pkg.add("IJulia")
```
I got a warning about WinRPM saying I should do WinRPM.update()
Then it gave me some build errors for  IJulia, but I unfortunately exited Julia before it struck me I should have copied the output. Sorry...

Anyway, I started new session:
```
julia> homedir()
"Z:\\"

julia> Pkg.update()
INFO: Initializing package repository Z:\.julia\v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
fatal: unable to access 'Z:\/.gitconfig': Invalid argument
ERROR: failed process: Process(`git clone -q -b metadata-v2 git://github.com/Jul
iaLang/METADATA.jl METADATA`, ProcessExited(128)) [128]
 in run at process.jl:531
```
Performed the two ENV above and did:
````
julia> Pkg.init()
INFO: Initializing package repository C:\Julia-0.4.1\juliaPackages\v0.4
INFO: Package directory C:\Julia-0.4.1\juliaPackages\v0.4 is already initialized.

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> Pkg.add("IJulia")
INFO: Nothing to be done
```

End result is that there's no Julia kernel in Jupyter :(

**Comment by CarlBrunius** [comment]
@JobJob 

Installing e.g. MultivariateStats seems to be working:

```
julia> Pkg.add("MultivariateStats")
INFO: Cloning cache of ArrayViews from git://github.com/JuliaLang/ArrayViews.jl.
git
INFO: Cloning cache of MultivariateStats from git://github.com/JuliaStats/Multiv
ariateStats.jl.git
INFO: Cloning cache of StatsBase from git://github.com/JuliaStats/StatsBase.jl.g
it
INFO: Cloning cache of StatsFuns from git://github.com/JuliaStats/StatsFuns.jl.g
it
INFO: Installing ArrayViews v0.6.4
INFO: Installing MultivariateStats v0.2.1
INFO: Installing StatsBase v0.7.4
INFO: Installing StatsFuns v0.2.0
INFO: Package database updated
INFO: METADATA is out-of-date - you may not have the latest version of Multivari
ateStats
INFO: Use `Pkg.update()` to get the latest versions of your packages

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Computing changes...
INFO: No packages to install, update or remove
```

**Comment by JobJob** [comment]
Ok good. What's the output of Pkg.build("IJulia")?

**Comment by CarlBrunius** [comment]
Well, what do you know...
```
julia> Pkg.build("IJulia")
INFO: Building WinRPM
INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
INFO: Building Nettle
INFO: Updating WinRPM package list
INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
INFO: Building ZMQ
INFO: Building IJulia
INFO: Found Jupyter version 4.0.6: jupyter
Writing IJulia kernelspec to C:\Julia-0.4.1\juliaPackages\v0.4\IJulia\deps\julia-0.4\kernel.json ...
Installing julia kernelspec julia-0.4
[InstallKernelSpec] Installed kernelspec julia-0.4 in C:\Users\brunius\AppData\Roaming\jupyter\kernels\julia-0.4
```
And I've got Julia 0.4.1 as a kernel in Jupyter :)

Any thoughts on changing HOME and JULIA_PKGDIR permanently?

**Comment by JobJob** [comment]
Nice.
Haven't run windows for a while, but I think your options are: put a `.juliarc.jl` file at `Z:\` (or whatever your output for `julia> homedir()` is and add the lines:

    ENV["HOME"] = "C:\best\path\ever"
    ENV["JULIA_PKGDIR"] = "C:\epic\packagedir\path"

Another option would be to start julia from a batch file (I assume they still exist), with something like:

    set HOME="C:\best\path\ever"
    set JULIA_PKGDIR = C:\epic\packagedir\path
    c:\path\to\julia

If you can get the sysadmin to change things then I think where julia looks is `echo %HOMEDRIVE%\%HOMEPATH%`

Ok HTH :)

**Comment by CarlBrunius** [comment]
Fantastic,
Thanks for helping me out. Much appreciated! :)
Carl

BTW loved teh paths :)

**Comment by JobJob** [comment]
Ha :+1:
