### ISSUE TITLE
Problems installing IJulia with Julia 0.4 on Ubuntu

### ISSUE THREAD

**Issue by rdeits** [JuliaLang/IJulia.jl#386]
I've been trying to install IJulia with Julia 0.4 on Ubuntu 14.04, but I've been unable to get it to work. Attempting to run:

```
Pkg.add("IJulia")
```

gives:

```
INFO: Building IJulia
INFO: Precompiling module JSON...
INFO: Precompiling module Conda...
INFO: Recompiling stale cache file /home/rdeits/.julia/lib/v0.4/Conda.ji for module Conda.
WARNING: Module BinDeps uuid did not match cache file
========================================================================[ ERROR: IJulia ]========================================================================

LoadError: __precompile__(true) but require failed to create a precompiled cache file
while loading /home/rdeits/.julia/v0.4/IJulia/deps/build.jl, in expression starting on line 2

=================================================================================================================================================================

========================================================================[ BUILD ERRORS ]=========================================================================

WARNING: IJulia had build errors.

 - packages with build errors remain installed in /home/rdeits/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("IJulia")`
 - build a single package by running its `deps/build.jl` script

=================================================================================================================================================================
INFO: Package database updated
```

I've purged julia, deleted ~/.julia, and all the julia-related files from .ipython, and reinstalled julia 0.4 from the staticfloat PPA, and I'm getting the same result. 

After this failure, I *can* complete the build, by restarting Julia and running `Pkg.build("IJulia")`. However, the installation doesn't actually seem to be functional. Running `notebook()` gives me the jupyter web interface, and I can create a new Julia 0.4 notebook, but executing any cell in that notebook just results in no output whatsoever from the kernel. 

As additional info: I can successfully install IJulia on Julia 0.3, but I still get no response from the kernel. Here's what the output looks like:

![screenshot from 2015-11-11 10 42 14](https://cloud.githubusercontent.com/assets/591886/11095043/26347f96-8861-11e5-9670-44d18d2f1abe.png)

Any advice or suggestions? I'm happy to help try to debug this, but I'm not really sure where to start.

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/13915 and https://github.com/JuliaLang/julia/issues/13200. The workaround is to just try again.
