### ISSUE TITLE
Jupyter PDF Export 

### ISSUE THREAD

**Issue by jdtuck** [JuliaLang/IJulia.jl#390]
When I try to download my Jupyter notebook using Plots.jl as a PDF I get this error

      nbconvert failed: Inkscape svg to pdf conversion failed

When I dig into the log  I get the following

    NbConvertApp] WARNING | Collisions detected in jupyter_nbconvert_config.py and jupyter_nbconvert_config.json config files. jupyter_nbconvert_config.json has higher priority: {
      "Exporter": {
    "template_path": "['.', '/home/jdtuck/.local/share/jupyter/templates'] ignored, using ['/home/jdtuck/.local/share/jupyter/templates']"
      }
    }
    /usr/lib/python3.5/site-packages/IPython/nbconvert.py:13: ShimWarning: The `IPython.nbconvert` package has been deprecated. You should import from ipython_nbconvert instead.
      "You should import from ipython_nbconvert instead.", ShimWarning)
    [NbConvertApp] Converting notebook AerialRadiationAlgorithmEvaluation.ipynb to latex
    /tmp/tmp_o4i1qpz/figure.svg:1: parser error : Document is empty
    
    ^
    /tmp/tmp_o4i1qpz/figure.svg:1: parser error : Start tag expected, '<' not found
    
    ^
    /tmp/tmp_o4i1qpz/figure.svg:1: parser error : Document is empty
    
    ^
    /tmp/tmp_o4i1qpz/figure.svg:1: parser error : Start tag expected, '<' not found
     
     ^

    ** (inkscape:16304): WARNING **: Specified document /tmp/tmp_o4i1qpz/figure.svg cannot be opened (does not exist or not a valid SVG file)

It seems as though the svg is not created properly. Same problem occurs with Gadfly.

The julia version is 0.4.1 and Pkg.status() is below. 

```
    14 required packages:
 - Cpp                           0.1.0
 - Debug                         0.1.6
 - ElasticFDA                    0.3.1
 - Gadfly                        0.4.0
 - HypothesisTests               0.2.10
 - IJulia                        1.1.8
 - Immerse                       0.0.9
 - JLD                           0.5.6
 - MAT                           0.2.14
 - Plotly                        0.0.3+             master
 - Plots                         0.5.0
 - PyPlot                        2.1.1
 - Qwt                           0.0.1
 - Winston                       0.11.13
63 additional packages:
 - ArrayViews                    0.6.4
 - BinDeps                       0.3.19
 - Blosc                         0.1.4
 - Cairo                         0.2.31
 - Calculus                      0.1.14
 - Codecs                        0.1.5
 - ColorTypes                    0.2.0
 - Colors                        0.6.0
 - Compat                        0.7.8
 - Compose                       0.4.0
 - Conda                         0.1.8
 - Contour                       0.0.8
 - DataArrays                    0.2.20
 - DataFrames                    0.6.10
 - DataStructures                0.3.13
 - Dates                         0.4.4
 - Dierckx                       0.1.7
 - Distances                     0.2.1
 - Distributions                 0.8.7
 - Docile                        0.5.19
 - DualNumbers                   0.1.5
 - FileIO                        0.0.3
 - FixedPointNumbers             0.1.1
 - ForwardDiff                   0.1.2
 - GZip                          0.2.18
 - Graphics                      0.1.3
 - Grid                          0.4.0
 - Gtk                           0.9.3
 - GtkUtilities                  0.0.7
 - HDF5                          0.5.6
 - HTTPClient                    0.2.0
 - Hexagons                      0.0.4
 - ImmutableArrays               0.0.11
 - IniFile                       0.2.4
 - Iterators                     0.1.9
 - JSON                          0.5.0
 - KernelDensity                 0.1.2
 - LaTeXStrings                  0.1.6
 - LibCURL                       0.2.0
 - Loess                         0.0.5
 - MathProgBase                  0.3.19
 - Measures                      0.0.1
 - NLopt                         0.2.3
 - NaNMath                       0.1.1
 - Nettle                        0.2.0
 - Optim                         0.4.4
 - PDMats                        0.3.6
 - Polynomials                   0.0.4
 - ProgressMeter                 0.2.2
 - PyCall                        1.2.0
 - Reexport                      0.0.3
 - Roots                         0.1.20
 - SHA                           0.1.2
 - Showoff                       0.0.6
 - SortingAlgorithms             0.0.6
 - StatsBase                     0.7.4
 - StatsFuns                     0.2.0
 - Tk                            0.3.6
 - URIParser                     0.1.1
 - WoodburyMatrices              0.1.2
 - ZMQ                           0.3.1
 - Zlib                          0.1.12
```

Also below is the example i am running on my Jupyter Notebook

```julia
using Plots
gadfly()
x = linspace(0,2*pi,101);
y = sin(x)
plot(x,y)
```

Thoughts?

**Comment by jdtuck** [comment]
tbreloff/Plots.jl/issues/72

**Comment by jdtuck** [comment]
tbreloff confirmed he could reproduce tbreloff/Plots.jl/issues/72

**Comment by stevengj** [comment]
I have no idea.  @minrk, any idea of why an SVG plot would display correctly in the notebook, but fail to convert?

@jdtuck, maybe you can post the notebook that is causing problems in a gist?

**Comment by jdtuck** [comment]
Here is the notebook https://gist.github.com/jdtuck/82dd792b9f3d6924228d

**Comment by minrk** [comment]
I'm not sure why the Inkscape conversion would fail, but we can probably try to look at it in isolation without being an nbconvert step.

**Comment by jdtuck** [comment]
It is really inkscape, or the fact the svg is not being created properly?

**Comment by Ken-B** [comment]
Did you try opening inkscape separately? I vaguely remember having encountered the same issue a long time ago and updating inkscape or opening the program and accepting first time terms and conditions or something fixed it. Sorry I can't be more precise.

**Comment by bspeice** [comment]
For what it's worth, I had this same error to realize that inkscape wasn't installed. If anyone comes across this issue, please make sure that inkscape is actually installed.

**Comment by stevengj** [comment]
Might be worth filing an issue with Jupyter to get a more helpful error message that suggests installing and launching Inkscape.

**Comment by bspeice** [comment]
I would like to comment with further information: having installed inkscape, I'm now having the same issue again. Not sure this is Jupyter, since working with matplotlib, etc., is working just fine. However, I would be willing to point the finger at Gadfly given the text of tbreloff/Plots.jl#72

**Comment by stevengj** [comment]
IJulia really has nothing to do with this; all of this export functionality is controlled by Jupyter, and you should file an issue there if you can't get it to work.
