### ISSUE TITLE
Missing stack traces

### ISSUE THREAD

**Issue by cstjean** [JuliaLang/IJulia.jl#393]
Since 0.4 I've had the stack traces frequently missing in IJulia on OSX. I'm sorry that I don't have code to reproduce it, since the issue is fairly random. But I found a work-around today that I thought I'd share: just adding a `print("")` statement in the code that's run brings back the trace (adding the statement to an IJulia cell does not work).

**Comment by JobJob** [comment]
Think this is likely JuliaLang/julia#13947 ?

**Comment by cstjean** [comment]
Ah, very likely. I can reproduce his result. I don't `rethrow` anything, but I have a lot of `try` `finally` blocks.
