### ISSUE TITLE
Impossible to exit processes launched from shell

### ISSUE THREAD

**Issue by LordZorgoth** [JuliaLang/IJulia.jl#396]
In both the notebook and console versions of Julia 0.5-dev (console running off of IPython3 4.0.0), if you attempt to run

;pdflatex foo.tex

on a file with errors, the standard methods of exiting the process don't work; if I type X and hit enter (the usual method of exiting), I just get blank input lines and no output. It seems like IJulia doesn't know how to send input to pdflatex.

This problem is not unique to pdflatex; nano also fails to receive any input. This problem also does not occur with the standard julia command in the terminal.

It is possible to exit these processes using external kill commands.

This is not a problem I've had in IPython.

**Comment by yuyichao** [comment]
How do you send stdin in ipython? (or how do you start a process with stdin connected in a ipython notebook or console with python kernel)?

**Comment by LordZorgoth** [comment]
I don't know. All I know is that in ipython, it works.

**Comment by yuyichao** [comment]
I'm asking how did you start the process in python, i.e. what do you type in python and what do you see.

**Comment by LordZorgoth** [comment]
Both of the following work:

!pdflatex foo.tex

import os
os.system("pdflatex foo.tex")

**Comment by yuyichao** [comment]
And how did you start IPython. I don't think that's working with `ipython console` or `ipython notebook`. It does work for `ipython` just like it works with `julia`.

**Comment by LordZorgoth** [comment]
Yeah, I just used plain ipython.

**Comment by yuyichao** [comment]
That's totally different than. IIUC, `ipython` is still the old improved python repl and doesn't redirect all the IO etc like what you need to when running arbitrary kernels.

Given that this doesn't seems to work with python kernel either and works both for plain `ipython` and `julia` I think it's an IJulia issue and is rather a limitation of the jupyter protocol. (I'm not sure how they could support it though, how do you integrate this in a note book?)

**Comment by stevengj** [comment]
Yes, this is a limitation of Jupyter, which has very limited support for capturing keyboard input.

The analogue of running `ipython` (which doesn't use Jupyter) is running `julia`.
