### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by ajkeller34** [JuliaLang/IJulia.jl#397]
Entering the following into a notebook leads to a large memory leak, which can eventually crash a 32-bit browser tab:

```
using Reactive, Interact, Gadfly
@manipulate for 
    paused=false,
    dt = fpswhen(lift(!, paused), 10)
    plot(x=collect(1:10),y=rand(10))
end
```

The leak happens when the notebook tab is open/front in the browser, using either the most recent IJulia release or master. It appears like a lot of detached DOM trees are responsible.

See some discussion [here](https://groups.google.com/d/msg/julia-users/YJEpl7LnpwQ/AimXPO61BwAJ). The problem can be ameliorated by installing Patchwork.jl but fundamentally I don't feel this bug has been addressed. If this is not an IJulia problem, that would also be great to know.

My IJulia package was built against Python 2.7.10, using jupyter 4.0.6, Google Chrome (32-bit) 47.0.2526.73 m on Windows 10 Pro.

```
Julia Version 0.4.2
Commit bb73f34 (2015-12-06 21:47 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by stevengj** [comment]
This sounds like an Interact problem, or possibly Jupyter.  Not really IJulia per se.
