### ISSUE TITLE
IJulia is broken

### ISSUE THREAD

**Issue by aragnon** [JuliaLang/IJulia.jl#398]
Hi, it appears that running `Pkg.add("IJulia")` is broken. Please fix it or stop advertising this module. 

It is also ridiculous that it is a WARNING that it had build errors. 

Platform Ubuntu 14.04/x86-64, Julia as specified on the Julia homepage. 

I can't say I am in any way enthusiastic about something which does not work. Let alone to use it as a replacement.

Also, your whole installation procedure (using Pkg.add to install system level tools) is amateuristic. Please learn a thing or two about package management before inventing another ridiculously stupid package management system next time. 

```
WARNING: Module BinDeps uuid did not match cache file
===============================[ ERROR: IJulia ]================================

LoadError: __precompile__(true) but require failed to create a precompiled cache file
while loading /root/.julia/v0.4/IJulia/deps/build.jl, in expression starting on line 2

================================================================================

=========================================================[ BUILD ERRORS ]==========================================================

WARNING: IJulia had build errors.

 - packages with build errors remain installed in /root/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("IJulia")`
 - build a single package by running its `deps/build.jl` script

===================================================================================================================================
INFO: Package database updated
```

**Comment by aragnon** [comment]
Even worse, doing `Pkg.add("IJulia")`afterwards says `"INFO: Nothing to be done"`. Really, fix your shit, please. For now, I will just not care one bit about julia, other than the entertainment value of how bad it is.

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/13200 also note that the error didn't come from BinDeps. You should remove IJulia and try again.

**Comment by aragnon** [comment]
@yuyichao Trying again is a ridiculous solution. I can't stop laughing at how idiotic that suggestion is.

**Comment by aragnon** [comment]
It would be valid to say that `Pkg.add("IJulia");Pkg.rm("IJulia");Pkg.add("IJulia");` are the new official installation instructions, but this won't stop other people laughing either.

**Comment by aragnon** [comment]
```
Pkg.add("IJulia")
INFO: Installing BinDeps v0.3.19
INFO: Installing Compat v0.7.8
INFO: Installing Conda v0.1.8
INFO: Installing IJulia v1.1.8
INFO: Installing JSON v0.5.0
INFO: Installing Nettle v0.2.0
INFO: Installing SHA v0.1.2
INFO: Installing URIParser v0.1.1
INFO: Installing ZMQ v0.3.1
INFO: Building Nettle
INFO: Building ZMQ
INFO: Building IJulia
INFO: Found Jupyter version 4.0.6: jupyter
Writing IJulia kernelspec to /root/.julia/v0.4/IJulia/deps/julia-0.4/kernel.json ...
Installing julia kernelspec julia-0.4
[InstallKernelSpec] Installed kernelspec julia-0.4 in /root/.local/share/jupyter/kernels/julia-0.4
```
After reloading a page, Julia is not actually added as a kernel in JupyterHub, so I suspect there is something else still broken.

**Comment by yuyichao** [comment]
> Trying again is a ridiculous solution.

I totally agree and I think that should be fixed.

**Comment by aragnon** [comment]
@yuyichao OK, now Julia 0.4.1 is listed, except it crashes instantly.

**Comment by yuyichao** [comment]
https://github.com/JuliaLang/IJulia.jl#debugging-ijulia-problems

**Comment by aragnon** [comment]
```
If IJulia is crashing (e.g. it gives you a "kernel appears to have died" message), you can modify it to print more descriptive error messages to the terminal: edit your IJulia/src/IJulia.jl file (in your .julia package directory) to change the line verbose = false at the top to verbose = true and const capture_stderr = true to const capture_stderr = false. Then restart the kernel or open a new notebook and look for the error message when IJulia dies
```
"look for the error message". And where would that be? I don't see anything remotely resembling a useful error message.

**Comment by aragnon** [comment]
OK, so, I found the error message:
```
ERROR: could not open file /root/.julia/v0.4/IJulia/src/kernel.jl
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
```

**Comment by aragnon** [comment]
I can `cat` the contents of that file as the user running the server, so... now we are at the point that my shell can do something Julia cannot. Excellent!

**Comment by yuyichao** [comment]
In that case, what's the permission of `/root/.julia/v0.4/IJulia/src/kernel.jl` and do you see the same error when running `julia /root/.julia/v0.4/IJulia/src/kernel.jl` ?

**Comment by aragnon** [comment]
@yuyichao -rw-r--r-- 1 root root, the second command works fine. The server also runs as root.

**Comment by ssfrr** [comment]
@aragnon: please reference the [Julia Community Standards](http://julialang.org/community/standards/). 

I understand that problems are frustrating, but your language and general rudeness in this issue is unproductive and not acceptable in the Julia Community. I assure you that @yuyichao is very kindly helping you in spite of your vitriol, and not because of it. Turning around and calling suggestions "idiotic" is certainly not very motivating for others who might otherwise want to help.

If you want help and to offer constructive criticism that's great and very welcome, but in return please be respectful in the future.

**Comment by aragnon** [comment]
@yuyichao OK, I fixed it myself already. It basically just comes down that the "kernel" runs as whatever user is logged in, which is not root. So, it's just a matter of installing a kernel in a system wide fashion. The error reporting could be orders of magnitude better.

**Comment by aragnon** [comment]
@ssfrr You don't get respect for delivering stuff which does not work, sorry. That's not how it works.

**Comment by aragnon** [comment]
@ssfrr And, to add to that, I intensely hate people who point at "community standards".

**Comment by yuyichao** [comment]
> the "kernel" runs as whatever user is logged in, which is not root

I suppose this is due to jupyter hub and that's a very reasonable thing to do.

If you want to install IJulia system wide, you can have a look at my PKGBUILD for ArchLinux at https://github.com/yuyichao/arch-pkg/blob/master/pkg/all/ijulia-git/PKGBUILD . I agree it's a little twisted because julia dosesn't have a super good out-of-the-box support for system wise package installation yet.

**Comment by aragnon** [comment]
@yuyichao Yeah, I understand the situation, so thanks for the helping hand, but I can probably fix the rest myself.

**Comment by stevengj** [comment]
@aragnon, you're asking people for free technical support; you might want to re-consider your attitude.

**Comment by aragnon** [comment]
I think you are the one who does not get who is providing a free service to who.

**Comment by simonster** [comment]
There is no possibility of positive future interaction in this issue, so let's just leave things here.
