### ISSUE TITLE
truncate output with show macro

### ISSUE THREAD

**Issue by nassarhuda** [JuliaLang/IJulia.jl#400]
Is there any straight forward way to truncate the output with show?

After browsing through some of the issues, it looks like this has to do with the output size yet I haven't read anything related to truncating the output. When it tries to output all the data this breaks my IJulia as well.

Thank you

**Comment by stevengj** [comment]
`@show` displays everything by design.... if you want to display truncated output, use `display(x)` or just put the thing you want to output as the last expression in the cell.

**Comment by stevengj** [comment]
Closing as using `limit=true` with `@show` would involve a change in `julia`, not IJulia.
