### ISSUE TITLE
Rename to Jupyter.jl?

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/IJulia.jl#401]
I recently taught a course on Julia, and one of the comments I received was along the lines of "the instructions said to do `Pkg.add("IJulia")`, but this actually installed a program called Jupyter".

I know that IJulia predates the IPython -> Jupyter rename, but this seems like a reasonable point, especially since "IJulia" isn't used anywhere else: e.g. when I'm using a notebook, I just see the Jupyter banner and "Julia 0.4.2" on the menu bar.

**Comment by yuyichao** [comment]
The python kernel of jupyter is still called ipython so I think the julia kernel of jupyter should be called ijulia.

**Comment by simonbyrne** [comment]
But the user doesn't see this: the names under the Kernel menu are just "Python x", "Julia y.y.y" etc.

**Comment by stevengj** [comment]
IJulia is intended to mirror IPython, which still exists.  See also IHaskell.  Jupyter is the back-end and the protocol, and IXXX is the kernel for XXX.

**Comment by andreasnoack** [comment]
Just had the same thought as @simonbyrne. I accept the technical correctness of the `IJulia` name but from a user perspective, I think `Jupyter.jl` would be more recognizable. I don't think it is a problem that the IJulia kernel would reside inside a Juputer.jl package. Developers will know how to find it.

**Comment by stevengj** [comment]
I don't think we're likely to rename.
