### ISSUE TITLE
Controlling the text representation of arrays

### ISSUE THREAD

**Issue by cstjean** [JuliaLang/IJulia.jl#402]
I have some large objects inside Arrays / DataFrames. I'm interested in either displaying them more concisely, or not displaying them at all (because accidentally printing a big dataframe tends to kill IJulia - any solution to that?)

To control how the objects show up, I've tried:
```julia
type Foo
    x
    y
end

function Base.show(io::IO, x::Foo)
    println(io, "x ---> $(x.x)")
    println(io, "y ---> $(x.y)")
end

function Base.writemime(st::IO, ty::MIME"text/plain", x::Foo)
    write(st, "some_foo")
end

[Foo(1,2), Foo(1,2)]
```
but while the Julia REPL calls the `show` method above, IJulia doesn't, and displays instead: 
```
2-element Array{Foo,1}:
 Foo(1,2)
 Foo(1,2)
```
Is there any way to control what gets displayed there? I could presumably define `show(... x::Array{Foo, 1})` but that will be tedious to define for all composite objects, and I don't see how it could work with DataFrames.

**Comment by stevengj** [comment]
Works for me:
![image](https://cloud.githubusercontent.com/assets/2913679/12722186/bd0677a2-c8d1-11e5-9b23-5fd00a6c8be0.png)

**Comment by cstjean** [comment]
Err, it now seems to work for me too. I don't remember what I did... Thank you for checking, and sorry for the noise!
