### ISSUE TITLE
IJulia build fails when g++ not installed?

### ISSUE THREAD

**Issue by anshuljoshi** [JuliaLang/IJulia.jl#403]
Whenever I have installed "IJulia" on Linux, it's build fails every time and I could see in the error that it couldn't find the necessary compilers. Installing g++ resolves that (gcc was already installed).
Is that a known issue?
Can we have in in the documentation so that people don't face any such problem in future on Linux?

**Comment by stevengj** [comment]
Probably the build failure is for one of IJulia's dependencies, e.g. Nettle?

**Comment by anshuljoshi** [comment]
yes actually, it is for many dependencies for IJulia.
