### ISSUE TITLE
LoadError: None of the selected providers can install dependency nettle.

### ISSUE THREAD

**Issue by FrankWessels** [JuliaLang/IJulia.jl#405]
I just seem to not be able to instal IJulia with Pkg.add("IJulia"). If I run a notebook the kernel dies.

![ijulia_nettle_error](https://cloud.githubusercontent.com/assets/15737359/12914772/aee00908-cf26-11e5-867a-bc684701720c.png)

**Comment by stevengj** [comment]
@FrankWessels, you should report this problem at [Nettle.jl](https://github.com/staticfloat/Nettle.jl).   Make sure you indicate what Windows version you are using.
