### ISSUE TITLE
The %%javascript works with Python Kernel but not Julia

### ISSUE THREAD

**Issue by ahwillia** [JuliaLang/IJulia.jl#408]
Adding a `%%javascript` magic at the top of a cell causes the cell to execute javascript code with my Python kernel. But when running a Julia kernel: 

```
%%javascript
console.log("hello world")
```

Produces:

```
LoadError: syntax: "%" is not a unary operator
while loading In[2], in expression starting on line 1
```

I'm running Julia 0.4.2. This is my Jupyter version:

```
Python 2.7.11 |Anaconda 2.5.0 (64-bit)| (default, Dec  6 2015, 18:08:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
```

**Comment by stevengj** [comment]
Magics are an IPython thing, not a Jupyter thing.  In general, we haven't found much need for them in IJulia — see #12.

For example, in this particular case you can just output HTML with a `<script>` tag:
```jl
HTML("""<script>
console.log("hello world")
</script>""")
```
If there is a strong need for a more compact syntax for this, we could always define a [new string type](http://docs.julialang.org/en/latest/manual/metaprogramming/#non-standard-string-literals) in Julia:
```
macro javascript_str(s)
    HTML("<script>$s</script>")
end

javascript"""
console.log("hello world")
"""
```
but it's not clear that there is much need for this.

**Comment by ahwillia** [comment]
Got it -- thanks!

**Comment by stevengj** [comment]
What is Javascript magic in IPython useful for in practice?

**Comment by ahwillia** [comment]
Syntax highlighting? Less clutter on the page than having `<script> ... </script>` (though the macro idea above is a nice fix). It would also be nice for people migrating from using Python to Julia in Jupyter notebooks... Maybe some documentation outlining the Julia alternatives to magics would be sufficient.

Agree that these points are on the aesthetic end of the spectrum.

**Comment by StefanKarpinski** [comment]
I think we should reconsider this: I've heard from multiple sources that lack of standard Jupyter magicks has been a stumbling block for them when using IJulia. Sure, there are other ways to do it with normal Julia syntax, but the magicks are a standard way to do these things in Jupyter, regardless of kernel, and we should probably conform to that standard. Having a `%` at the start of a line is incredibly rare in Julia, although its technically valid syntax to write `%(a,b)`.

**Comment by stevengj** [comment]
@StefanKarpinski, I'm strongly opposed to encouraging people to use a syntax that will *only* ever work in a Jupyter cell, rather than a syntax that will work no matter where the code is.  With a magic, just copying and pasting it into a file and then running it *in the notebook* with `include` will fail.

Moreover, many of the IPython magics could be sensible operations outside of IPython, but by making them magics you make it impossible to use outside of Jupyter.

**Comment by StefanKarpinski** [comment]
I'm sympathetic to that, but it seems like Jupyter users find this lack of support for magicks pretty annoying. I think a common workflow is: 1) lookup how to do something in Jupyter, 2) try it in Julia, 3) find that it doesn't work, 4) start looking for something else, 5) give up.

**Comment by stevengj** [comment]
Maybe we should just support the `%lsmagics` command, and use it to explain the equivalent of IPython magics in Julia.

**Comment by johnmyleswhite** [comment]
Perhaps we could have an intermediate solution: if you try to execute a magic, it doesn't work -- but it does issue a warning message with full details about how to achieve the equivalent result in portable Julia.

**Comment by stevengj** [comment]
@johnmyleswhite, that seems reasonable too.

**Comment by madeleineudell** [comment]
I just entered into the workflow @StefanKarpinski describes today. I'd suggest that a fix, at least to the documentation, is called for (though personally I'd like to see the magics implemented, even if they're less portable). 

If we stick to a documentation+ fix, I'd second both the suggestion of @stevenj and @johnmyleswhite. One nice (even, magical) way to implement @johnmyleswhite's suggestion might be to have magics output the correct, Julian code that would produce the same result as what the user was trying to do with magics. 

If the package does not implement magics, I'd also suggest dropping the phrase "and magics" from the package description on GitHub, and adding a description of how to access equivalent functionality to the README.

**Comment by StefanKarpinski** [comment]
Personally, I don't really believe that having non-standard code work differently in different interactive environments is really that big of a deal, so I'm in favor of just implementing support for standard Jupyter magicks.

**Comment by johnmyleswhite** [comment]
FWIW, I actually agree with @stevengj on this front: from experience with similar solutions in other systems, I am pretty confident that if the magics are implemented in IJulia, you will start to see monthly complaints on the main Julia repo that the Julia REPL is "totally broken. It can't even run this simple code that works in IJulia." That might still happen with an error message, but discouraging people from using the magics should be the long-term goal unless there's a plan to make them built-in for all possible Julia environments.

**Comment by stevengj** [comment]
Okay, I've pushed a couple of commits that recognize if the user tried to enter IPython-like magics, and print out help and a Julia analogue if possible.  See https://github.com/JuliaLang/IJulia.jl/blob/master/src/magics.jl

**Comment by stevengj** [comment]
(Looking at the help convinced me that we would be completely crazy to implement many of them, e.g. do we really want users to type `%pwd` instead of `pwd()`?)

**Comment by stevengj** [comment]
Also, some of the magics, like `%matplotlib`, would be impossible to implement without pulling in unacceptable dependencies, in this case PyPlot.   Instead, the help can just point to the relevant package(s).
