### ISSUE TITLE
MathJax doesn't render higher order roots 

### ISSUE THREAD

**Issue by SoYman** [JuliaLang/IJulia.jl#409]
I'm not sure if I this is specific to IJulia or more generally Jupyter or MathJax but when the HTML-CSS renderer tries to display a cube root, for example, the output is simply: \root{3}{x} with no pretty printing.

**Comment by stevengj** [comment]
I don't think this is IJulia specific.   See e.g. ipython/ipython#1359 ... but it looks like `\sqrt[3]{x}` (which is the standard LaTeX syntax for this) works
