### ISSUE TITLE
Indent change doesn't works

### ISSUE THREAD

**Issue by apetrushin** [JuliaLang/IJulia.jl#411]
The default indent is 4 spaces, in Jupyther it's possible to change it to 2 space with the following command:

```
var cell = Jupyter.notebook.get_selected_cell();
var config = cell.config;
var patch = {
      CodeCell:{
        cm_config:{indentUnit:2}
      }
    }
config.update(patch)
```

It changes indentation to 2 space, it works for python notebook, but not for julia, in case of julia the tab size changed to 2 but auto-indent still 4.

**Comment by stevengj** [comment]
I've never looked at this feature; how did you even do it in Julia?  Via PyCall?

**Comment by apetrushin** [comment]
Nope, it's JavaScript, you need to open the developer console in Jupyter paste this code there and hit "Enter". The Jupyter then magically updates its own setting :).

**Comment by luizParreira** [comment]
Would be great to have this working, IMHO Julia looks much better on a 2 space indentation. Anyone have any idea on what it would take to implement this?

**Comment by stevengj** [comment]
If you have to [open up the JavaScript console](http://jupyter-notebook.readthedocs.io/en/latest/frontend_config.html) for every notebook where you want to change the indentation setting, it hardly seems worth the trouble to support — very few users would use it.

**Comment by cossio** [comment]
Is there a way to set this setting in a config file or something?

**Comment by stevengj** [comment]
Closing as code formatting is a notebook issue, not an IJulia issue.
