### ISSUE TITLE
Matplotlib animation displays extra plot

### ISSUE THREAD

**Issue by ahwillia** [JuliaLang/IJulia.jl#414]
This is driving me a bit nuts. I'm using the following code to produce a simple animation. It works in the sense that the movie gets displayed but I also get an extra plot in my notebook, showing one of the frames of the movie. 

Using `IJulia.clear_output()` only deletes the movie I want! The bonus frame stays around.

My guess is that this has something to do with `PyCall` (the equivalent example in a Jupyter notebook with a Python kernel works fine, so I'm convinced this is specific to Julia)

**Code:**

```julia
using PyCall
import IJulia
@pyimport matplotlib.animation as animation
using PyPlot

function showanim(filename)
    base64_video = base64encode(open(readbytes, filename))
    display("text/html", """<video controls src="data:video/x-m4v;base64,$base64_video">""")
end

A = randn(20,20,20)

fig = figure(figsize=(2,2))

function make_frame(i)
    imshow(A[:,:,i+1],interpolation="none")
end

anim = animation.FuncAnimation(fig, make_frame, frames=size(A,3), interval=20)
anim[:save]("test2.mp4", bitrate=-1, extra_args=["-vcodec", "libx264", "-pix_fmt", "yuv420p"]);
showanim("test2.mp4");
```

**Screenshot:**

<img width="576" alt="screen shot 2016-04-19 at 3 23 36 pm" src="https://cloud.githubusercontent.com/assets/636625/14657557/7cc63d30-0643-11e6-95f0-4697bd4276f1.png">

**Comment by JobJob** [comment]
Hi, it's a bit kludgy, but I tried adding `empty!(IJulia.displayqueue)` just before the `showanim` and that works. 

@stevengj should `IJulia.clear_output` possibly include `empty!(displayqueue)`? I have limited experience with `clear_output` so I'm not sure, but it helps for this particular case.

**Comment by ahwillia** [comment]
Thanks, you are a hero. As a workaround I'll put `empty!(IJulia.displayqueue)` at the top of the `showanim` function.

Should I close this, or leave open in hopes of a less "kludgy" solution?

**Comment by JobJob** [comment]
Good. I think we can leave it open and wait for @stevengj to weigh in.

**Comment by stevengj** [comment]
Emptying the displayqueue on `clear_output` seems reasonable.

As an alternative, you could also do
```jl
withfig(fig) do
    anim = animation.FuncAnimation(fig, make_frame, frames=size(A,3), interval=20)
    anim[:save]("test2.mp4", bitrate=-1, extra_args=["-vcodec", "libx264", "-pix_fmt", "yuv420p"])
end
```
The `withfig` function was designed for using PyPlot with Interact.jl animations, and what it does is to eliminate side effects from plotting (e.g. `imshow` will no longer push a figure to display).
