### ISSUE TITLE
Julia PyPlot: plot 3D surface with as face colors the norm of surface gradient

### ISSUE THREAD

**Issue by hiemstar** [JuliaLang/IJulia.jl#418]
Does anyone know how to plot a 3D surface with Julia's Pyplot with e.g the norm of the surface-gradient as the face color?

Similar to this topic for Python: http://stackoverflow.com/questions/6539944/color-matplotlib-plot-surface-command-with-surface-gradient

**Comment by stevengj** [comment]
You do it the same way as in the Matplotlib example you cite, with some translations of the syntax.
```jl
using PyPlot
x = -5:0.25:5
y = x'
R = sqrt(x.^2 .+ y.^2)
Z = sin(R)
surf(x,y,Z, facecolors=get_cmap("jet")(R/maximum(R)), linewidth=0, antialiased=false, shade=false)
```
Here, I colored the faces according to the radius `R` rather than the norm of the gradient.   Julia doesn't have a built-in `gradient` function for multidimensional arrays at the moment (JuliaLang/julia#16113).

In general, you should ask for help on the [julia-users](https://groups.google.com/forum/#!forum/julia-users) mailing list and similar forums, not in Github issues.  In any case, this is a PyPlot question, not an IJulia question.

**Comment by hiemstar** [comment]
Thanks. I still get the following error though. Any idea where that comes from?

using PyPlot
​
x = -5:0.25:5
y = x'
R = sqrt(x.^2 .+ y.^2)
Z = sin(R)
surf(x,y,Z, facecolors=get_cmap("jet")(R/maximum(R)), linewidth=0, antialiased=false, shade=false)
LoadError: MethodError: `call` has no method matching call(::PyPlot.ColorMap, ::Array{Float64,2})
Closest candidates are:
  BoundsError()
  BoundsError(!Matched::Any...)
  DivideError()
  ...
while loading In[2], in expression starting on line 7

**Comment by hiemstar** [comment]
Figured it out. We need the .o after the get_cmap function. 

using PyPlot
​
x = -5:0.25:5
y = x'
R = sqrt(x.^2 .+ y.^2)
Z = sin(R)
surf(x,y,Z, facecolors=get_cmap("jet").o(R/maximum(R)), linewidth=0, antialiased=false, shade=false)

**Comment by stevengj** [comment]
Oh, the `.o` is not needed in the latest PyPlot master; I really need to tag a new version.

**Comment by likefrankie** [comment]
@stevengj - The code below should work if "sqrt" is changed to "sqrt**.**" 

> You do it much the same way as in the Matplotlib example you cite, albeit with some translations of the syntax.
> using PyPlot
> x = -5:0.25:5
> y = x'
> R = sqrt(x.^2 .+ y.^2)
> Z = sin(R)
> surf(x,y,Z, facecolors=get_cmap("jet")(R/maximum(R)), linewidth=0, antialiased=false, shade=false)
> Here, I colored the faces according to the radius R rather than the norm of the gradient.   Julia doesn't have a built-in gradient function for multidimensional arrays at the moment (JuliaLang/julia#16113).
> In general, you should ask for help on the julia-users mailing list and similar forums, not in Github issues.  In any case, this is a PyPlot question, not an IJulia question.

**Comment by stevengj** [comment]
@likefrankie, note that the code posted above was in 2016, for an earlier version of Julia.  Indeed, you need `sqrt.(x)` etcetera these days.
