### ISSUE TITLE
Inclusion of IJulia notebook into another IJulia notebook

### ISSUE THREAD

**Issue by Teo-ShaoWei** [JuliaLang/IJulia.jl#419]
I would like to get a sense of whether we are interested in such a functionality in IJulia...

I am interested to write a function `include_notebook` that can be run in an IJulia notebook, which takes in a `path\to\<target>.ipynb`, and another optional symbol for type of import (and possibly more optional/keyword arguments).

If type is `:module`, which is also the default, the code , that will take all the source code in `<target>.ipynb`, concatenate them and treat them as definition for the module `module_name`. By default, module name will be `IJ_<target>`.

If type is `:function`, then code will come back as a function with no input argument, with default name `f_<target>`. The output of the function will thus be the last line of code in `<target>.ipynb` due to how Julia is structured.

If type is `:script`, the source code will be concatenated and thrown in "as is". This ensures a flat structure in the notebook that calls the function.

This way, we can write our source code in separate IJulia notebooks. I find this functionality very useful for me. Has it been developed in IJulia? Or is there no interest for such funtionality? I can get to writing the function and send a pull request if this function can be included into IJulia.

**Comment by stevengj** [comment]
This is already implemented: https://github.com/stevengj/NBInclude.jl

**Comment by Teo-ShaoWei** [comment]
Ah, noted with thanks @stevengj

Yes the remaining two are idiomatic and I was thinking of implementing it as per what you mentioned.
