### ISSUE TITLE
When is on_msg called

### ISSUE THREAD

**Issue by spencerlyon2** [JuliaLang/IJulia.jl#420]
I've been working on getting two way javascript <==> julia communication happening in the notebook. I have a great solution for the julia ==> javascript part of this and am struggling a bit on getting data back from javascript into Julia.

spencerlyon2/PlotlyJS.jl#37 explains what's happening in more detail, but I'll summarize what I think the issue is:

- When my package is loaded in the notebook, it evaluates a javascript file to define two custom targets. One evaluates some javascript code Julia sends over and the other evaluates it and returns the output back to Julia. This part of the setup is working as I can `console.log` the code and return value in those javascript target functions and see it in my javascript console.
- On the Julia side, when I want to get a return value back from javascript, I create an `IJulia.Comm` object and fill its `on_msg` field with code that handles the data Julia is supposed to receive from javascript. To do this I simply call `comm = Comm(:my_target_that_returns_stuff)` and then set `comm.on_msg = my_julia_function_that_receives`.
- I've put tests in the `on_msg` function that will print to the screen or create files on my computer to let me know that `on_msg` is actually being called. As far as I can tell it never is.

So my main question is, when I have a `Comm`, is there anything I need to do for `on_msg` to be called beyond simply setting `on_msg` to be the function I want? Perhaps I have to register the Comm or provide some special data in the `comm.send` call on the javascript side in order to trigger IJulia to actually call my `on_msg`.

Thanks!

**Comment by stevengj** [comment]
@shashi, you are the expert on this part of the code.

**Comment by shashi** [comment]
This works for me...

In JS console, set up a "comm_target"
```
c = IPython.notebook.kernel.comm_manager.register_target("test", function (x,y,z) {
    console.log(x,y,z);
    window.comm=x // we will use this later
})
```
In the notebook run:
```
using IJulia.CommManager
c = Comm(:test)
c.on_msg = (x) -> open(io->write(io, "got the message $x"), "/tmp/log", "a")

```

Now in JS console, run:

```
window.comm.send("msg")
```

results in `/tmp/log` being written:

```
got the message IPython Msg [ idents 68D931C8B13A49BEA5DF36607334D0CA ] {
  parent_header = Dict{AbstractString,Any}(),
  header = Dict{AbstractString,Any}("msg_id"=>"30B1308328A8406182960C1E45111BB4","msg_type"=>"comm_msg","username"=>"username","version"=>"5.0","session"=>"68D931C8B13A49BEA5DF36607334D0CA"),
  metadata = Dict{AbstractString,Any}(),
  content = Dict{AbstractString,Any}("comm_id"=>"5cc67c98-aeac-4daf-a8e5-a9c6a5363b50","data"=>"msg")
}
```

These steps need to happen roughly in the above order... If it doesn't work for you, it might be an issue specific to your version of Jupyter / OS...

**Comment by spencerlyon2** [comment]
Hey @shashi thanks for following up here.

What I want to do is register a target that will run some javascript code I send in a msg from Julia, and then `send` the return value of that code back to Julia.

I haven't seen any examples where a registered function also sends a message (this is all on the javascript side). Do you know of there is anything special that I need to do to make this happen?

One thing I can think of is that perhaps I can't send from the callback I define for my comm's `register_target`  because within that callback the comm isn't yet fully initialized. Is this possible?

**Comment by shashi** [comment]
I guess the problem with doing `comm.send` inside `register_target` callback is that, `register_target` is called when a Comm object is constructed, at which point you still haven't set a on_msg callback on the Julia side...

creating the comm with `Comm(:test2, string(Base.Random.uuid4()), true, msg -> open(x->write(x, "got $msg"), "/tmp/log", "a"))` works as it sets the callback at construction time.

Maybe the args should have been kwargs so that you need only to set `on_msg` keyword arg...

**Comment by spencerlyon2** [comment]
Hmm I think it should still be ok in my example, here's roughly what I'm doing.

in the javascript:

```javascript
        comm_manager.register_target("plotlyjs_return", function (comm) {
            comm.on_msg(function (msg) {
                // Call the code in the message
                val = eval(msg.content.data.code);

                // resolve any promises so we get a raw value
                val = resolve_promises(comm, val);

                // Send the value back to Julia
                comm.send({action: "plotlyjs_ret_val", ret: val});

                // Clean up
                delete msg.content.data.code;  // clean up
                delete val;
            });
	    });
```

Then in the Julia

```julia
    const _ijulia_return_comms = Dict{Base.Random.UUID,Comm}()
    function get_comm(jd::JupyterDisplay)
        if haskey(_ijulia_return_comms, jd.divid)
            return _ijulia_return_comms[jd.divid]
        else
            comm = Comm(:plotlyjs_return, string(jd.divid))  # jd.divid is a Base.Random.UUID

            function handle_comm_msg(msg)
                open(joinpath(ENV["HOME"], "from_plotly_comm.txt"), "w") do f
                    print(f, "I am in on_msg from plotly")
                end
                if haskey(msg.content, "data")
                    action = get(msg.content["data"], "action", "")
                    if action == "plotlyjs_ret_val"
                        val = msg.content["data"]["ret"]
                        # now that we have the value, we can notify waiting
                        # tasks that the return value is ready
                        notify(jd.cond, val)
                    end
                end
            end

            comm.on_msg = handle_comm_msg

            _ijulia_return_comms[jd.divid] = comm
            return comm
        end
    end
````

Then when I actually use it I do something like this:

```julia
comm = get_comm(jd)
send_comm(comm, Dict("code" => "some javascript code")
```


To me this seems like it should work because once `get_comm` is called, the comm should be totally initialized and its `on_msg` should be ready to go. So, when I finally get to `send_comm` I believe everything should be ready. Does that sound right, or is there something I'm missing?

**Comment by shashi** [comment]
Your set up works for me on 0.5-dev Jupyter 4.2.0 (I'm doing the JS set-up in the js console)... I created a `Displ` type with Condition and UUID. I get the file `from_plotly_comm.txt` written in my HOME directory.

One pitfall is initially calling the `register_target`, I had to use this trick to make it robust: https://github.com/JuliaLang/Interact.jl/blob/master/src/IJulia/ijulia.js#L83-L88 have you done this?

**Comment by spencerlyon2** [comment]
Thanks @shashi  I did borrow your trick for making `register_target` more robust -- thanks for that.

I updated my jupyter to 4.2.0 and I too get that file written in my HOME. 

I'm still not getting the `wait` and `notify` on my `Condition` to work, but that's a separate issue. We can probably close this and say it was resolved by updating jupyter.

Did you say that you managed to get the condition/wait/notify working?

**Comment by shashi** [comment]
Cool! What version were you using?

I doubt something like resolve_promises is possible in JavaScript.

You'll need something like,

```
isPrimise(ret) ? ret.then(function (val) { comm.send(val); }) :
comm.send(val)
```

**Comment by spencerlyon2** [comment]
I think I was using jupyter 4.1.0.

Ok so I now know for certain that I am sending the message from js to Julia AND that it the msg has the data I want (yay! Progress). However, I can't seem to get the `notify` and `wait` working on the condition. Did you ever get that working properly? 

I'm going to close the issue as `on_msg` seems to work as expected on jupyter 4.1.0, but any tips on the async stuff on the julia side would be great.

**Comment by shashi** [comment]
You should take a look at how Blink does it if you haven't already. https://github.com/JunoLab/Blink.jl/blob/master/res/blink.js#L31-L46
