### ISSUE TITLE
How to interact with Jupyter from REPL?

### ISSUE THREAD

**Issue by EricForgy** [JuliaLang/IJulia.jl#423]
Hi,

For some experiments, I'd like to be able to interact with Jupyter via IJulia from the REPL. Is this possible?

By the way, while trying a few things, I notice that this line:

https://github.com/JuliaLang/IJulia.jl/blob/master/src/IJulia.jl#L198

detaches the process even if `detached = false`. I'm probably misunderstanding something, but is that the intended behavior?

Best regards,
Eric

**Comment by EricForgy** [comment]
No matter what I've tried so far, when I run

~~~julia
julia> using IJulia
~~~

and launch a notebook, there is always a second Julia process running in the background. I suppose this Julia process is also `using IJulia`, inits it and creates all the sockets I want to hook into. How can I get hold of these sockets (and other variables) from the REPL?

Thanks.

**Comment by stevengj** [comment]
@EricForgy, the process is spawned detached regardless, but if `detached=false` then Julia blocks on that process and kills it when it is done.

**Comment by stevengj** [comment]
The way Jupyter works is that every time you open a new notebook it spawns a new kernel process, in this case a new Julia process.  You can't access the variables of that process from another Julia process.

**Comment by EricForgy** [comment]
Thanks @stevengj . This is a very cool package and I'm learning a lot by reading through it. I almost have a solution that does what I want and will report back here when it is working :pray:
