### ISSUE TITLE
WARNING: Base.ASCIIString is deprecated, use String instead.

### ISSUE THREAD

**Issue by Shaun1818** [JuliaLang/IJulia.jl#424]
When I run a code block i get the following error 
![image](https://cloud.githubusercontent.com/assets/19259454/15387387/f9116700-1e00-11e6-85a0-34300138c038.png)

Any one had the same problem?

**Comment by yuyichao** [comment]
Already fixed on master

**Comment by yuyichao** [comment]
And these are warnings not errors.
