### ISSUE TITLE
writemime deprecation warning

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/IJulia.jl#426]
With very recent Julia 0.5 master and latest IJulia master:

```
WARNING: Base.writemime is deprecated.
  likely near /Users/dpsanders/.julia/v0.5/IJulia/src/kernel.jl:31
```

The only occurrence of `writemime` seems to be in [this](https://github.com/JuliaLang/IJulia.jl/blob/fcbcef24d2b022464092c1d0f99555edc27973a0/src/execute_request.jl#L25) function. Unfortunately I haven't been keeping track of those changes so don't know how to fix it.

**Comment by stevengj** [comment]
Waiting for JuliaLang/Compat.jl#219 before we can do anything.

**Comment by dpsanders** [comment]
Ah OK, thanks.

**Comment by amitmurthy** [comment]
https://github.com/JuliaLang/Compat.jl/pull/219 is now closed.

**Comment by amitmurthy** [comment]
Would be great to have this fixed before JuliaCon. Can then use the latest master with IJulia.

**Comment by wookay** [comment]
I did pull request #434

**Comment by alanedelman** [comment]
+1 for fix

**Comment by jonalm** [comment]
I recently upgraded to julia 0.5.0 and I get this error with jupyter notebook (using IJulia 1.2.0 and PyPlot 2.2.1 on OSX).

`using PyPlot`
gives:
/Users/jonalm/anaconda2/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
WARNING: Base.writemime is deprecated.
  likely near /Users/jonalm/.julia/v0.5/IJulia/src/kernel.jl:35
WARNING: Base.writemime is deprecated.
  likely near /Users/jonalm/.julia/v0.5/IJulia/src/kernel.jl:35
WARNING: Base.writemime is deprecated.
  likely near /Users/jonalm/.julia/v0.5/IJulia/src/kernel.jl:35

Shouldn't the merge have fixed the issue, or am I missing something?

**Comment by stevengj** [comment]
This was fixed by #434 some time ago.

**Comment by jonalm** [comment]
Thanks for the pointer @stevengj. It took me some time figure out that I needed a Pkg.checkout rather than an Pkg.update, but it's working now.

**Comment by stevengj** [comment]
You needed a `Pkg.checkout("IJulia")`?  I thought the `writemime` fix was already tagged.   In any case, I'll hopefully be tagging a new version soon.

**Comment by jonalm** [comment]
No. It turns out to be an PyPlot issue. I checked out both IJulia and PyPlot first, but I only need checkout PyPlot to make it work. Using the tagged release of PyPlot (2.2.1) gives for some reason the warning "....likely near /Users/jonalm/.julia/v0.5/IJulia/src/kernel.jl:35".

**Comment by GeoHubX** [comment]
I was the source of #474. I also had to checkout PyCall to 1.7.2+ to resolve this issue after the Julia 0.5.0 update.
