### ISSUE TITLE
delayed output in Julia 0.3

### ISSUE THREAD

**Issue by DalimilMazac** [JuliaLang/IJulia.jl#429]
When running a Julia 0.3.12 kernel on Jupyter 4.1.1, the output of any cell is not shown dynamically, but only when the whole cell has finished evaluating. For example
`print("a"); sleep(3);print("b")` would display "ab" after 3 seconds, rather than first a, and then b 3 seconds later.

This issues is not present with Julia 0.4.5 kernel, but I need to run Julia 0.3.12 for compatibility reasons.

**Comment by stevengj** [comment]
@JobJob, you did some work on the asynchronous I/O ... any idea of why it would be different in 0.3?

(As a practical matter, it's going to be harder and harder to use Julia 0.3, since probably none of the package developers are using it regularly anymore.)

**Comment by JobJob** [comment]
Sorry, somehow I missed this @ mention. Is this still an issue @DalimilMazac ? I could look into it.

**Comment by stevengj** [comment]
Since we dropped Julia 0.3 support some time ago, I think this issue can be closed.
