### ISSUE TITLE
Use markdown cell before function definitions as docstring

### ISSUE THREAD

**Issue by ChristianKurz** [JuliaLang/IJulia.jl#435]
Julia allows to define a docstring by fencing markdownsyntax with three quotation marks directly in front of a function e.g.

``` Julia
"""
    doctest()

This is a **markdown** docstring
"""
function doctest()
end
```

In IJulia-notebooks it would be nice to have the docstring-markdown correctly parsed. 
I propose to treat markdown cells directly preceeding function definitions as docstrings.

This would result in the following two cells to be treated exactly the same as the former example.

``` Markdown
"""
    doctest()

This is a **markdown** docstring
"""
```

``` Julia
function doctest()
end
```

Especially, calling `?doctest` should also print the same docstring for both versions.
I think it would be best to just have the same syntax seperated over two cells to get the nice markdown formatting while keeping compatibility.

**Comment by stevengj** [comment]
I'm skeptical of this.  It violates the typical expectation that Markdown cells in Jupyter do not normally affect code execution.

I would only be in favor of doing this for markdown cells that were tagged in some way, e.g. using the proposed jupyter/notebook#601

**Comment by shorty66** [comment]
I agree that a tag or label would be less confusing. TBH the idea just came to my mind and i didn't spend to much time thinking about the consequences.
Do people even write docstrings in jupyter-notebooks?

**Comment by stevengj** [comment]
@shorty66, they might, since they can use notebooks with NBInclude.jl to develop Julia modules etcetera.  I don't think it's super common, though.

**Comment by shorty66** [comment]
I did not know about that package yet - seems really useful to me, as i do most of my editing in notebooks.
Just for the reference i will add [the announcement thread in julia-users](https://groups.google.com/forum/#!searchin/julia-users/nbinclude/julia-users/erb34bODmds/IAfAqd1xAwAJ) to this issue.

@stevengj I really like the idea of included unit tests and i see that you already had the idea of **docstring-cells**.

**Comment by stevengj** [comment]
Closing as docstring-cells seems unlikely to get traction.
