### ISSUE TITLE
requiring "ijulia" in module "Main" did not define a corresponding module

### ISSUE THREAD

**Issue by haihan** [JuliaLang/IJulia.jl#440]
after I run `Pkg.build("IJulia")` and `using Julia` it appears that :
`using ijulia
INFO: Recompiling stale cache file /Users/haihan/.julia/lib/v0.4/ijulia.ji for module ijulia.
WARNING: requiring "ijulia" in module "Main" did not define a corresponding module.
`
does someone know what happen? I use a Mac OS X system. thanks

**Comment by yuyichao** [comment]
`using IJulia`

**Comment by haihan** [comment]
@yuyichao  thanks a lot! all problems are solved
