### ISSUE TITLE
Following the debugging instructions leads to "Kernel appears to have died" message

### ISSUE THREAD

**Issue by crbinz** [JuliaLang/IJulia.jl#446]
With `verbose = false` and `const capture_stderr = true`, a julia-v0.4.6 notebook starts just fine. Following the instructions in the README and setting `verbose = true` and `const capture_stderr = false` causes any new Julia notebook to crash upon opening.

`Pkg.status()` shows ` - IJulia                        1.2.0`

```
julia> versioninfo()
Julia Version 0.4.6
Commit 2e358ce (2016-06-19 17:16 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) CPU E5-1650 0 @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by stevengj** [comment]
Sorry about that, should be fixed in IJulia master (`Pkg.checkout("IJulia")`)
