### ISSUE TITLE
Disable deprecation warnings in IJulia?

### ISSUE THREAD

**Issue by AStupidBear** [JuliaLang/IJulia.jl#448]
Is there a way to disable deprecation warnings in IJulia, like using ``` --depwarn=no``` in REPL?

**Comment by darwindarak** [comment]
You can find the `kernel.json` file associated with your version of Julia with `jupyter kernelspec list`, then add `"--depwarn=no"` as an entry in the `"argv"` array.

**Comment by AStupidBear** [comment]
Thanks
