### ISSUE TITLE
Default installation under Windows leads to unexpected behavior

### ISSUE THREAD

**Issue by matteyas** [JuliaLang/IJulia.jl#449]
To reproduce:
0) Have none of the IJulia pre-requisites installed / in PATH.
1) Run an Admin command prompt and launch the Julia REPL (I used 0.4.5 on win10-x64)
2) `Pkg.add("IJulia")`, this step should use miniconda to install jupyter and anything else needed.
3) `using IJulia; notebook()`

This should result in a jupyter instance that tries to serve the notebook from the root of c: (an instance did spawn on my machine, but what it actually tries to do is partly speculation) which leads to a 404 error in the jupyter page that opens in a browser, since Windows does not allow access to the root or something like that.

**Comment by stevengj** [comment]
Hmm, it would be easy enough to change the directory if `pwd()` returns `c:\`.   What directory should it default to on Windows?

cc @Carreau ... should `jupyter notebook` be smarter about this?

**Comment by stevengj** [comment]
Or maybe this should be fixed in `julia` itself ... maybe `julia.exe` should change to `homedir()` by default?

**Comment by stevengj** [comment]
I guess it is happening because your `julia.exe` program is in the root directory?

**Comment by matteyas** [comment]
Julia was installed in c:\Julia-0.4.5, where any IO should be fine.

**Comment by Carreau** [comment]
We can likely check that the directory the notebook is started from (or the directory it is configured to start in) have sufficient permission and abort if that's not the case. I **think** that may have been taken care of recently (at least we had complaint of notebook note starting in `C:\System32\`) I'll investigate.

**Comment by stevengj** [comment]
@matteyas, then how are you launching Julia?   Are you opening `cmd.exe` in the root directory and then typing in the path of `julia.exe` or something?

**Comment by matteyas** [comment]
I had julia.exe in my PATH variable, so I could start it anywhere and I am certain I did not start it in C:\. I am currently trying to reproduce the error (though with 0.4.6), and I will post results within 12h or so!

**Comment by stevengj** [comment]
What is `IJulia.notebook_cmd`?

**Comment by matteyas** [comment]
julia> IJulia.notebook_cmd
2-element Array{ASCIIString,1}:
 "C:\\Users\\[me]\\.julia\\v0.4\\Conda\\deps\\usr\\Scripts\\jupyter"
 "notebook"

**Comment by stevengj** [comment]
Okay, I've changed it to default to opening the dashboard in `homedir()`.   Let me know if `Pkg.checkout("IJulia")` (to grab the latest IJulia master) does not fix the problem.

**Comment by stevengj** [comment]
(Julia doesn't use `cmd -c` to spawn processes; it uses `uv_spawn`, which calls the Win32 API function `CreateProcessW` directly.)

**Comment by matteyas** [comment]
Neat, I'll try that as soon as I get back to work. I just find it really weird that the notebook started in the very same path that any new cmd.exe instance changes directory to on startup (through a startup-script). Before trying the fix, I'll see if changing the cmd startup path will change the notebook path as well, just out of curiosity.
