### ISSUE TITLE
Limit show/display output?

### ISSUE THREAD

**Issue by tlnagy** [JuliaLang/IJulia.jl#455]
Would it be possible to limit the maximum lines from `println` and `show`? I find that I often stall out `IJulia` when accidentally printing a too large array and then it is annoying and painful to clear the output without the browser going down. Say 1000 lines?

**Comment by stevengj** [comment]
You can use `display(x)` if you want to output an array in a limited fashion.  Or `writemime(STDOUT, "text/plain", x)` (renamed to `show` in Julia 0.5) if you need to output to a stream.  This is what is used for the output of a cell (i.e. to display the result of the last expression).

**Comment by stevengj** [comment]
Although it might be reasonable to also truncate stdout/stderr messages sent to the front-end?

@Carreau, does the IPython kernel do any kind of output limiting to prevent huge amounts of text from being dumped into the notebook?

**Comment by Carreau** [comment]
The notebook server have an option to throttle output but it's opt-in and mostly for student making infinit while loop.

```
--NotebookApp.iopub_data_rate_limit=<Float>
    Default: 0
    (bytes/sec) Maximum rate at which messages can be sent on iopub before they
    are limited.
--NotebookApp.iopub_msg_rate_limit=<Float>
    Default: 0
    (msg/sec) Maximum rate at which messages can be sent on iopub before they
    are limited.
--NotebookApp.rate_limit_window=<Float>
    Default: 1.0
    (sec) Time window used to  check the message and data rate limits.
--NotebookApp.reraise_server_extension_failures=<Bool>
```

It's stalling the notebook for 2 reasons:
 1) appending DOM element is expensive – it should be better once we have a virtual-DOM.
 2) we need to parse ansi-escape sequence ; but as we don't have access to the state of the ansi parsing lib every time you append something it needs to reparse from the beginning of the stream.

In the end we should not send the full info to the browser and cache it on the server sending it only if frontend needs it; we have plans for that but not soon.

There is an intermediate step possible (we had prototype) where if too much output get produced we had a "Too much output click here to show it" though nobody agreed on what was "too much" so we removed it.

**Comment by tlnagy** [comment]
> You can use `display(x)` if you want to output an array in a limited fashion.

The key here is accidentally. Sometimes I forget to remove `println` commands in a cell before running it with new input, or a matrix is huge and crashes my browser. I was hoping of limiting these cases as it is painful to recover the IJulia notebook when the browser slows to a crawl.

> There is an intermediate step possible (we had prototype) where if too much output get produced we had a "Too much output click here to show it" though nobody agreed on what was "too much" so we removed it.

Why would anyone need 10,000 lines printed out? That amount works fine. It's when I accidentally print a 2500x2500 matrix that I have to fight to kill the kernel before the browser crashes.

**Comment by stevengj** [comment]
I agree that e.g. a 512kB default limit (per code cell) (= 13000 lines at 40 characters per line) makes sense.

I don't think it is useful to make it opt-in, because the cases where you need it will always be the cases where you forgot to opt-in.

**Comment by tlnagy** [comment]
> I don't think it is useful to make it opt-in, because the cases where you need it will always be the cases where you forgot to opt-in.

Agreed. I think it's one of those things where we can make it the default and if someone needs more output then we could add an opt-out condition. How would the 512kb limit affect something like `Images.jl` where your code can output images?

**Comment by Carreau** [comment]
I don't remember if its mimetype aware. @ellisonbg you are using it IIRC.

On Aug 31, 2016 13:50, "Tamas Nagy" <notifications@github.com> wrote:

I don't think it is useful to make it opt-in, because the cases where you
need it will always be the cases where you forgot to opt-in.

Agreed. I think it's one of those things where we can make it the default
and if someone needs more output then we could add an opt-out condition.
How would the 512kb limit affect something like Images.jl where your code
can output images?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/JuliaLang/IJulia.jl/issues/455#issuecomment-243897100>,
or mute the thread

**Comment by stevengj** [comment]
@tlnagy, I would only advocate imposing a limit for `stdout` and `stderr` output, which is strictly for plain text.  It wouldn't affect multimedia display at all.

**Comment by tlnagy** [comment]
> I would only advocate imposing a limit for stdout and stderr output (stream messages in the Jupyter protocol), which is strictly for plain text.

I think that's a great idea. This has always been a peeve of mine with jupyter notebooks and it would be awesome to have it fixed.

**Comment by Carreau** [comment]
> I think that's a great idea. This has always been a peeve of mine with jupyter notebooks and it would be awesome to have it fixed.

Yes, I think it make sens, lot of other modifications to the server woudl make sens, but as the notebook server act only as a proxy that copy buffers ( move ?) between ZMQ and Websocket the current implementation is likely naive and does not even inspect to see what's it's limiting, though the activity and bandwith we have on the server have [dramatically dropped](https://github.com/jupyter/notebook/graphs/commit-activity) since march going from ~50 comit a day to ~10 and almost no one  that have bandwidh to improve that. We got funding to hire a part time maintainer (so bugs should stop piling up) , but right now it seem like most of the interest/ resource is on the [jupyterlab](https://github.com/jupyter/jupyterlab/graphs/commit-activity) repo.

**Comment by stevengj** [comment]
@Carreau, I was thinking of imposing the limitation on the IJulia side, so that we don't even send the data to the server beyond a certain limit.

**Comment by Carreau** [comment]
Ah, sure, you could also. Sorry I misinterpreted.

**Comment by tlnagy** [comment]
I just ran into this again because `Images` did not have a specialized `show` function defined so instead it dumped a 2000x2000 matrix of RGB values to the IJulia console bringing my browser to a grinding halt. Currently, I'm typing this in Chrome because Firefox is still trying to close that tab

**Comment by stevengj** [comment]
A PR to implement the limit would be welcome.

**Comment by tlnagy** [comment]
I would give it a shot, but I'm not sure where to start. I imagine I could modify one of the functions in https://github.com/JuliaLang/IJulia.jl/blob/master/src/stdio.jl and then have a counter to keep track of the number of bytes that are written?

**Comment by tlnagy** [comment]
This is actually more difficult to implement then I thought. I've spent a little time looking at the codebase and it appears to be quite difficult to establish how big a dump to stdout will be. I tried a couple things where I was counting the number bytes flowing through `watch_stream` over a period of 5seconds or so, but that's not a good solution. 

One thing that might work would be intercept all messages labeled stdout and count the number of bytes appended to one cell since all that information should be there.

**Comment by stevengj** [comment]
I would define a `const stdio_bytes = Ref(0)` that gets reset to `0` at the beginning of each code-cell execution.  Every time `watch_stream` wakes up and reads something, it would increment this counter, and then truncate the messages when the total goes over `const stdio_limit = Ref(1<<19)`

**Comment by tlnagy** [comment]
I didn't realize that there is can only be one executing command at a time and that this is stored as in the parent header of the global variable `execute_msg`. Therefore, it is quite easy to count the number of bytes written by an execution request as long as the counter is reset when there's a new execution request.

**Comment by juliohm** [comment]
I don't know if it is related, but long runs with ProgressMeter.jl are truncated with the message:

>Excessive output truncated after 524411 bytes.

This means that the progress bar that should be showing up until the end of the simulation, stops moving. Is this an issue that should be reported in ProgressMeter.jl instead?

**Comment by stevengj** [comment]
Yes, I think it would have to be fixed there, possibly by manually resetting `IJulia.stdio_bytes[] = 0`

**Comment by juliohm** [comment]
Thank you @stevengj, will open an issue there.
