### ISSUE TITLE
Syntax highlighting after Reinstalling Julia

### ISSUE THREAD

**Issue by madarivi** [JuliaLang/IJulia.jl#457]
I had some problems with permissions in my julia folder so I reinstalled julia directly on C in "C:\Julia" (Windows 7). I'm also using jupyter notebooks installed with my anaconda python installation. After running Pkg.build("IJulia") the julia kernel seems to work fine except for that the syntax highlighting is completely gone.

**Comment by stevengj** [comment]
That's weird; @Carreau, why would syntax highlighting disappear?

**Comment by yuyichao** [comment]
I remember seeing syntax highlighting disappearing in certain cases ~1.5yr ago (maybe https://github.com/JuliaLang/IJulia.jl/issues/271) What's julia, IJulia and jupyter/ipython versions?

**Comment by madarivi** [comment]
julia -> 0.4.6
jupyter -> 4.1.0
IJulia -> 1.2.0

**Comment by stevengj** [comment]
Closing as not reproducible.
