### ISSUE TITLE
notebook() blocks the current process.

### ISSUE THREAD

**Issue by Ismael-VC** [JuliaLang/IJulia.jl#458]
When doing:

`using IJulia; notebook()`

The terminal gets blocked, it would be nice to be able to continue working in the same terminal after the fact, this can be done with:

`using IJulia; @async notebook()`

It would be nice if `notebook` ran asynchronously by default instead. So that one could continue using the terminal, this is specially useful from a user perspective, since after calling `notebook` we **can't** see the server messages update anymore, like if we did:

`jupyter notebook` 

instead from the shell.

So I think either notebook should not block the process or if it's decided it's better this way, it would be useful if it printed out the server messages this would be useful for debugging purposes, currently if something fails I have to use `jupyter notebook` manually in order to see such messages.

**Comment by yuyichao** [comment]
`notebook(detached=true)` Since this is possible to do and documented and since that makes exiting harder I think we should keep the same default.

**Comment by Ismael-VC** [comment]
Also why does it block it so much that I can't even CTRL-C to get back to the julia prompt?

**Comment by Ismael-VC** [comment]
@yuyichao Ah I see what you mean, it should be added that `notebook(detached=true)` will not only persist after the julia process exits, but that it will also wont block the current running process, thank you very much!

**Comment by Ismael-VC** [comment]
I have updated my readme PR at #459, so hopefully new users will have a better workflow experience.
