### ISSUE TITLE
"Unsupported keyword argument dir"-error when calling notebook(dir="/some/path")

### ISSUE THREAD

**Issue by BenjaminBorn** [JuliaLang/IJulia.jl#460]
Hi guys,

on a fresh 0.5 RC4 install with IJulia 1.2.0, I get an error message when trying to open the notebook in a different directory via `notebook(dir="/some/path")` (as described in the readme, actual path replaced), while it works fine when opening a notebook in the home directory without passing on a path.

The error message reads:

```
julia> notebook(dir="/some/path")
ERROR: MethodError: no method matching notebook(; dir="/some/path")
Closest candidates are:
  notebook(; detached) at /Users/[removed]/.julia/v0.5/IJulia/src/IJulia.jl:192 got unsupported keyword argument "dir"
 in (::IJulia.#kw##notebook)(::Array{Any,1}, ::IJulia.#notebook) at ./<missing>:0
```

My system information:

> Julia Version 0.5.0-rc4+0
> Commit 9c76c3e* (2016-09-09 01:43 UTC)
> Platform Info:
>   System: Darwin (x86_64-apple-darwin15.6.0)
>   CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
>   WORD_SIZE: 64
>   BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
>   LAPACK: libopenblas64_
>   LIBM: libopenlibm
>   LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)

**Comment by stevengj** [comment]
Sorry, I just realized I hadn't tagged a new version of IJulia in a while.  It works now in IJulia `master`, and if you wait a day or so it will work after you do `Pkg.update()`.
