### ISSUE TITLE
The Julia kernel keep dying and failed to restart

### ISSUE THREAD

**Issue by zlqs1985** [JuliaLang/IJulia.jl#464]
I enconter a problem right now that the Julia kernel in the Jupyter notebook is always dead, and fail to restart.
I call the notebook directly from the cmd. My Os is Win10 and my Julia version is 0.4.2
The message from cmd
![image](https://cloud.githubusercontent.com/assets/10328230/18582205/829380ce-7c36-11e6-90d2-2cec42dcea0d.png)

Any suggestion? Thank you.

**Comment by stevengj** [comment]
It says you are missing the `IJulia\src\kernel.jl` file, so I'm guessing you accidentally removed the IJulia package?   Try opening up the Julia command-line, and typing `Pkg.add("IJulia")`.

**Comment by serdar-** [comment]
I have the same problem, is there a solution already?

**Comment by stevengj** [comment]
@serdar, your problem is with MbedTLS (try `using MbedTLS`) and should be reported at https://github.com/JuliaWeb/MbedTLS.jl
