### ISSUE TITLE
IJulia No Longer Opens at the Right Path

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaLang/IJulia.jl#465]
IJulia no longer opens at the current location of the REPL. Example:

```julia
cd(Pkg.dir("IJulia"))
using IJulia
notebook()
```

This can be a painful issue to deal with on Windows because it defaults to the user folder, which in order to get to the Julia library you have to go into a hidden folder which does not show up in Jupyter (so now I don't know how to actually get into the Julia library with IJulia since this change).

Julia v0.6 with IJulia on release.

**Comment by stevengj** [comment]
This is a documented change.   As explained in the README, if you want to open in a specific directory you can do `notebook(dir = Pkg.dir("IJulia"))`

As an aside, I would really recommend against putting your notebooks into the IJulia package directory.  Package directories are really intended to be controlled by the packages, not for storing arbitrary user files.  I would put your notebooks somewhere where you put your other files, e.g. somewhere in the `My Documents` folder on Windows.
