### ISSUE TITLE
jupyter lab support?

### ISSUE THREAD

**Issue by AStupidBear** [JuliaLang/IJulia.jl#466]
Now IJulia works find in jupyter lab except that there's no code highlighting anymore.
![image](https://cloud.githubusercontent.com/assets/16422976/18622918/f09d1a1a-7e68-11e6-8a5a-5a28bd38a597.png)

**Comment by stevengj** [comment]
@Carreau, any idea why the Julia highlighting mode would be disabled here?

**Comment by Carreau** [comment]
(Still highly beta though)

**Comment by juliohm** [comment]
I've just installed JupyterLab but it doesn't show the Julia kernel, only Python 3. What is needed to make it visible? Could you please reference where the issue was solved?

**Comment by stevengj** [comment]
Presumably you need to install the kernel config file for Julia.  This is done automatically by `Pkg.build("IJulia")`, but maybe JupyterLab uses a different directory for its kernel info?

**Comment by juliohm** [comment]
@stevengj you mean that perhaps I need to rerun `Pkg.build("IJulia")` after having installed JupyterLab?

**Comment by stevengj** [comment]
@juliohm, no, not unless JupyterLab uses a different location for its kernel info.  Does JupyterLab come with its own `jupyter`?   If so, you might need to set `ENV["JUPYTER"]=/path/to/jupyterlab/jupyter"; Pkg.build("IJulia")`

**Comment by juliohm** [comment]
I am not sure if it comes with its own Jupyter, isn't it a Jupyter extension? I opened an issue in their github page to see if someone there can help.

**Comment by stevengj** [comment]
Code highlighting was apparently fixed some time ago by jupyterlab/jupyterlab#1137

@Carreau, presumably more Julia users will start to try JupyterLab with IJulia soon, and will file issues as they arise, but feel free to file issues with us if there are additional updates to the messaging protocol that we need to be aware of.  When work on the JupyterLab debugger (jupyter/debugger#2) gets further along, it would be good to touch base with people like @Keno who have been working on Julia debuggers.
