### ISSUE TITLE
Location of the Configuration Files

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaLang/IJulia.jl#467]
I am trying to get [RISE](https://github.com/damianavila/RISE#configure-your-own-options) to work with IJulia and while it works, it doesn't do the vertical scrolling. To do this, you have to modify the Jupyter configuration files. I cannot find the configuration files [in the usual locations](http://jupyter.readthedocs.io/en/latest/projects/jupyter-directories.html), so I was wondering if anyone knows where they are (are they buried in the Conda.jl package somewhere?).

**Comment by stevengj** [comment]
```
using Conda
run(`$(joinpath(Conda.BINDIR, "jupyter")) --paths`)
```

**Comment by stevengj** [comment]
Also try passing `--config-dir` and `--data-dir`
