### ISSUE TITLE
Incorrect indentation following Dict comprehensions

### ISSUE THREAD

**Issue by hessammehr** [JuliaLang/IJulia.jl#484]
Dictionary comprehensions in IJulia notebooks cause extra indentation on following lines, e.g.
```julia
Dict(a=>a for a=1:5)
    # next line of codes starts here
```

**Comment by hessammehr** [comment]
Looks like this happens with any generator expression:
```julia
sum(x for x=1:5)
     # next line of codes starts here
```
Could this be a CodeMirror issue?

**Comment by stevengj** [comment]
Yes, it would be a problem with the codemirror mode; cc @malmaud

**Comment by hessammehr** [comment]
codemirror/codemirror#4356
