### ISSUE TITLE
Feature request: Shortcut for turning pipe'd function into "standard form"

### ISSUE THREAD

**Issue by marius311** [JuliaLang/IJulia.jl#486]
Very often during more free-form data analysis work, I use the awesome/convenient pipe operator by quickly writing something like,

`x |> plot`

but then after a bit I'll also want to pass some options to `plot`, so I'll have to entirely rewrite the line to,

`plot(x,min=0)`

It would be really cool if IJulia had a command / keyboard shortcut to automatically turn the `x |> plot` line into `plot(x)`, then I can insert the `min=0` part where it needs to go. 

Mathematica has this, for example; it allows typing `x // Plot`, and then "Ctrl+Shift+N" turns it into `Plot[x]`. 

This becomes even more useful the more operators you chain, since turning e.g. `x |> abs |> log |> plot` into `plot(log(abs(x)))` takes quite a bit of typing.

**Comment by stevengj** [comment]
This isn't possible in the IJulia kernel.  It *might* be possible in the Julia CodeMirror mode, but more likely seems like it would require changes in Jupyter itself.  cc @Carreau.

**Comment by Carreau** [comment]
That's something that would be nice and can be generalized as a way for the server-side/kernel-side to "rewite" input/part of input.

I think that the [Microsoft/language-server-protocol](https://github.com/Microsoft/language-server-protocol) is a nice step toward that. It defines a number of interfaces that allow linters/refactor tools to be plugged in and send the equivalent of a diff/patch that can be applied with UI indications. Then a shortcut can likely be added on top of that to trigger some actions. 

there are a number of similar improvement I would like to see  like for example : 

```
log(abs(x)))|<tab>
```

To be able to tab-complete by prepending `plot(` that's of course much harder than usual tab completion, as you can mean `plot(log(abs(x)))` or `log(plot(abs(x)))`, the computer might not be able to infer. Note that in above example I have an extra unbalance closing parenthesis to hint the completer I'd like to pre-complete. 

That something that would be great but that I don't see being worked on soon, as we are pretty busy in a lot of place already. 

I can see the argument to ask companies for funding to implement that in a year or so be much more compelling once we have JupyterLab stable.
