### ISSUE TITLE
Kernel error

### ISSUE THREAD

**Issue by idontgetoutmuch** [JuliaLang/IJulia.jl#489]
I just installed `julia`

```
Hogsmill:GeometricIntegrators.jl dom$ julia --version
julia version 0.5.0`
```

And launched `IJulia` as per the instructions

```
~/GeometricIntegrators.jl $ julia
julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0 (2016-09-19 18:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  x86_64-apple-darwin15.6.0

WARNING: Terminal not fully functional
julia> using IJulia
using IJulia

julia> notebook()
notebook()
```

When I try to run a note book I get a kernel error with this when I click on the `Kernel error` box.

```
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/Cellar/julia/HEAD/bin/julia'
```

Also the box next to the `Kernel error` says `Julia 0.4.0-dev` so somehow `Jupyter` is pointing at the wrong `IJulia`. Now I could just create a link but this feels sub-optimal. Nor did Googling didn't turn up any answers on how to get `Jupyter` to point at the correct `IJulia` :(

**Comment by idontgetoutmuch** [comment]
If I try to create a new `IJulia` notebook then I do get the option of 'Julia 0.4.0-dev`, `Julia 0.5.0` and `Python 3`. If I select `Julia 0.5.0` then the kernel dies and the log shows

```
signal (4): Illegal instruction: 4
while loading /Users/dom/.julia/v0.5/IJulia/src/kernel.jl, in expression starting on line 8
abort at /usr/local/opt/llvm37-julia/lib/llvm-3.7/lib/libLLVM-3.7.dylib (unknown line)
uv_thread_create at /private/tmp/julia-20161115-4038-1ewl56v/deps/srccache/libuv-8d5131b6c1595920dd30644cd1435b4f344b46c8/src/unix/thread.c:88
init at /Users/dom/.julia/v0.5/IJulia/src/init.jl:88
unknown function (ip: 0x318daa4e2)
jl_call_method_internal at /private/tmp/julia-20161115-4038-1ewl56v/src/./julia_internal.h:189 [inlined]
jl_apply_generic at /private/tmp/julia-20161115-4038-1ewl56v/src/gf.c:1942
do_call at /private/tmp/julia-20161115-4038-1ewl56v/src/interpreter.c:66
eval at /private/tmp/julia-20161115-4038-1ewl56v/src/interpreter.c:190
jl_toplevel_eval_flex at /private/tmp/julia-20161115-4038-1ewl56v/src/toplevel.c:558
jl_parse_eval_all at /private/tmp/julia-20161115-4038-1ewl56v/src/ast.c:717
jl_load at /private/tmp/julia-20161115-4038-1ewl56v/src/toplevel.c:596 [inlined]
jl_load_ at /private/tmp/julia-20161115-4038-1ewl56v/src/toplevel.c:605
include_from_node1 at ./loading.jl:488
jlcall_include_from_node1_20158 at /usr/local/Cellar/julia/0.5.0/lib/julia/sys.dylib (unknown line)
jl_call_method_internal at /private/tmp/julia-20161115-4038-1ewl56v/src/./julia_internal.h:189 [inlined]
jl_apply_generic at /private/tmp/julia-20161115-4038-1ewl56v/src/gf.c:1942
process_options at ./client.jl:262
_start at ./client.jl:318
jlcall__start_21507 at /usr/local/Cellar/julia/0.5.0/lib/julia/sys.dylib (unknown line)
jl_call_method_internal at /private/tmp/julia-20161115-4038-1ewl56v/src/./julia_internal.h:189 [inlined]
jl_apply_generic at /private/tmp/julia-20161115-4038-1ewl56v/src/gf.c:1942
true_main at /usr/local/Cellar/julia/0.5.0/bin/julia (unknown line)
main at /usr/local/Cellar/julia/0.5.0/bin/julia (unknown line)
Allocations: 2074895 (Pool: 2073985; Big: 910); GC: 1

signal (6): Abort trap: 6
while loading /Users/dom/.julia/v0.5/IJulia/src/kernel.jl, in expression starting on line 8
sigprocmask at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 2074895 (Pool: 2073985; Big: 910); GC: 1
[I 10:44:37.207 NotebookApp] KernelRestarter: restarting kernel (1/5)
[D 10:44:37.208 NotebookApp] Starting kernel: ['/usr/local/Cellar/julia/0.5.0/bin/julia', '-i', '--startup-file=yes', '/Users/dom/.julia/v0.5/IJulia/src/kernel.jl', '/Users/dom/Library/Jupyter/runtime/kernel-f4fa89fb-f118-4222-b26e-498b2a63387b.json']
[D 10:44:37.211 NotebookApp] Connecting to: tcp://127.0.0.1:60923
PROFILE = Dict{String,Any}(Pair{String,Any}("key","a5da0a68-6adc-40a6-9c05-84fc159ca9df"),Pair{String,Any}("transport","tcp"),Pair{String,Any}("signature_scheme","hmac-sha256"),Pair{String,Any}("ip","127.0.0.1"),Pair{String,Any}("shell_port",60920),Pair{String,Any}("control_port",60923),Pair{String,Any}("hb_port",60924),Pair{String,Any}("stdin_port",60922),Pair{String,Any}("kernel_name","julia-0.5"),Pair{String,Any}("iopub_port",60921))
```

**Comment by idontgetoutmuch** [comment]
I can create a `Python 3` notebook without any problems.

**Comment by dpsanders** [comment]
It looks like you installed Julia via homebrew. Do you get the same problem if you install it using the dmg downloaded from the Julia home page instead?

**Comment by idontgetoutmuch** [comment]
Yes I `brew` uninstalled `julia` and installed the dmg from the homepage but I still get the same results.

**Comment by JobJob** [comment]
Maybe try `Pkg.update(); Pkg.build("IJulia")` from a julia repl

**Comment by idontgetoutmuch** [comment]
I deleted all old versions of `julia` (of which there were many), edited the xml of the notebook to point at the correct version of `julia` and now I am in business. What caused the original problem will forever remain one of the world's great unsolved mysteries. Thanks to @JobJob and @dpsanders for your suggestions.

**Comment by JobJob** [comment]
Haha, glad you got there in the end.

**Comment by andreasnoack** [comment]
I'm getting this right now with Julia 0.5 and have tried to delete all Jupyter configuration files and `Pkg.update(); Pkg.build("IJulia")` without any luck so I'll reopen. Any ideas about how to debug this further would be great.

**Comment by andreasnoack** [comment]
Julia 0.4 works fine. Both 0.5 and 0.4 are build from source. All packages are updated.

**Comment by stevengj** [comment]
The error message quoted above mentiones `uv_thread_create`.  Try commenting out the `start_heartbeat` call in `init.jl`.   (That will cause Jupyter to think the kernel has died, but the error message should be different if this is the source of the segfault.)

**Comment by andreasnoack** [comment]
If I comment out `start_heartbeat` at line 88 in `init.jl` then the notebook works. No errors.

**Comment by stevengj** [comment]
It's weird that Jupyter doesn't kill the kernel if we [don't respond to heartbeat requests](http://jupyter-client.readthedocs.io/en/latest/messaging.html#heartbeat-for-kernels); it used to do that.  @minrk, is the heartbeat still required?

Meanwhile, could you play around with [heartbeat.jl](https://github.com/JuliaLang/IJulia.jl/blob/master/src/heartbeat.jl) and see if you can get it to spawn a thread without crashing?   I can't reproduce the problem on my machine.

**Comment by andreasnoack** [comment]
I also used to work for me on 0.5. Which version of ZMQ are you using?

**Comment by minrk** [comment]
Heartbeats are required for 'remote' kernels, that is connecting to a kernel that another process started (e.g. connecting a qtconsole to a notebook's kernel), but when the notebook starts its own kernels, it uses direct process polling rather than the heartbeat messages to determine if the kernel is alive.

**Comment by msjuhasznora** [comment]
Hi everyone.
I am quite new to both Mac and Julia. (Also to Jupyter in fact).
That also means that I do not really have old versions of anything here, just installed Julia from the official website, and installed anaconda. I get this same red button appearing, saying "Kernel error" when I open a new julia 0.5.0 notebook.
Where can I find this init.jl file on my mac to edit it?

**Comment by andreasnoack** [comment]
It is in `~/.julia/v0.5/IJulia/src`.

**Comment by andreasnoack** [comment]
Just tried this again and now I can't reproduce. Weird.

**Comment by msjuhasznora** [comment]
Thanks.

**Comment by johnfgibson** [comment]
One of my students just hit this with julia-0.6.0 and 0.6.1 on MacOS. The fix of commenting out `start_heartbeat` worked.

**Comment by stevengj** [comment]
This issue was fixed a while ago.
