### ISSUE TITLE
Newlines missing from module inspect results

### ISSUE THREAD

**Issue by BenRussert** [JuliaLang/IJulia.jl#493]
Not sure if this issue is in IJulia or base, but if you inspect a module the newlines after links/URL are truncated so they dont render correctly in a notebook etc.

To reproduce, (JuMP docs as an example):

```
using JuMP
IJulia.docdict("JuMP")["text/markdown"]
```
or
```
?JuMP
```
...etc

The newlines after urls are missing so all appear on one line in raw markdown.

**Comment by stevengj** [comment]
I get the same thing for `?JuMP` in the REPL, so it's not an IJulia issue.  It may be a problem with Julia's Markdown parser—maybe it doesn't recognize standalone links like this, as opposed to embedded `[link](url)` links.
