### ISSUE TITLE
Plot to screen after writemime() deprecation

### ISSUE THREAD

**Issue by mbaz** [JuliaLang/IJulia.jl#494]
I'm trying to update Gaston for use in IJulia after the writemime() deprecation in Julia 0.5

In Julia 0.4, I had this function to generate a plot for use in an IJulia notebook:

    function writemime(io::IO, ::MIME"image/png", x::Figure)
        # The plot is written to /tmp/gaston-ijula.png. Read the file and
        # write it to io.
        data = open(readbytes, "$(gnuplot_state.tmpdir)gaston-ijulia.png","r")
        write(io,data)
    end

Following the discussion in https://github.com/JuliaLang/julia/issues/14052, I changed the function definition to 

    function show(::MIME"image/png", io::IO, x::Figure)

I also import Base.show instead of Base.writemime; I also tried reversing the order of MIME and io. However, when I try plotting in a notebook, I get the textual description of the plot, not the plot itself. How should I update my code to make it work again?

(I'm not sure if this is the right forum for this question, but nothing seems to be an obvious fit. Please let me know if I should post this somewhere else.)

**Comment by stevengj** [comment]
Your arguments are in the wrong order.  Define `Base.show(io::IO, ::MIME"image/png", x::Figure)`.

**Comment by stevengj** [comment]
See also http://docs.julialang.org/en/latest/manual/types.html#Custom-pretty-printing-1

**Comment by stevengj** [comment]
i.e. basically you just need to do a search-and-replace of `writemime` with `show`; the arguments are the same.

**Comment by mbaz** [comment]
Thanks for your help. Defining `Base.show()` instead of `show()` did the trick.
