### ISSUE TITLE
IJulia pendant for IPythons %hist / %history

### ISSUE THREAD

**Issue by crstnbr** [JuliaLang/IJulia.jl#497]
I'm using IJulia within qtconsole via

` jupyter qtconsole --kernel julia-0.5`

A usual workflow for me is playing around in this interactive qtconsole and then copy the working code into some script file. When using IPython (instead of IJulia) I can get a simple linear ordered history, which is very nicely copyable, by running `%hist` or `%history`.

I think I figured out that in Julia the best I can do is use IJulia.In dictionary (got that from [magics.jl](https://github.com/JuliaLang/IJulia.jl/blob/bbfd419dbe896b3b5c3b29557c951c47df489338/src/magics.jl#L123), by the way, the relevant help only shows up when executing `%history` and not for `%hist`). However, to get a simple linear ordered history from it I have to fiddle around to get rid of the mapping information ("number"=>) the quotation marks and line breaks (\n) etc.

I would like to have a simple plain text ordered history of the last X executed commands/cells. To avoid keeping another history, it would be enough to provide a function that maps IJulia.In to such a simple history.

**Comment by stevengj** [comment]
`history(n) = print(join(map(n -> In[n], sort(collect(keys(In)))[end-n:end]), "\n\n"))` prints the last n history items, for example.  Is this what you had in mind?

**Comment by crstnbr** [comment]
Yes, thanks! That is more elegant than my personal fiddling solution.
To be precise, I find those two functions very convenient:
```
history(n) = print(join(map(n -> In[n], sort(collect(keys(In)))[end-n:end]), ""))
history() = print(join(map(n -> In[n], sort(collect(keys(In)))[1:end]), ""))
```

Of course, I can define them myself but why not integrate this function and suggest it when someone tries to call the above IPython magic commands? You guys know better then me what to integrate and what not but, if I have a vote, I would vote for integration :)

I would love to hear your (general) comments on this (Should I prepare a pull request? Does it have any chance?). Otherwise this issue can be closed.

**Comment by stevengj** [comment]
It seems reasonable to me to include this, and PR would be welcome.

I would tend to suggest calling it `printhistory`, with an optional `io` argument to output to a different stream:
```jl
"""
documentation
"""
function printhistory(io::IO, n=length(In))
    n = min(n, length(In))
    n < 0 && throw(ArgumentError("a non-negative argument is required"))
    print(join(map(n -> In[n], sort(collect(keys(In)))[end-n+1:end]), "\n\n"))
end
printhistory(n=length(In)) = printhistory(STDOUT, n)
```

**Comment by stevengj** [comment]
or maybe:
```
I = sort(collect(keys(In)))
for i in I
    println(io, "# In[$i]:\n", In[i])
end
```

**Comment by stevengj** [comment]
Of course, if you really want to emulate `%history`, you'll also want to write methods that support ranges for `n`, or regex patterns.  This wouldn't be too hard.

**Comment by crstnbr** [comment]
Ok, I'll prepare a nice version with those features and make a PR. Thank you!
