### ISSUE TITLE
Make `ENV["JUPYTER"] = ""` the default

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/IJulia.jl#501]
I suggest making `ENV["JUPYTER"] = ""` the default.

The alternative (using a pre-installed Jupyter setup) should be the option that requires setup -- it causes too many issues with getting the right versions of packages to work together.

**Comment by stevengj** [comment]
I'm fine with that.  Maybe we should do a similar thing in PyCall?

**Comment by stevengj** [comment]
A PR would be welcome.

**Comment by dpsanders** [comment]
Yes, I think we should do the same in PyCall. I can try a PR.

**Comment by dgleich** [comment]
After just hosting a Julia install session for my class where a variety of students had custom pythons and/or previous Jupyter installs that were driving us crazy with a large diversity of errors -- I would highly endorse this suggestion! (In fact, I wish I had known about it 48 hours ago...).

**Comment by shashi** [comment]
Thank you for doing this @stevengj this will make Interact's life way easier. cc @JobJob

**Comment by stevengj** [comment]
Just pushed a commit to do the same thing (default to Conda on Mac and Windows, use `python` on Linux) in PyCall: https://github.com/JuliaPy/PyCall.jl/commit/bf2f7d46f2c5940062ffd55363fde0e2a22b5fd1
