### ISSUE TITLE
Check for jupyter in the environment before installing conda/etc.

### ISSUE THREAD

**Issue by Chris7** [JuliaLang/IJulia.jl#506]
Is there any reason to not check the environment for a Jupyter install? I don't mean the `JUPYTER` env var, but searching the current user's path to see if the jupyter executable exists.

From a user's stance, being ambushed by a conda + a ton of conda dependencies is terrifying (especially when rebuilding a Docker image and not knowing this is a new default behavior from Julia)

**Comment by yuyichao** [comment]
This is done intentional. Ref https://github.com/JuliaLang/IJulia.jl/issues/501.

I don't like it either (because I've never used a broken distro) but apparently it has caused many issues and it's possible to disable in my packaging script...

**Comment by stevengj** [comment]
I wonder if we should switch back to the old behavior (looking for `jupyter` in the PATH by default) on Linux systems, where the culture is a bit different (people don't expect self-contained installs) and if `jupyter` is installed it is much more likely to be working.

**Comment by Chris7** [comment]
Thanks for your quick replies! I would certainly be in support of that change @stevengj, as it's much more in line with the expected user experience of installing Julia on Linux.

**Comment by stevengj** [comment]
A PR would be welcome.

**Comment by stevengj** [comment]
Done.

**Comment by Chris7** [comment]
Thank you! Amazed how responsive you all are!
