### ISSUE TITLE
current_module() is now sometimes IJulia

### ISSUE THREAD

**Issue by cstjean** [JuliaLang/IJulia.jl#507]
Running this code in a fresh notebook now prints `IJulia` on Julia 0.5. It used to print `Main`:

```julia
immutable Foo end
function Base.show(io::IO, ::MIME"text/html", ::Foo)
    @show current_module()
end
Foo()
```

I've bisected the change to [this commit](https://github.com/JuliaLang/IJulia.jl/commit/3ed9573d517fa62dd3dd56c084d7549ec372c6ec). I have some code that relies on the former behavior. It's admittedly not the cleanest code. Should I fix it not to depend on `current_module()`, or is this a legitimate IJulia bug?

**Comment by stevengj** [comment]
I'm not 100% sure whether you should rely on this, but it shouldn't hurt to change the `eval` to `eval(Main, :(IJulia.display_dict(...)))`.  A PR would be welcome.

**Comment by cstjean** [comment]
Will do.

**Comment by yuyichao** [comment]
Should ideally splice the function instead of `IJulia` being accessible. Or ideally use `eval(current_module(), :($display_dict(...)))` and change the one above it similarly.
