### ISSUE TITLE
Awkwardness with limitstringmime

### ISSUE THREAD

**Issue by shashi** [JuliaLang/IJulia.jl#509]
![screenshot from 2017-01-30 11-55-09](https://cloud.githubusercontent.com/assets/25916/22414116/0b407b7c-e6e3-11e6-99ef-37ccf85567c8.png)

(seems like it is calling a fallback show which accesses undefined fields)

Defining show doesn't help.

![screenshot from 2017-01-30 11-56-43](https://cloud.githubusercontent.com/assets/25916/22414132/3b779032-e6e3-11e6-8d0a-9cae678789a5.png)

Nor does defining show with MIME"text/plain"

![screenshot from 2017-01-30 11-57-56](https://cloud.githubusercontent.com/assets/25916/22414158/6603ce4c-e6e3-11e6-8fdd-c5527bca1b17.png)

It seems only this works:

![screenshot from 2017-01-30 12-01-20](https://cloud.githubusercontent.com/assets/25916/22414232/e300ab18-e6e3-11e6-817b-b641920ec3c2.png)

Even if all you're interested in is the HTML rendering of X, you need to define this method because we send the plain text representation to Jupyter unconditionally.

How can this be made better?

**Comment by mbauman** [comment]
This is an error from a bad definition `PersistentVector` — `indices(x)` needs to return a tuple of indices.

**Comment by shashi** [comment]
Oh. But it just calls the base fallback...?

**Comment by mbauman** [comment]
Sorry, I edited my comment — the issue is in `size`.  See: https://github.com/JuliaLang/FunctionalCollections.jl/pull/31

**Comment by shashi** [comment]
Thanks! Sure enough, that fixed it. I wonder if this can be made easier to debug.

I guess we can close this issue then.
