### ISSUE TITLE
Problems with building IJulia, Julia 0.6

### ISSUE THREAD

**Issue by nevencaplar** [JuliaLang/IJulia.jl#510]
Hello,

I seem to have a problem with building IJulia, when using Julia 0.6 version. So what I did:

1. First attempt to build fails with `UndefVarError: Uint8 not defined` (https://gist.github.com/nevencaplar/537e5123ed2dd875f77c6c73e1719c90)

I changed the value in the build.jl where the error occurred from Uint8->UInt8.

2. After that the build seems to be ok, or at least it exits without errors (https://gist.github.com/nevencaplar/3c16dbb3c4bcf535af8be2aa85c48859)

3. I try `using IJulia` but  (https://gist.github.com/nevencaplar/f97a8474f754261572e8f601eddf8726)
with errors which I do not know how to solve.

Any help would be appreciated! It would be great if this could be done without reverting to 0.5 version or lower, as I had to quite a bit of trouble to already get so far (https://github.com/JuliaLang/julia/issues/20197).

**Comment by yuyichao** [comment]
Update `IJulia`, you appears to be using a very old version.
