### ISSUE TITLE
Tab complete when a block is running

### ISSUE THREAD

**Issue by mortenpi** [JuliaLang/IJulia.jl#511]
Currently tab completion doesn't work if a block is running, which I presume is because the connection to the kernel is occupied. However, it would be nice if you could use tab complete greek letters etc. even if another block is running.

**Comment by stevengj** [comment]
Not possible, I'm afraid.   The execution task and the task that responds to completion requests are running in different tasks, but these are "green threads"—they only cooperatively multitask.   The completion task can't run until the execution task either finishes or yields (e.g. by doing I/O or by calling `yield`).
