### ISSUE TITLE
loading external libraries in iJulia

### ISSUE THREAD

**Issue by ultradian** [JuliaLang/IJulia.jl#517]
I am having a problem getting IJulia to load the external libraries for MXNet and am hoping for some hints how to proceed.  MXNet works fine for me in the REPL, and as the [user guide](http://dmlc.ml/MXNet.jl/latest/user-guide/install/) states:

> When the MXNET_HOME environment variable is detected and the corresponding libmxnet.so could be loaded successfully, MXNet.jl will skip automatic building during installation and use the specified libmxnet instead.

> Basically, MXNet.jl will search libmxnet.so or libmxnet.dll in the following paths (and in that order):

>    * $MXNET_HOME/lib: customized libmxnet builds
>    * Pkg.dir("MXNet")/deps/usr/lib: automatic builds
>    * Any system wide library search path

> Note that MXNet.jl can not load libmxnet.so even if it is on one of the paths above in case a library it depends upon is missing from the LD_LIBRARY_PATH. Thus, if you are going to compile to add CUDA, the path to the CUDA libraries will have to be added to LD_LIBRARY_PATH

So I defined the environment variables in my notebook:
```
ENV["MXNET_HOME"] = "/home/milton/mxnet"
ENV["LD_LIBRARY_PATH"] = "/home/milton/mxnet/lib:/usr/local/cuda/lib64"
```
but still get the error:
```
error compiling #Variable#215: could not load library "/home/milton/mxnet/lib/libmxnet.so"
libcudart.so.7.5: cannot open shared object file: No such file or directory

in Variable(::Symbol) at /home/milton/.julia/v0.5/MXNet/src/symbolic-node.jl:232
```
So, is there someplace else I need to define a path to help the notebook find `libcudart.so` which is located in  `/usr/local/cuda/lib64`?

**Comment by stevengj** [comment]
LD_LIBRARY_PATH is special, because it affects the runtime linker.  I think it has to be in the environment before `julia` launches — I don't think you can change it within Julia itself?

**Comment by ultradian** [comment]
@stevengj, I tested it and you are right. I just launch in a terminal where  LD_LIBRARY_PATH is set.  Thanks!
