### ISSUE TITLE
Multi-user

### ISSUE THREAD

**Issue by pipedream** [JuliaLang/IJulia.jl#519]
How do I install IJulia on a multi-user sytem for all users?

**Comment by yuyichao** [comment]
Systemwise install is strongly system dependent. It is possible already with [a bit of hack](https://github.com/yuyichao/arch-pkg/blob/7e203501a452374595ee76e81baea42ec5c66ef6/pkg/all/ijulia-git/PKGBUILD). It's probably a [Pkg3](https://github.com/JuliaLang/Juleps/blob/b07cf116e7e67c456eccd79d657a30e4dee26a90/Pkg3.md) issue to make this easier when possible.
