### ISSUE TITLE
Dead Julia 0.5.1 kernel on Juliabox

### ISSUE THREAD

**Issue by selvaprabun** [JuliaLang/IJulia.jl#523]
Getting a julia 0.5.1 dead kernel since the morning. Restarting or logging in again don't help. I use Julia in the class I teach and my students and teaching assistants are also getting the same issue. Is there a way to resolve this? Thanks.

**Comment by stevengj** [comment]
I just tried an 0.5.1 notebook on juliabox, and it works fine for me.  Maybe it was a transitory problem with the servers?

In any case, juliabox-specific problems should be reported at https://github.com/JuliaCloud/JuliaBox
