### ISSUE TITLE
Custom formating of error messages

### ISSUE THREAD

**Issue by phlavenk** [JuliaLang/IJulia.jl#524]
Hello,
I'd like to bring the functionality of OhMyRepl.jl error message formatting into IJulia. So far I've found the push_posterror_hook(f) function. But there is nowhere mentioned what structures / API the user function should access in order to modify the output message. Could someone give me some hint if this is the right hook to do it and how I can access the strings that will appear in the output? I'll then add the implementation details to the documentation.

**Comment by JobJob** [comment]
Ok sounds interesting, what features exactly are you trying to bring over? (I've never used OhMyRepl). 

The processing of the request (i.e. running the user input) happens [here](https://github.com/JuliaLang/IJulia.jl/blob/master/src/execute_request.jl#L116). You have `preexecute_hooks` and `postexecute_hooks` that run before and after processing the request. You can push functions to them with `push_preexecute_hook()` `push_postexecute_hook()`, but the functions won't get any info (like the code executed or the result) passed to them, it's possible you may have to modify the calls to those hooks to get what you want done. 

Also IJulia captures stdout and stderr, and sends these as messages to the Jupyter server which forwards them to the browser window.  Though there may be a way to access these too, if needs be.

For more details, it would be good to know more specifics about what you're hoping to do.

**Comment by phlavenk** [comment]
My problem is given here:
[More compact type info in stacktrace/errors for Unitful.jl](https://discourse.julialang.org/t/more-compact-type-info-in-stacktrace-errors-for-unitful-jl/2923)
```julia
julia> using Unitful
julia> 1u"mm"+1u"s"
ERROR: Unitful.DimensionError()
 in +(::Unitful.Quantity{Int64,Unitful.Dimensions{(Unitful.Dimension{:Length}(1/
/1),)},Unitful.Units{(Unitful.Unit{:Meter}(-3,1//1),),Unitful.Dimensions{(Unitfu
l.Dimension{:Length}(1//1),)}}}, ::Unitful.Quantity{Int64,Unitful.Dimensions{(Un
itful.Dimension{:Time}(1//1),)},Unitful.Units{(Unitful.Unit{:Second}(0,1//1),),U
nitful.Dimensions{(Unitful.Dimension{:Time}(1//1),)}}}) at c:\Users\phlavenk\Doc
uments\programs\juliadata\v0.5\Unitful\src\Unitful.jl:311
```
With the OhMyREPL, the stacktrace looks much better:
```julia
julia> using Unitful, OhMyREPL

julia> 1u"mm"+1u"s"
------ DimensionError ------------------ Stacktrace (most recent call last)

 [1] - +(::Quantity{Int64, Dimensions:{?}, Units:{mm}}, ::Quantity{Int64, Dimens
ions:{?}, Units:{s}}) at Unitful.jl:311

Unitful.DimensionError()
```
So my idea is to hook the error formating code of OhMyREPL into IJulia, or, less ambitious implementation is to just replace my known long type definitions by shortened version by regex string replace.

**Comment by JobJob** [comment]
Firstly, have you seen the stack traces in 0.6 - they are much clearer, probably obviate the need for this particular feature.

If you still want to go with it, you're right you might have wanted `post_error_hook`, which gets called [here](https://github.com/JuliaLang/IJulia.jl/blob/master/src/execute_request.jl#L208) but it doesn't pass the backtrace, and can't modify the error string.

You could probably do what you wanted by modifying the [error_content function](https://github.com/JuliaLang/IJulia.jl/blob/master/src/execute_request.jl#L72). Particularly the first line looks like it handles the traceback.

Ok HTH.

**Comment by phlavenk** [comment]
I just tryed the julia 0.6 and you are right, the stacktraces are improved a lot. So I'll giveup for now and wait to for 0.6 to see if it proves nice enough to use. Thank you for your help.
