### ISSUE TITLE
How to install IJulia without installing conda?

### ISSUE THREAD

**Issue by iamthad** [JuliaLang/IJulia.jl#529]
An existing `jupyter` can be used by setting `ENV["JUPYTER"]`. Similarly, an existing `conda` can be used by setting `ENV["CONDA_JL_HOME"]`. 

Personally, I don't generally use `conda`. If I have a functional `jupyter` that meets IJulia's requirements, how can I avoid installing `conda` at all? It appear to only be necessary for installing `jupyter`.

**Comment by stevengj** [comment]
Just set the JUPYTER environment variable. The Conda.jl package will still be installed, but it won't install a miniconda distro if Conda.add is never called.

**Comment by yuyichao** [comment]
You don't need to install `conda`. `Conda.jl` will install it only on demand.

**Comment by iamthad** [comment]
Thanks for the quick response. I was confusing "Building Conda" with actually installing it.

**Comment by yuyichao** [comment]
> Building Conda

If you don't see super long output then it doesn't actually install anything. You'll not mistaken it if it does ;-p
