### ISSUE TITLE
Broken tab completion when there is nothing to tab-complete

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/IJulia.jl#530]
I get this error when tab-completing a string, but only if there is no file or folder to complete, eg: `"nocompletion\<TAB\>" gives this:

```
KERNEL EXCEPTION
BoundsError: attempt to access "\"nocompletion\""
  at index [-1]

Stacktrace:
 [1] next at ./strings/string.jl:197 [inlined]
 [2] getindex(::String, ::Int64) at ./strings/basic.jl:32
 [3] ind2chr(::String, ::Int64) at ./strings/basic.jl:269
 [4] complete_request(::ZMQ.Socket, ::IJulia.Msg) at /home/fredrik/.julia/v0.6/IJulia/src/handlers.jl:40
 [5] eventloop(::ZMQ.Socket) at /home/fredrik/.julia/v0.6/IJulia/src/eventloop.jl:8
 [6] (::IJulia.##9#12)() at ./task.jl:335
```

At my home computer this is shown in the terminal where I started the notebook, but at work it was shown inline in the notebook.

I am on `julia master` and `IJulia 1.5.0`

**Comment by stevengj** [comment]
That's weird, I can't reproduce.  Does it happen for you with julia 0.5.x?

**Comment by fredrikekre** [comment]
I get the same on 0.5.1. Maybe I never realized until today since this was the first time it leaked into the notebook. This is on 0.5.1:

```
KERNEL EXCEPTION
BoundsError: attempt to access 11-element Array{UInt8,1} at index [-1]

 in next at ./strings/string.jl:92 [inlined]
 in getindex(::String, ::Int64) at ./strings/basic.jl:70
 in ind2chr(::String, ::Int64) at ./strings/basic.jl:227
 in complete_request(::ZMQ.Socket, ::IJulia.Msg) at /home/fredrik/.julia/v0.5/IJulia/src/handlers.jl:40
 in eventloop(::ZMQ.Socket) at /home/fredrik/.julia/v0.5/IJulia/src/eventloop.jl:8
 in (::IJulia.##13#19)() at ./task.jl:360
```

**Comment by fredrikekre** [comment]
I just tried on my mac (the above mentioned computers where both ubuntu) and I get the same on 0.5.1 and on master

**Comment by stevengj** [comment]
I couldn't get it with your example above, but I got a similar exception for typing tab after `plt[:hi`.

**Comment by stevengj** [comment]
Interestingly, the Base.REPLCompletions.completions` function seems to be quite inconsistent about what it returns when no completions are found:
```
julia> Base.REPLCompletions.completions(code, 7)
(String[],0:-1,false)

julia> Base.REPLCompletions.completions("foobar", 6)
(String[],1:6,true)
```
IJulia works fine in the second case, but not the first.

**Comment by fredrikekre** [comment]
Thanks, it fixed my issue too.
