### ISSUE TITLE
How to turn a dict into application/json?

### ISSUE THREAD

**Issue by BenRussert** [JuliaLang/IJulia.jl#531]
Is there support in IJulia or another package to turn a dict into raw application/json? What I am looking for is analogous to the [`IPython.Display.JSON`](http://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#IPython.display.JSON) function.

**Comment by stevengj** [comment]
`JSON.json(IJulia.display_dict(x))`

**Comment by BenRussert** [comment]
I tried this, but it still outputs `text/plain` mimetype.

**Comment by stevengj** [comment]
What type of x are you passing? Does it have `show` methods for other mime types?

**Comment by BenRussert** [comment]
Just a dict. In the example below the `data` variable is a python dict. I am trying to get the same functionality to work with julia.

![](https://cloud.githubusercontent.com/assets/13285808/24886344/3270935a-1e54-11e7-9a48-2454fa4f8cc7.gif)

**Comment by stevengj** [comment]
If you want to turn a dict into JSON, just do
```
using JSON
JSON.json(mydict)
```
See the JSON.jl package for more info.

**Comment by stevengj** [comment]
Or is it that you want the display widget?

**Comment by BenRussert** [comment]
If the results of `JSON.json(mydict)` returned a `json` mimetype instead of `text/plain` the widget in the example would work, so that is what I am looking to achieve.

**Comment by stevengj** [comment]
I tried editing `IJulia/src/inline.jl` to add "application/json" to the list of supported MIME types, and then did:
```
using JSON
display("application/json",JSON.json(Dict("foo"=>3, "bar"=>[1,2,17])))
```
and it displayed nothing.

Are you sure that this is actually supported in Jupyter?  Maybe it is a custom widget in IPython.  @Carreau, do you know how JSON widgets are displayed?

**Comment by Carreau** [comment]
Using `application/json` should work, but you would need to use [atom hydrogen](https://atom.io/packages/hydrogen) , the classic notebook does not have a default render for 'application/json'. It has been a long standing issue, but nobody took the time to write the code to do that (contribution welcome).

**Comment by BenRussert** [comment]
I should have mentioned I was doing this in hydrogen. I can try the example @stevengj gave above.

**Comment by BenRussert** [comment]
So close.

python:
![ipython](https://cloud.githubusercontent.com/assets/10860657/25461653/cc4710aa-2aaf-11e7-8c5c-067b7ff52f5f.png)
IJulia:
![ijulia](https://cloud.githubusercontent.com/assets/10860657/25461659/db5366f2-2aaf-11e7-8745-be4f23d03e17.png)

**Comment by stevengj** [comment]
Seems like the `display` issue was fixed, and the remaining issue is on the notebook side.
