### ISSUE TITLE
Dead kernel

### ISSUE THREAD

**Issue by ablekh** [JuliaLang/IJulia.jl#532]
Hi everyone, I'm trying to install and test IJulia kernel on JupyterHub (on Debian 7, if it matters). JupyterHub has been installed a while ago (Python 2/3 and MATLAB kernels) and is running well (knocking on wood ...). I installed Julia as a binary (neither via packages due to relatively old Debian, nor from source - due to other reasons). Then I installed IJulia via `Pkg.add("IJulia")`. Then I had to manually move the kernelspec to a common location (specifically, to `/usr/local/share/jupyter/kernels`), based on @minrk's advice in some other thread. After that, just in case, I restarted JupyterHub and tried to create a Julia notebook. However, unfortunately, the kernel connected for a moment and then I was greeted with a generic error message about dead kernel (offering restart, which didn't help anyway). I have researched for a while and tried various approaches, including updating and building the package as well as following advice in the section "Debugging IJulia problems" (enabling verbose/error output), but to no avail. Any help will be much appreciated.

**Comment by stevengj** [comment]
Usually in the terminal where you are running the `jupyter` process there will be a more informative error message.   (Or in some log file; I'm not sure how JupyterHub works.)

**Comment by ablekh** [comment]
@stevengj Thank you for the advice. I forgot that I'm using `nohup` when starting JuputerHub, so the "more informative error message" went to `nohup.out`. The relevant error message (I'm omitting similar restart error messages) is this:

```
[I 2017-04-30 05:42:05.120 ablekh handlers:155] Creating new notebook in
[I 2017-04-30 05:42:08.582 ablekh kernelmanager:117] Kernel started: 19e7d270-23c3-43ef-90e8-24bee642c35f
^[[1m^[[31mERROR: could not open file /root/.julia/v0.5/IJulia/src/kernel.jl
 in include_from_node1(::String) at ./loading.jl:488
 in process_options(::Base.JLOptions) at ./client.jl:265
 in _start() at ./client.jl:321
```

The file in question has the following attributes (I'm also including info on some other files/dirs):

```
-rw-r--r-- 1 root root 801 Apr 30 05:00 /root/.julia/v0.5/IJulia/src/kernel.jl

drwxr-xr-x  5 root    root          4096 Apr 30 05:00 .julia

/usr/local/share/jupyter/kernels (not sure why sticky bit is set for some - likely need to fix it):

drwxr-xr-x 2 root staff 4096 Mar 25 00:57 imatlab
drwxr-sr-x 2 root staff 4096 Apr 30 06:45 julia-0.5
drwxr-sr-x 2 root staff 4096 Apr 30 06:09 python2
drwxr-xr-x 2 root staff 4096 Jul 21  2016 python3
drwxr-sr-x 2 root staff 4096 Oct 18  2016 template
```

**Comment by ablekh** [comment]
Perhaps, I can try changing group for IJulia to `staff`, but the files are readable for group & others anyway...

**Comment by stevengj** [comment]
Closing as no one has reproduced anything like this recently.

**Comment by ablekh** [comment]
@stevengj Thank you! My environment has changed. I will post here, if I experience this problem again.
