### ISSUE TITLE
Adding Ijulia kernel to an already installed Jupyter for dummies!

### ISSUE THREAD

**Issue by mehdirezaie** [JuliaLang/IJulia.jl#533]
Hi!
Sorry if it is a dumb question, but I am new to Jupyter and Julia, so here I am trying to get some help. I would highly appreciate any form of help.

So based on the documentation, we just need to do:
```
ENV["JUPYTER"] = Path_2_JUPYTER
Pkg.build("IJulia")
```
My question is what the path to jupyter is exactly?
In fact, which one of the following addresses should be used?
```
Mehdis-MacBook-Air:~ mehdi$ jupyter --paths
config:
    /Users/mehdi/.jupyter
    /Users/mehdi/anaconda/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /Users/mehdi/Library/Jupyter
    /Users/mehdi/anaconda/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /Users/mehdi/Library/Jupyter/runtime
```
Thanks!
Mehdi

**Comment by stevengj** [comment]
It is the path to the `jupyter` probram itself.  `which jupyter`  should tell you.

**Comment by mehdirezaie** [comment]
Thanks @stevengj , but could you please be more specific?

**Comment by yuyichao** [comment]
What do you need to be more specific than

> `which jupyter` should tell you.

?

**Comment by mehdirezaie** [comment]
@yuyichao Better to ask, what command and where I should type it to get the path to the `jupyter` program?
I am so sorry if this is too obvious and dumb, I am new to Jupyter

**Comment by yuyichao** [comment]
You type the the `whuch Jupiter command at the same place you typed. `jupyter --paths`
