### ISSUE TITLE
IOPub data rate exceeded

### ISSUE THREAD

**Issue by cormullion** [JuliaLang/IJulia.jl#534]
When loading SVGs into a notebook, I sometimes see this in pink:

```
IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.
```

I'd like to try changing the limit (at  my own risk of course :)), but not sure what kind of variable it is or how to change it.

**Comment by stevengj** [comment]
Duplicate of #528.
