### ISSUE TITLE
Kernel dies upon initialization

### ISSUE THREAD

**Issue by kxgao** [JuliaLang/IJulia.jl#535]
Hi,

I have an IPython notebook running some code in Julia 0.5.1. A few days ago it was working, but now when I initialize it it throws the error 'the kernel appears to have died'. I get the same error when I create a new notebook.

Any idea on what could be the cause?

Thanks.

**Comment by stevengj** [comment]
See https://github.com/JuliaLang/IJulia.jl#debugging-ijulia-problems

**Comment by stevengj** [comment]
Closing as not reproducible.
