### ISSUE TITLE
Slow/Frozen Jupyter Notebook

### ISSUE THREAD

**Issue by chelseas** [JuliaLang/IJulia.jl#536]
When I have "include" statements in an IJulia notebook and I run the cell containing that code more than once, the cell never finishes executing the second or third time. I have to shut down the IJulia notebook and re-start it in order to execute the code again successfully. 

When I have code where the entirety of the code is written in the cell (no use of the "include" statement) it executes fine multiple times.

[frozen_notebook_example.zip](https://github.com/JuliaLang/IJulia.jl/files/977205/frozen_notebook_example.zip)

See the minimal example attached.

**Comment by stevengj** [comment]
Works fine for me.

![image](https://cloud.githubusercontent.com/assets/2913679/25722560/a7dddf8a-30e2-11e7-8da7-7ded13f05793.png)

What is the output of `versioninfo(true)`?

**Comment by chelseas** [comment]
This is the output of versioninfo(true):
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
  WORD_SIZE: 64
  uname: Darwin 15.6.0 Darwin Kernel Version 15.6.0: Thu Sep  1 15:01:16 PDT 2016; root:xnu-3248.60.11~2/RELEASE_X86_64 x86_64 i386
Memory: 8.0 GB (173.046875 MB free)
Uptime: 603754.0 sec
Load Avg:  2.1728515625  2.1943359375  1.93701171875
Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz: 
       speed         user         nice          sys         idle          irq
#1  2600 MHz   
In [ ]:


Also I think I have more precisely pinpointed the problem. Try running all the cells, saving the notebook, and then running them all again. This is what freezes my notebook.
​

**Comment by stevengj** [comment]
This issue seems gone with recent versions?
