### ISSUE TITLE
Avoiding output truncation during a simple animation

### ISSUE THREAD

**Issue by ajdunlap** [JuliaLang/IJulia.jl#537]
When you use clear_output repeatedly to create a simple animation, stdio_bytes is not reset to 0, so after a certain amount of time the animation is stopped because stdio_bytes is too big. I propose that clear_output reset stdio_bytes to 0. I would submit a patch for this (it's probably just one line to add stdio_bytes[] = 0 to the definition of clear_output) but I'm not confident in my ability to download and set up everything properly to test it.

**Comment by stevengj** [comment]
cc @JobJob

**Comment by stevengj** [comment]
That seems reasonable.

**Comment by JobJob** [comment]
Great bug report and fix, well played all round.
