### ISSUE TITLE
Jupyter Notebook not displaying PyPlot graphs

### ISSUE THREAD

**Issue by udion** [JuliaLang/IJulia.jl#538]
When I try to plot a graph using PyPlot in jupyter notebook I am getting the following as object but not the graph itself, how to display the graph inside the notebook?

![selection_014](https://cloud.githubusercontent.com/assets/18963158/25770067/7e3f56e6-3249-11e7-9898-781136a2ace6.png)

**Comment by stevengj** [comment]
It works for me.  What is `versioninfo(true)`?

(PS. Note that if you want to use `plt.xxx` for everything, you can do `import PyPlot; plt = PyPlot` instead of `using`, which imports things like `plot` into the global namespace.)

**Comment by Kelvyn88** [comment]
Close this issue please.
