### ISSUE TITLE
Is this neat solution for d3.js in notebooks possible in IJulia?

### ISSUE THREAD

**Issue by zahachtah** [JuliaLang/IJulia.jl#545]
Hi, I do some d3.js interactive figures at times and found this neat way to do this in a python notebook using the magic functionality. Julia doesn't use that but I figure there must be a similar way to do it. The neat solution is found [here](https://github.com/ResidentMario/py_d3)

with the main code for doing it is [here](https://github.com/ResidentMario/py_d3/blob/master/py_d3/py_d3.py)

I wish I was better coder to solve this my self but I have to ask here instead if someone has a good idea for this.

Many thanks!

**Comment by stevengj** [comment]
You can just do:
```
display("text/javascript", """
...
""')
```
to insert arbitrary JavaScript into the notebook.

The `%%d3` magic just inserts [a particular bit of JavaScript into the cell](https://github.com/ResidentMario/py_d3/blob/master/py_d3/py_d3.py).

If you wanted to, you could easily define an Julia package providing a `d3` string macro that does the same thing, i.e. 
```
macro d3_str(s)
    display("text/javascript", d3stuff * s)
end
```
where `d3stuff` is the `requirejs.config` etcetera similar to the `%d3` cell magics.   Then you could just do
```
d3"""
....my javascript code...
"""
```
exactly like `%d3`.

**Comment by stevengj** [comment]
(The reason why IJulia doesn't support "magics" is that they are not necessary: everything that requires magics in IPython can be done with ordinary Julia functions and macros.

**Comment by JobJob** [comment]
I liked this idea, I whipped up a quick package: https://github.com/JobJob/D3Magic.jl

**Comment by zahachtah** [comment]
One cannot other but love the Julia community <3

Thanks all!

**Comment by zahachtah** [comment]
I remember seeing blink.jl being used interactively, but anyone know if its possible to control in-notebook d3 graphs interactively using the sweet d3Magic.jl??

**Comment by JobJob** [comment]
Not sure exactly what you mean, but please open an issue on the D3Magic repo (and maybe close this issue). Also fyi, just added a section to the README about syntax highlighting.

**Comment by zahachtah** [comment]
ok!
