### ISSUE TITLE
duplication of .ji files

### ISSUE THREAD

**Issue by PaulSoderlind** [JuliaLang/IJulia.jl#549]
Short version: IJULIA creates its own version of .ji files (for all packages).

Longer version:
My .juliarc.jl contains this line:
ENV["JULIA_PKGDIR"] = "D:\\Julia\\Packages"
and this puts all packages under D:\Julia\Packages\v0.5, while the .ji files end up in C:\Users\MyUserName\.julia\lib\v0.5. (Yes, this is Win7.) All is well so far.

IJULIA seems to create its own .ji files: it recompiles all packages and places the resulting .ji files under D:\Julia\Packages\lib\v0.5. Not a tragedy, but it seems unnecessary. 

Is there an easy way around this? Setting some additional environment variable?

/Paul S

**Comment by stevengj** [comment]
Have your .juliarc file push the desired cache directory to the front of `Base.LOAD_CACHE_PATH`

**Comment by PaulSoderlind** [comment]
Yes,
```
insert!(Base.LOAD_CACHE_PATH,1,"D:\\Julia\\Packages\\lib\\v0.5")
```
seems to work well. Thanks.
