### ISSUE TITLE
Convert to script - preserve markdown to comments

### ISSUE THREAD

**Issue by mirestrepo** [JuliaLang/IJulia.jl#554]
When downloading (or converting) a Julia notebook to script, markdown is not perserved. In Python, markdown is converted to comments and this seems to be a sensible behavior

**Comment by stevengj** [comment]
What conversion tool are you using?  IJulia itself does no conversion.

**Comment by mirestrepo** [comment]
Either `jupyter nbconvert --to script notebook` or the file/export menu within the notebook. Since the results are different for python and Julia notebooks, I thought it would be related to IJulia

**Comment by stevengj** [comment]
@Carreau, is there some style sheet that needs to be set up for nbconvert to know about Julia comments?

**Comment by Carreau** [comment]
Oops, that seem to be an oversight, the config option is not exposed. 

you can workaround with this:

```
$ cat julia.tpl
{%- extends 'script.tpl' -%}

{% block markdowncell scoped %}
{{ cell.source | comment_lines(prefix='# ') }}
{% endblock markdowncell %}
```
```
$ jupyter nbconvert --to script my_notebook.ipynb --template julia  ; cat my_notebook.jl
[NbConvertApp] Converting notebook my_notebook.ipynb to script
[NbConvertApp] Writing 92 bytes to my_notebook.jl

# This is a julia notebook
#
#  - with markdown
#
#  > citation

1+1

println("Hey")
```

**Comment by Carreau** [comment]
i'm going to open an issue on nbconvert.

**Comment by stevengj** [comment]
Closing as an nbconvert issue.
