### ISSUE TITLE
Odd behaviour of IndexStyle() with Nullable Arrays

### ISSUE THREAD

**Issue by questors** [JuliaLang/IJulia.jl#556]
In IJulia using Julia 0.6.0-rc3  if I write in the first cell with a newly started kernel:
```
#Pkg.add("NullableArrays")
using NullableArrays
A = NullableArray([1.]);
```
and then in the next cell:  `IndexStyle(A)` I get a response:  `IndexLinear()`

But if I drop the semi-colon suppressing the output: 
```
#Pkg.add("NullableArrays")
using NullableArrays
A = NullableArray([1.])
```
and then in the next cell:  `IndexStyle(A)` I get a response:  `IndexCartesian()`

I do not get the same behaviour in the REPL, it always returns `IndexLinear()`
I have gert the same behaviour on JuliaBox using Julia 0.6.0-rc2

**Comment by stevengj** [comment]
Interesting, I can reproduce this.  @yuyichao, I'm guessing it is some kind of world-age problem, possibly a bug in Julia itself?

**Comment by questors** [comment]
I also cannot get a view of a `NullableArray` to display in IJulia which might be related.  My amateur attempt to track down why, revealed the `IndexStyle` issue from inspection of the `SubArray` type parameters.

**Comment by stevengj** [comment]
Seems like this issue is not reproducible these days?
