### ISSUE TITLE
tab completion for strings/paths

### ISSUE THREAD

**Issue by kalmarek** [JuliaLang/IJulia.jl#557]
```julia
mkdir("./r=2")
path = "r=2<TAB>
```
results in 
```
KERNEL EXCEPTION
BoundsError: attempt to access 11-element Array{UInt8,1} at index [-1]

 in ind2chr(::String, ::Int64) at ./strings/basic.jl:227
 in complete_request(::ZMQ.Socket, ::IJulia.Msg) at /home/kalmar/.julia/v0.5/IJulia/src/handlers.jl:40
 in eventloop(::ZMQ.Socket) at /home/kalmar/.julia/v0.5/IJulia/src/eventloop.jl:8
 in (::IJulia.##13#19)() at ./task.jl:360
```
the same with `mkdir("r2")` completes to `"r2/`. 
This might be a superficial example, but when the directory with `=` in its name is not empty, it is not possible to complete names of files inside, whereas without `=` in the name it is.

Julia 0.5.2;
IJulia of today

I'm not sure how related https://github.com/JuliaLang/IJulia.jl/issues/530 is.

**Comment by stevengj** [comment]
I can't reproduce this kernel exception.  What do `versioninfo()` and `IJulia.jupyter_vers` and `IJulia.execute_msg.header["version"]` give?

Separately, I do see that the tab completion is getting confused by the `=`.  That's due to a limitation of [`IJulia.find_parsestart`](https://github.com/JuliaLang/IJulia.jl/blob/1b17812b9ee2a544821fe4d00cfd9ac93a2491e5/src/handlers.jl#L6-L21), which should probably be improved.

**Comment by kalmarek** [comment]
```
Julia Version 0.5.2
Commit f4c6c9d4bb* (2017-05-06 16:34 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE NO_AFFINITY HASWELL)
  LAPACK: liblapack
  LIBM: libm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake-avx512)
```
`IJulia.jupyter_vers` is `v"4.3.0"`
`IJulia.execute_msg.header["version"]` is `"5.0"`

**Comment by stevengj** [comment]
I'm confused by the `in complete_request(::ZMQ.Socket, ::IJulia.Msg) at /home/kalmar/.julia/v0.5/IJulia/src/handlers.jl:40`, since line 40 of `handlers.jl` is not in the `complete_request` function in the latest IJulia.  Are you sure you aren't using an older version of IJulia?

**Comment by kalmarek** [comment]
Hmm... before opening this I run `Pkg.update()` followed by `Pkg.rm("IJulia")`, `Pkg.add("IJulia")`.

However after physically removing `IJulia` and `IJulia.ji` from `.julia/...` and running `Pkg.update()` I can no longer reproduce kernel exception.

**Comment by stevengj** [comment]
`Pkg.rm` may refuse to remove the package if it is dirty (if you have local edits).
