### ISSUE TITLE
IJulia build on Debian fails to find system jupyter and jupyter-notebook-kernelspec

### ISSUE THREAD

**Issue by ajalexei** [JuliaLang/IJulia.jl#559]
Installation of IJulia package on Debian Buster, julia 0.6.0 has two issues:
1. The system installation of jupyter is ignored, due to a different name of the script: jupyter-notebook (Debian) vs jupyter (expected). This is fixed by setting the ENV["JUPYTER"] to point to the right script.
2. The other issue:
`LoadError: could not spawn `/usr/bin/jupyter-notebook-kernelspec install --replace --user /home/alexei/.julia/v0.6/IJulia/deps/julia-0.6`: no such file or directory (ENOENT)
while loading /home/alexei/.julia/v0.6/IJulia/deps/build.jl, in expression starting on line 7`
is caused by Debian using "jupyter-kernelspec" name rather than the "jupyter-notebook-kernelspec" expected by IJulia. Also the script is placed in "jupyter-client" package, different from the "jupyter-notebook" package that provides the notebooks.
I suggest either fixing this on the IJulia side or adding this info to Troubleshooting.

**Comment by stevengj** [comment]
A PR for build.jl would be welcome.

**Comment by stevengj** [comment]
We no longer use `jupyter kernelspec`, so this issue is moot.
