### ISSUE TITLE
IJulia status replies come in really slowly

### ISSUE THREAD

**Issue by JMurph2015** [JuliaLang/IJulia.jl#562]
I was benchmarking the performance of a jupyter_client backend, and I hypothesized that the fastest kernel for execution overhead times would be IJulia given that it's native Julia and not a IPython wrapper.  IJulia is slightly faster when it comes to sending 'execute_reply's, but it is an order of magnitude (~70ms or much more sometimes, >400ms) slower than IPython to publish the 'idle' status on IOPub.  

This is important because my client needs to wait for the 'idle' message so that it knows when all stdout and stderr streams have been pushed.  Thus, IJulia is roughly an order of magnitude slower or more when it comes to real world performance for me.

I don't really know how to go about fixing this, but I thought it was worth posting an issue to raise awareness.

**Comment by yuyichao** [comment]
https://github.com/JuliaLang/IJulia.jl/pull/491

**Comment by JMurph2015** [comment]
This is pretty evil behavior if you ask me.  

Such arbitrary delays are not a part of the kernel protocol and degrade the interoperability of the kernels (due to my application now having to specially initialize IJulia kernels differently than others so that things don't slow to an absolute crawl).  

A Signal interface on which processes can require Julia to hold is one thing, but the stopgap of just setting an arbitrary (and relatively high) delay on all 'idle' messages is pretty unsightly (even if it is resettable by user processes).  It should always be the bare minimum the currently running code needs (aka an async hold condition).

**Comment by JMurph2015** [comment]
For context, your default delay slows IJulia from 1.5x faster than IPython to 42.3x slower than IPython, aka slows Julia down by a factor of 63.5.  That's a _nearly two orders of magnitude_ slowdown.

**Comment by JMurph2015** [comment]
Just an update, I created a fork and made a channel interface (using channels with size 1 as semaphores).  If you want to hold the 'idle' reply, you just register a semaphore and fulfill it sometime between t=0 and t=timeout.  When you are done you just call IJulia.remove_hold_channel with the instance, or you close the channel and it will automatically be culled.

**Comment by koffie** [comment]
I think this is indeed an important thing to fix. Nice to see that you made a pull request for this. This timeout of 0.5 seconds is really ridiculous, it is so long that it is even noticeable by the enduser. Just in case someone comes here before the pull request is merged: just do the following in your notebook to make it feel snappy again.
```
import IJulia
IJulia.set_idle_delay(0.01)
```

**Comment by stevengj** [comment]
As I said in #563, once Interact.jl is fixed we can get rid of the delay entirely.

**Comment by JobJob** [comment]
> it is so long that it is even noticeable by the enduser

Hi @koffie out of curiosity - what is it that is noticeable to you?

**Comment by JMurph2015** [comment]
@JobJob @stevengj Any status on the removal of the delay?  Also, I find it especially noticeable when Julia clearly has already compiled something, but the notebook still pauses as if it's recompiling every time.  When I turn the delay off, it goes back to the expected ~instant response to running already compiled code.

**Comment by JobJob** [comment]
> but the notebook still pauses

What do you mean by pauses? I thought this issue only affected the whether the busy indicator in the top right displays (and the hourglass favicon in newer Jupyter versions). Delaying the "Status: idle"  shouldn't affect how quickly the output or results display. Does it for you?

Anyway, I think at the end of of the *looooong* discussion in #563, an amusing twist was revealed:  the bug that the idle delay was working around might have been fixed in Jupyter.

I just tested now with 
```
IJulia.set_idle_delay(0.0)
using Interact, Reactive

p = Signal(0.0)
push!(p, "1") #error because "1" is a String and p is a Float64 Signal
p
```

And I couldn't replicate the old Interact problem (truncated stacktrace) on Jupyter 5.x, so I'm happy for us to remove all the `idle_delay` stuff.

**Comment by JMurph2015** [comment]
@JobJob As far as I could tell this morning (admittedly I was not properly caffeinated at the time) when doing some problem sets, responses were coming in more slowly when the delay was off than when it was on.  Not sure why, maybe it is peculiar to the behavior of nteract or something like that, but just felt that way.  I'm going to open a PR on removing the delay!
