### ISSUE TITLE
How to install and run Julia in Jupyter on windows? 

### ISSUE THREAD

**Issue by hwdong** [JuliaLang/IJulia.jl#566]
I installed python2.7 ,then "pip install jupyter", then download and install julia.
The I run : 
Env["JUPYTER"]= ""C:/python 2.7/script"
Pkg.add("IJulia") 
Pkg.update("IJulia") 

But when I run "jupyter notebook" ,there is no Julia on the  Jupyter "new "menu.

**Comment by stevengj** [comment]
Presumably, you want:
```
ENV["JUPYTER"]= "C:\\python 2.7\\script\\jupyter"
Pkg.build("IJulia")
```
The `ENV["JUPYTER"]` (note capitalization)` needs to be the actual path of the `jupyter` executable, not just the path to the directory containing `jupyter`.

**Comment by stevengj** [comment]
Note that github issues are not the right place to ask usage questions; see e.g. https://discourse.julialang.org/ for that.

If you don't understand concepts like paths, you might be better off letting Julia install and run its own Jupyter for you:
```jl
ENV["JUPYTER"]="" # tells IJulia to install its own Jupyter
Pkg.build("IJulia")

using IJulia
notebook()
```
