### ISSUE TITLE
failed to install IJulia on ubuntu

### ISSUE THREAD

**Issue by hwdong** [JuliaLang/IJulia.jl#568]
#julia> Pkg.build("IJulia")

julia> Pkg.build("IJulia")
INFO: Building Conda
INFO: Building MbedTLS
INFO: Building ZMQ
INFO: Building IJulia
INFO: Found Jupyter version 4.3.0: /usr/local/bin/jupyter
Writing IJulia kernelspec to /home/s/.julia/v0.6/IJulia/deps/julia-0.6/kernel.json ...
Installing julia kernelspec julia-0.6
[InstallKernelSpec] Removing existing kernelspec in /home/s/.local/share/jupyter/kernels/julia-0.6
[Errno 13] Permission denied: '/home/s/.local/share/jupyter/kernels/julia-0.6/kernel.json'
[InstallKernelSpec] Removing existing kernelspec in /home/s/.local/share/jupyter/kernels/julia-0.6
[Errno 13] Permission denied: '/home/s/.local/share/jupyter/kernels/julia-0.6/kernel.json'
===============================[ ERROR: IJulia ]================================

LoadError: failed process: Process(`/usr/local/bin/jupyter-kernelspec install --replace --user /home/s/.julia/v0.6/IJulia/deps/julia-0.6`, ProcessExited(1)) [1]
while loading /home/s/.julia/v0.6/IJulia/deps/build.jl, in expression starting on line 7

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: IJulia had build errors.

 - packages with build errors remain installed in /home/s/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("IJulia")`
 - build a single package by running its `deps/build.jl` script

================================================================================

**Comment by stevengj** [comment]
As the `Permission denied: '/home/s/.local/share/jupyter/kernels/julia-0.6/kernel.json'` message indicates, you have a permissions problem in your home directory.  If you don't know how to change ownership/permissions in your home directory (e.g. `sudo chown -R $USER /home/s/.local`), you should find someone locally at your institution who knows Linux and can help you.
