### ISSUE TITLE
Installation doesn't work system-wide

### ISSUE THREAD

**Issue by newey01c** [JuliaLang/IJulia.jl#571]
I'm writing a set of Ansible scripts to run this kernel on a multi-user Jupyter server but I can't seem to get it installed system-wide - is there an easy way to do this?

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/IJulia.jl/issues/519 not really a IJulia issue since it has provided enough hook to do that (see my comment in that issue) within the current framework.
