### ISSUE TITLE
Erratic Behavior in cell

### ISSUE THREAD

**Issue by rand5** [JuliaLang/IJulia.jl#578]
I was working in a notebook when suddenly the code in a cell disappeared. I was able to select the cell and convert it from `code` to `markdown`, at which point I could see the the code that had been there, but I am unable to convert the cell back from `markdown` to `code`, or do anything else with it for that matter. When I copy the markdown text into a cell in a new notebook, the code is truncated to the first 30 or so lines out of ~250. Clicking within the cell causes 20 more lines to appear, and so on, until the cell collapses and nothing is shown.
Tested on both v0.5 and v0.6 with same result when copy+pasting the same chunk of code.

**Comment by stevengj** [comment]
Sounds like a Jupyter bug, not IJulia, and should probably be reported there.

(See if you can reproduce the same problem with the Python kernel.)
