### ISSUE TITLE
If clause in generator expression breaks automatic indentation

### ISSUE THREAD

**Issue by neil-lindquist** [JuliaLang/IJulia.jl#580]
I've noticed that the automatic indentation breaks when using an if statement in a generator expression. 
This happens in both the text file editor and the notebook editor.
For example  after `[x for x in [1, 2, 3] if x > 1]`, the auto indent will go to 12 spaces (3 levels).  However, `[x for x in [1, 2, 3]]` works as expected and doesn't cause indentation on the next line.
I tried this on IJulia's master branch and it still had the issue.

**Comment by stevengj** [comment]
This needs to be fixed [in CodeMirror](https://github.com/codemirror/CodeMirror/tree/master/mode/julia).
