### ISSUE TITLE
"WARNING: Compat.AsyncCondition is deprecated" showed when using Jupyter.

### ISSUE THREAD

**Issue by MBL-Quincy** [JuliaLang/IJulia.jl#581]
Env: 
macOS 10.12.6
Jupyter  4.3.0
IJulia 1.6.0

when begin an IJulia kernel, it showed "`WARNING: Compat.AsyncCondition is deprecated, use Base.AsyncCondition instead.`".

**Comment by stevengj** [comment]
Fixed by https://github.com/JuliaInterop/ZMQ.jl/pull/152

(Note that this is in ZMQ.jl, not IJulia.jl.)

**Comment by stevengj** [comment]
You don't mention what Julia version you are using, but it sounds like you may be on 0.7?  I would generally recommend sticking with 0.6 unless you are a Julia developer.

**Comment by MBL-Quincy** [comment]
Thank you! (It's 0.6)

**Comment by stevengj** [comment]
Oh I see what happened: Compat just deprecated the `Compat.AsyncCondition` binding when they dropped 0.4 support.
