### ISSUE TITLE
MacPorts jupyter expects versioned command names

### ISSUE THREAD

**Issue by dyne2meter** [JuliaLang/IJulia.jl#582]
I have read https://github.com/JuliaLang/IJulia.jl/issues/453 because I am getting a similar error when trying to use my macports installation as my jupyter environment in julia.

This problem crops up in trying to execute the script with the macports jupyter installation in OS X 10.9. In reference to #453, I avoid using pip with macports.

I think the following is why (but it could be much more complicated than I realize):
https://trac.macports.org/ticket/50608

If I could set my ENV["JUPYTER"} properly this would save me well over half a gigabyte of miniconda and auxiliary software in the .julia directory.

I've deleted ~/.julia until I know that installing the full IJulia package is absolutely necessary.

_Edit to add_: It occurs to me that I could try adding ipython and jupyter to the Apple python2.7 installation, but I can't rightly recall just how large that will be in comparison to the standard IJulia package which seems to duplicate several hundred megabytes of dylibs in running the miniconda or whatever other reason there might be for doing that.

**Comment by stevengj** [comment]
See [this comment](https://trac.macports.org/ticket/50608#comment:4) about how to set your `PATH` so that the `jupyter` command works.

Alternatively, if you want to provide a PR (patch) to the IJulia build script, so that if you supply `jupyterX.Y` then it looks for `jupyterX.Y kernelspecX.Y` etcetera for MacPorts, that would be welcome.

**Comment by dyne2meter** [comment]
That my current macports jupyter won't support IJulia has deeper roots than I thought: I don't think a simple patch to the build script would fix what's wrong, there, even if I had a clue how to go about that business.

My macports jupyter executable does not even list kernelspec as one of its available subcommands. This is odd, because that macports ticket I referenced leads off with a probe for subcommands that does include it. As far as I know, installing kernels is way above my paygrade, and that is why the pre-cooked (brewed?) IJulia installation may be the only way to go for me.

Interestingly, I also had a look inside my sage installation, which is also full of python and boasts its own notebook interface. This interface is heavily customized, probably for the same reasons that IJulia's is. There are executable jupyter executables (with unversioned filenames, even!) and a kernelspec is visible, but when I stick that in as my ENV["JUPYTER"] path, the version of jupyter that gets returned is 0.0.0, which is too low to suit the IJulia build script. Even though the sage jupyter version I have is actually 4.x, using it seems also (sadly) unworkable from where I sit.

Someday, when the world improves, we won't be duplicating gigabytes of Python to install several different math packages. It's not that we lack disk space; the situation just shouts wastage. Maybe that improved world will be Linux. Sorry to have troubled you, and thanks for my little sniff of the rarefied air of a big software project.

PS: This news might require another change to the thread title, but I'll leave that to the experts, too.

**Comment by stevengj** [comment]
@dyne2meter, according to the linked thread, if the command is `jupyter3.4`, then kernelspec is `jupyter3.4 kernelspec3.4`.  Potentially our build script could check for this.

(Nowadays, a lot of people have switched from macports to homebrew.)

**Comment by jjstickel** [comment]
I'm not sure when things changed with Macports' Jupyter, but this now works:
`$ jupyter-3.6 notebook`
So, now IJulia can work with Macports' Jupyter:
`$ Julia`
`julia> ENV["JUPYTER"] = "jupyter-3.6"`
`julia> Pkg.add("IJulia")`

**Comment by stevengj** [comment]
Great!
