### ISSUE TITLE
Strange behavior creating parametric mutable structs in IJulia / Jupyter

### ISSUE THREAD

**Issue by wilkieolin** [JuliaLang/IJulia.jl#592]
I'm using Jupyter 4.3.0 / IJulia 1.6.2 with Julia 0.6, and trying to create a new mutable struct with a parametric type when I encountered some very strange behavior. When typing a line like this:

`mutable struct test{a::Real, b::Real}`

If I hit return to start a new line and try typing, the new characters do not appear. Additionally, if I click on or try to select the cell, the existing text in the cell is pasted on a new line inside of the cell. This happens regardless of whether I start a new notebook or use a different browser. The issue appears to happen with earlier kernels as well. Kernels for different languages like Python do not replicate this issue.

A workaround is removing the type restrictions on the type parameter, but I'd prefer to have the full functionality available inside IJulia.

**Comment by stevengj** [comment]
I can't replicate your behavior; if I hit return in a cell containing that line it all works fine.  (I'm using Jupyter 5 ... can you try upgrading?)

Typing in cells really has nothing to do with IJulia (which is only involved when you *execute* a cell), so this is a Jupyter problem and not IJulia.

Note, by the way, that your syntax is incorrect: I think you want `mutable struct test{a<:Real, b<:Real}`.

**Comment by wilkieolin** [comment]
Thanks for the response - I will try upgrading Jupyter.
