### ISSUE TITLE
Installation error on Windows

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/IJulia.jl#593]
The following installation error was reported by a student on Windows 10 from a fresh `.julia` with Julia 0.6:
"Error executing Jupyter command 'kernelspec': [Errno 'jupyter-kernelspec' not found] 2" 
(see below for transcript).

```

INFO: Installing Jupyter via the Conda package.
INFO: Downloading miniconda installer ...
INFO: Installing miniconda ...
Warning: 'defaults' already in 'channels' list, moving to the top
DEBUG menuinst_win32:__init__(185): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Users\PROPIETARIO\.julia\v0.6\Conda\deps\usr', env_name: 'None', mode: 'None', used_mode: 'user'
INFO: Found Jupyter version 4.3.0: C:\Users\PROPIETARIO\.julia\v0.6\Conda\deps\usr\Scripts\jupyter
INFO: Installing Julia kernelspec julia-0.6
Error executing Jupyter command 'kernelspec': [Errno 'jupyter-kernelspec' not found] 2
[InstallKernelSpec] Removing existing kernelspec in C:\Users\PROPIETARIO\AppData\Roaming\jupyter\kernels\julia-0.6
[InstallKernelSpec] Installed kernelspec julia-0.6 in C:\Users\PROPIETARIO\AppData\Roaming\jupyter\kernels\julia-0.6
INFO: Package database updated

```

**Comment by dpsanders** [comment]
Various other `jupyter` subcommands also don't work. IJulia / Jupyter itself does work, but for example `Interact` cannot use `jupyter` subcommands to check that it is correctly installed.

**Comment by stevengj** [comment]
How can IJulia work if the kernelspec command didn't?

**Comment by stevengj** [comment]
Try `using Conda; Conda.update(); Conda.add("jupyter")` then `filter(s->contains(s,"jup"), readdir(Conda.SCRIPTDIR))` and `filter(s->contains(s,"jup"), readdir(Conda.BINDIR))` to see if the `jupyter` commands are there.

**Comment by dpsanders** [comment]
I'm not sure how IJulia can work.
I'll try that and report back, thanks.

**Comment by dpsanders** [comment]
Here's the results:
```
julia> filter(s->contains(s,"jup"), readdir(Conda.SCRIPTDIR))
24-element Array{String,1}:
 "jupyter-console-script.py"
 "jupyter-console.exe"
 "jupyter-kernelspec-script.py"
 "jupyter-kernelspec.exe"
 "jupyter-migrate-script.py"
 "jupyter-migrate.exe"
 "jupyter-nbconvert-script.py"
 "jupyter-nbconvert.exe"
 "jupyter-nbextension-script.py"
 "jupyter-nbextension.exe"
 ⋮
 "jupyter-run-script.py"
 "jupyter-run.exe"
 "jupyter-script.py"
 "jupyter-serverextension-script.py"
 "jupyter-serverextension.exe"
 "jupyter-troubleshoot-script.py"
 "jupyter-troubleshoot.exe"
 "jupyter-trust-script.py"
 "jupyter-trust.exe"
 "jupyter.exe"

julia> filter(s->contains(s,"jup"), readdir(Conda.BINDIR))
0-element Array{String,1}
```

**Comment by stevengj** [comment]
Could this be a resurgence of https://github.com/jupyter/notebook/issues/448 and #363?

**Comment by dpsanders** [comment]
Here's an example of `Pkg.build("Interact")`. 
Despite apparently knowing where the executables are, it can't find them:

```
Pkg.build("Interact")

Out[ ] INFO: Checking out Interact master...
INFO: Pulling Interact latest master...
INFO: No packages to install, update or remove
INFO: Building Interact
INFO: Enabling widgetsnbextension
Error executing Jupyter command 'nbextension': [Errno 'jupyter-nbextension' not found] 2
WARNING: Could not enable widgetsnbextension
WARNING: cannot determine jupyter's python path in Windows, bailing.
```

**Comment by rajraomichigan** [comment]
I encountered these all well. I removed all (other) python installations and then Interact worked..

**Comment by stevengj** [comment]
Can you reduce it to an example that does not involve Julia, i.e. running `jupyter` on the command line?

**Comment by dpsanders** [comment]
I don't know how to run jupyter from the command line in Windows :/

**Comment by stevengj** [comment]
@dpsanders, do `println(joinpath(Conda.SCRIPTDIR, "jupyter"))` in Julia, then paste that into a Windows command-line to run `jupyter`.

**Comment by BenjaminBorn** [comment]
@dpsanders did you find a solution? Some of my students also run into this problem on Windows.

**Comment by dpsanders** [comment]
Sorry for the delay. Pasting into the Windows command line gives
```
C:\Users\toodi>C:\Users\toodi\.julia\v0.6\Conda\deps\usr\Scripts\jupyter
usage: jupyter [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
               [--paths] [--json]
               [subcommand]
jupyter: error: one of the arguments --version subcommand --config-dir --data-dir --runtime-dir --paths is required
```
In other words, it correctly locates jupyter.

**Comment by dpsanders** [comment]
**But** doing `C:\Users\toodi\.julia\v0.6\Conda\deps\usr\Scripts\jupyter kernelspec`, i.e. trying to run the `jupyter` command, fails, saying that it can't find `jupyter-kernelspec`. This seems to be the crux of the matter!

**Comment by evetion** [comment]
Just encountered this, temporary workaround is adding the `.julia\v0.6\Conda\deps\usr\Scripts` folder to the PATH environment variable.

This _will_ conflict with existing python installations, use with caution.

**Comment by rtZamb** [comment]
@dpsanders I had the almost the exact same issue with respect to `jupyter-kernalspec` when installing IJulia but I already had jupyter installed so I used the ENV["JUPYTER"] method described at this homepage. Once the install seemed to fail:
```
INFO: Found Jupyter version 4.4.0: C:\Programming\Python3.6\Scripts\jupyter
INFO: Installing Julia kernelspec julia-0.6
Error executing Jupyter command 'kernelspec': [Errno 'jupyter-kernelspec' not found] 2
[InstallKernelSpec] Removing existing kernelspec in C:\Users\jarvis\AppData\Roaming\jupyter\kernels\julia-0.6
[InstallKernelSpec] Installed kernelspec julia-0.6 in C:\Users\jarvis\AppData\Roaming\jupyter\kernels\julia-0.6
```

Importing the IJulia package in the REPL seemed to fix the problem. The output was: 
```
import IJulia  
INFO: Recompiling stale cache file C:\Users\jarvis\.julia\lib\v0.6\IJulia.ji for module IJulia.
```

I subsequently was able to run the Julia kernal in jupyter without it dying.

**Comment by stevengj** [comment]
IJulia no longer uses `jupyter kernelspec`, so this issue should be moot.
