### ISSUE TITLE
Updating julia needs reinstalling IJulia for nteract getting to work again

### ISSUE THREAD

**Issue by fbruetting** [JuliaLang/IJulia.jl#594]
I installed a new version of Julia into a new directory and corrected my symlink in /usr/local/bin/ appropriately, but nteract failed every time, because the old folder was still referenced. After deleting and installing IJulia again, it worked. Please fix this!

**Comment by stevengj** [comment]
As explained in the README, if you install Julia into a new directory, you need to re-run `Pkg.build("IJulia")`.
