### ISSUE TITLE
display with arbitrary mimetype

### ISSUE THREAD

**Issue by ssfrr** [JuliaLang/IJulia.jl#595]
It looks like way the Jupyter team is expecting custom fancy data displays and widgets is to have a javascript jupyter extension that's registered to handle a custom mimetype, and then have the kernel display the data (as JSON?) with that mimetype.

See the discussion [here](https://github.com/jupyterlab/jupyterlab/issues/2666)

Currently I have some fancy audio buffer display that just dumps javascript into the cell output, but apparently jupyter is moving away from allowing that, and it doesn't work in jupyterlab.

I don't have a full understanding of how the display code works, but from the code [here](https://github.com/JuliaLang/IJulia.jl/blob/4efeb51d610319f0b2a99c93ac4aeb329c793967/src/inline.jl#L5-L7) it seems like there are a set of pre-set mimetypes that data is expected to render into.

Is there currently a way to display data with a custom mimetype, or would that require changes to IJulia.jl?

This also might be related to #531.

**Comment by stevengj** [comment]
Ah, I wasn't aware that Jupyter supports arbitrary mime types now.  Presumably you have to supply some kind of Javascript code, too, to actually display the data?

**Comment by ssfrr** [comment]
Yeah, I think they idea is that the user needs to have an extension installed that provides the javascript that handles that mimetype.

**Comment by stevengj** [comment]
Just pushed a commit to allow this.  You should be able to do
```jl
display("foo/bar", UInt8[....binary data...])
```
and it will send that MIME data to Jupyter.

**Comment by ssfrr** [comment]
amazing, thanks! It's going to be a bit before I port over my current display stuff to the new jupyter way, but I think this is all I need on the IJulia side.

**Comment by sglyon** [comment]
To use this does `istextmime("foo/bar")` need to be true?

**Comment by sglyon** [comment]
I can't get this to work...

I'm trying to tap into the `"application/vnd.plotly.v1+json"` mimetype from jupyterlab. I have installed/configured the jupyterlab extension (basically the javascript part @stevengj and @ssfrr alluded to above) and have confirmed that it works properly by trying this example in a python notebook (from the [readme for the jlab extension](https://github.com/jupyterlab/jupyter-renderers/tree/master/packages/plotly-extension#usage)):

```python
from IPython.display import display

def Plotly(data=[], layout={}):
    bundle = {}
    bundle['application/vnd.plotly.v1+json'] = {
        'data': data,
        'layout': layout,
    }
    display(bundle, raw=True)

data = [
    {'x': [1999, 2000, 2001, 2002], 'y': [10, 15, 13, 17], 'type': 'scatter'},
    {'x': [1999, 2000, 2001, 2002], 'y': [16, 5, 11, 9], 'type': 'scatter'}
]

layout = {
    'title': 'Sales Growth',
    'xaxis': {'title': 'Year', 'showgrid': False, 'zeroline': False},
    'yaxis': {'title': 'Percent', 'showline': False}
}

Plotly(data, layout)
```

I've tried  a few attempts in Julia and just get a blank plot div. This tells me that the mime-type info is making it to jupyter, but somehow the corresponding data isn't correct. 

Here's some of the Julia codes I've tried

```julia
using JSON

struct SimplePlot
    data::Vector
    layout::Dict
end

function IJulia.display_dict(m::SimplePlot)
    Dict("application/vnd.plotly.v1+json" => json(m))
end

m = SimplePlot([Dict("x" => [1, 2, 3], "y" => rand(3), "type" => "scatter")], Dict("title" => "working!"))
```

and 

```julia
using JSON

data = Dict("x" => [1, 2, 3], "y" => [5, 0, 3])
layout = Dict()
fig = Dict("data" => data, "layout" => layout)
IJulia.send_ipython(IJulia.publish[],
    IJulia.msg_pub(IJulia.execute_msg, "display_data",
        Dict("source" => "julia", # optional
             "metadata" => Dict("raw" => true), # optional
             "data" => Dict("application/vnd.plotly.v1+json" => json(fig))
        )
    )
)
```

Do you see something I'm doing wrong here? Is there a way to replicate the Python example?

**Comment by sglyon** [comment]
I got it to work. This was the magic incantation:

```julia
using JSON

data = Dict("x" => [1, 2, 3], "y" => [5, 0, 3])
layout = Dict()
fig = Dict("data" => [data], "layout" => layout)
IJulia.send_ipython(IJulia.publish[],
    IJulia.msg_pub(IJulia.execute_msg, "display_data",
        Dict("source" => "julia", # optional
             "metadata" => IJulia.metadata(fig), # optional
             "data" => Dict("application/vnd.plotly.v1+json" => fig)
        )
    )
)
```

The secret was to pass just `fig` and not a json string of fig
