### ISSUE TITLE
IJulia heartbeat error when jupyter is launched from emacs

### ISSUE THREAD

**Issue by sswatson** [JuliaLang/IJulia.jl#596]
If I start my Jupyter process from emacs, then everything works fine with all my kernels except Julia. And the Julia kernel works if I comment out the line 

```julia
 start_heartbeat(heartbeat[])
```

in `IJulia/src/init.jl`. So perhaps there is some issue with `start_heartbeat` which only shows up when Jupyter is launched in certain ways. 

I'm on macOS Sierra, using Julia 0.6.0 and Emacs 25.1.1, and my MWE is putting 

```(start-process "Jupyter" "*jupyter-buffer*" "~/anaconda/bin/jupyter" "notebook")```

in an emacs buffer and doing `C-x C-e`.

**Comment by stevengj** [comment]
See also #489.  Apparently we don't need the heartbeat for the notebook, only for certain remote-process situations, so it should be safe to disable.   I still don't know why it is breaking on some machines, though.

**Comment by sswatson** [comment]
Thanks, stevengj. I will just keep it disabled.
