### ISSUE TITLE
Nightly Status

### ISSUE THREAD

**Issue by Nosferican** [JuliaLang/IJulia.jl#599]
I Julia is currently broken on the nightly versions...
See [ZMQ](https://github.com/JuliaInterop/ZMQ.jl/issues/159) to compile the dependency, but the kernel keeps restarting.
The solution to compile JSON is given in [413](https://github.com/JuliaLang/Compat.jl/pull/413).

**Comment by Nosferican** [comment]
Any plans to when IJulia will start development to support 0.7? Now with `alpha` at `rc` after FemToCleaner is up?

**Comment by stevengj** [comment]
See #623.
