### ISSUE TITLE
Jupyter notebook kernel keeps dying

### ISSUE THREAD

**Issue by cpar8566** [JuliaLang/IJulia.jl#600]
Hi, all. I am quite new to jupyter notebook. I have previously installed julia and have never used it since and I have recently taken the upgrade process.

When I start jupyter notebook both by anaconda or julia terminal, it opens up fine and everything works fine until when i try using pyplot, the kernel suddenly dies.

<img width="1173" alt="screen shot 2017-11-28 at 3 41 02 am" src="https://user-images.githubusercontent.com/18750943/33278194-e08d2c0a-d3ee-11e7-8fc3-55c99fa4b0e7.png">
<img width="1004" alt="screen shot 2017-11-28 at 3 41 31 am" src="https://user-images.githubusercontent.com/18750943/33278195-e0ec5216-d3ee-11e7-815e-1690fd9cc509.png">
<img width="646" alt="screen shot 2017-11-28 at 3 41 58 am" src="https://user-images.githubusercontent.com/18750943/33278196-e144ed7c-d3ee-11e7-948b-70e38d451ce9.png">

I have been on this issue for a very long time, tried deleting python, julia and anaconda and reinstalled everything but still the same issue.

Anyone please help!!!!!!!!!!!!

**Comment by cpar8566** [comment]
FYI, I have tried Pkg.update(), Pkg.add("IJulia") and there was nothing wrong with these. I tried Pkg.rm("IJulia"), then Pkg.build("IJulia"), then got following error message. 

Could this possibly be an issue?

<img width="1303" alt="screen shot 2017-11-28 at 3 59 07 am" src="https://user-images.githubusercontent.com/18750943/33278842-e9fdede0-d3f0-11e7-8fec-84c1952c3fc9.png">
<img width="950" alt="screen shot 2017-11-28 at 3 59 51 am" src="https://user-images.githubusercontent.com/18750943/33278845-ea58c9fe-d3f0-11e7-9d25-04c9149780ec.png">

**Comment by stevengj** [comment]
Looks like something is wrong with your Homebrew installation.   Until `Pkg.build("IJulia")` succeeds, you're not likely to get the notebook to work.

You could try
```
rm(Pkg.dir("Homebrew","deps","usr"), recursive=true)
Pkg.build("Homebrew")
Pkg.build("IJulia")
```
Also, the "port 8888 is already in use" error message makes it seem like Jupyter or something is already running on your system?

**Comment by clemens-tolboom** [comment]
fwiw:
- on macos I had a docker container started on port 8888 which I shut down.
- next started Jupyter which it's python kernel kept dying.
- starting another Jupyter instance it picked another port 8889

Guess we can close this issue?

**Comment by ctkelley** [comment]
I just started having this problem and am not sure what to do at all. 

I'm on a Mac with the latest OS and Julia 1.1.1.  Everything was fine until today. I am not getting error messages from the REPL. I tried to build and update and that did not solve the problem.

Selecting "restart and clear output" from the pulldown menu works for a few seconds. Then the kernel dies again. 

I am completely confused.

**Comment by stevengj** [comment]
Could it be jupyter/jupyter_client#463?  Are you getting "Adapting from protocol" messages over and over in the terminal?

**Comment by ctkelley** [comment]
I'm not getting complaints from the terminal at all. The kernel keeps restarting and dying. 
I did an update this morning and conda was changed. Could that be it?

**Comment by stevengj** [comment]
If you updated Julia and changed where Julia is installed you need to re-run `build IJulia` as explained in the README.

**Comment by ctkelley** [comment]
Turns out it's simpler than that. I did the update from the pkg prompt, but the problem was that I did an RTFM from Revise and made a startup_iulia.jl file with

**try
    @eval using Revise
catch**

in it. That seemed to kill my kernel. I figured this out when I looked at the time machine version from yesterday. 

Why would that kill the kernel?

**Comment by stevengj** [comment]
That sounds like a separate issue; I would file an issue with Revise.
