### ISSUE TITLE
Jupyter --allow-root support

### ISSUE THREAD

**Issue by adamws** [JuliaLang/IJulia.jl#601]
I observed following error on Kali Linux:
```
julia> using IJulia
INFO: Precompiling module IJulia.
julia> notebook()
Process(setenv(`/root/.julia/v0.6/Conda/deps/usr/bin/jupyter notebook --NotebookApp.iopub_data_rate_limit=2147483647`; dir="/root"), ProcessExited(1))
```
Running `notebook` with `jupyter` directly gives more details:
`[C 12:33:36.678 NotebookApp] Running as root is not recommended. Use --allow-root to bypass.`

I believe that support for this flag should be provided.

**Comment by stevengj** [comment]
Don't run as root; this is just always a bad idea (google it).  Create a user account on your machine and use that for day-to-day work.

You can always run `/root/.julia/v0.6/Conda/deps/usr/bin/jupyter --allow-root` manually, but I don't think we should automate this.   People shouldn't be running `julia`, much less `jupyter`, as root except under exceptional circumstances.

**Comment by adamws** [comment]
ok, I can agree with that although running as root might be justified is some [cases](https://docs.kali.org/policy/kali-linux-root-user-policy). I'm not going to create separate user just for julia - I overcome this problem with source modification, for me it's enough. If you don't want to add support for such functionality, fine, I get that. Can you at least return meaningful message? It took me some time to figure out where the problem was.

**Comment by stevengj** [comment]
I'm not suggesting creating a separate user just for Julia.  I'm suggesting that you should follow standard Unix practice: create a user account for yourself on your machine and do *all* your work as that user, not as root.

Kali Linux is a specialized distro for security testing.  You shouldn't be using that for general computational work, e.g. Julia software development.
