### ISSUE TITLE
Weird parse bug.

### ISSUE THREAD

**Issue by yipinghuang1991** [JuliaLang/IJulia.jl#603]
Type something like this into a cell: `f(M::{T})`
Then delete the `}` after `T`: `f(M::{T)`
The particular cell will stop refreshing content unless you add the `}` back. (It do refresh actually, but very slow.) And after some seconds  ~~the content of the cell will disappear~~ the cell will be blank, but everything is still in .ipynb.

`versioninfo()`
```
Julia Version 0.6.1
Platform Info:
  OS: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas.so
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, ivybridge)
```

`Pkg.status("IJulia")`
```
 - IJulia                        1.6.2
```

I can confirm this on Jupyter-notebook and JupyterLab.
`conda list | grep jupyter`
```
jupyter                   1.0.0            py36h9896ce5_0  
jupyter_client            5.1.0            py36h614e9ea_0  
jupyter_console           5.2.0            py36he59e554_1  
jupyter_core              4.4.0            py36h7c827e3_0  
jupyterlab                0.30.6           py36h2f9c1c0_0  
jupyterlab_launcher       0.6.0                    py36_0
```

**Comment by stevengj** [comment]
I can reproduce — it sounds like a CodeMirror bug.  @Carreau or @malmaud, any insight into this?

**Comment by stevengj** [comment]
Problem seems to be gone in the latest version.
