### ISSUE TITLE
ijulia stop on precompile any pacakge

### ISSUE THREAD

**Issue by babaq** [JuliaLang/IJulia.jl#604]
i just checkout the latest Ijulia, and find it stop working when `using` invoked precompile.
![image](https://user-images.githubusercontent.com/92771/34187665-661df288-e4e7-11e7-8068-76dbbcadde8e.png)

if i do `using GLM` in command line, and after package been precompiled, Ijulia doesn't complain anymore.

**Comment by babaq** [comment]
after deleting and reinstalling Ijulia and precompile most of the packages in command-line prompt, the Ijulia seems working again.

**Comment by stevengj** [comment]
That was a problem on IJulia master, which should be fixed now.  (By deleting and re-installing IJulia, you went back to the latest tagged version.  In general, you should be cautious about using the bleeding-edge development version of any package.)
