### ISSUE TITLE
IJulia Installation error on macOS

### ISSUE THREAD

**Issue by ghost** [JuliaLang/IJulia.jl#607]
Got the following error during installation of IJulia on macOS Sierra. The Julia version is 0.6.2 (2017-12-13 18:08 UTC) 

```
    ...
    widgetsnbextension:                 3.1.0-py27_0     conda-forge
    zeromq:                             4.2.1-1          conda-forge

ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 
'conda-forge::widgetsnbextension-3.1.0-py27_0'.

LinkError: post-link script failed for package conda-forge::widgetsnbextension-3.1.0-py27_0
running your command again with `-v` will provide additional information
location of failed script: /Users/antonio/.julia/v0.6/Conda/deps/usr/bin/.widgetsnbextension-post-link.sh
==> script messages <==
<None>

**Comment by cgfloare** [comment]
I suppose this is something similar with the problem reported [here](https://github.com/ContinuumIO/anaconda-issues/issues/8087) and solved by [pyandri](https://github.com/ContinuumIO/anaconda-issues/issues/8087#issuecomment-358803791).

**Comment by stevengj** [comment]
IJulia no longer needs Conda to install, so this issue seems moot.
