### ISSUE TITLE
Got problem building IJulia

### ISSUE THREAD

**Issue by couzhei** [JuliaLang/IJulia.jl#616]
I was planning to build your package on Julia 0.6.2 running on Ubuntu 14.04, I guess somehow that the problem might be related to the installation of the Julia itself, here is what I did to use Julia on my machine.
I first downloaded the binary source code for the latest Julia available, then un-`tar` it on `/usr/local/bin/`, then I added its directory to `PATH` and also ran `chmod +x {julia directory}/bin`, so typing `julia` is now running fine in my terminal. Thereafter I entered into Julia environment, ran `Pkg.add("IJulia")`... fine ... ran `Pkg.build("IJulia")` but here is what I got:

```
INFO: Building Conda
INFO: Building MbedTLS
Using system libraries...
INFO: Building ZMQ
INFO: Building IJulia
INFO: Found Jupyter version 4.3.0: jupyter
INFO: Installing Julia kernelspec julia-0.6
[Errno 13] Permission denied: '/home/couzhei/.local/share/jupyter/kernels'
[Errno 13] Permission denied: '/home/couzhei/.local/share/jupyter/kernels'
===============================[ ERROR: IJulia ]================================

LoadError: failed process: Process(`jupyter-kernelspec install --replace --user /tmp/julia-0.6`, ProcessExited(1)) [1]
while loading /home/couzhei/.julia/v0.6/IJulia/deps/build.jl, in expression starting on line 103

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: IJulia had build errors.

 - packages with build errors remain installed in /home/couzhei/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("IJulia")`
 - build a single package by running its `deps/build.jl` script

================================================================================

julia>
```

I ignored the above warning and errors, optimistically thought it's going to work, but `using IJulia` says it's not installed properly.
Any suggestions?

**Comment by couzhei** [comment]
Do you think I might better be off putting the julia directory in /home directory?

**Comment by stevengj** [comment]
How could permission be denied for `/home/couzhei/.local/share/jupyter/kernels`?  I would check the permissions on these directories with `ls -ld /home/couzhei/.local /home/couzhei/.local/share /home/couzhei/.local/share/jupyter /home/couzhei/.local/share/jupyter/kernels` ... maybe you installed something as a different user (as root?) or with the wrong permissions?

**Comment by couzhei** [comment]
How can such procedure be done? I don't think that is the problem, however do you think putting `anaconda3` in the `/usr/local/bin` directory might get me into the trouble. Actually I put almost everything related to development into that folder out of habit, but I saw many people who put their `anaconda3` in the home directory. I show you the results form `ls -ld`-ing here though, the `kernels` directory does not exist!
```
couzhei@couzhei-lappy:~$ ls -ld /home/couzhei/.local /home/couzhei/.local/share /home/couzhei/.local/share/jupyter /home/couzhei/.local/share/jupyter/kernels
ls: cannot access /home/couzhei/.local/share/jupyter/kernels: Permission denied
drwx------  3 couzhei couzhei 4096 Jan  4 20:58 /home/couzhei/.local
drwx------ 27 couzhei couzhei 4096 Jan 19 21:56 /home/couzhei/.local/share
drwx------  3 root    root    4096 Jan  8 17:37 /home/couzhei/.local/share/jupyter
couzhei@couzhei-lappy:~$ 

```

**Comment by couzhei** [comment]
Nope. Removing anaconda3 folder from user and re-run its bash source file and putting it in the home directory does not solve anything, same issues, same errors, same permissions-related issues.

**Comment by stevengj** [comment]
The problem is not the location of Anaconda, the problem is the permission in your home directory.  In particular, note:
```
drwx------  3 root    root    4096 Jan  8 17:37 /home/couzhei/.local/share/jupyter
```
Probably you made the mistake of running Jupyter as `root` when you first installed it, and so this directory got installed with the wrong permissions.  To fix the permissions, you can type
```sh
sudo chown -R couzhei:couzhei /home/couzhei/.local/share/jupyter
```
to change the ownership of that directory.  (Either use `sudo` or switch to the `root` user to run this command.)

(In general, it is a bad idea to log in as `root` at all unless you really know what you are doing.  Use `sudo` to run commands that require admin permissions.)
