### ISSUE TITLE
Unnecessary installation of Jupyter via Conda

### ISSUE THREAD

**Issue by asood314** [JuliaLang/IJulia.jl#626]
Hi,

I just installed IJulia on OS X 10.9.5. I set the "JUPYTER" environment variable prior to calling Pkg.add("IJulia") in order to avoid installing a second copy of Jupyter on my system, but the installer claimed my version was too old and installed it anyway.

INFO: /user/local/bin/jupyter was too old: got 0.0.0, required ≥ 3.0
INFO: Installing Jupyter via the Conda package.

I installed Jupyter quite recently, so I had a hard time believing it was too old and certainly wasn't buying that it was version 0.0.0. Sure enough, the version of my existing installation was 4.4.0, which appears to be the same version that Julia installed unnecessarily via Conda.

bash-3.2$ jupyter --version
4.4.0

INFO: Found Jupyter version 4.4.0: /Users/asood/.julia/v0.6/Conda/deps/usr/bin/jupyter

**Comment by stevengj** [comment]
The error message may be leading you astray here.  It gets "0.0" if there is *any* error in running the JUPYTER that you specified.

In your case, it looks like you mis-typed the path: probably you meant `/usr/local/bin/jupyter` and not `/user/local/bin/jupyter`.

If `jupyter` is in your PATH, you can also just use `ENV["JUPYTER"]="jupyter"`.

**Comment by stevengj** [comment]
I just pushed a patch (397d190ae68c6d61425b0239733090cd93450875) that should give a more informative error message in cases like this.
