### ISSUE TITLE
IJulia doesn't seem to know about `struct` in Jupyterlab

### ISSUE THREAD

**Issue by MasonProtter** [JuliaLang/IJulia.jl#635]
When I use IJulia in Jupyterlab I don't get any syntax highlighting, autocomplete or automatic indentation for `struct`.

**Comment by stevengj** [comment]
Probably you just need a more recent version of the Julia CodeMirror mode (https://github.com/codemirror/CodeMirror/blob/master/mode/julia/julia.js).
