### ISSUE TITLE
PyPlot causing Jupyter notebook kernel to die repeatedly

### ISSUE THREAD

**Issue by fufjvnvnf** [JuliaLang/IJulia.jl#639]
I upgraded to julia 0.6.2 today and my PyPlot exploded. I believe this is the same issue as [here](https://github.com/JuliaPy/PyPlot.jl/issues/315).  The problem is while the workaround proposed in the  thread worked in my julia REPL, PyPlot is still causing my Jupyter notebook kernel to die. Toward the end of the issue they also mention that this has been fixed in the recent anaconda released, but the problem is I don't think I ever installed anaconda or miniconda on my computer. I am confused by this issue overall so I had to pose it here, and I am sorry if it is irrelevant to IJulia.

**Comment by stevengj** [comment]
The issue that you mentioned was fixed in a recent Anaconda release.   Have you tried just updating Anaconda?

**Comment by fufjvnvnf** [comment]
@stevengj I don't think I ever installed anaconda or miniconda on my computer; typing conda on my computer results in a command not found. I am on mac and I installed julia through the mac dmg.

**Comment by stevengj** [comment]
Where are you getting PyPlot from, then?   PyCall by default on the Mac installs an anaconda python distribution via the Conda.jl package.  Update it with
```jl
using Conda
Conda.update()
```

**Comment by fufjvnvnf** [comment]
This seems to solve the problem! Thank you so much!
