### ISSUE TITLE
IJulia and Julia 0.7.0-DEV

### ISSUE THREAD

**Issue by jheinen** [JuliaLang/IJulia.jl#648]
I can't install `IJulia` in the current development version (0.7.0-DEV.4858):

```julia
│ # Build failed for IJulia
│   exception =
│    LoadError: UndefVarError: JULIA_HOME not defined
```

Is there any workaround?

**Comment by stevengj** [comment]
See #623.  Waiting for work on ZMQ.

**Comment by stevengj** [comment]
Duplicate of #637
