### ISSUE TITLE
Installation Error on Windows 7 x64

### ISSUE THREAD

**Issue by ChiaraCCC** [JuliaLang/IJulia.jl#652]
![error](https://user-images.githubusercontent.com/38471135/38886145-676b16f2-4275-11e8-88ab-b40660db7e67.JPG)

Could you please help with this error message? I just installed Julia v.06 and tried to add IJulia.

**Comment by stevengj** [comment]
Since the problem is with `Pkg.build("MbedTLS")`, you should report the issue at [https://github.com/JuliaWeb/MbedTLS.jl](MbedTLS.jl).
