### ISSUE TITLE
Despite ENV["JUPYTER"] being declared, Conda is still downloaded

### ISSUE THREAD

**Issue by Magalame** [JuliaLang/IJulia.jl#657]
I already have an version of Anaconda installed on my machine, and want to use it as the support for the jupyter notebook. 

I specified the path:

`ENV["JUPYTER"]="C:\\Users\\username\\Anaconda3\\Scripts\\jupyter"`

Then:

`Pkg.add("IJulia")`

Which gaves me:

```INFO: Updating cache of IJulia...
INFO: Installing BinDeps v0.8.8
INFO: Installing BinaryProvider v0.3.0
INFO: Installing Compat v0.64.0
INFO: Installing Conda v0.7.1
INFO: Installing IJulia v1.8.0
INFO: Installing JSON v0.17.2
INFO: Installing MbedTLS v0.5.8
INFO: Installing Nullables v0.0.5
INFO: Installing SHA v0.5.7
INFO: Installing URIParser v0.3.1
INFO: Installing ZMQ v0.6.0
INFO: Building Conda
INFO: Building MbedTLS
INFO: Building ZMQ
Info: Downloading https://github.com/JuliaInterop/ZMQBuilder/releases/download/v4.2.5+2/ZMQ.x86_64-w64-mingw32.tar.gz to C:\Users\username\.julia\v0.6\ZMQ\deps\usr\downloads\ZMQ.x86_64-w64-mingw32.tar.gz...
INFO: Building IJulia
INFO: Found Jupyter version 4.4.0: C:\Users\username\Anaconda3\Scripts\jupyter
INFO: Installing Julia kernelspec julia-0.6
Error executing Jupyter command 'kernelspec': [Errno 'jupyter-kernelspec' not found] 2
[InstallKernelSpec] Removing existing kernelspec in C:\Users\username\AppData\Roaming\jupyter\kernels\julia-0.6
[InstallKernelSpec] Installed kernelspec julia-0.6 in C:\Users\username\AppData\Roaming\jupyter\kernels\julia-0.6
INFO: Package database updated 
```

I can now access Julia through the notebook I had already installed, althouh Conda was still downloaded at `C:\Users\username\.julia\v0.6\Conda`, is there a reason why? 

Note: it works fine with this folder (Conda) deleted, so I'd assume it isn't used at all

**Comment by stevengj** [comment]
What is the output of
```
ENV["JUPYTER"]="C:\\Users\\username\\Anaconda3\\Scripts\\jupyter"
chomp(read(`$(ENV["JUPYTER"]) --version`, String))
```
?

**Comment by Magalame** [comment]
It throws a method error:
```
ERROR: MethodError: no method matching read(::Cmd, ::Type{String})
Closest candidates are:
  read(::AbstractString, ::Any...) at io.jl:160
  read(::IO, ::Type{T}, ::Int64, ::Int64...) where T at io.jl:373
  read(::IO, ::Type{T}, ::Integer, ::Integer...) where T at io.jl:374
  ...
```

**Comment by stevengj** [comment]
Sorry, you also need `using Compat` to run that.

**Comment by Magalame** [comment]
No problem, it seems to be working fine:
```
julia> chomp(read(`$(ENV["JUPYTER"]) --version`, String))
"4.4.0"
```

**Comment by stevengj** [comment]
Looking more closely at your `Pkg.add` output, it seems like everything is working correctly — it used the `jupyter` that you specified.

I think the confusion here is that the *Julia* Conda.jl package is always installedy, but it doesn't actually run the Miniconda installer if you aren't using it.   All that is installed are a few tiny Julia files that are used to control Miniconda *if* it is installed.
