### ISSUE TITLE
Command to run jupyterlab

### ISSUE THREAD

**Issue by swt30** [JuliaLang/IJulia.jl#666]
Much like `IJulia.notebook()`, it might be nice to have the option to run jupyterlab through this package. That way users without jupyterlab installed centrally on their system can still run it without having to go digging in `.julia/.../Conda/deps/usr/bin`.

**Comment by swt30** [comment]
I got this to run really easily by doing
```jl
Conda.add("jupyterlab")
IJulia.notebook_cmd[2] = "lab"
IJulia.notebook()
```
so it would be simple to add. The question is if jupyterlab should be a dependency of this package... it could be installed on-demand if necessary?

**Comment by stevengj** [comment]
Having an `IJulia.jlab()` command that installs it on-demand (assuming we are using `Conda`) and otherwise searches the `jupyter` path would be nice.

**Comment by stevengj** [comment]
We now have a `jupyterlab()` function.
