### ISSUE TITLE
Problem with loading IJulia on Mac OS 10.13.5

### ISSUE THREAD

**Issue by cwglover32** [JuliaLang/IJulia.jl#670]
I'm new to Julia and IJulia. I have Julia-0.7 running on my mac terminal mode. I then used the Anaconda for Mac to install Python and several different environments, including "jupyter". I then ran the "Julia" command "Pkg.add("IJulia"). Please see the attached screenshots to see what happened in detail. Basically, the "Pkg.add("IJulia") command produced some warnings that I could determine if the script was able to correct or not.

(see -
<img width="756" alt="screen shot 2018-07-01 at 3 22 24 pm" src="https://user-images.githubusercontent.com/40725863/42138418-d21ed3aa-7d42-11e8-9c1f-07e91131ebdd.png">)

So I tried to use IJulia to see if the I can use it. I get the message "Package IJULIA not found in current path: - Run `Pkg.add("IJULIA")` to install the IJULIA package."

So I run "Pkg.add("IJulia") again. Something different results with now warnings that I can see. Then I try running "using IJulia" again.  Also with a different result.

(see - 
<img width="754" alt="screen shot 2018-07-01 at 3 30 17 pm" src="https://user-images.githubusercontent.com/40725863/42138473-bebb8ec4-7d43-11e8-885e-e073f0f5385d.png">)

This time it says to run the "Pkg.build("IJulia"). So I did and It gave me errors and warnings. 

(see - 
<img width="760" alt="screen shot 2018-07-01 at 3 33 33 pm" src="https://user-images.githubusercontent.com/40725863/42138509-43bfc9fa-7d44-11e8-94c7-dcb246bc9ad8.png">)

<img width="760" alt="screen shot 2018-07-01 at 3 33 33 pm" src="https://user-images.githubusercontent.com/40725863/42138507-3e6a96f6-7d44-11e8-8756-76266bb23d48.png">

What do I do now? Please help me!!

**Comment by stevengj** [comment]
Don't use Julia 0.7 if you are new to Julia.  Use 0.6.  0.7 is not ready for production use yet, and many packages (including IJulia) are not compatible yet.  (See also #623.)
