### ISSUE TITLE
ERROR: LoadError: Failed to precompile IJulia ; ERROR: LoadError: UndefVarError: uuid4 not defined

### ISSUE THREAD

**Issue by fpmenninger** [JuliaLang/IJulia.jl#676]

**Comment by stevengj** [comment]
If you are on Julia 0.7beta then you need to check out the master branch of IJulia.

**Comment by fpmenninger** [comment]
Thanks for the response.
I have added and updated most recent package of IJulia using Package manager.
Is that not the master branch?

julia> versioninfo(true)
┌ Warning: `versioninfo(verbose::Bool)` is deprecated, use `versioninfo(verbose=verbose)` instead.
│   caller = top-level scope at none:0
└ @ Core none:0
Julia Version 0.7.0-beta.0
Commit f41b1ecaec (2018-06-24 01:32 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
      Microsoft Windows [Version 6.1.7601]
  CPU: AMD Athlon(tm) II X2 260 Processor:
              speed         user         nice          sys         idle          irq
       #1  3200 MHz  1025883745            0    116563120    680029543      1103410  ticks
       #2  3200 MHz  990751040            0    127368904    704355715      6440875  ticks

  Memory: 15.74930191040039 GB (8184.6015625 MB free)
  Uptime: 1.8224757267443e6 sec
  Load Avg:  0.0  0.0  0.0
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, amdfam10)
Environment:
  AXIS2C_HOME = C:\mEMBOSS\axis2c
  CMDSTAN_HOME = C:\Users\Tracy\Stan\cmdstan-2.17.1
  EMBOSS_AXIS2C_HOME = C:\mEMBOSS\axis2c
  HOME = C:\Users\Tracy
  HOMEDRIVE = C:
  HOMEPATH = \Users\Tracy
  JAGS_HOME = C:\PortableApps\JAGSPortable\App\JAGS\
  PATHEXT = .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.RB;.RBW
Packages:
  Package Directory: C:\Users\Tracy\.julia\v0.7
  Package Status:
7 required packages:
 - BenchmarkTools                0.3.1
 - Distributions                 0.15.0
 - Gadfly                        0.7.0
 - IJulia                        1.8.0
 - LightGraphs                   0.13.0
 - PyCall                        1.16.1
 - Stan                          3.0.1
68 additional packages:
 - AxisAlgorithms                0.2.0
 - BinDeps                       0.8.8
 - BinaryProvider                0.3.0
 - Calculus                      0.4.0
 - CategoricalArrays             0.3.9
 - CodecZlib                     0.4.3
 - ColorTypes                    0.6.7
 - Colors                        0.8.2
 - CommonSubexpressions          0.1.0
 - Compat                        0.65.1
 - Compose                       0.6.0
 - Conda                         0.7.1
 - Contour                       0.4.0
 - CoupledFields                 0.0.1
 - DataArrays                    0.7.0
 - DataFrames                    0.11.6
 - DataStreams                   0.3.4
 - DataStructures                0.8.3
 - DiffEqDiffTools               0.4.1
 - DiffResults                   0.0.3
 - DiffRules                     0.0.4
 - Distances                     0.6.0
 - DocStringExtensions           0.4.4
 - Documenter                    0.18.0
 - DualNumbers                   0.3.0
 - FixedPointNumbers             0.4.6
 - ForwardDiff                   0.7.5
 - Hexagons                      0.1.0
 - IndirectArrays                0.4.2
 - Interpolations                0.7.3
 - IterTools                     0.2.1
 - JSON                          0.17.2
 - Juno                          0.4.1
 - KernelDensity                 0.4.1
 - LineSearches                  3.2.5
 - Loess                         0.3.0
 - MacroTools                    0.4.0
 - MbedTLS                       0.5.8
 - Measures                      0.2.0
 - Media                         0.3.0
 - Missings                      0.2.9
 - NLSolversBase                 4.4.1
 - NaNMath                       0.3.1
 - NamedTuples                   4.0.2
 - Nullables                     0.0.5
 - Optim                         0.14.1
 - PDMats                        0.9.1
 - Parameters                    0.8.1
 - PositiveFactorizations        0.1.0
 - QuadGK                        0.2.1
 - Ratios                        0.2.0
 - Reexport                      0.1.0
 - Rmath                         0.3.3
 - SHA                           0.5.7
 - ShowItLikeYouBuildIt          0.2.0
 - Showoff                       0.1.1
 - SimpleTraits                  0.7.1
 - SortingAlgorithms             0.2.1
 - SpecialFunctions              0.4.0
 - StaticArrays                  0.7.0
 - StatsBase                     0.22.0
 - StatsFuns                     0.6.0
 - TranscodingStreams            0.5.2
 - URIParser                     0.3.1
 - VersionParsing                1.1.0
 - WeakRefStrings                0.4.6
 - WoodburyMatrices              0.2.2
 - ZMQ                           0.6.1


julia> using IJulia
[ Info: Precompiling module IJulia
┌ Warning: Deprecated syntax `parametric method syntax clear_history{T <: Integer}(r:
:AbstractRange{T})` around C:\Users\Tracy\.julia\packages\IJulia\oaZM\src\IJulia.jl:201.
│ Use `clear_history(r::AbstractRange{T}) where T <: Integer` instead.
└ @ nothing IJulia.jl:201
WARNING: importing deprecated binding Base.MersenneTwister into IJulia.
WARNING: Base.MersenneTwister is deprecated: it has been moved to the standard library package `Random`.
Add `using Random` to your imports.
  likely near C:\Users\Tracy\.julia\packages\IJulia\oaZM\src\init.jl:8
WARNING: importing deprecated binding Base.srand into IJulia.
WARNING: Base.srand is deprecated: it has been moved to the standard library package
`Random`.
Add `using Random` to your imports.
  likely near C:\Users\Tracy\.julia\packages\IJulia\oaZM\src\init.jl:8
┌ Warning: `Array{T, 1}(m::Int) where T` is deprecated, use `Array{T, 1}(undef, m)` instead.
│   caller = top-level scope at none:0
└ @ Core none:0
┌ Warning: Deprecated syntax `immutable` at C:\Users\Tracy\.julia\packages\IJulia\oaZM\src\stdio.jl:7.
│ Use `struct` instead.
└ @ nothing stdio.jl:7
WARNING: importing deprecated binding Base.@sprintf into IJulia.
WARNING: Base.@sprintf is deprecated: it has been moved to the standard library package `Printf`.
Add `using Printf` to your imports.
  likely near C:\Users\Tracy\.julia\packages\IJulia\oaZM\src\stdio.jl:41
WARNING: importing deprecated binding Base.Void into IJulia.
WARNING: Base.Void is deprecated, use Nothing instead.
  likely near C:\Users\Tracy\.julia\packages\IJulia\oaZM\src\stdio.jl:244
┌ Warning: Deprecated syntax `type` at C:\Users\Tracy\.julia\packages\IJulia\oaZM\src\msg.jl:6.
│ Use `mutable struct` instead.
└ @ nothing msg.jl:6
┌ Warning: Deprecated syntax `try without catch or finally` at C:\Users\Tracy\.julia\packages\IJulia\oaZM\src\handlers.jl:110.
└ @ nothing handlers.jl:110
┌ Warning: Deprecated syntax `type` at C:\Users\Tracy\.julia\packages\IJulia\oaZM\src\comm_manager.jl:10.
│ Use `mutable struct` instead.
└ @ nothing comm_manager.jl:10
┌ Warning: Deprecated syntax `parametric method syntax (::Type{Comm{target}}){target}
(id, primary, on_msg, on_close)` around C:\Users\Tracy\.julia\packages\IJulia\oaZM\src\comm_manager.jl:16.
│ Use `(::Type{Comm{target}})(id, primary, on_msg, on_close) where target` instead.
└ @ nothing comm_manager.jl:16
┌ Warning: Deprecated syntax `parametric method syntax comm_target{target}(comm::Comm
{target})` around C:\Users\Tracy\.julia\packages\IJulia\oaZM\src\comm_manager.jl:45.
│ Use `comm_target(comm::Comm{target}) where target` instead.
└ @ nothing comm_manager.jl:45
WARNING: Base.Markdown is deprecated, run `using Markdown` instead
  likely near C:\Users\Tracy\.julia\packages\IJulia\oaZM\src\magics.jl:26
WARNING: Base.Random is deprecated, run `using Random` instead
  likely near C:\Users\Tracy\.julia\packages\IJulia\oaZM\src\execute_request.jl:100
WARNING: Base.Random is deprecated, run `using Random` instead
  likely near C:\Users\Tracy\.julia\packages\IJulia\oaZM\src\execute_request.jl:100
in uuid4 at C:\Users\Tracy\.julia\packages\IJulia\oaZM\src\init.jl
ERROR: LoadError: LoadError: LoadError: UndefVarError: uuid4 not defined
Stacktrace:
 [1] getproperty at .\sysimg.jl:13 [inlined]
 [2] uuid4() at C:\Users\Tracy\.julia\packages\IJulia\oaZM\src\init.jl:9
 [3] top-level scope at none:0
 [4] include at .\boot.jl:317 [inlined]
 [5] include_relative(::Module, ::String) at .\loading.jl:1075
 [6] include at .\sysimg.jl:29 [inlined]
 [7] include(::String) at C:\Users\Tracy\.julia\packages\IJulia\oaZM\src\IJulia.jl:35
 [8] top-level scope at none:0
 [9] include at .\boot.jl:317 [inlined]
 [10] include_relative(::Module, ::String) at .\loading.jl:1075
 [11] include at .\sysimg.jl:29 [inlined]
 [12] include(::String) at C:\Users\Tracy\.julia\packages\IJulia\oaZM\src\IJulia.jl:35
 [13] top-level scope at none:0
 [14] include at .\boot.jl:317 [inlined]
 [15] include_relative(::Module, ::String) at .\loading.jl:1075
 [16] include(::Module, ::String) at .\sysimg.jl:29
 [17] top-level scope at none:0
 [18] eval at .\boot.jl:319 [inlined]
 [19] eval(::Expr) at .\client.jl:394
 [20] top-level scope at .\none:3 [inlined]
 [21] top-level scope at .\<missing>:0
in expression starting at C:\Users\Tracy\.julia\packages\IJulia\oaZM\src\execute_request.jl:100
in expression starting at C:\Users\Tracy\.julia\packages\IJulia\oaZM\src\handlers.jl:2
in expression starting at C:\Users\Tracy\.julia\packages\IJulia\oaZM\src\IJulia.jl:348
ERROR: Failed to precompile IJulia to C:\Users\Tracy\.julia\compiled\v0.7\IJulia\nfu7.ji.
Stacktrace:
 [1] error at .\error.jl:33 [inlined]
 [2] compilecache(::Base.PkgId) at .\loading.jl:1205
 [3] _require(::Base.PkgId) at .\loading.jl:1007
 [4] require(::Base.PkgId) at .\loading.jl:879
 [5] require(::Module, ::Symbol) at .\loading.jl:874

**Comment by fredrikekre** [comment]
> I have added and updated most recent package of IJulia using Package manager.
Is that not the master branch?

No, that will only get you the last release. There is not yet a Julia v0.7 compatible IJulia release. To add IJulia at the master branch you can 
```
pkg> add IJulia#master
```
