### ISSUE TITLE
`using Compat.InteractiveUtils` needed somewhere

### ISSUE THREAD

**Issue by schmrlng** [JuliaLang/IJulia.jl#682]
`Base.@which`, `Base.@code_XXX`, etc. have associated deprecation warnings on 0.7 -- I think the fix is to include `using Compat.InteractiveUtils` somewhere, but naively putting this at the top of `src/IJulia.jl` doesn't seem to stop the warnings.

**Comment by stevengj** [comment]
It needs to be in IJulia/src/kernel.jl.  Add a line `using IJulia.Compat.InteractiveUtils` at the top after `import IJulia`.   A PR would be welcome.
