### ISSUE TITLE
Ijulia dependencies of ZMQ,CodeZlib and MbedTLS have build errors.

### ISSUE THREAD

**Issue by TAUFEEQ1** [JuliaLang/IJulia.jl#684]
Attempting to install IJulia results in the errors:
Building MbedTLS
Info: Downloading https://github.com/JuliaWeb/MbedTLSBuilder/releases/download/v0.11/MbedTLS.v1.0.0.x86_64-linux-gnu.tar.gz to /home/nsamba/.julia/v0.6/MbedTLS/deps/usr/downloads/MbedTLS.v1.0.0.x86_64-linux-gnu.tar.gz...
[22:15:00] ######################################################################## 100.0%
[22:15:00] curl: (35) gnutls_handshake() failed: Error in the pull function.
===========================================================================[ ERROR: MbedTLS ]===========================================================================

LoadError: Could not download https://github.com/JuliaWeb/MbedTLSBuilder/releases/download/v0.11/MbedTLS.v1.0.0.x86_64-linux-gnu.tar.gz to /home/nsamba/.julia/v0.6/MbedTLS/deps/usr/downloads/MbedTLS.v1.0.0.x86_64-linux-gnu.tar.gz
while loading /home/nsamba/.julia/v0.6/MbedTLS/deps/build.jl, in expression starting on line 45

========================================================================================================================================================================
INFO: Building ZMQ
Info: Downloading https://github.com/JuliaInterop/ZMQBuilder/releases/download/v4.2.5+6/ZMQ.x86_64-linux-gnu.tar.gz to /home/nsamba/.julia/v0.6/ZMQ/deps/usr/downloads/ZMQ.x86_64-linux-gnu.tar.gz...
[22:15:22] ######################################################################## 100.0%
[22:15:22] curl: (35) gnutls_handshake() failed: Error in the pull function.
=============================================================================[ ERROR: ZMQ ]=============================================================================

LoadError: Could not download https://github.com/JuliaInterop/ZMQBuilder/releases/download/v4.2.5+6/ZMQ.x86_64-linux-gnu.tar.gz to /home/nsamba/.julia/v0.6/ZMQ/deps/usr/downloads/ZMQ.x86_64-linux-gnu.tar.gz
while loading /home/nsamba/.julia/v0.6/ZMQ/deps/build.jl, in expression starting on line 44

========================================================================================================================================================================

============================================================================[ BUILD ERRORS ]============================================================================

**Comment by stevengj** [comment]
I think this was a temporary github server outage yesterday.
