### ISSUE TITLE
Allow Installation Without Jupyter

### ISSUE THREAD

**Issue by travigd** [JuliaLang/IJulia.jl#692]
I'm running Julia kernels in a dockerized environment (running kernels are connected to from frontends that are completely separate) where having Jupyter itself installed is completely superfluous (it adds a LOT of dependencies to install Jupyter + Conda when it won't even be used). Is there a way to just skip this step (e.g. environment variable)?

```
user@ef06f0d39e8b:/$ du -sh /usr/local/julia/share/julia/site/v0.6/Conda/
1.5G	/usr/local/julia/share/julia/site/v0.6/Conda/
```

**Comment by stevengj** [comment]
How can we install the kernel configuration file without `jupyter`?

**Comment by stevengj** [comment]
I guess we can install in the “standard” location (is this documented?) and only install Jupyter if `notebook()` is called...

**Comment by travigd** [comment]
@stevengj Do you mean the `kernel.json` file in `.../share/jupyter/kernels` or the `deps.jl` file in the IJulia package directory?

If the former, I vote "just don't.", and if the latter, I think that the check for that file would move away from module initialization and into the `notebook()` command. I'm not sure if the constants defined in `deps.jl` are used anywhere else but I was able to [comment out the `include`](https://github.com/travigd/IJulia.jl/commit/9eb404e35d4bb01b2e2c23c4448d95b724670b72) and have the kernel itself run just fine.

**Comment by stevengj** [comment]
I mean the `kernel.json` file, so that it works with any existing Jupyter installation.  Why not install this, since the installation directory is documented: http://jupyter.readthedocs.io/en/latest/projects/jupyter-directories.html, and this way it will work with any `jupyter` installation regardless of PATH.

I don't like the idea of making `notebook()` issue an error and forcing you to install Jupyter manually.  Why not just install Jupyter automatically if it is not found?

**Comment by travigd** [comment]
Those directories might not exist (e.g. they wouldn't in my scenario), so I suppose just make sure that that's handled gracefully.

As for `notebook()`, I don't have strong opinions, it just seems that installing the notebook is a relatively large operation that might not be expected or desired (principle of least astonishment) when running `notebook()`. For example, if my PATH is misconfigured I don't want to install Conda + Jupyter. Maybe a prompt before installing (if in a terminal, otherwise default to yes)? But I'm not a consumer of that API so I certainly won't be upset if you decide to just have it download and install everything.

**Comment by stevengj** [comment]
> Those directories might not exist (e.g. they wouldn't in my scenario), so I suppose just make sure that that's handled gracefully.

You'd call `mkpath`.

**Comment by travigd** [comment]
I think a prompt would be nice, if running interactively (and default to just downloading if running non-interactively).

```
Jupyter wasn't found in your PATH. Download it? [Y/n]:
```
