### ISSUE TITLE
Kernel died for turtle graphics

### ISSUE THREAD

**Issue by Sastry-Akundy** [JuliaLang/IJulia.jl#695]
I tried following tutorial from Think python. Kernel dies first time, but runs second time. Help please
import turtle
bob = turtle.Turtle()
print(bob)
for i in range(4):
             bob.fd(100)
             bob.lt(90)
turtle.mainloop()

**Comment by stevengj** [comment]
It sounds like you are running Python, not Julia — you are reporting bugs in the wrong place.
