### ISSUE TITLE
Precompiling IJulia fails on Julia 1.0 due to srand not defined

### ISSUE THREAD

**Issue by jessebett** [JuliaLang/IJulia.jl#698]
Since `srand` has been depreciated IJulia doesn't precompile for v1.0:

```
using IJulia
[ Info: Precompiling IJulia [7073ff75-c697-5162-941a-fcdaad2a7d2a]
ERROR: LoadError: LoadError: UndefVarError: srand not defined
```

**Comment by fredrikekre** [comment]
This should be fixed on IJulia master, maybe you can try that? We should make a new 1.0 compatible release though

**Comment by stevengj** [comment]
Was fixed by #696.

**Comment by stevengj** [comment]
In general, you shouldn't be using Julia 1.0-alpha unless you are willing to check out `master` versions of many packages and fix deprecation problems as they arise.

**Comment by jessebett** [comment]
Sorry. You're right about that @stevengj. Still a bit confused by Pkg 3 and thought I checked out master but hadn't...
