### ISSUE TITLE
Julia ERROR, Cannot install any package, 

### ISSUE THREAD

**Issue by KathyGCY** [JuliaLang/IJulia.jl#701]
Julia ERROR, Cannot install any package, 

<img width="571" alt="screen shot 2018-08-10 at 9 58 27 am" src="https://user-images.githubusercontent.com/14912791/43961849-0fd47c80-9c84-11e8-950b-ab4b43d7009d.png">
<img width="680" alt="screen shot 2018-08-10 at 9 58 40 am" src="https://user-images.githubusercontent.com/14912791/43961852-13680380-9c84-11e8-8ee5-994091e49855.png">

**Comment by fredrikekre** [comment]
You need to `import Pkg`. Please ask questions on http://discourse.julialang.org.

Also, try to find some more updated tutorial, that looks to be written for Julia v0.3, which is really old.
