### ISSUE TITLE
`history` can't `print` to IO argument

### ISSUE THREAD

**Issue by rickhg12hs** [JuliaLang/IJulia.jl#706]
Reference:

https://github.com/JuliaLang/IJulia.jl/blob/acbd9e24ef95f04645ac6602c6dbfaea9bebbca8/src/IJulia.jl#L237

The `io::IO` function parameter is unused.  Shouldn't the `print` statement be:

```julia
print(io, In[n])
```

**Comment by stevengj** [comment]
Thanks, this was a bug.
