### ISSUE TITLE
no output in jupyter when the kernel is julia1.0

### ISSUE THREAD

**Issue by lujianok** [JuliaLang/IJulia.jl#707]
After I run a cell, no output appears.

**Comment by strickek** [comment]
On Windows?

**Comment by lujianok** [comment]
Windows 10

**Comment by stevengj** [comment]
Duplicate of #693.

**Comment by lujianok** [comment]
NO, I scroll back to Julia 0.6.4.

**Comment by stevengj** [comment]
Please file a new issue, then, specify Julia 0.6, give your system information and the output of `Pkg.build("IJulia")`, and try the https://github.com/JuliaLang/IJulia.jl#debugging-ijulia-problems suggestion.
