### ISSUE TITLE
Plot images in RCall are not shown in Julia 0.7

### ISSUE THREAD

**Issue by mac-wac** [JuliaLang/IJulia.jl#713]
Hi. I don't know that it is proper to report this issue here. If wrong, please let me know where I should report.

I upgraded Julia into 0.7 and tried RCall in jupyter (both in notebook and qtconsole) but images were not shown.

    using RCall
    using RDatasets
    R"library(ggplot2)"
    mtcars=dataset("datasets","mtcars")
    R"ggplot($mtcars,aes(x=WT,y=MPG))+geom_point()" #No image is output.
    
    using PyPlot
    plot(mtcars[:WT],mtcars[:MPG],linestyle="",marker=".") #This works.

![ijulia](https://user-images.githubusercontent.com/2494662/44267077-ced1fe80-a267-11e8-88ad-ba78f4572cec.png)

Either with Julia 0.6 and jupyter or with Julia 0.7 and REPL, this worked correctly.

My environment:

- Ubuntu 18.04
- Julia 0.7.0
- IJulia 1.9.2
- RCall 0.12.0
- R 3.4.4
- Python 3.6.5
- Jupyter 4.4.0
- Jupyter-notebook 5.6.0

Thank you!

**Comment by stevengj** [comment]
How was the image shown with 0.7 in the REPL?

**Comment by mac-wac** [comment]
In a new R window, not in a terminal itself. Please excuse my insufficient explanation (and  my broken English).

**Comment by randy3k** [comment]
@mac-wac 
Thank you for bringing it up. I forgot to test the IJulia code for Julia v0.7. https://github.com/JuliaInterop/RCall.jl/pull/263 has fixed the issue.

@stevengj 
Thanks for the cc.

**Comment by mac-wac** [comment]
@randy3k 
Thank you. RCall@0.12.1 finely works!

@stevengj 
Thank you.
