### ISSUE TITLE
Jupyter notebook works with Python Kernel but not Julia kernel

### ISSUE THREAD

**Issue by mayaoguangtc** [JuliaLang/IJulia.jl#718]
I am using Windows 10. I installed Python 3.7 and Julia 1.0.0 downloaded from official sites, both x64 version. 

In Julia REPL, I installed several Packages using Pkg.add(""), including IJulia, PyCall, IPython.

But when I trying to use using IJulia and notebook() to run the Jupyter notebook, the new notebook with Julia kernel does not work. 
The input label is In[*] and does not have any output for simple inputs like 2+2.
But when I change the kernel to Python 3 in the same notebook, the inputs and be executed. Input 2+2 returns 4.

I was wondering what is wrong with my Julia program and have no clue right now. Anybody can help? Thanks a lot.

versioninfo() returns
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)

Pkg.status() returns
    Status `C:\Users\mayao\.julia\environments\v1.0\Project.toml`
  [8f4d0f93] Conda v1.0.1
  [f6369f11] ForwardDiff v0.8.5
  [7073ff75] IJulia v1.9.3
  [18364772] IPython v0.1.0
  [95701278] ImplicitEquations v0.4.0
  [91a5bcdd] Plots v0.19.3
  [438e738f] PyCall v1.18.2
  [f2b01f46] Roots v0.7.1
  [24249f21] SymPy v0.8.0

**Comment by fredrikekre** [comment]
#693

**Comment by mayaoguangtc** [comment]
@fredrikekre  That thread is not a fix to my problem. Actually, he does not solve this problem at all. His problem disappears when he switched to Julia 1.0. But in my case, the problem still exists when I am already using Julia 1.0. 
Thus I think we should keep this thread open and to see if anyone can have a real solution. Thanks

**Comment by mayaoguangtc** [comment]
@Datseris  Hi, there. I ran into a similar problem as you do in #693 .  But my problem does not go away when I have julia 1.0 installed. Do you have any suggestions? Thanks.

**Comment by fredrikekre** [comment]
I did not suggest that it was a solution, I mean that this issue is a duplicate of #693  and we should concentrate the discussion to that issue.
