### ISSUE TITLE
Returning syntax error when creating a module in jupyter (Ubuntu 18.04, julia 0.7/1.0)

### ISSUE THREAD

**Issue by HTSykora** [JuliaLang/IJulia.jl#722]
When trying to create a `module` in a jupyter notebook the following error message is returned:
`syntax: "module" expression not at top level`

![ijulia_issue](https://user-images.githubusercontent.com/11589875/44905623-f074c080-ad12-11e8-84b3-178e9d277051.png)

**Comment by stevengj** [comment]
Thanks, it looks like this is a bug in SoftGlobalScope.jl.     A temporary workaround is to set `IJulia.SOFTSCOPE[] = false`

**Comment by stevengj** [comment]
Closed by https://github.com/stevengj/SoftGlobalScope.jl/pull/5
