### ISSUE TITLE
Cannot define modules

### ISSUE THREAD

**Issue by bicycle1885** [JuliaLang/IJulia.jl#723]
Evaluating `module Foo end` in a Jupyter Notebook cell results in `syntax: "module" expression not at top level` as follows:

![image](https://user-images.githubusercontent.com/905683/44947048-092fc400-ae42-11e8-892c-bdc0b95caa27.png)

I'm using IJulia.jl v1.10.0 on Julia 0.7.0.

**Comment by bicycle1885** [comment]
I think this is a side-effect of #720. Setting `IJULIA_SOFTSCOPE` to `no` when starting up a Jupyter server makes the problem go away.

**Comment by stevengj** [comment]
This was fixed by https://github.com/stevengj/SoftGlobalScope.jl/pull/5, so it should be fixed by a `Pkg.update`.

**Comment by stevengj** [comment]
(Duplicate of #722)
