### ISSUE TITLE
Tab-completion breaks with Pycall

### ISSUE THREAD

**Issue by cscherrer** [JuliaLang/IJulia.jl#733]
Tab completion becomes erratic after evaluating this code:

```julia
using PyCall
@pyimport pymc3 as pm
α,β = 1,1
β = [1,2.5]
x1 = randn(100)
x2 = randn(100) * 0.2;
y = α .+ β[1]*x1 .+ β[2]*x2 .+ randn(100)
function mymod()
    @pywith pm.Model() as m begin
        α = pm.Normal("α", mu=0,sd=10)
        β = pm.Normal("β",mu=0,sd=10,shape=2)
        σ = pm.HalfNormal("σ",sd=1)
    
        μ = α + β[1]*x1 + β[2]*x2
        y_obs = pm.Normal("y_obs", mu=μ,sd=σ,observed=y)
        return pm.sample()
    end
end
t = mymod();
```

Before evaluation of that last line, `t[:\alpha <TAB>` produces `t[:α` as expected. But after it, `<TAB>` in that context does nothing. Even stranger, ...
- It still works at the beginning of a line, or to write nonsense like `tα`. 
- Other values like `p[:\alpha <TAB>` seem fine
- There's no problem in the main Julia repl, only Jupyter notebooks with IJulia.

**Comment by stevengj** [comment]
Not sure what you expect `t[:α<TAB>` to do?  There seems to be nothing for it to complete to, so you tab completion correctly does nothing

Anyway, the latest version of PyCall uses `t.α` and supports better tab completion of Python objects.

**Comment by cscherrer** [comment]
> Not sure what you expect `t[:α<TAB>` to do?

You seem to have misread. The problem is with typing `t[:\alpha <TAB>`; the expected **result** is `t[:α`. 

This error is still present on a fresh install, on a new computer. This is for `PyCall v1.91.0`. Unless it's corrected in a prerelease, an you please re-open this issue?

**Comment by stevengj** [comment]
> The problem is with typing `t[:\alpha <TAB>`; the expected **result** is `t[:α`. 

Works fine for me (note: no space after `\alpha` when you hit tab).

PyCall shouldn't have anything to do with this.  If you open up a fresh notebook and type ``t[:\alpha<TAB>`, do you get `t[:α`?

**Comment by stevengj** [comment]
Ah, I can reproduce it now.  If I simply do
```jl
using PyCall
t = PyObject(1)
```
then tab-completing `t[:\alpha` no longer works.

**Comment by stevengj** [comment]
I get exactly the same issue in the REPL with `t = PyObject(1)`, so this is an issue with the Julia stdlib `REPL.REPLCompletions` module, not IJulia.

**Comment by cscherrer** [comment]
Great, thank you for tracking it down!
