### ISSUE TITLE
Minor issue - having comment as last line suppresses output

### ISSUE THREAD

**Issue by tk3369** [JuliaLang/IJulia.jl#734]
Type the following in a jupyter notebook cell:
```
a = 1
#b
```

I expect output of `1` to be displayed but the comment acts like a semicolon and suppresses output.

**Comment by stevengj** [comment]
IJulia calls the [`REPL.ends_with_semicolon` function](https://github.com/JuliaLang/IJulia.jl/blob/a5860bb8d41d58cd9b068420f4122f415cb2bde8/src/execute_request.jl#L139), so its behavior is the same as the REPL here, and any fixes should be applied to the REPL stdlib package in the JuliaLang/julia repository.

**Comment by stevengj** [comment]
See also #109, JuliaLang/julia#6225, and ipython/ipython#4525 … solving this properly (handling comments but not getting confused by `#` in strings) basically requires one to implement a [FSM](https://en.wikipedia.org/wiki/Finite-state_machine) to walk through the code.

**Comment by stevengj** [comment]
Actually, I take it back, the problem is not in `REPL.ends_with_semicolon`:
```
julia> using REPL

julia> REPL.ends_with_semicolon("a = 1\n#b")
false
```
It looks like this is a bug in SoftScope.jl:
```
julia> using SoftGlobalScope

julia> softscope_include_string(Main, "a = 1\n#b")
```
