### ISSUE TITLE
Julia XGboost Error : Julia version 1.0 on windows 10

### ISSUE THREAD

**Issue by ajaychat3** [JuliaLang/IJulia.jl#737]
Building IJulia ──────────→ `C:\Users\chatura\.julia\packages\IJulia\k5o7j\deps\build.log`
  Building Plots ───────────→ `C:\Users\chatura\.julia\packages\Plots\MnXMC\deps\build.log`
  Building XGBoost ─────────→ `C:\Users\chatura\.julia\dev\XGBoost\deps\build.log`
 Resolving package versions...
┌ Error: Error building `XGBoost`:
│ ERROR: LoadError: UndefVarError: info not defined
│ Stacktrace:
│  [1] top-level scope at C:\Users\chatura\.julia\dev\XGBoost\deps\build.jl:14
│  [2] include at .\boot.jl:317 [inlined]
│  [3] include_relative(::Module, ::String) at .\loading.jl:1038
│  [4] include(::Module, ::String) at .\sysimg.jl:29
│  [5] include(::String) at .\client.jl:388
│  [6] top-level scope at none:0
│ in expression starting at C:\Users\chatura\.julia\dev\XGBoost\deps\build.jl:7
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Pkg\src\Operations.jl:1068

**Comment by MoonCoral** [comment]
This has nothing to do with IJulia.
It has already been raised at the proper place: https://github.com/dmlc/XGBoost.jl/issues/52
