### ISSUE TITLE
build IJulia failed with Julia 1.0

### ISSUE THREAD

**Issue by hajsf** [JuliaLang/IJulia.jl#747]
I could not add `IJulia`, and got the below error, I know my internet connection is very bad, not sure if this has any impact:

> (v1.0) pkg> build IJulia
>   Building Conda ──→ `~/.julia/packages/Conda/m7vem/deps/build.log`
>   Building ZMQ ────→ `~/.julia/packages/ZMQ/ABGOx/deps/build.log`
>   Building MbedTLS → `~/.julia/packages/MbedTLS/Qo8TN/deps/build.log`
>   Building IJulia ─→ `~/.julia/packages/IJulia/k5o7j/deps/build.log`
> ┌ Error: Error building `IJulia`: 
> │   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> │                                  Dload  Upload   Total   Spent    Left  Speed
>  10 36.2M   10 4078k    0     0  19833      0  0:31:56  0:03:30  0:28:26     0
> │ curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
> │ [ Info: Installing Jupyter via the Conda package.
> │ [ Info: Downloading miniconda installer ...
> │ ERROR: LoadError: failed process: Process(`curl -g -L -f -o /Users/hasan/.julia/packages/Conda/m7vem/deps/usr/installer.sh https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh`, ProcessExited(56)) [56]
> │ Stacktrace:
> │  [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at ./error.jl:42
> │  [2] pipeline_error at ./process.jl:695 [inlined]
> │  [3] #run#505(::Bool, ::Function, ::Cmd) at ./process.jl:653
> │  [4] run at ./process.jl:651 [inlined]
> │  [5] download(::String, ::String) at ./download.jl:48
> │  [6] macro expansion at ./logging.jl:311 [inlined]
> │  [7] _install_conda(::String, ::Bool) at /Users/hasan/.julia/packages/Conda/m7vem/src/Conda.jl:146
> │  [8] _install_conda(::String) at /Users/hasan/.julia/packages/Conda/m7vem/src/Conda.jl:145
> │  [9] runconda(::Cmd, ::String) at /Users/hasan/.julia/packages/Conda/m7vem/src/Conda.jl:111
> │  [10] add at /Users/hasan/.julia/packages/Conda/m7vem/src/Conda.jl:174 [inlined] (repeats 2 times)
> │  [11] top-level scope at logging.jl:311
> │  [12] top-level scope at /Users/hasan/.julia/packages/IJulia/k5o7j/deps/build.jl:38
> │  [13] include at ./boot.jl:317 [inlined]
> │  [14] include_relative(::Module, ::String) at ./loading.jl:1038
> │  [15] include(::Module, ::String) at ./sysimg.jl:29
> │  [16] include(::String) at ./client.jl:388
> │  [17] top-level scope at none:0
> │ in expression starting at /Users/hasan/.julia/packages/IJulia/k5o7j/deps/build.jl:9
> └ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1068
> 
> ![ijulia error](https://user-images.githubusercontent.com/26045838/45587654-58c9c180-b911-11e8-84f2-79ef28b4553b.png)
>

**Comment by jvlatzko** [comment]
```
using Pkg
Pkg.build("IJulia")

```
Works for me? (I don't know about your `(v1.0) pkg> build IJulia` however..)

**Comment by stevengj** [comment]
The error
```
Info: Downloading miniconda installer ...
 ERROR: LoadError: failed process: Process(curl -g -L -f -o  …
```
means that the download is failing, which indicates a problem with your network connection.  You could try again somewhere you have a better network connection.

`build IJulia` works fine on my Mac with 1.0.
