### ISSUE TITLE
Indentation issues with if-else

### ISSUE THREAD

**Issue by jtackm** [JuliaLang/IJulia.jl#765]
When typing a typical if-else construct into a Jupyterlab notebook, code after the else (or also elseif) is automatically indented one level further than expected (similar to when forgetting an end), albeit the code is working properly. This is annoying as everything that follows an if-else needs to repeatedly by re-indented by hand. It used to be different, any idea what could cause this? 

Example:

```
x = 1
y = 0
if x == 1
    y = 5
else
    y = -5
end
```

This is on Julia 1.0.0 and ```[7073ff75] IJulia v1.13.0```.

**Comment by stevengj** [comment]
Code formatting in Jupyter is done with CodeMirror, so you should file an issue there.  cc @malmaud
