### ISSUE TITLE
dead kernel

### ISSUE THREAD

**Issue by graham1984** [JuliaLang/IJulia.jl#767]
I keep getting dead kernel. I'm not sure whats happening it worked until yesterday but this is now what happens when I try and build

julia> Pkg.build("IJulia")
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Building Conda ──→ `~/.julia/packages/Conda/uQitS/deps/build.log`
  Building ZMQ ────→ `~/.julia/packages/ZMQ/ABGOx/deps/build.log`
┌ Error: Error building `ZMQ`: 
│ ERROR: LoadError: could not open file /Users/grahamwhite/.julia/packages/BinaryProvider/1nGWd/src/OutputCollector.jl
│ Stacktrace:
│  [1] include at ./boot.jl:317 [inlined]
│  [2] include_relative(::Module, ::String) at ./loading.jl:1041
│  [3] include at ./sysimg.jl:29 [inlined]
│  [4] include(::String) at /Users/grahamwhite/.julia/packages/BinaryProvider/1nGWd/src/BinaryProvider.jl:1
│  [5] top-level scope at none:0
│  [6] include at ./boot.jl:317 [inlined]
│  [7] include_relative(::Module, ::String) at ./loading.jl:1041
│  [8] include(::Module, ::String) at ./sysimg.jl:29
│  [9] top-level scope at none:2
│  [10] eval at ./boot.jl:319 [inlined]
│  [11] eval(::Expr) at ./client.jl:389
│  [12] top-level scope at ./none:3
│ in expression starting at /Users/grahamwhite/.julia/packages/BinaryProvider/1nGWd/src/BinaryProvider.jl:8
│ ERROR: LoadError: Failed to precompile BinaryProvider [b99e7846-7c00-51b0-8f62-c81ae34c0232] to /Users/grahamwhite/.julia/compiled/v1.0/BinaryProvider/ek6VZ.ji.
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] macro expansion at ./logging.jl:313 [inlined]
│  [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1187
│  [4] _require(::Base.PkgId) at ./logging.jl:311
│  [5] require(::Base.PkgId) at ./loading.jl:855
│  [6] macro expansion at ./logging.jl:311 [inlined]
│  [7] require(::Module, ::Symbol) at ./loading.jl:837
│  [8] include at ./boot.jl:317 [inlined]
│  [9] include_relative(::Module, ::String) at ./loading.jl:1041
│  [10] include(::Module, ::String) at ./sysimg.jl:29
│  [11] include(::String) at ./client.jl:388
│  [12] top-level scope at none:0
│ in expression starting at /Users/grahamwhite/.julia/packages/ZMQ/ABGOx/deps/build.jl:1
└ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1069
  Building MbedTLS → `~/.julia/packages/MbedTLS/CwGUN/deps/build.log`
┌ Error: Error building `MbedTLS`: 
│ ERROR: LoadError: could not open file /Users/grahamwhite/.julia/packages/BinaryProvider/1nGWd/src/OutputCollector.jl
│ Stacktrace:
│  [1] include at ./boot.jl:317 [inlined]
│  [2] include_relative(::Module, ::String) at ./loading.jl:1041
│  [3] include at ./sysimg.jl:29 [inlined]
│  [4] include(::String) at /Users/grahamwhite/.julia/packages/BinaryProvider/1nGWd/src/BinaryProvider.jl:1
│  [5] top-level scope at none:0
│  [6] include at ./boot.jl:317 [inlined]
│  [7] include_relative(::Module, ::String) at ./loading.jl:1041
│  [8] include(::Module, ::String) at ./sysimg.jl:29
│  [9] top-level scope at none:2
│  [10] eval at ./boot.jl:319 [inlined]
│  [11] eval(::Expr) at ./client.jl:389
│  [12] top-level scope at ./none:3
│ in expression starting at /Users/grahamwhite/.julia/packages/BinaryProvider/1nGWd/src/BinaryProvider.jl:8
│ ERROR: LoadError: Failed to precompile BinaryProvider [b99e7846-7c00-51b0-8f62-c81ae34c0232] to /Users/grahamwhite/.julia/compiled/v1.0/BinaryProvider/ek6VZ.ji.
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] macro expansion at ./logging.jl:313 [inlined]
│  [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1187
│  [4] _require(::Base.PkgId) at ./logging.jl:311
│  [5] require(::Base.PkgId) at ./loading.jl:855
│  [6] macro expansion at ./logging.jl:311 [inlined]
│  [7] require(::Module, ::Symbol) at ./loading.jl:837
│  [8] include at ./boot.jl:317 [inlined]
│  [9] include_relative(::Module, ::String) at ./loading.jl:1041
│  [10] include(::Module, ::String) at ./sysimg.jl:29
│  [11] include(::String) at ./client.jl:388
│  [12] top-level scope at none:0
│ in expression starting at /Users/grahamwhite/.julia/packages/MbedTLS/CwGUN/deps/build.jl:1
└ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1069

julia>

**Comment by stevengj** [comment]
This is a problem installing ZMQ and MbedTLS, not IJulia, and the problem seems to be with the BinaryProvider package, so it should be reported there if it is still occurring.
