### ISSUE TITLE
JuliaPro/Julia Start Error

### ISSUE THREAD

**Issue by Svansing** [JuliaLang/IJulia.jl#768]
I just installed Julia on my Mac. After press enter to start Julia, it shows that "ERROR: SystemError (with /Users/myname/.julia/logs): mkdir: Permission denied" ("myname" is my system name). 

This does not happen for previous installation.

**Comment by ArcherWoo** [comment]
Do you fix this problem? I met same issue as well.....

**Comment by stevengj** [comment]
Is your problem just with Julia, or does it involve Jupyter/IJulia?  If the former, you should report the problem at the main Julia repository.

**Comment by stevengj** [comment]
This issue seems unrelated to IJulia per se.
