### ISSUE TITLE
Magic command error not working with Julia 1.0 due to Base.Markdown import

### ISSUE THREAD

**Issue by krystophny** [JuliaLang/IJulia.jl#769]
When trying to run magic `%` commands in the current IJulia version it should give an error message

> ... Julia does not use the IPython %magic syntax. To interact with the IJulia kernel ...

This fails because `Base.Markdown` is used instead of `Markdown,` even though using Markdown is already correct.

e.g. https://github.com/JuliaLang/IJulia.jl/blob/3e78f61d0f94387f62b4bd735518bfb22111c0cb/src/magics.jl#L34

It is easy to fix by replacing `Base.Markdown` by `Markdown` in all occurrences.

**Comment by stevengj** [comment]
Thanks, should be fixed now on the `master` branch.
