### ISSUE TITLE
IJulia ships out text/plain but not text/latex

### ISSUE THREAD

**Issue by bkamins** [JuliaLang/IJulia.jl#771]
See https://github.com/JuliaData/DataFrames.jl/issues/1581 for a description.
The core problem is that for `DataFrame` the DataFrames.jl package provides:
* `text/plain`
* `text/html`
* `text/latex`

formats, but IJulia pushes out to Jupyter only the first two. Then when trying to convert the notebook to PDF via LaTeX `text/plain` format is used by Jupyter producing an error (and it should use `text/latex` which gives a nicely formatted table in LaTeX).

**Comment by pdeffebach** [comment]
Actually, I think this is likely a larger issue about the way the html escaping works. The html conversion seems to have some problems with escaping rules for the styled input. This is likely a problem beyond DataFrames but I would need to explore more. 

The issue might be with pandoc, ultimately. But it's unclear.

**Comment by bkamins** [comment]
To my understanding the issue (maybe not the only issue) is that if you look at a sample cell in the notebook it looks like this:

```
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<table class=\"data-frame\"><thead><tr><th></th><th>A</th><th>B</th><th>C</th></tr><tr><th></th><th>Int64</th><th>Bool</th><th>Char</th></tr></thead><tbody><tr><th>1</th><td>1</td><td>true</td><td>'a'</td></tr><tr><th>2</th><td>2</td><td>false</td><td>'b'</td></tr></tbody></table>"
      ],
      "text/plain": [
       "2×3 DataFrame\n",
       "│ Row │ A     │ B     │ C    │\n",
       "│     │ \u001b[90mInt64\u001b[39m │ \u001b[90mBool\u001b[39m  │ \u001b[90mChar\u001b[39m │\n",
       "├─────┼───────┼───────┼──────┤\n",
       "│ 1   │ 1     │ true  │ 'a'  │\n",
       "│ 2   │ 2     │ false │ 'b'  │"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "x = Dict(\"A\" => [1,2], \"B\" => [true, false], \"C\" => ['a', 'b'])\n",
    "DataFrame(x)"
   ]
  },
```

in `outputs/data` section you have two kinds of outputs `"text/html"` which is used for rendering in the browser and `"text/plain"` which is used for generaring PDF via LaTeX. However, actually the `"text/plain"` output is intended to be sent to a terminal (as it contains escapes) and IJulia should collect and send `"text/latex"` to PDF generation as we can produce such output in DataFrames.jl.

**Comment by stevengj** [comment]
Yes, we should send both.
