### ISSUE TITLE
MethodError for docstring of copy inside of jupyter

### ISSUE THREAD

**Issue by Blonck** [JuliaLang/IJulia.jl#776]
Hi,

I guess I found a bug when displaying the docstring inside jupyter

`?copy` gives 

> MethodError: no method matching latex(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Markdown.HorizontalRule)
> Closest candidates are:
>   latex(::IO, !Matched::Markdown.Table) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Markdown/src/GitHub/table.jl:154
>   latex(::IO, !Matched::Markdown.LaTeX) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Markdown/src/IPython/IPython.jl:28
>   latex(::IO, !Matched::Markdown.MD) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Markdown/src/render/latex.jl:19
>   ...
> 
> Stacktrace:
>  [1] latex(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Array{Any,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Markdown/src/render/latex.jl:23
>  [2] latex at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Markdown/src/render/latex.jl:19 [inlined]
>  [3] show at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Markdown/src/render/latex.jl:172 [inlined]
>  [4] limitstringmime(::MIME{Symbol("text/latex")}, ::Markdown.MD) at /home/marenz/.julia/packages/IJulia/yRDsd/src/inline.jl:37
>  [5] display_mimestring(::MIME{Symbol("text/latex")}, ::Markdown.MD) at /home/marenz/.julia/packages/IJulia/yRDsd/src/execute_request.jl:72
>  [6] display_dict(::Markdown.MD) at /home/marenz/.julia/packages/IJulia/yRDsd/src/execute_request.jl:100
>  [7] #invokelatest#1 at ./essentials.jl:697 [inlined]
>  [8] invokelatest at ./essentials.jl:696 [inlined]
>  [9] execute_request(::ZMQ.Socket, ::Msg) at /home/marenz/.julia/packages/IJulia/yRDsd/src/execute_request.jl:255
>  [10] #invokelatest#1 at ./essentials.jl:697 [inlined]
>  [11] invokelatest at ./essentials.jl:696 [inlined]
>  [12] eventloop(::ZMQ.Socket) at /home/marenz/.julia/packages/IJulia/yRDsd/src/eventloop.jl:8
>  [13] (::getfield(IJulia, Symbol("##12#15")))() at ./task.jl:259

Displaying other docstring works so I guess the rendering of some Markdown element fails.
I would like to fix the bug myself, but the last time I used Julia was somewhen before v0.2. So I even have no idea where to start.

Julia version: 1.0.2
IJulia version: 1.14.0
Jupyer version: 4.4.0

Would be nice if anybody could look into it or give a hint how to fix it. Thanks.

**Comment by stevengj** [comment]
This looks like a bug in Julia's markdown rendering; it claims to support text/latex output, but is missing latext rendering rules for some elements.

It was exposed in the latest IJulia release by 7311e517194ddba07af64952b0f9413401213050 (since previously we did not output text/latex if text/markdown was available).

It should be fixed in Julia, but in the meantime we should probably wrap the rendering code in a `try` block so that it ignores errors in inessential MIME types.
