### ISSUE TITLE
wrong menu item anchor href with julia kernel

### ISSUE THREAD

**Issue by xgdgsc** [JuliaLang/IJulia.jl#780]
I have a weird issue with julia kernel on my machine. I' m not sure it' s a problem with IJulia.jl but want to ask here. 

The menu items of my julia notebook like "Find and replace" would have href to `<a href="#"> Find and Replace </a>` with inspect element. The link hint when I move mouse over that `#` would be `http://localhost:8888/#` instead of the correct  `http://localhost:8888/MY_NOTEBOOK_PATH.ipynb#` . So clicking on items would result in a disastrous redirect to root. It doesn' t happen to a newly created julia notebook. It only happens to an old notebook I have worked with for a month, which I compared sections in the file except "cells" , they are basically the same. What could be the reason? Any suggestions on posible workarounds? Thanks.

 here' s the old(left) and new created file content compare side by side. 
![deepinscreenshot_select-area_20181114181703](https://user-images.githubusercontent.com/1189869/48476267-8eb7f300-e839-11e8-9ef6-fd7b6f674384.png)

**Comment by stevengj** [comment]
Closing in favor of https://github.com/JuliaGizmos/Interact.jl/issues/277
