### ISSUE TITLE
Install fails in official Docker image due to missing bunzip2

### ISSUE THREAD

**Issue by msegado** [JuliaLang/IJulia.jl#781]
FYI, IJulia installation is currently failing in the official Docker image... looks like the miniconda installer assumes `bunizip2` will be available, which isn't by default.

To reproduce:
```
docker run --rm julia julia -e 'using Pkg; Pkg.add("IJulia")'
```
The relevant part of the output:
```
...
  Building Conda ──→ `~/.julia/packages/Conda/uQitS/deps/build.log`
  Building ZMQ ────→ `~/.julia/packages/ZMQ/ABGOx/deps/build.log`
  Building MbedTLS → `~/.julia/packages/MbedTLS/r1Ufc/deps/build.log`
  Building IJulia ─→ `~/.julia/packages/IJulia/DL02A/deps/build.log`
┌ Error: Error building `IJulia`: 
│   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
│                                  Dload  Upload   Total   Spent    Left  Speed
100 59.6M  100 59.6M    0     0  4335k      0  0:00:14  0:00:14 --:--:-- 4353k
│ WARNING: bzip2 does not appear to be installed this may cause problems below
│ PREFIX=/root/.julia/conda/3
│ /root/.julia/conda/3/installer.sh: 346: /root/.julia/conda/3/installer.sh: bunzip2: not found
│ tar: This does not look like a tar archive
│ tar: Exiting with failure status due to previous errors
│ ┌ Warning: Could not execute `jupyter --version`.
│ └ @ Main ~/.julia/packages/IJulia/DL02A/deps/build.jl:41
│ [ Info: Installing Jupyter via the Conda package.
│ [ Info: Downloading miniconda installer ...
│ [ Info: Installing miniconda ...
│ ERROR: LoadError: failed process: Process(`/root/.julia/conda/3/installer.sh -b -f -p /root/.julia/conda/3`, ProcessExited(1)) [1]
...
```

**Comment by msegado** [comment]
Yeah, looks like someone already opened an issue over there: https://github.com/ContinuumIO/anaconda-issues/issues/8182

Seems like it's also caused problems for people installing Anaconda on GCP. Hopefully they just bundle bunzip2 with the installer to simplify things in the future.

(Alternatively, it would be possible for Conda.jl to work around it by shipping a backup bunzip2 binary, but it's probably better to just wait for the upstream installer fix and assume that most people installing on atypical Linux systems will know how to work around it in the meantime...)

**Comment by stevengj** [comment]
IJulia no longer uses Jupyter to build itself, so this issue seems moot.  Anyway is an Anaconda or Conda.jl issue, not IJulia.
