### ISSUE TITLE
Garbage collection issues using IJulia?

### ISSUE THREAD

**Issue by jnoynaert** [JuliaLang/IJulia.jl#785]
The Julia kernel appears to refuse to garbage collect allocations on Windows?

Repeatedly calling: 
> x = fill(NaN, (5000000,8))

increases the size of the Julia process in memory by 305 mb chunks (with no limit, until reaching out of memory).
-Reassigning x = 0 does not reduce the process size in memory as reported by task manager.
-Calling GC.gc() does not release the additional memory.

When using the standard Julia REPL, memory growth halts at +710 mb, with the additional allocation released (to +305mb, expected size of the array in memory) after a manual garbage collection call.

This behavior holds true for any large array operations so far.

IJulia 1.14.1 (using default miniconda setup, conda v1.1.1)
Julia 1.0.2 
Windows 7 SP1

**Comment by stevengj** [comment]
The `Out` array records all of the outputs of the previous cells.  So if `x` is the output of your cells, it gets saved.  You can do `empty!(Out)` to force IJulia to forget the old outputs.

**Comment by stevengj** [comment]
See e.g. [here](https://stackoverflow.com/questions/49515085/python-garbage-collection-sometimes-not-working-in-jupyter-notebook) and [here](https://stackoverflow.com/questions/16261240/releasing-memory-of-huge-numpy-array-in-ipython/16278056) for similar discussions about IPython.

**Comment by jnoynaert** [comment]
Makes sense. Knowing that saves the usability of jupyter/hydrogen for me for a lot of work--thanks!
