### ISSUE TITLE
Error when installing IJulia

### ISSUE THREAD

**Issue by ANEREL** [JuliaLang/IJulia.jl#786]
![capture](https://user-images.githubusercontent.com/20476534/49434493-fb7d3800-f7bc-11e8-8b37-88dbab4b6f2f.PNG)

**Comment by fredrikekre** [comment]
Seems like a JuliaPro issue that you should report to JuliaComputing instead.

**Comment by ANEREL** [comment]
Thank you @fredrikekre will open an issue there.
