### ISSUE TITLE
[Docs] How can I tell if my code runs on Jupyter?

### ISSUE THREAD

**Issue by Datseris** [JuliaLang/IJulia.jl#798]
Juno provides the following code snippet that can check whether the code runs on Juno:
```julia
(isdefined(Main, :Juno) && Main.Juno.isactive())
```
what is the equivalent for IJulia?

I need this because IJulia can't display UnicodePlots properly and I am defining a struct that is displayed as a unicode plot. I need to dispatch to use ASCII if the code runs on IJulia.

---

I couldn't find the answer to this in the docs and I think it should be included there.

**Comment by stevengj** [comment]
See here: https://github.com/JuliaLang/IJulia.jl#detecting-that-code-is-running-under-ijulia

Why don't UnicodePlots display properly?

**Comment by stevengj** [comment]
Ah, I see Evizero/UnicodePlots.jl#9

**Comment by Datseris** [comment]
Thank you for your attention. But yes as you saw already, for example a scatter plot looks like this currently: 

![image](https://user-images.githubusercontent.com/19669089/51432408-b65f7900-1c37-11e9-8382-c5c9ddcd49ae.png)
