### ISSUE TITLE
Informative "Kernel Died" Message

### ISSUE THREAD

**Issue by MaximilianJHuber** [JuliaLang/IJulia.jl#799]
Sometimes when I run Julia in a Jupyter Notebook it crashes and the "kernel died" message comes up. But the error message (e.g. SEGFAULT ...) is not displayed in the notebook or in the console, so I have to run Julia in a console and reproduce the error there, to read what happened. 
Can this be improved?

**Comment by stevengj** [comment]
Usually any error messages are displayed in the console for me... what OS are you using, and how are you launching Jupyter?

**Comment by stevengj** [comment]
See also https://github.com/JuliaLang/IJulia.jl#debugging-ijulia-problems … because IJulia is capturing stdout, sometimes you have to disable that to see error messages.

**Comment by MaximilianJHuber** [comment]
I run Win10 and call `.....\.julia\packages\Conda\hsaaN\deps\usr\Scripts\jupyter-notebook.exe`.

Thank you for your suggestion, I will do just that.

**Comment by MaximilianJHuber** [comment]
Works!
