### ISSUE TITLE
Typing this string by accident crashes a cell

### ISSUE THREAD

**Issue by sefffal** [JuliaLang/IJulia.jl#811]
If you type the following into an IJulia cell:
```julia
abc::Def{,
```
The cell hangs and you can no longer edit it. If you're persistent and you try to edit it, the contents of the cell sometimes disappears. Sometimes this even gets auto-saved and you lose work.
I noticed that if you're quick, you can change the cell type to Raw or Markdown and fix the typo, then convert it back to recover.

Tested in Jupyter 4.2.0, Jupyter Lab version 0.31.8,  Julia 1.0.3, IJulia v1.15.2

**Comment by sefffal** [comment]
I should add that this has happened to me a number of times across recent Chrome, Firefox, and Edge browsers on Windows 10 with all updates installed.

**Comment by stevengj** [comment]
Sounds like a bug in CodeMirror (the software that handles cell editing) and should be reported there.
