### ISSUE TITLE
I am not able to open jupyter notebook when i use the statement notebook(detached=true). I have even tried to see which ports are open and even tried on chrome (localhost:8888) but it doesnt open. I have also installed anaconda and still i am not able to open Jupyter notebook on my system.

### ISSUE THREAD

**Issue by AbhinavKoul** [JuliaLang/IJulia.jl#814]
description :  Win 10 64 bit

**Comment by stevengj** [comment]
Could be some kind of firewall on your system that is preventing jupyter from talking to your browser.   See e.g. https://github.com/ipython/ipython/issues/2499

**Comment by stevengj** [comment]
If it also happens with anaconda then it is not an IJulia-specific issue.
