### ISSUE TITLE
Incorrect Indentation  when multiple "for" or "if" are used in list comprehensions in V1.17.0

### ISSUE THREAD

**Issue by fulgenssequar** [JuliaLang/IJulia.jl#817]
In the jupyter cells, after meeting list comprehensions with multiple "for" or "if", the code afterward gets wrong indentation as if it is expecting an "end".
For example:

[x for x in 1:10] #No mistake

[x for x in 1:10 if x > 4] #Mistake

[(x,y) for x in 1:10 for y in 5:7] #Mistake

[(x,y) for x in 1:10 for y in 5:7 end] #No mistake, though incorrect in grammar

**Comment by stevengj** [comment]
File an issue with https://github.com/codemirror/CodeMirror, which is responsible for the formatting.
