### ISSUE TITLE
DataFrame display does not truncate columns

### ISSUE THREAD

**Issue by namheegordonkim** [JuliaLang/IJulia.jl#822]
Currently, if I try to print a dataframe, rows are truncated with "..." after a few entries, but columns are displayed from first to last. This is problematic if I have a very high dimensional data, e.g. bioinformatics.

Is there a way to configure it so that only first columns show, and should this be the default behavior as with Pandas in Python kernel?

**Comment by stevengj** [comment]
IJulia sets the default number of columns to 80 and passes `:limit=>true`, so it is up to the DataFrames.jl package to use this information—you should file an issue there.
