### ISSUE TITLE
Package Blink not found in current path:Package Blink not found in current path:

### ISSUE THREAD

**Issue by markb1957** [JuliaLang/IJulia.jl#825]
Caveats: I am NOT a developer at all. My abilities consist of very limited Matlab use and some limited Fortran back in the "submit a stack of cards" days. 
Issue : What I am trying to do is install IJulia so I can run Jupyter notebook and learn what Julia is all about. I am doing this on a Mac. My abilities, such as they are, do extend to being able to poke around directories in the Terminal window.  So in the process of trying to do this, I get the message in the subject line. I do a system wide search for Blink and don't find it (it turns out there's a gif on my machine called Blink, tho...who knew?) Any help greatly appreciated. And in fact, if you think I am headed down the wrong track to learn Julia, especially as a Matlab replacement, please advise.  Thanks, Mark

**Comment by stevengj** [comment]
It sounds like you are trying to use the Blink package (https://github.com/JunoLab/Blink.jl)?

You can install Blink in Julia by doing
```jl
using Pkg
Pkg.add(“Blink”)
```
IJulia itself does not use Blink, so I guess it was being used by some other code you are trying to run in Julia?

In general, you use Pkg to install Julia packages and all their dependencies. (Even easier, you can just type `]` at the Julia prompt to enter package mode, at which point you can simply type `add Blink`)

**Comment by stevengj** [comment]
For general Julia usage questions, I recommend asking at https://github.com/JunoLab/Blink.jl

**Comment by stevengj** [comment]
To install IJulia itself you should just be doing `Pkg.add(“IJulia”)`
