### ISSUE TITLE
Links provided by @which do not work for some functions

### ISSUE THREAD

**Issue by 4lrdyD** [JuliaLang/IJulia.jl#832]
In previous versions of Julia and IJulia, the links provided by `@which` opened a page with the corresponding code on github. Now, in the current version, the macro provides the link, however, it doesn't open any page for some especific functions, for example:
```
a=sparse(rand(10));
b=a;
@which a+b
```
**Result:**
+(x::SparseArrays.AbstractSparseArray{Tv,Ti,1} where Ti where Tv, y::SparseArrays.AbstractSparseArray{Tv,Ti,1} where Ti where Tv) in SparseArrays at [C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\SparseArrays\src\sparsevector.jl:1292](url)

By clicking on the link, it doesn't redirect to the desired page.

**Comment by stevengj** [comment]
This is JuliaLang/julia#31084, not an IJulia bug.
