### ISSUE TITLE
warning when running Pkg.build - a deprecated syntax?

### ISSUE THREAD

**Issue by HaoLi111** [JuliaLang/IJulia.jl#833]
my environment:

  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0 (2018-08-08 06:46 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

```julia

Pkg.build("SpecialFunctions")
```
shows

```
WARNING: Base.Pkg is deprecated, run `using Pkg` instead
  likely near C:\Users\DELL\.julia\packages\IJulia\9ajf8\src\kernel.jl:52
```

**Comment by fredrikekre** [comment]
Just as the warning suggests you need `using Pkg` before calling `Pkg.build`.

**Comment by stevengj** [comment]
Or use `] build SpecialFunction`
