### ISSUE TITLE
Issues concerning installation of Blink and Escher

### ISSUE THREAD

**Issue by Bilgemesh** [JuliaLang/IJulia.jl#836]
Hi!
I am really sorry to disturb you with an issue which might have already been discussed a lot of times, but I have no other opportunity to get a solution. First of all Blink doesn't install properly in my computer with Julialang Repl: there were many errors which had accompanied the installation process. Now after "using Blink" gives out different errors: 

1) ERROR: LoadError: MbedTLS not installed properly, run Pkg.build("MbedTLS"), restart Julia and try again ;
2) ERROR: LoadError: LoadError: Failed to precompile MbedTLS [739be429-bea8-5141-9913-cc70e7f3736d] to C:\Users\Robwarts\.julia\compiled\v1.1\MbedTLS\bf9T0.ji ;
3) ERROR: LoadError: LoadError: Failed to precompile HTTP [cd3eb016-35fb-5094-929b-558a96fad6f3] to C:\Users\Robwarts\.julia\compiled\v1.1\HTTP\zXWya.ji ;
4) ERROR: LoadError: LoadError: Failed to precompile Mux [a975b10e-0019-58db-a62f-e48ff68538c9] to C:\Users\Robwarts\.julia\compiled\v1.1\Mux\cs9xb.ji ;
5) ERROR: Failed to precompile Blink [ad839575-38b3-5650-b840-f874b8c74a25] to C:\Users\Robwarts\.julia\compiled\v1.1\Blink\wSmkt.ji ;

As for Escher it also very faulty in my JuliaLang Repl. 
I even downloaded the Blink zip-file from GitHub and pasted it into the Julialang folder. So hasn't worked adequately yet. So, neither Blink nor Escher is available to me. 
Could you, please, kindly comment this mistakes. Were there solved problems. 
I am a self-taught programmer, approximately lika a junior level in C++ and C.

**Comment by stevengj** [comment]
What is the full error log when you do
```jl
import Pkg
Pkg.build("MbedTLS")
```
?   If there is an error message about a download failure, perhaps you are behind some kind of firewall that prevents Julia from downloading things?

In any case, none of these are errors with IJulia.   If the root problem is a failure installing MbedTLS, then you should file an issue with the MbedTLS.jl package.
