### ISSUE TITLE
Error platform_key() is deprecated while building ZMQ and building MbedTLS

### ISSUE THREAD

**Issue by Potatohuntress** [JuliaLang/IJulia.jl#838]
Hello everyone,
for a schoolproject I need to work out a Operations Research Model with IJulia and JuMP in a jupiternotebook.

**Right now I did the following steps:**
1. Download and install Anaconda for Python 3.7 on Windows (I am using Win7)
2. Download and install Julia v1.1.0 (64bit Windows)
3. Open Julia
4. press ] and "add IJulia"
but now I am getting this [Error platform_key() is deprecated](https://imgur.com/a/mZlLpfy)

![Error_add IJulia](https://user-images.githubusercontent.com/50263497/57177710-4e8c1180-6e67-11e9-96a6-4c32efdea668.PNG)

I had the same problem yesterday and ignored it, which resulted in my Julia 1.1.0-jupyter-notebook always having a dead kernel? I did some nice internet magic, which of course didn't work and today I had to wipe the whole computer. I am now on my second try and now I need to know, what the two errors for **building ZMQ** **and building MbedTLS** mean.

Quick Edit: Firewall is off

**Comment by Potatohuntress** [comment]
ok. I fixed the symptoms and now my 1.1.0 Julia kernel works fine for jupiter-notebooks on Anaconda3. 

1. Beg a friend to install it on his computer (without problems, no idea why my computer did not work) and make him send you his .julia folder (where the packages are installed)
2. Delete your .julia folder
3. Open Julia -> ] ->(check here with "status", if you really don't have any packages installed) and add IJulia
4. Ignore the Errors (see picture in first post)
5. Delete the ZMQ and the MbedTLS folder
6. Copy the ZMQ and the MbedTLS folder of your friend in your .julia\packages folder.
7. Restart Julia and try ] -> build IJulia to see, if it works now (for me it did)

again, sorry for the shitty fix

**Comment by stevengj** [comment]
The "platform_key is deprecated" is a warning about an API change, not an error, which is why it is safe to ignore it.

The actual error seems to be some kind of network error due to a security firewall that is blocking your downloads.  (It's pretty hard to tell for sure because the screenshot is low resolution … don't post screenshots, copy the actual text and paste it into a [quoted code block](https://help.github.com/en/articles/basic-writing-and-formatting-syntax#quoting-code).)

**Comment by davidbp** [comment]
I had a similar issue.

I removed anaconda, downloaded it again and now it works. Maybe this way you don't need a friend with the ZMQ and MbedTLS folders :). I had this issue with  OSX Mojave.
