### ISSUE TITLE
[Meta] Code Change IPython 1.0 -> 2.0

### ISSUE THREAD

**Issue by Carreau** [JuliaLang/IJulia.jl#84]
I open this as a meta issue for all the change/simplification/removed IPython-ism
that happen during the development toward 2.0.

 - [ ] ipython/ipython#4292 should allow you to simply set the `char`s on which the completer can be reinvoke (`!` is not a valid char in python tokens for example)
 - [ ] ipython/ipython#4293 should allow you to get rid of the tooltip.js you are sending in  your profile.

I'll try to keep updating this issue every time we remove a python-ism or that something that may simplify your packaging is submitted.

**Comment by stevengj** [comment]
I think this can be closed since #325?
