### ISSUE TITLE
add info on nteract to README.md?

### ISSUE THREAD

**Issue by PaulSoderlind** [JuliaLang/IJulia.jl#841]
nteract seems to be a promising alternative way of working with notebooks and it avoids the need to have a Python installation. 

I followed these steps and it works well (on Windows and Ubuntu):
- installed IJulia (but did not run `notebook()` to avoid prompting a download of Python)
- installed nteract desktop

Mentioning this in the README.md might be worthwile.

**Comment by stevengj** [comment]
Sure, a PR would be welcome

**Comment by PaulSoderlind** [comment]
done
