### ISSUE TITLE
Failed to install IJulia on windows 10 / Julia 1.1.1

### ISSUE THREAD

**Issue by patdub** [JuliaLang/IJulia.jl#843]
building of conda, ZMS, MdebTLS and IJulia is ok but after entering using IJulia then notebook(), I have the following error message:

[ Info: Downloading miniconda installer ...
ERROR: failed process: Process(`'C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe' -Version 3 -NoProfile -Command "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; (New-Object System.Net.Webclient).DownloadFile('https://repo.continuum.io/miniconda/Miniconda3-4.5.4-Windows-x86_64.exe', 'C:\Users\Patrick\.julia\conda\3\installer.exe')"`, ProcessExited(3221225477)) [3221225477]

Any idea.
Julia 1.1.0 was ok.
Patrick.

**Comment by patdub** [comment]
The problem is probably coming from windows where PowerShell fails to start in an unpredictable way.

I succeed to have a PowerShell operating correctly for some time and I have now IJulia correctly running.

Patrick.

**Comment by Javsnot** [comment]
Did the problem resolve itself? I am getting the same exact error for Pkg.build("PyCall")...
