### ISSUE TITLE
Jupyter display full output results

### ISSUE THREAD

**Issue by shuqing333** [JuliaLang/IJulia.jl#844]
Hi I'm trying to change the Jupyter default output display setting from only display the last result to display all results. But I tried the code 
```py
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"
```
It gives me the error message
> syntax: extra token "IPython" after end of expression

I don't know how to solve this problem. None of the method seems to work

**Comment by stevengj** [comment]
IJulia is not Python, and Python code won't work — all the code input is in Julia.

IJulia doesn't have the analogue of `ast_node_interactivity = "all"`; it only ever displays the last result in a cell.   You can add [`@show` in front of specific lines](https://docs.julialang.org/en/latest/base/base/#Base.@show) where you want to see intermediate outputs, however.

**Comment by PToTheK** [comment]
Is there another way to enable this feature in iJulia?

Maybe by wrapping up each expression internally with a call to display.

**Comment by fredrikekre** [comment]
You can use [`Unlimited`](https://tkf.github.io/DisplayAs.jl/stable/#DisplayAs.Unlimited) from the [`DisplayAs.jl`](https://github.com/tkf/DisplayAs.jl) package.

**Comment by PToTheK** [comment]
@fredrikekre thank you very much for this ultrafast answer!
How does this apply to the case:

    a=1
    b=7

where the output should be

    1
    7

**Comment by MohammadHudaNSW** [comment]
Can this feature be created please for Julia?
Similar to IPython's:

```
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"
```

**Comment by xgdgsc** [comment]
If you don' t use jupyter notebook' s markdown capabilities you can try my workflow described at [Release persist inline results · xgdgsc/julia-vscode](https://github.com/xgdgsc/julia-vscode/releases/tag/persist) . Which shows and persists inline results of every cell line.
