### ISSUE TITLE
Docstrings don't open in section at bottom of screen

### ISSUE THREAD

**Issue by jvns** [JuliaLang/IJulia.jl#85]
In IPython Notebook, when I type `pd.read_csv(` and press tab three times, the documentation opens in a separate section at the bottom of the screen, which makes it easy to read a long docstring. 

In the IJulia notebook, this doesn't seem to be working. I'm using the latest snapshot of Julia 2.0 and IPython Notebook 1.0 from Anaconda. 

Here's a screenshot of the IPython behavior: 

![python-notebook](https://f.cloud.github.com/assets/817739/1315603/0a655842-3289-11e3-926e-79e19ff1110f.png)

**Comment by stevengj** [comment]
Seems like this issue is no longer relevant to Jupyter.
