### ISSUE TITLE
Interact only works after kernel restart

### ISSUE THREAD

**Issue by hhaensel** [JuliaLang/IJulia.jl#850]
For kernels >= 0.7 Interact does not work if the kernel is loaded for the first time.
A minimal example is
```
using Interact
s = slider(1:10)
x = observe(s)
display.([s, x]);
```

![image](https://user-images.githubusercontent.com/31985040/60420180-607bfd80-9be7-11e9-86e9-dac06ab1132a.png)

The slider is drawn and can be moved, but the attached observable is not responsive.

After a kernel restart, though, everything works as expected.

![image](https://user-images.githubusercontent.com/31985040/60420417-fc0d6e00-9be7-11e9-998d-54cd1b5d7491.png)

**Comment by travigd** [comment]
This issue should be moved to [WebIO](https://github.com/JuliaGizmos/WebIO.jl/issues) and addressed there. Please repost. Thanks!

**Comment by hhaensel** [comment]
Done!
[WebIO PR #316](https://github.com/JuliaGizmos/WebIO.jl/issues/316)
