### ISSUE TITLE
Number coloring

### ISSUE THREAD

**Issue by cossio** [JuliaLang/IJulia.jl#860]
I'm not sure if this can be addressed here.

In Julia you can type `10000` or `10_000` to refer to the same integer, or `10000.0` and `10_000.0` to refer to the same float.

But Jupyter lab notebook coloring seems to distinguish between them:

![image](https://user-images.githubusercontent.com/10637482/62299575-2e0e2c00-b443-11e9-94ae-466f646dcc5f.png)

This is a visual nuisance.

**Comment by stevengj** [comment]
I agree that this should be fixed, but that's not up to IJulia — syntax highlighting in a Jupyter notebook is handled by CodeMirror, so this should be fixed in the Julia CodeMirror mode.  

cc @malmaud

**Comment by cossio** [comment]
Is there another Github repo where the issue should be raised?
