### ISSUE TITLE
IJulia doesn't work with Jupyter --transport=ipc 

### ISSUE THREAD

**Issue by marius311** [JuliaLang/IJulia.jl#862]
I'm trying to install a Julia 1.1 / IJulia 1.19.0 kernel on JupyterLab 1.0.4. It installs fine, but then the kernel hangs whenever I try to evaluate anything. The JupyterLab statusbar tells me `Julia 1.1 | Connected`. I have tried enabling IJulia debug but nothing is printed. By inserting my own print statements, I have verified that it at least makes it to right before the line: https://github.com/JuliaLang/IJulia.jl/blob/a93ddfdd834a3cbf7fb1990f7f77109e700a8563/src/kernel.jl#L52

One weird thing is that this is happening when JupyterLab is launched by JupyterHub, but on the same system if I launch JupyterLab by hand, the kernel seems to work fine. 

Any suggestions how I can figure out what is going on? Thanks for any help.

**Comment by rcthomas** [comment]
I've confirmed this behavior on the same system.  I also have a docker-compose setup that runs a hub and a notebook container with 2 test users in it.  If you install IJulia into a test user account on the target container and try to use the kernel, you get the behavior described by @marius311 here.

I've set logging on the notebook config to report everything, and turned on `c.Session.debug`.  So far mostly I see messages from the notebook server like 

`[W 2019-08-05 22:11:40.485 SingleUserLabApp handlers:229] Timeout waiting for kernel_info reply from e0a618ab-d82c-48f8-a8f9-1bb297a733f6`

In another session I saw (info lines in between redacted):

```
[W 2019-08-05 22:07:03.572 SingleUserLabApp handlers:229] Timeout waiting for kernel_info reply from c05c1303-1c69-435a-a3e8-b0bf51e2d51d
[E 2019-08-05 22:07:03.576 SingleUserLabApp handlers:276] Error opening stream: HTTP 404: Not Found (Kernel does not exist: c05c1303-1c69-435a-a3e8-b0bf51e2d51d)
[E 2019-08-05 22:07:03.588 SingleUserLabApp handlers:276] Error opening stream: HTTP 404: Not Found (Kernel does not exist: c05c1303-1c69-435a-a3e8-b0bf51e2d51d)
```

Finally, when I shut down the server from the hub, I get a bunch of json output from the notebook server log that starts with

```
{'content': {},
 'header': {'date': datetime.datetime(2019, 8, 6, 5, 10, 40, 548133, tzinfo=datetime.timezone.utc),
            'msg_id': '99d0eb7c-00f899e777236d621f7a8768',
            'msg_type': 'kernel_info_request',
            'session': '54a76483-470f-4f74-80f8-d6b4c84bcedd',
            'username': 'torgo',
            'version': '5.3'},
 'metadata': {},
 'msg_id': '99d0eb7c-00f899e777236d621f7a8768',
 'msg_type': 'kernel_info_request',
 'parent_header': {}}
[b'<IDS|MSG>',
 b'436975ef45ccaeb7910d182ac8202f0c173d64335c683a1ee15561c692e48e6c',
 b'{"msg_id":"99d0eb7c-00f899e777236d621f7a8768","msg_type":"kernel_info_reques'
 b't","username":"torgo","session":"54a76483-470f-4f74-80f8-d6b4c84bcedd","date'
 b'":"2019-08-06T05:10:40.548133Z","version":"5.3"}',
 b'{}',
 b'{}',
 b'{}']
[]
{'buffers': [],
 'content': {},
 'header': {'date': '2019-08-06T05:11:40.511Z',
            'msg_id': 'c661a6fe-cf76-475a-9667-995acf9a508d',
            'msg_type': 'kernel_info_request',
            'session': '54a76483-470f-4f74-80f8-d6b4c84bcedd',
            'username': '',
            'version': '5.2'},
 'metadata': {},
 'parent_header': {}}
```

I can provide the docker-compose setup if that helps debug.

**Comment by rcthomas** [comment]
It seems fine when the hub and the notebook server run on the same container, but when you split the hub out and have notebooks spawn on another container, it just seems the kernel fails to initialize, it just times out.  Doesn't matter if the proxy is running in the same container as the hub or in a separate container.

Does anyone else have a successful JupyterHub setup with IJulia running from notebooks spawned remotely?

**Comment by rcthomas** [comment]
IJulia works with the default `--transport` option (tcp) but with `--transport=ipc` it fails.  This Dockerfile can reproduce the issue:

```
FROM continuumio/miniconda3
RUN \
    conda update --yes conda && \
    conda install --yes jupyterlab
WORKDIR /root
RUN \
    wget https://julialang-s3.julialang.org/bin/linux/x64/1.2/julia-1.2.0-linux-x86_64.tar.gz && \
    tar zxvf julia-1.2.0-linux-x86_64.tar.gz
ENV PATH=/root/julia-1.2.0/bin:$PATH
RUN \
    julia -e 'ENV["JUPYTER"]=""; ENV["IJULIA_DEBUG"]=true; using Pkg; Pkg.add("IJulia")'
CMD ["jupyter", "lab", "--allow-root", "--ip=0.0.0.0", "--debug", "--transport=ipc"]
```

**Comment by marius311** [comment]
Awesome, thanks for tracking that down @rcthomas. Any chance this could get looked at now that we have a much better handle on what's happening? 

I'm guessing this may have been what was reported in https://github.com/JuliaLang/IJulia.jl/issues/561 too.

**Comment by stevengj** [comment]
Right now the ZMQ sockets [are bound to](https://github.com/JuliaLang/IJulia.jl/blob/92b01a291519ecf68fbb58019c29b7747044584d/src/init.jl#L87-L91) `transport://ip:port`, where `transport`, `ip`, and `port` are obtained from the `profile` dictionary that Jupyter provides to IJulia upon launch.

Presumably for `ipc` transport the socket is bound in some other way?

**Comment by stevengj** [comment]
Ah, it seems that for ipc you are supposed to do `ip-port` rather than `ip:port`.  At least, this is [what ipykernel does](https://github.com/ipython/ipykernel/blob/ca3077e87618eacbb5e312af3f10935269ed91e2/ipykernel/kernelapp.py#L183-L200).  A PR following ipykernel would be welcome.

**Comment by marius311** [comment]
PR submitted! Thanks for the simple instructions. I confirm this fixes it too on the cluster I initially ran into this on (NERSC).

**Comment by aramirezreyes** [comment]
Oh god! This was extremely hard to find! I've spent several days trying pinpoint the problem. Also on NERSC's Cori system.
