### ISSUE TITLE
Calls to jupyterlab() always ask to install on Windows

### ISSUE THREAD

**Issue by jlperla** [JuliaLang/IJulia.jl#866]
On Windows 10, Julia 1.2.  Doesn't seem to happen on OSX.

When I call 
```julia
using IJulia; jupyterlab(detached = true)
```
The first time, it correctly asks me to install jupyterlab, then installs it and launches the browser

However, on subsequent times it still asks to install jupyterlab.  Running it again, I get
```julia
julia> using IJulia; jupyterlab(detached = true)
install JupyterLab via Conda, y/n? [y]:
[ Info: Running `conda install -y jupyterlab` in root environment
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

[ Info: running setenv(`'C:\Users\jlperla\.julia\conda\3\Scripts\jupyter.exe' lab`,
# etc.
```
This is inconsistent with calling `notebook()` which doesn't have this issue

**Comment by jlperla** [comment]
Here is the issue:  the code to construct the executable name to be checked is wrong on windows.  See this output
```
julia> jupyter = first(IJulia.find_jupyter_subcommand("lab"))
"C:\\Users\\jlperla\\.julia\\conda\\3\\Scripts\\jupyter.exe"

julia> "$jupyter-lab"
"C:\\Users\\jlperla\\.julia\\conda\\3\\Scripts\\jupyter.exe-lab"
```
This should instead be
```
"C:\\Users\\jlperla\\.julia\\conda\\3\\Scripts\\jupyter-lab.exe"
```
A possible solution is to strip the `.exe` from the end of the `jupyter` string, and then add it back after appending the `lab`.  Need to be careful not to break OSX/linux though.

**Comment by stevengj** [comment]
Should be fixed on master, thanks!

**Comment by jlperla** [comment]
Any hope of a not-to-distant tagged release for this issue?

**Comment by stevengj** [comment]
Can you confirm that master solves the problem on Windows?

**Comment by jlperla** [comment]
I can confirm on Windows.  After deleting `.julia/conda` it installs things correctly on the first call, and it no longer asks to install after that.
