### ISSUE TITLE
Windows Permission Denied

### ISSUE THREAD

**Issue by versipellis** [JuliaLang/IJulia.jl#878]
When trying to start the kernels for jupyter, I'm getting a `PermissionError` error:

```
File "C:\Users\uname\.julia\conda\3\lib\site-packages\jupyter_client\connect.py", line 102, in secure_write
    with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\uname\\AppData\\Roaming\\jupyter\\runtime\\kernel-7de90d25-3e15-4cc1-8a7b-1e3bc54d4f18.json'
```

I've checked permissions and read/write is fine for all users, so not quite sure what the issue might be.

**Comment by travigd** [comment]
This is not an IJulia issue, but rather, an issue with Jupyter notebook itself (the error message there originates from the code in the jupyter-client package, which is part of the broader Jupyter ecosystem which is all written in python).

Looks like this might be related:
https://github.com/jupyter/notebook/issues/4907

**Comment by kevin-bates** [comment]
I believe this issue should be closed as it is indeed related to https://github.com/jupyter/notebook/issues/4907 as @travigd points out.
