### ISSUE TITLE
I bulid Ijulia

### ISSUE THREAD

**Issue by ice-bird** [JuliaLang/IJulia.jl#879]
If you have a question please search or post to our Discourse site: https://discourse.julialang.org.
We use the GitHub issue tracker for bug reports and feature requests only.

If you're submitting a bug report, be sure to include as much relevant information as
possible, including a minimal reproducible example and the output of `versioninfo()`.
If you're experiencing a problem with a particular package, open an issue on that
package's repository instead.

Thanks for contributing to the Julia project!

**Comment by ice-bird** [comment]
i installed IJullia and jupyter successfully. i download a .ipynb file .it use julia ,but when i clik it to open with vscode ,it show entirely, but cant run code. it just show error "println is not defined". i know it only recongnize.how to solve.
another imformation, when i open jyputer in web,i can new julia .ipynb.
![批注 2019-10-15 173359](https://user-images.githubusercontent.com/54264951/66819790-248c5e80-ef72-11e9-93b3-e0a291c3ea4e.png)
![批注 2019-10-15 173555](https://user-images.githubusercontent.com/54264951/66819879-4685e100-ef72-11e9-8c6b-1f589436a6f4.png)

**Comment by fredrikekre** [comment]
That is a python stacktrace so the kernel seems to be running python, not julia.
