### ISSUE TITLE
can`t build("ZMQ")  Could not list contents of tarball 

### ISSUE THREAD

**Issue by MRtianyanxiaobai** [JuliaLang/IJulia.jl#889]
julia> Pkg.build("ZMQ")
  Building ZMQ → `C:\Users\Mr_xiaobai\.julia\packages\ZMQ\ABGOx\deps\build.log`
┌ Error: Error building `ZMQ`:
│ ┌ Warning: platform_key() is deprecated, use platform_key_abi() from now on
│ │   caller = ip:0x0
│ └ @ Core :-1
│ ┌ Warning: Could not extract the platform key of https://github.com/JuliaInterop/ZMQBuilder/releases/download/v4.2.5+6/ZMQ.x86_64-w64-mingw32.tar.gz; continuing...
│ └ @ BinaryProvider C:\Users\Mr_xiaobai\.julia\packages\BinaryProvider\kcGxO\src\Prefix.jl:185
│ ERROR: LoadError: Could not list contents of tarball C:\Users\Mr_xiaobai\.julia\packages\ZMQ\ABGOx\deps\usr\downloads\ZMQ.x86_64-w64-mingw32.tar.gz
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] #list_tarball_files#143(::Bool, ::typeof(list_tarball_files), ::String) at C:\Users\Mr_xiaobai\.julia\packages\BinaryProvider\kcGxO\src\Prefix.jl:468
│  [3] list_tarball_files at C:\Users\Mr_xiaobai\.julia\packages\BinaryProvider\kcGxO\src\Prefix.jl:457 [inlined]
│  [4] #install#133(::Prefix, ::String, ::Bool, ::Bool, ::Bool, ::typeof(install), ::String, ::String) at C:\Users\Mr_xiaobai\.julia\packages\BinaryProvider\kcGxO\src\Prefix.jl:327
│  [5] (::BinaryProvider.var"#kw##install")(::NamedTuple{(:prefix, :force, :verbose),Tuple{Prefix,Bool,Bool}}, ::typeof(install), ::String, ::String) at .\tuple.jl:0
│  [6] top-level scope at C:\Users\Mr_xiaobai\.julia\packages\ZMQ\ABGOx\deps\build.jl:44
│  [7] include at .\boot.jl:328 [inlined]
│  [8] include_relative(::Module, ::String) at .\loading.jl:1105
│  [9] include(::Module, ::String) at .\Base.jl:31
│  [10] include(::String) at .\client.jl:432
│  [11] top-level scope at none:5
│ in expression starting at C:\Users\Mr_xiaobai\.julia\packages\ZMQ\ABGOx\deps\build.jl:40
│ caused by [exception 1]
│
│ Stacktrace:
│  [1] error() at .\error.jl:42
│  [2] #list_tarball_files#143(::Bool, ::typeof(list_tarball_files), ::String) at C:\Users\Mr_xiaobai\.julia\packages\BinaryProvider\kcGxO\src\Prefix.jl:465
│  [3] list_tarball_files at C:\Users\Mr_xiaobai\.julia\packages\BinaryProvider\kcGxO\src\Prefix.jl:457 [inlined]
│  [4] #install#133(::Prefix, ::String, ::Bool, ::Bool, ::Bool, ::typeof(install), ::String, ::String) at C:\Users\Mr_xiaobai\.julia\packages\BinaryProvider\kcGxO\src\Prefix.jl:327
│  [5] (::BinaryProvider.var"#kw##install")(::NamedTuple{(:prefix, :force, :verbose),Tuple{Prefix,Bool,Bool}}, ::typeof(install), ::String, ::String) at .\tuple.jl:0
│  [6] top-level scope at C:\Users\Mr_xiaobai\.julia\packages\ZMQ\ABGOx\deps\build.jl:44
│  [7] include at .\boot.jl:328 [inlined]
│  [8] include_relative(::Module, ::String) at .\loading.jl:1105
│  [9] include(::Module, ::String) at .\Base.jl:31
│  [10] include(::String) at .\client.jl:432
│  [11] top-level scope at none:5
│
│ 7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21
│
│
│
│ ERROR:
│ Can't load module: 7z.dll
│
│
│ ERROR:
│ Can't load module: 7z.dll
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Pkg\src\backwards_compatible_isolation.jl:649
false

**Comment by zombie110year** [comment]
install 7zip and set it in `$env:Path` may take effect?
the output shows:

```
Can't load module: 7z.dll
```

**Comment by stevengj** [comment]
Closing, as this is not an IJulia problem.  Also, the mechanism for installing ZMQ has recently changed completely (in Julia 1.3), so please file a ZMQ.jl issue only if an error continues to occur for installing the latest ZMQ.
