### ISSUE TITLE
Feature Request : Allow IJulia to run on root.

### ISSUE THREAD

**Issue by ucalyptus** [JuliaLang/IJulia.jl#895]
**Issue** : Current Version of IJulia does not support for root running of jupyter notebooks
**StackOverflow Link** : [Click Here](https://stackoverflow.com/questions/59900896/why-is-notebook-not-working-for-ijulia)
**How to reproduce** : When in root , `using IJulia; notebook(detached = true)` does not enable `http://localhost:8888/tree` to work even if `ProcessRunning` is mentioned .

**Solution**: Some functionality like `notebook(detached=true allow-root)` just like `jupyter notebook --allow-root`  that returns a `http://localhost:8888/tree/token?.......` .

**Comment by stevengj** [comment]
You can always just run `jupyter notebook --allow-root` yourself.   Running as root is a rare and dangerous enough operation that it seems fine to not provide an easy `IJulia.notebook()` interface to it … you should have to know what you are doing, and if you know what you are doing then invoking `jupyter` directly is easy.
