### ISSUE TITLE
Package name should ideally be Jupyter.jl

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/IJulia.jl#904]
This just occurred to me a couple of days ago, that this package would be ideally called Jupyter.jl. Of course, I imagine this may be a hard thing to pull off now that the name is well established - but I thought I would at least mention it here.

**Comment by travigd** [comment]
The name IJulia is inline with the other naming conventions in the Jupyter community.

Jupyter refers to the broader platform (including the notebook frontend as well as the standards about how communication works) whereas the individual kernels are typically named with the I (part of the history of the Jupyter project splitting out of IPython).

So, the Python kernel is actually ipykernel, for R it's IRKernel, etc. and they all implement the Jupyter kernel communication spec.

**Comment by stevengj** [comment]
Duplicate of #401.
