### ISSUE TITLE
Zero before another number breaks ijulia

### ISSUE THREAD

**Issue by SirLukeSchande** [JuliaLang/IJulia.jl#907]
When entering another number after a 0 IJulia stops displaying a. This means that either the single zero and the curser stay or the whole cell goes blank. This Error occurs when entering a Float without the 0 in front of the decimal point, i.e. .03 instead of 0.03

The Javascript console reads:

```
Error: Mode julia failed to advance stream. codemirror.js:1156
    readToken codemirror.js:1156
    runMode codemirror.js:1210
    highlightLine codemirror.js:1056
    getLineStyles codemirror.js:1100
    buildLineContent codemirror.js:1733
    getLineContent codemirror.js:2123
    updateLineText codemirror.js:2131
    updateLineForChanges codemirror.js:2080
    patchDisplay codemirror.js:4200
    updateDisplayIfNeeded codemirror.js:4101
    endOperation_W1 codemirror.js:3809
    endOperations codemirror.js:3786
    endOperation codemirror.js:3775
    finishOperation codemirror.js:2035
    endOperation codemirror.js:3772
    runInOp codemirror.js:3901
    poll codemirror.js:9501
    init codemirror.js:9295
```

I am on:
```
Julia Version 1.4.0
Commit b8e9a9ecc6 (2020-03-21 16:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, sandybridge)
```

The error does not occur when using Python.

Thanks in advance.

**Comment by stevengj** [comment]
Can you please report the bug to https://github.com/codemirror/CodeMirror?   That's what's doing the code highlighting, not IJulia.

**Comment by stevengj** [comment]
(When you post the issue, probably post some more info about your system, browser, software versions, etcetera.  I can't reproduce: 
![image](https://user-images.githubusercontent.com/2913679/77823903-e96f8900-70d4-11ea-9ad4-571aff9bf8ba.png))

**Comment by stevengj** [comment]
See codemirror/CodeMirror#6288
