### ISSUE TITLE
@__DIR__ does nto behave as "expected" in IJulia

### ISSUE THREAD

**Issue by Datseris** [JuliaLang/IJulia.jl#915]
Hi there, i have a notebook in a folder A of my computer.

When I start Julia I automatically set my working directory to the desktop.

I fire up IJulia and launch the notebook. In there I type:
```
joinpath(@__DIR__)
```
which returns `"C:\\Users\\datse\\Desktop"`, i.e. it does not return the directory of the file containing the macro call. Or maybe it does "technically" given how IJulia works under the hood, but this is not my typicall usage of `@__DIR__`.

How can I obtain the source directory of the notebook inside the notebook?

**Comment by travigd** [comment]
This might(?) not be possible.

Jupyter is designed to have two separate parts: the frontend (e.g., Jupyter Notebook, Nteract, QT Console, Jupyter Lab, etc.) and the kernel (IPython, IJulia, IRKernel).

The kernel part doesn't have very much knowledge of all of what's going on in the frontend, it's basically just a process that responds to code execution requests. In particular, it doesn't know what notebook file the code requests are coming from (all that IJulia sees is a request to execute `println("foobar")` and nothing more).

When you start IJulia, the working directory is set by default to be the directory of the notebook, so removing the part where it automatically sets the working directory to the desktop should fix that issue. If you do that in `startup.jl`, you can just add a check like this:
```julia
if !haskey(ENV, "JPY_PARENT_PID")
    cd(...)
end
```

**Comment by stevengj** [comment]
Not possible in general: https://github.com/ipython/ipython/issues/10123

**Comment by Datseris** [comment]
For what it is worth, @travigd solution was good enough for me :)
