### ISSUE TITLE
Pkg.add("IJulia") git proxy error without using proxy

### ISSUE THREAD

**Issue by pmcb99** [JuliaLang/IJulia.jl#916]
I just did a fresh install of Manjaro with KDE Plasma 5.18.4. I installed julia and it works fine. I also installed jupyter notebook and it too is fine.

When I type
`using Pkg`
`Pkg.add("IJulia") 

I get a GitError about invalid proxy options. Again this is a clean install so I have not messed with any git proxy settings. I tested git and it is working perfectly, libgit2 is also installed. 
![image](https://user-images.githubusercontent.com/41525169/79280047-4aee7080-7ea7-11ea-98e0-d07e6fc909df.png)

`

**Comment by travigd** [comment]
Did you install Julia using the system package manager? That frequently results in things being very broken™. Installing a pre-built binary is a much better approach.

https://julialang.org/downloads/

**Comment by pmcb99** [comment]
Thanks for the help. The binary is better.
