### ISSUE TITLE
Cell content disappears 

### ISSUE THREAD

**Issue by otobrzo** [JuliaLang/IJulia.jl#919]
From time to time the content of cell in my notebook just disappears. 

<img width="1266" alt="Snímek obrazovky 2020-04-22 v 18 41 25" src="https://user-images.githubusercontent.com/16555995/80010339-94077b80-84ca-11ea-9a2f-3605a402ea5f.png">

It starts with freezing of cursor at a specific position in the cell and then all just disappear.
I can export the notebook to the script and the cell content is there. The parts of the code can disappear due to the keyboard activity in the emptied cell.

```
using ProgressMeter
using Flux: @epochs

N_epochs = 500
loss_train = zeros(Float16,N_epochs,1) 
loss_test = zeros(Float16,N_epochs,1) 

#evalcb() = @show(loss(gpu(test_X), gpu(test_Y)))

@showprogress 1 "Computing..." for epoch = 1:N_epochs

    Flux.train!(loss, params(model), dataset_batch, opt)#, cb = throttle(evalcb, 5))
        
    loss_train[epoch] = loss(gpu(training_X), gpu(training_Y)) 
    loss_test[epoch] = loss(gpu(test_X), gpu(test_Y))
    
end
```

It is not connected to anything specific in the code.

Julia 1.3.1
IJulia v1.21.2
python3.7
jupyter core     : 4.5.0
jupyter-notebook : 5.7.8
qtconsole        : 4.3.1
ipython          : 5.8.0
ipykernel        : 4.9.0
jupyter client   : 5.2.4
jupyter lab      : 2.0.0
nbconvert        : 5.4.0
ipywidgets       : 6.0.0
nbformat         : 4.4.0
traitlets        : 4.3.2

ubuntu 19.10

**Comment by jmert** [comment]
This is* a bug in CodeMirror (https://github.com/codemirror/CodeMirror/issues/6064) in performing the syntax highlighting for Julia code. I've seen the same problem, and it took my quite a while to track down this issue as being exactly what I was running into.

\* The caveat is that I don't see your code having any numbers with a leading `0` as was reported in the CodeMirror issue (and is exactly the behavior I was struggling against).

**Comment by stevengj** [comment]
Indeed, it sounds like a CodeMirror bug.  Please file a CodeMirror issue if this has not been resolved by the latest CodeMirror…

**Comment by M007-lab** [comment]
Same Issue here. It really occurs a lot  !
