### ISSUE TITLE
Underscore notation for numbers makes number different colours.

### ISSUE THREAD

**Issue by cjwyett** [JuliaLang/IJulia.jl#932]
Hi, 

In Julia we can make large numbers easier to read with underscores. For example `1000000` can be written as `1000_000`.

This still works in the jupyter notebook with Ijulia, but its not nice to look at. The numbers before the underscore are green, as with all other numbers, but the numbers after the underscore are black. In our example above `1000` is green while `_000` is black. 

Thanks

**Comment by stevengj** [comment]
Syntax coloring in notebooks is performed by CodeMirror, not IJulia, so you should file the issue there: https://github.com/codemirror/CodeMirror
