### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by jlumpe** [JuliaLang/IJulia.jl#936]
Given that this is one of the most popular Julia packages, I think it would be very useful to have some actual documentation generated by `Documenter.jl`. For one, it would be very helpful to have some more documentation about the API and the internals (these might be present in docstrings, but you have to go searching for them). I think this creates a barrier to those like myself who would otherwise be interested in contributing to the project.

If the maintainers are open to this I can definitely start putting together a documentation skeleton to get the ball rolling.

**Comment by logankilpatrick** [comment]
Hey @jlumpe , definitely give it a go and open a PR for this. I am happy to review and get some eyes on it.

**Comment by stevengj** [comment]
All the documentation is in README.JL — the package pre-dates Documenter.jl considerably and was never updated to use it.  A PR transferring the current documentation to Documenter.jl would be welcome, and it can be expanded subsequently.

**Comment by jlumpe** [comment]
PR is here: #941
