### ISSUE TITLE
Handling of `local y = (x = i)` in soft scope

### ISSUE THREAD

**Issue by bkamins** [JuliaLang/IJulia.jl#938]
The following cell executed in top level:
```
x = 1
for i in 1:10
    local y = (x = i)
end
```
throws a warning `Warning: Assignment to `x` in soft scope is ambiguous ` under Julia 1.5+ in Jupyter Notebook, but does not print a warning in Julia REPL.

**Comment by bkamins** [comment]
Since 1.5 got released I think it would be good to have a look at this issue.

@StefanKarpinski bumping it following your request in the release announcement blog post 😄 (this is probably an easy fix, but I have not dug in IJulia.jl internals deep enough to diagnose it quickly).

Quickly looking at it for me it seems that the core issue is in `SoftGlobalScope._softscope`.

If I understand the design objectives correctly setting `IJulia.SOFTSCOPE[] = true` should make IJulia behave as if the expressions were executed in REPL under Julia 1.5+. Is this correct?

**Comment by bkamins** [comment]
Actually thinking of it maybe a more general fix would be to add to `include_string` (or in general `include`) a kwarg that would allow the user to decide if the passed code should be evaluated as a script (the current behavior) or "as if" it was passed in REPL?

**Comment by StefanKarpinski** [comment]
What is the state of IJulia's soft scope stuff. Is it using the same machinery as the REPL for Julia 1.5?

**Comment by bkamins** [comment]
As far as I checked this code today it in the end (after several intermediate steps) calls
https://github.com/stevengj/SoftGlobalScope.jl/blob/master/src/SoftGlobalScope.jl#L122
if `IJulia.SOFTSCOPE[] = true`.

If `IJulia.SOFTSCOPE[] = false` it calls `include_string` so essentially it makes then a Jupyter Notebook cell to be treated as a "non-REPL" scope.

**Comment by StefanKarpinski** [comment]
Seems like the fix is to stop using SoftGlobalScope.jl on Julia 1.5 and use the built-in soft scope implementation. Or update SoftGlobalScope.jl to do that instead.

**Comment by bkamins** [comment]
Agreed that this would be simplest - but I feel it would be safest if @stevengj has a look at it as it is easy to overlook something.

**Comment by stevengj** [comment]
In Julia 1.5, SoftGlobalScope just calls through to the `REPL.softscope` function, which should be the right thing here (https://github.com/stevengj/SoftGlobalScope.jl/pull/25)

**Comment by stevengj** [comment]
Looks like I just need to tag a new release of SoftGlobalScope.

**Comment by stevengj** [comment]
Should be fixed by https://github.com/JuliaRegistries/General/pull/18928

**Comment by bkamins** [comment]
Thank you!
