### ISSUE TITLE
v1.21.4 breaks IJulia with "InteractiveUtils not defined" Error

### ISSUE THREAD

**Issue by Paethon** [JuliaLang/IJulia.jl#955]
Installing the newest IJulia (v1.21.4) and starting a notebook breaks as soon as the first cell is executed with many of the following Error messages (the previous version works):

```
ERROR: LoadError: UndefVarError: InteractiveUtils not defined
in expression starting at /home/paethon/.julia/packages/IJulia/rWZ9e/src/kernel.jl:12
[I 19:55:05.973 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
┌ Warning: this kernel.jl is different from the one provided by IJulia
│   this_kernel_file = "/home/paethon/.julia/packages/IJulia/rWZ9e/src/kernel.jl"
│   ijulia_kernel_file = "/home/paethon/.julia/packages/IJulia/DrVMH/src/kernel.jl"
```

Versioninfo:
```
Julia Version 1.5.2
Commit 539f3ce943* (2020-09-23 23:17 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-10.0.1 (ORCJIT, skylake)
Environment:
  JULIA_CUDA_USE_BINARYBUILDER = false
  JULIA_NUM_THREADS = 8
```

**Comment by fredrikekre** [comment]
The warning you see
> ┌ Warning: this kernel.jl is different from the one provided by IJulia
│   this_kernel_file = "/home/paethon/.julia/packages/IJulia/rWZ9e/src/kernel.jl"
│   ijulia_kernel_file = "/home/paethon/.julia/packages/IJulia/DrVMH/src/kernel.jl"

suggest you have not rebuild IJulia after an update.

**Comment by Paethon** [comment]
Hmm, no that does not seem to be the issue. 
I ran `build IJulia` in pkg mode and also restarted julia after updating.

Could it be that a local jupyter installation is interfering?

**Comment by Paethon** [comment]
OK, I just deleted the whole `packages/IJulia` folder and reinstalled it. That has fixed it.
