### ISSUE TITLE
Error in installing IJulia.jl

### ISSUE THREAD

**Issue by farhatizakaria** [JuliaLang/IJulia.jl#956]
Updating registry at `C:\Users\hilcomputer\.julia\registries\General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Resolving package versions...
Downloading artifact: MbedTLS
Exception lors de la définition de « SecurityProtocol » : « Impossible de conve
rtir la valeur Null en type « System.Net.SecurityProtocolType » en raison de va
leurs d'énumération non valides. Spécifiez l'une des valeurs d'énumération suiv
antes et réessayez. Les valeurs d'énumération possibles sont « Ssl3, Tls ». »
Au niveau de ligne : 1 Caractère : 35
+ [System.Net.ServicePointManager]:: <<<< SecurityProtocol =
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException

Exception lors de l'appel de « DownloadFile » avec « 2 » argument(s) : « La con
nexion sous-jacente a été fermée : Une erreur inattendue s'est produite lors de
 l'envoi. »
Au niveau de ligne : 12 Caractère : 24
+ $webclient.DownloadFile <<<< ("https://pkg.julialang.org/artifact/a5355b4efc1
953f6d15e22618ff5dabbbd0f84dd", "C:\Users\HILCOM~1\AppData\Local\Temp\jl_54NPE7
Rg1K-download.gz")
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException
Downloading artifact: MbedTLS
Exception lors de la définition de « SecurityProtocol » : « Impossible de conve
rtir la valeur Null en type « System.Net.SecurityProtocolType » en raison de va
leurs d'énumération non valides. Spécifiez l'une des valeurs d'énumération suiv
antes et réessayez. Les valeurs d'énumération possibles sont « Ssl3, Tls ». »
Au niveau de ligne : 1 Caractère : 35
+ [System.Net.ServicePointManager]:: <<<< SecurityProtocol =
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException

Exception lors de l'appel de « DownloadFile » avec « 2 » argument(s) : « La con
nexion sous-jacente a été fermée : Une erreur inattendue s'est produite lors de
 l'envoi. »
Au niveau de ligne : 7 Caractère : 24
+ $webclient.DownloadFile <<<< ("https://github.com/JuliaBinaryWrappers/MbedTLS
_jll.jl/releases/download/MbedTLS-v2.16.8+0/MbedTLS.v2.16.8.x86_64-w64-mingw32.
tar.gz", "C:\Users\HILCOM~1\AppData\Local\Temp\jl_Svo7n2ZpTc-download.gz")
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException
ERROR: Unable to automatically install 'MbedTLS' from 'C:\Users\hilcomputer\.jul
ia\packages\MbedTLS_jll\qGMUr\Artifacts.toml'
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] ensure_artifact_installed(::String, ::Dict{String,Any}, ::String; platform:
:Pkg.BinaryPlatforms.Platform, verbose::Bool, quiet_download::Bool) at D:\buildb
ot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Pkg\src\Artifacts.jl:8
98
 [3] ensure_all_artifacts_installed(::String; platform::Pkg.BinaryPlatforms.Plat
form, pkg_uuid::Nothing, include_lazy::Bool, verbose::Bool, quiet_download::Bool
) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Pkg\src\
Artifacts.jl:962
 [4] download_artifacts(::Pkg.Types.Context, ::Array{String,1}; platform::Pkg.Bi
naryPlatforms.Windows, verbose::Bool) at D:\buildbot\worker\package_win64\build\
usr\share\julia\stdlib\v1.5\Pkg\src\Operations.jl:663
 [5] download_artifacts(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}; p
latform::Pkg.BinaryPlatforms.Windows, verbose::Bool) at D:\buildbot\worker\packa
ge_win64\build\usr\share\julia\stdlib\v1.5\Pkg\src\Operations.jl:642
 [6] add(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}, ::Array{Base.UUI
D,1}; preserve::Pkg.Types.PreserveLevel, platform::Pkg.BinaryPlatforms.Windows)
at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Pkg\src\Op
erations.jl:1141
 [7] add(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}; preserve::Pkg.Ty
pes.PreserveLevel, platform::Pkg.BinaryPlatforms.Windows, kwargs::Base.Iterators
.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at D:\buildbot\worker\pa
ckage_win64\build\usr\share\julia\stdlib\v1.5\Pkg\src\API.jl:188
 [8] add(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at D:\buildbot\w
orker\package_win64\build\usr\share\julia\stdlib\v1.5\Pkg\src\API.jl:139
 [9] #add#21 at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1
.5\Pkg\src\API.jl:67 [inlined]
 [10] add at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\
Pkg\src\API.jl:67 [inlined]
 [11] #add#20 at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v
1.5\Pkg\src\API.jl:66 [inlined]
 [12] add at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\
Pkg\src\API.jl:66 [inlined]
 [13] add(::String; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTu
ple{(),Tuple{}}}) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdl
ib\v1.5\Pkg\src\API.jl:65
 [14] add(::String) at D:\buildbot\worker\package_win64\build\usr\share\julia\st
dlib\v1.5\Pkg\src\API.jl:65
 [15] top-level scope at REPL[2]:1

**Comment by stevengj** [comment]
Sounds like an error downloading the https://github.com/JuliaLang/MbedTLS.jl package, so you could file an issue there.   But I suspect that it is some kind of firewall blocking Julia binary downloads on your system, so for a general question like that I would tend to ask on https://discourse.julialang.org/
