### ISSUE TITLE
Autocomplete DataFrame column names

### ISSUE THREAD

**Issue by gugatr0n1c** [JuliaLang/IJulia.jl#957]
Hi,

using julia 1.5.1
"DataFrames"     => v"0.21.8"
"IJulia"         => v"1.21.3"

using DataFrames
frame = DataFrame(PART_NAME=String[], YEAR_URL=String[])
...
some code
...
frame[:P] and hit tab does not auto-filles full_name.

There is a workaround using frame.P and tab to auto-filled with getproperty syntax.
But i some cases like:
sort!(frame, :colname) is syntax with :colname required.

Is it possible to support auto-complete also for :colname syntax?
I thing dataframes package is super popular and this will be very usefull.

Note:
- this is working in VSCode + julia + dataframe
- also working equivalent in python + pandas_dataframe: frame["P+tab"] to autocomplete

Thank you

**Comment by stevengj** [comment]
IJulia uses the autocompletion functions from the Julia REPL package (https://github.com/JuliaLang/julia/blob/master/stdlib/REPL/src/REPLCompletions.jl), so you should file an issue https://github.com/JuliaLang/julia if there is missing functionality.
