### ISSUE TITLE
ZMQ unsatiable constraints

### ISSUE THREAD

**Issue by SimonEnsemble** [JuliaLang/IJulia.jl#971]
my student on Windows got the following error when trying to install `IJulia`. any idea how to fix this? thanks.

[second line]
![image](https://user-images.githubusercontent.com/30643894/103692146-375eca80-4f4c-11eb-9bef-0601dd3235e7.png)

**Comment by stevengj** [comment]
I've never seen this before.  I would assume that your student's `.julia` directory is corrupted somehow.   Maybe delete it and start over.  Restart Julia and run:
```jl
julia> rm(raw"C:\Users\shawn\.julia", recursive=true)

pkg> add IJulia
```
Noe that you get the `pkg>` prompt by typing `]` at the `julia>` prompt.  No need to run `build` manually, it is automatically run by `add`.

**Comment by fredrikekre** [comment]
Likely that it is the registry that is corrupt so should be enough to delete `rm(raw"C:\Users\shawn\.julia\registries\General", recursive=true)`
