### ISSUE TITLE
errors thrown from a kernel are not pretty printed

### ISSUE THREAD

**Issue by untoreh** [JuliaLang/IJulia.jl#974]
Don't know if this is the correct place for this issue...with
```julia
[][fill(1, 10000)]
```
in the repl, I get 
```
ERROR: BoundsError: attempt to access 0-element Array{Any,1} at index [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1  …  1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]
```
whereas from a notebook, it prints the full array.
Browsers can handle big strings fine, sadly emacs cannot, and in those cases has to be restarted.

**Comment by stevengj** [comment]
Thanks, should be fixed now.
