### ISSUE TITLE
macOS: Julia unresponsive unless iJulia is in the global environment?

### ISSUE THREAD

**Issue by dpo** [JuliaLang/IJulia.jl#975]
Is it expected that IJulia must be installed in the global environment? I followed the troubleshooting steps in the documentation and confirmed that my firewall isn't the issue. If IJulia is installed in an environment other than the global environment, evaluating a cell never completes (the status remains  `[*]`).

**Comment by fredrikekre** [comment]
I usually have it in my local environment so something else must be up. https://github.com/JuliaLang/IJulia.jl/issues/968 maybe if you are using Julia 1.6.

**Comment by dpo** [comment]
I'm on Julia 1.5.3. I checked that a Python notebook works (and it does).

**Comment by nilshg** [comment]
This can be closed.
