### ISSUE TITLE
Urgent Help: Unable to link Jupyter Notebook to Julia

### ISSUE THREAD

**Issue by Prabhav17** [JuliaLang/IJulia.jl#981]
Hello,
I am using Julia for the first time. I downloaded Julia and tried to attach jupyter notebook to it. But I am getting an error as shown below:
julia> notebook()
install Jupyter via Conda, y/n? [y]: y
[ Info: Downloading miniconda installer ...
ERROR: failed process: Process(`'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' -Version 3 -NoProfile -Command "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; (New-Object System.Net.Webclient).DownloadFile('https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe', 'C:\Users\Admin\.julia\conda\3\installer.exe')"`, ProcessExited(3221225477)) [3221225477]

Please help me in resolving the issue. 

![error_1](https://user-images.githubusercontent.com/19263701/106038860-0fbbd780-609e-11eb-9820-3d9b6030d639.PNG)

**Comment by fredrikekre** [comment]
Looks like you are using an ancient version of Windows and may need their "easy fix", see https://julialang.org/downloads/platform/#windows_7_windows_server_2012_installation_notes.

**Comment by nilshg** [comment]
This can be closed.
