### ISSUE TITLE
Why can only 8 columns be displayed in JupyterLab

### ISSUE THREAD

**Issue by Jianqing001** [JuliaLang/IJulia.jl#984]
input:  df=CSV.read("E:\\Study\\Titanic.csv",DataFrame)
output:
891 rows × 12 columns (omitted printing of 8 columns)
.......

**Comment by Jianqing001** [comment]
891 rows × 12 columns (omitted printing of 8 columns)

**Comment by Jianqing001** [comment]
jupyterlab  V3.0

**Comment by fredrikekre** [comment]
Because DataFrames limit the number of columns to fit the screen

**Comment by Jianqing001** [comment]
But my screen can actually show a lot more

**Comment by fredrikekre** [comment]
You will have to ask DataFrames developers about that, or use the forum: https://discourse.julialang.org/

**Comment by stevengj** [comment]
You can try setting `ENV["COLUMNS"]=200` to tell DataFrames that a wider display is possible (the default in IJulia is 80).
