### ISSUE TITLE
Unable to download the miniconda while using IJulia

### ISSUE THREAD

**Issue by Yuqingyo** [JuliaLang/IJulia.jl#988]
Hello, I wanna using IJulia in the Jupyter Notebook

julia> using IJulia
julia> IJulia.notebook()
install Jupyter via Conda, y/n? [y]: y**

[ Info: Downloading miniconda installer ...

So, sad. No response to this command, I have been waiting for 1 hour.............

Pls help me!!!!!!!!!!Thank you so much.

**Comment by Yuqingyo** [comment]
![Uploading image.png…]()

**Comment by stevengj** [comment]
Presumably you have some kind of firewall on your machine that is blocking the download?

In any case, this is actually the [Conda.jl package](https://github.com/JuliaPy/Conda.jl).   You should get the same error (after running `pkg> add Conda` at the package prompt) from
```jl
import Conda
Conda.add("jupyter")
```
If you can't figure out your download problems, you could ask on [Julia discourse](https://discourse.julialang.org/).

Alternatively, you can just install Jupyter yourself, e.g. by downloading Anaconda Python or some other Python distro.
