### ISSUE TITLE
Display/println order incorrect

### ISSUE THREAD

**Issue by adamoppenheimer** [JuliaLang/IJulia.jl#998]
There seems to be an issue with the order of the `display` function with respect to `print` statements. I am just starting with Julia and coming from Python, so this may just be an artifact from Jupyter notebook with Python that is not supposed to apply with Julia.

The issue is that `display` output seems to come at the start of cells, regardless of its placement in the code (at least in the few cases I tried). Also note this does not occur when `print` is used to display variables instead of `display`.

An example code is as follows:
```
A = Array{Float64, 2}(undef, 2, 3)
println("A")
display(A)
println("B")
```

I would expect "A" to be printed, then the matrix A to be displayed, then "B" to be printed. Instead, the matrix A is printed first, and then "A" and "B" are printed.

Here is an example in Jupyter:
<img width="368" alt="Screen Shot 2021-04-04 at 02 01 56" src="https://user-images.githubusercontent.com/40669484/113500249-75876e00-94ea-11eb-9db8-c41ad072521f.png">

If I use `print` instead, this is the output:
<img width="490" alt="Screen Shot 2021-04-04 at 02 13 04" src="https://user-images.githubusercontent.com/40669484/113500363-53dab680-94eb-11eb-80a0-29d95434d063.png">

**Comment by stevengj** [comment]
Just put `flush(stdout)` after the first `println`.

I suppose we could patch the [IJulia `display` function](https://github.com/JuliaLang/IJulia.jl/blob/cc07f6d1f5f13bd15ba9d9c60223121f8b20e8ec/src/inline.jl#L59) so that it flushes stdio automatically.

**Comment by stevengj** [comment]
Try out #999, which should fix your problem.

**Comment by stevengj** [comment]
(The basic issue here is that stdio streams, e.g. `println`, use a different mechanism in Jupyter than multimedia output, i.e. `display`.  We can't guarantee that interleaving the two will be shown in-order, because that depends on the front-end, but flushing seems to do the trick in Jupyter at least.)

**Comment by adamoppenheimer** [comment]
Thank you, I tried out the changes you made to `inline.jl` and they seem to work.
